import test from 'node:test';
import assert from 'node:assert/strict';
import {cloudTransition,commandHash,CLOUD_LEASE_MS} from '../app/lounge-cloud-engine.ts';
import {newLoungeLedger,validateLedger} from '../app/lounge-economy.ts';
import {defaultLook} from '../app/lounge-look.ts';
import {accountSave,validPassword,ACCOUNT_IDS} from '../app/lounge-accounts.ts';
const member=actor=>({id:crypto.randomUUID(),actor,username:ACCOUNT_IDS[actor],connection:crypto.randomUUID(),sequence:0,epoch:0,code:''});
function harness(){let world={schema:1,ledger:newLoungeLedger(),rooms:{},receipts:{}},now=Date.now();return {get world(){return world;},advance(ms){now+=ms;},async run(p,op,extra={}){const c={op,connection:p.connection,code:p.code,...(!['read','wallet'].includes(op)?{requestId:crypto.randomUUID(),sequence:++p.sequence}:{}),...(['open','join'].includes(op)?{epoch:p.epoch}:{}),...extra},hash=await commandHash(c),r=cloudTransition(world,p,c,hash,now);world=r.state;p.epoch=r.response.epoch;if(r.response.code)p.code=r.response.code;validateLedger(world.ledger);return {...r,command:c,hash};},replay(p,c,hash){const r=cloudTransition(world,p,c,hash,now);world=r.state;return r;}};}
test('account sanitation fixes actor, separates saved outfits and bounds passwords',()=>{assert.equal(accountSave({actor:6,saved:[{id:'a',actor:6,look:defaultLook(6),name:'x'}]},0).actor,0);assert.equal(accountSave({saved:[]},0).saved.length,0);assert.equal(validPassword('123456789'),false);assert.equal(validPassword('가'.repeat(25)),false);assert.equal(validPassword('valid-long-password'),true);});
test('one initial grant per fixed account follows rooms, leaves and reconnects',async()=>{const h=harness(),a=member(0),b=member(1);const first=await h.run(a,'open');b.code=a.code;await h.run(b,'join');assert.equal(first.response.wallet.balance,100000);await h.run(a,'leave');await h.run(b,'leave');a.code='';await h.run(a,'open');assert.equal(Object.keys(h.world.ledger.accounts).length,2);assert.equal(h.world.ledger.accounts['wallet-'+a.id],100000);});
test('receipts and epoch block late takeover even after receipt eviction',async()=>{const h=harness(),a=member(0);const first=await h.run(a,'open');const before=h.world.ledger.revision;const duplicate=h.replay(a,first.command,first.hash);assert.equal(duplicate.response.ok,true);assert.equal(h.world.ledger.revision,before);const oldConnection=a.connection;a.connection=crypto.randomUUID();await h.run(a,'join');const denied=await h.run(a,'read',{connection:oldConnection});assert.equal(denied.response.ok,false);assert.equal(denied.response.packet,null);for(let i=0;i<513;i++)await h.run(a,'action',{action:{kind:'emote',emote:'♥'}});const old=h.replay(a,first.command,first.hash);assert.equal(old.response.ok,false);assert.equal(old.response.packet,null);assert.equal(h.world.rooms[a.code].leases[a.id].connection,a.connection);});
test('failed guesses and cross-room reads never return a private packet',async()=>{const h=harness(),a=member(0),b=member(1);await h.run(a,'open');const bad=await h.run(b,'read',{code:a.code});assert.equal(bad.response.ok,false);assert.equal(bad.response.packet,null);const badAction=await h.run(b,'action',{code:a.code,action:{kind:'look',look:defaultLook(1)}});assert.equal(badAction.response.ok,false);});
test('lease expiry refunds only its own room and a later action cannot resurrect it',async()=>{const h=harness(),a=member(0),b=member(1),c=member(2),d=member(3);await h.run(a,'open');b.code=a.code;await h.run(b,'join');let r=await h.run(a,'action',{action:{kind:'invite',game:'chess',players:[b.id],stake:1000}});let inv=r.response.packet.invites[0];await h.run(b,'action',{action:{kind:'reply',id:inv.id,accept:true}});const game1=h.world.rooms[a.code].snapshot.chess.id;await h.run(c,'open');d.code=c.code;await h.run(d,'join');r=await h.run(c,'action',{action:{kind:'invite',game:'chess',players:[d.id],stake:1000}});inv=r.response.packet.invites[0];await h.run(d,'action',{action:{kind:'reply',id:inv.id,accept:true}});const game2=h.world.rooms[c.code].snapshot.chess.id;h.advance(CLOUD_LEASE_MS-1000);await h.run(c,'read');await h.run(d,'read');h.advance(2000);await h.run(c,'read');assert.equal(h.world.rooms[a.code],undefined);assert.notEqual(h.world.ledger.games[game1].state,'reserved');assert.equal(h.world.ledger.games[game2].state,'reserved');assert.equal((await h.run(a,'read')).response.packet,null);});
