'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUp,Backpack,BookOpen,Check,ChevronRight,Coins,Heart,HelpCircle,Home,Leaf,MapPin,Minus,Moon,Plus,Settings,ShoppingBag,Sun,Users,Volume2,VolumeX,X,Camera} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import World,{type Target,type WorldApi} from './world';
import IslandMap,{MayorAvatar} from './island-map';
import {FRIENDS,MAYOR,REGIONS,ITEMS,NODES,SPOTS,DECOR,visitRegion,claimExploration,freshSave,hydrate,requestFor,handIn,buy,walkable,type Save,type Resource,type Point} from './game-data';
import {chime,music} from './sound';
import {registerIslandJournal} from './webmcp';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {createSavePersistence} from './save-storage';
import {useMultiplayer} from './use-multiplayer';
import {MultiplayerPanel} from './multiplayer-ui';
import {EMOTES,persistentPosition,roomCode,visitingSpawn} from './multiplayer-protocol';
type Panel='start'|'bag'|'journal'|'friends'|'dialogue'|'shop'|'home'|'fish'|'help'|'settings'|'picnic'|'celebrate'|'mayor'|'map'|'online'|null;
function Avatar({id,className='',style}:{id:number;className?:string;style?:React.CSSProperties}){return <span className={`avatar ${className}`} style={{backgroundImage:'var(--sprite-sheet)',backgroundPosition:`${(id%3)*50}% ${Math.floor(id/3)*100}%`,...style}} role="img" aria-label={`${FRIENDS[id].look} 캐릭터`}/>}
function PanelShell({open,title,description,children,onClose,wide=false}:{open:boolean;title:string;description:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className={`game-panel ${wide?'wide':''}`}><DialogTitle className="panel-title">{title}</DialogTitle><DialogDescription className="panel-description">{description}</DialogDescription>{children}</DialogContent></Dialog>}
export default function IslandGame(){
 const [save,setSave]=useState<Save>(freshSave),saveRef=useRef(save);saveRef.current=save;const [initialized,setInitialized]=useState(false),[panel,setPanel]=useState<Panel>('start'),[selected,setSelected]=useState(0),[hasSave,setHasSave]=useState(false),[worldEpoch,setWorldEpoch]=useState(0),[ready,setReady]=useState(false),[assetError,setAssetError]=useState(false),[near,setNear]=useState<Target|null>(null),[npc,setNpc]=useState(1),[message,setMessage]=useState(''),[zoom,setZoom]=useState(1),[night,setNight]=useState(false),[sound,setSound]=useState(false),[placing,setPlacing]=useState<string|null>(null),[saveStatus,setSaveStatus]=useState('이 기기에 자동 저장'),[fishPhase,setFishPhase]=useState<'ready'|'waiting'|'reel'|'success'|'miss'>('ready'),[fishCursor,setFishCursor]=useState(0),[fishMisses,setFishMisses]=useState(0),[clock,setClock]=useState('오후 2:30'),[journalOpen,setJournalOpen]=useState(true),[activeRegion,setActiveRegion]=useState<string|null>('village'),[resetOpen,setResetOpen]=useState(false);
 const [persistence]=useState(()=>createSavePersistence(()=>localStorage));
 const world=useRef<WorldApi|null>(null),soundRef=useRef(sound),fishStart=useRef(0),fishTimeout=useRef<ReturnType<typeof setTimeout>|null>(null);soundRef.current=sound;
 const homePosition=useRef<Point|null>(null),[invitation,setInvitation]=useState('');
 const {session:multiplayer,view:online}=useMultiplayer({
  local:()=>({character:saveRef.current.character,name:saveRef.current.names[saveRef.current.character],...(world.current?.pose()??{...saveRef.current.position,facing:1})}),
  island:()=>({placed:saveRef.current.placed,night}),
  arrive:host=>{world.current?.teleport(visitingSpawn(host));setNear(null);setMessage(`${host.name}의 섬에 도착했어요! 함께 산책해 보세요.`);},
  exit:()=>{const origin=homePosition.current;homePosition.current=null;if(origin){world.current?.teleport(origin);const next={...saveRef.current,position:origin};saveRef.current=next;setSave(next);}setNear(null);setPlacing(null);},
 });
 const visiting=online.role==='guest';
 const storedPosition=()=>persistentPosition(homePosition.current,world.current?.position(),saveRef.current.position);
 useEffect(()=>{const read=()=>{const code=roomCode(new URLSearchParams(window.location.hash.slice(1)).get('room')||'');if(code)setInvitation(code);};read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read);},[]);
 useEffect(()=>{if(online.error)setMessage(online.error);},[online.error]);
 useEffect(()=>registerIslandJournal(()=>saveRef.current),[]);
 useEffect(()=>{try{const previous=persistence.read();if(previous){setSave(previous);setSelected(previous.character);setHasSave(true)}}catch{setSaveStatus('저장 공간을 사용할 수 없어요')}setInitialized(true)},[]);
 useEffect(()=>{if(!initialized||!hasSave)return;try{persistence.write(save);setSaveStatus('이 기기에 자동 저장')}catch{setSaveStatus('저장 공간이 부족해요 · 설정에서 백업')}},[save,initialized,hasSave]);
 useEffect(()=>{const persist=()=>{if(!persistence.enabled)return;const p=storedPosition();setSave(s=>({...s,position:p}))};const t=setInterval(persist,4000);const unload=()=>{try{persistence.write({...saveRef.current,position:storedPosition()})}catch{}};window.addEventListener('pagehide',unload);return()=>{clearInterval(t);window.removeEventListener('pagehide',unload)}},[persistence]);
 useEffect(()=>{const tick=()=>{const now=new Date();setClock(now.toLocaleTimeString('ko-KR',{hour:'numeric',minute:'2-digit'}))};tick();const t=setInterval(tick,30000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),3500);return()=>clearTimeout(t)},[message]);
 useEffect(()=>()=>{music(false);if(fishTimeout.current)clearTimeout(fishTimeout.current)},[]);
 const tell=(text:string)=>setMessage(text);
 const update=(fn:(s:Save)=>Save)=>{const next=fn(saveRef.current);saveRef.current=next;setSave(next)};
 const close=()=>{setPanel(null);if(fishTimeout.current)clearTimeout(fishTimeout.current);setFishPhase('ready')};
 const open=(p:Panel)=>{setPlacing(null);if(p==='map')update(s=>({...s,position:storedPosition()}));setPanel(p)};
 const hostRoom=()=>{setPlacing(null);setNear(null);void multiplayer.start('host');};
 const joinRoom=(input:string)=>{const code=roomCode(input);if(!code)return;multiplayer.leave();homePosition.current=world.current?.position()??saveRef.current.position;setPlacing(null);setNear(null);void multiplayer.start('guest',code);};
 const go=(target:Target)=>{close();if(world.current?.go(target)===false)tell('그곳으로 이어지는 길을 찾지 못했어요. 다른 지점에서 다시 시도해 주세요.')};
 const goSpot=(id:string)=>{const p=SPOTS.find(x=>x.id===id)!;go({...p,type:'spot',label:p.name})};
 const goMayor=()=>go({...MAYOR,type:'mayor',label:'호현 촌장과 대화'});
 const goRegion=(id:string)=>{const region=REGIONS.find(r=>r.id===id);if(region)go({...region,type:'region',label:region.name})};
 const arriveRegion=(id:string|null)=>{setActiveRegion(id);if(!id)return;const region=REGIONS.find(r=>r.id===id);if(region&&!saveRef.current.explored.includes(id)){update(s=>visitRegion(s,id));tell(`${region.emoji} ${region.name} 발견! · 탐험 수첩에 기록했어요.`)}};
 const receiveExploration=()=>{const next=claimExploration(saveRef.current);if(!next)return;update(()=>next);chime(sound);tell('섬 한 바퀴 탐험 완료! 호현 촌장의 선물 · 도토리 +100')};
 const interact=(t:Target)=>{if(t.type==='node'){const node=NODES.find(n=>n.id===t.id);if(!node||Date.now()-(saveRef.current.picked[node.id]||0)<30000)return;update(s=>({...s,bag:{...s.bag,[node.kind]:s.bag[node.kind]+1},picked:{...s.picked,[node.id]:Date.now()},harvested:s.harvested+1,coins:s.coins+2}));chime(soundRef.current);tell(`${ITEMS[node.kind].emoji} ${ITEMS[node.kind].name} +1  ·  도토리 +2`);setNear(null)}
 else if(t.type==='friend'){const i=Number(t.id);setNpc(i);update(s=>({...s,talked:s.talked.includes(i)?s.talked:[...s.talked,i]}));open('dialogue')}
 else if(t.type==='mayor'){update(s=>({...s,mayorMet:true}));open('mayor')}else if(t.type==='region'){arriveRegion(t.id);tell(REGIONS.find(r=>r.id===t.id)?.description||'새로운 풍경을 발견했어요.')}else if(t.type==='decor'){if(homePosition.current)return;update(s=>{const d=s.placed.find(p=>p.id===t.id);return d?{...s,decor:[...s.decor,d.kind],placed:s.placed.filter(p=>p.id!==t.id)}:s});tell('장식을 주머니에 넣었어요.')}
 else if(t.id==='fish'){setFishPhase('ready');open('fish')}else open(t.id as Panel)};
 const selectCharacter=()=>{if(!ready)return;if(!hasSave){const s=freshSave(selected);persistence.activate();setSave(s);saveRef.current=s;setHasSave(true)}setPanel(invitation?'online':null);tell(invitation?'초대받은 방에 참가해 보세요.':'여섯섬에 잘 왔어요! 친구에게 다가가 인사해 보세요.');chime(sound)};
 const accept=()=>{update(s=>({...s,accepted:s.accepted.includes(npc)?s.accepted:[...s.accepted,npc]}));tell('친구의 부탁을 수첩에 적었어요.');close()};
 const deliver=()=>{const next=handIn(saveRef.current,npc);if(!next)return;update(()=>next);chime(sound);tell('고마워!  ♥ +2  ·  도토리 +25');close()};
 const gift=(item:Resource)=>{if(saveRef.current.bag[item]<1)return;update(s=>({...s,bag:{...s.bag,[item]:s.bag[item]-1},hearts:s.hearts.map((h,i)=>i===npc?Math.min(5,h+1):h)}));chime(sound);tell(`${save.names[npc]}에게 ${ITEMS[item].name}를 선물했어요. ♥ +1`);close()};
 const purchase=(id:string)=>{const next=buy(saveRef.current,id);if(!next){tell('도토리나 주머니 공간이 부족해요.');return}update(()=>next);chime(sound);tell('구입했어요! 주머니에서 꺼내 섬에 놓아 보세요.')};
 const sell=(item:Resource)=>{if(saveRef.current.bag[item]<1)return;update(s=>({...s,coins:s.coins+ITEMS[item].price,bag:{...s.bag,[item]:s.bag[item]-1}}));chime(sound,[523,659]);tell(`${ITEMS[item].name} 1개 판매 · 도토리 +${ITEMS[item].price}`)};
 const place=(p:Point)=>{if(homePosition.current){tell('가구는 내 섬으로 돌아가서 놓아 주세요.');setPlacing(null);return;}const id=placing;if(!id||!walkable(p))return;update(s=>{const i=s.decor.indexOf(id);if(i<0)return s;return {...s,decor:s.decor.filter((_,j)=>i!==j),placed:[...s.placed,{id:`d${Date.now()}`,kind:id,...p}]}});setPlacing(null);chime(sound);tell('우리 섬이 조금 더 근사해졌어요! 가까이서 E를 누르면 회수할 수 있어요.')};
 const startFishing=()=>{if(fishTimeout.current)clearTimeout(fishTimeout.current);setFishPhase('waiting');fishTimeout.current=setTimeout(()=>{fishStart.current=performance.now();setFishPhase('reel');chime(sound,[440,880])},1400+Math.random()*1800)};
 const greenWidth=Math.min(44,26+fishMisses*6),greenStart=50-greenWidth/2;
 useEffect(()=>{if(fishPhase!=='reel'||panel!=='fish')return;let f=0;const tick=()=>{setFishCursor((Math.sin((performance.now()-fishStart.current)/420)+1)*50);f=requestAnimationFrame(tick)};f=requestAnimationFrame(tick);return()=>cancelAnimationFrame(f)},[fishPhase,panel]);
 const reel=()=>{if(fishPhase!=='reel')return;const v=(Math.sin((performance.now()-fishStart.current)/420)+1)*50;if((v>=greenStart&&v<=greenStart+greenWidth)||fishMisses>=2){setFishPhase('success');setFishMisses(0);update(s=>({...s,bag:{...s.bag,fish:s.bag.fish+1},fishCaught:s.fishCaught+1,coins:s.coins+5}));chime(sound,[523,659,784,1046])}else{setFishPhase('miss');setFishMisses(n=>n+1)}};
 useEffect(()=>{if(panel!=='fish')return;const listener=(e:KeyboardEvent)=>{if(e.code==='Space'&&!e.repeat){e.preventDefault();if(fishPhase==='reel')reel();else if(fishPhase==='ready'||fishPhase==='miss'||fishPhase==='success')startFishing()}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[panel,fishPhase,fishMisses]);
 const dayTasks=[{label:'섬의 선물 5개 줍기',value:Math.min(save.harvested,5),max:5},{label:'친구 3명과 인사하기',value:Math.min(save.talked.length,3),max:3},{label:'물고기 1마리 낚기',value:Math.min(save.fishCaught,1),max:1},{label:'섬에 장식 하나 놓기',value:Math.min(save.placed.length,1),max:1}];
 const allDayDone=dayTasks.every(t=>t.value===t.max);
 const startPicnic=()=>{if(saveRef.current.done.length<5||saveRef.current.bag.apple<2||saveRef.current.bag.fish<1)return;update(s=>({...s,bag:{...s.bag,apple:s.bag.apple-2,fish:s.bag.fish-1},picnic:true,coins:s.coins+100}));setPanel('celebrate');chime(sound,[523,659,784,1046,1318])};
 const exportSave=()=>{const blob=new Blob([JSON.stringify({...saveRef.current,position:storedPosition()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='여섯섬-저장.json';a.click();URL.revokeObjectURL(url)};
 const resetProgress=()=>{
  let clean:Save;
  try{clean=persistence.reset()}catch{tell('저장 데이터를 지우지 못했어요. 브라우저의 저장 공간 접근을 확인해 주세요.');return}
  multiplayer.leave();homePosition.current=null;setInvitation('');history.replaceState(null,'',window.location.pathname+window.location.search);
  if(fishTimeout.current){clearTimeout(fishTimeout.current);fishTimeout.current=null}
  fishStart.current=0;soundRef.current=false;music(false);
  saveRef.current=clean;setSave(clean);setHasSave(false);setSelected(0);setNpc(1);
  setNear(null);setPlacing(null);setFishPhase('ready');setFishCursor(0);setFishMisses(0);
  setZoom(1);setNight(false);setSound(false);setActiveRegion('village');setJournalOpen(true);
  setReady(false);setAssetError(false);setWorldEpoch(value=>value+1);
  setResetOpen(false);setPanel('start');setSaveStatus('새 친구를 선택해 주세요');
  setMessage('초기화했어요. 새 캐릭터로 섬 생활을 시작해 보세요.');
 };
 const downloadPhoto=()=>{const url=world.current?.snapshot();if(!url)return;const a=document.createElement('a');a.href=url;a.download='여섯섬-추억.png';a.click();tell('섬의 모습을 사진으로 저장했어요.')};
 const q=requestFor(save.character,npc),canDeliver=save.accepted.includes(npc)&&save.bag[q.item]>=q.count;
 return <main className={`island-app ${night?'night':''}`}>
 {initialized&&<World key={worldEpoch} save={save} paused={panel!==null||resetOpen} zoom={zoom} night={night} placing={placing} onAct={interact} onNear={setNear} onPlace={place} onRegion={arriveRegion} api={world} onReady={ok=>{setReady(ok);setAssetError(!ok)}} network={multiplayer} visiting={visiting}/>}
 <div className="edge-shade" aria-hidden="true"/>
 <header className="topbar"><div className="brand"><span className="brand-mark"><Leaf size={27}/></span><div><span className="eyebrow">OUR LITTLE ISLAND</span><h1>우리들의 여섯섬</h1></div></div><div className="weather"><Sun size={23}/><div><strong>{clock}</strong><span>9월의 어느 좋은 날</span></div></div><div className="top-actions"><div className="coin-pill"><span>🌰</span><strong>{save.coins.toLocaleString()}</strong></div><button className="icon-btn" onClick={()=>{setSound(!sound);music(!sound)}} title={sound?'소리 끄기':'소리 켜기'} aria-label={sound?'소리 끄기':'소리 켜기'}>{sound?<Volume2/>:<VolumeX/>}</button><button className="icon-btn" onClick={()=>open('settings')} aria-label="설정"><Settings/></button></div></header>
 {panel!=='start'&&<>
 <div className="online-hud"><button className={`online-toggle ${online.status==='connected'?'connected':''}`} onClick={()=>open('online')}><Users size={18}/><span>{online.status==='connected'?`함께 놀기 · ${online.players.length}명`:online.status==='connecting'?'친구와 연결 중…':'친구와 함께 놀기'}</span>{online.status==='connected'&&<span className="online-dot"/>}</button>{online.status==='connected'&&<div className="quick-emotes">{EMOTES.slice(0,3).map(emote=><button key={emote} aria-label={`${emote} 보내기`} onClick={()=>multiplayer.sendEmote(emote)}>{emote}</button>)}</div>}</div>
 <aside className="friend-rail"><span className="rail-title">우리 여섯</span>{FRIENDS.map((f,i)=><button key={f.name} className={`friend-orb ${i===save.character?'selected':''}`} style={{'--friend-color':f.color} as React.CSSProperties} aria-label={i===save.character?`내 캐릭터 ${save.names[i]}`:`${save.names[i]}에게 찾아가기`} title={save.names[i]} onClick={()=>{if(i===save.character)open('friends');else go({...f,id:String(i),type:'friend',label:`${save.names[i]}와 대화`})}}><Avatar id={i}/>{i===save.character?<span className="you-dot">나</span>:save.done.includes(i)?<span className="done-dot"><Check size={12}/></span>:null}</button>)}</aside>
 <aside className={`quest-card ${journalOpen?'':'collapsed'}`}><button className="quest-heading" onClick={()=>setJournalOpen(!journalOpen)}><span className="quest-icon"><BookOpen size={19}/></span><strong>오늘의 작은 행복</strong><span>{journalOpen?'−':'+'}</span></button>{journalOpen&&<><p className="quest-intro">서두르지 않아도 괜찮아</p>{dayTasks.map((t,i)=><button className="quest-row" key={t.label} onClick={()=>i===0?go({...NODES[0],type:'node',label:'사과 줍기'}):i===1?open('friends'):i===2?goSpot('fish'):open('bag')}><span className={`task-check ${t.value===t.max?'checked':''}`}>{t.value===t.max&&<Check size={13}/>}</span><span>{t.label}</span><small>{t.value}/{t.max}</small></button>)}<div className="quest-divider"/><button className="picnic-link" onClick={()=>open('journal')}><span>🧺 함께 소풍 가는 날</span><b>{save.done.length}/5 <ChevronRight size={14}/></b></button><Progress value={save.done.length*20} className="quest-progress" aria-label="소풍 부탁 완료"/>{allDayDone&&!save.dayReward&&<button className="primary small" onClick={()=>{update(s=>({...s,coins:s.coins+40,dayReward:true}));tell('오늘의 작은 행복 완료! 도토리 +40')}}>선물 받기 🌰 40</button>}{save.dayReward&&<span className="reward-done">오늘의 선물을 받았어요 ✓</span>}</>}</aside>
 <div className="location-pill"><MapPin size={16}/><span>{placing?'우리 섬 꾸미는 중':REGIONS.find(r=>r.id===activeRegion)?.name||'여섯섬 · 산책길'}</span><span className="live-dot"/></div>
 <div className="side-tools"><button className="icon-btn" aria-label="전체 지도" title="전체 지도 (M)" onClick={()=>open('map')}><MapPin/></button><button className="icon-btn" aria-label="확대" onClick={()=>setZoom(z=>Math.min(1.8,z+.15))}><Plus/></button><button className="icon-btn" aria-label="축소" onClick={()=>setZoom(z=>Math.max(1,z-.15))}><Minus/></button><button className="icon-btn" aria-label="섬 사진 저장" onClick={downloadPhoto}><Camera/></button><button className="icon-btn" aria-label="조작 안내" onClick={()=>open('help')}><HelpCircle/></button></div>
 <div className="bottom-area">{placing?<div className="action-hint placement"><span>{DECOR.find(d=>d.id===placing)?.emoji} 원하는 땅을 눌러 놓아 주세요</span><button onClick={()=>setPlacing(null)} aria-label="배치 취소"><X size={18}/></button></div>:near?<button className="action-hint" onClick={()=>interact(near)}><kbd>E</kbd>{near.label}<span className="hint-touch">누르기</span></button>:<div className="walking-hint">가고 싶은 곳을 누르거나 방향키로 걸어 보세요</div>}<nav className="dock" aria-label="게임 메뉴"><button onClick={()=>open('bag')}><Backpack/><span>주머니</span><kbd>B</kbd></button><button onClick={()=>open('journal')}><BookOpen/><span>섬 수첩</span><kbd>J</kbd></button><button onClick={()=>open('friends')}><Users/><span>친구들</span></button><i/><button onClick={()=>goSpot('home')}><Home/><span>우리 집</span></button><button onClick={()=>goSpot('shop')}><ShoppingBag/><span>상점</span></button></nav><span className="keyboard-tip"><kbd>W A S D</kbd> 이동 <span>·</span> <kbd>Shift</kbd> 달리기 <span>·</span> <kbd>M</kbd> 지도 <span>·</span> <kbd>E</kbd> 대화 / 줍기 <span>·</span> <span>{saveStatus}</span></span></div>
 <div className="touch-pad">{[['arrowup',ArrowUp],['arrowleft',ArrowLeft],['arrowdown',ArrowDown],['arrowright',ArrowRight]].map(([key,Icon])=>{const C=Icon as typeof ArrowUp;return <button key={String(key)} className={String(key)} aria-label={String(key)} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);world.current?.key(String(key),true)}} onPointerUp={()=>world.current?.key(String(key),false)} onPointerCancel={()=>world.current?.key(String(key),false)} onLostPointerCapture={()=>world.current?.key(String(key),false)}><C size={20}/></button>})}</div>
 </>}
 {message&&<div className="game-toast" role="status"><span>✦</span>{message}</div>}
 <PanelShell open={panel==='start'} title="여섯이라서, 더 좋은 섬." description={hasSave?'우리들의 느긋한 하루가 기다리고 있어요.':'오늘은 누구의 하루를 살아 볼까요?'} onClose={()=>{if(hasSave&&ready)close()}} wide><div className="start-emblem">🌿</div><div className="character-grid">{FRIENDS.map((f,i)=><button key={i} className={`character-card ${selected===i?'chosen':''}`} style={{'--friend-color':f.color} as React.CSSProperties} disabled={hasSave&&save.character!==i} onClick={()=>setSelected(i)}><span className="character-stage"><Avatar id={i}/></span><strong>{save.names[i]}</strong><small>{f.look}</small>{selected===i&&<span className="choose-check"><Check size={14}/></span>}</button>)}</div><p className="start-note">여섯 친구와 호현 촌장이 함께하는 더 넓어진 섬. 이름은 설정에서 바꿀 수 있어요.</p><button className="primary start-button" disabled={!ready||!initialized} onClick={selectCharacter}>{assetError?'그림을 불러오지 못했어요 · 새로고침해 주세요':!ready?'섬으로 가는 배를 준비하고 있어요…':hasSave?'우리 섬 이어서 놀기':'이 친구로 섬에 놀러 가기'} <ArrowRight size={20}/></button><span className="start-foot">산책하고, 선물하고, 함께 소풍 가요.</span></PanelShell>
 <PanelShell open={panel==='bag'} title="차곡차곡, 내 주머니" description="모은 재료로 친구를 도와주거나 상점에서 도토리로 바꿔 보세요." onClose={close} wide><div className="inventory-grid">{(Object.keys(ITEMS) as Resource[]).map(k=><div className={`inventory-item ${save.bag[k]?'':'empty'}`} key={k}><span>{ITEMS[k].emoji}</span><strong>{ITEMS[k].name}</strong><b>× {save.bag[k]}</b></div>)}</div><h3 className="section-label">섬에 놓을 장식 <span>{save.decor.length}개</span></h3>{save.decor.length?<div className="decoration-list">{save.decor.map((id,i)=>{const d=DECOR.find(x=>x.id===id)!;return <button key={`${id}${i}`} onClick={()=>{if(visiting){tell('방문 중에는 방장이 가구를 꾸밀 수 있어요. 내 섬에서 꺼내 놓아 주세요.');return;}close();setPlacing(id)}}><span>{d.emoji}</span><strong>{d.name}</strong><small>꺼내 놓기</small></button>})}</div>:<div className="empty-state"><span>🧺</span><p>마음에 드는 장식 하나로<br/>우리 섬을 꾸며 볼까요?</p><button className="secondary" onClick={()=>goSpot('shop')}>상점으로 산책하기 <ArrowRight size={16}/></button></div>}</PanelShell>
 <PanelShell open={panel==='journal'} title="우리들의 섬 수첩" description="친구 다섯 명의 부탁을 들어주고, 여섯이 함께 소풍을 떠나요." onClose={close} wide><div className="journal-summary"><span>🧺</span><div><strong>{save.picnic?'함께여서 완벽했던 소풍':'함께 소풍 가는 날'}</strong><p>{save.picnic?'우리의 첫 추억이 생겼어요. 섬 생활은 계속돼요.':`준비가 하나씩 모이고 있어요 · ${save.done.length} / 5`}</p></div></div><div className="request-list">{FRIENDS.map((f,i)=>{if(i===save.character)return null;const r=requestFor(save.character,i),done=save.done.includes(i);return <button key={i} onClick={()=>go({...f,id:String(i),type:'friend',label:`${save.names[i]}와 대화`})}><Avatar id={i}/><div><strong>{save.names[i]}의 {r.title}</strong><span>{done?'고마워! 소풍에서 만나자.':save.accepted.includes(i)?`${ITEMS[r.item].emoji} ${ITEMS[r.item].name} ${save.bag[r.item]}/${r.count}`:'이야기를 나누고 부탁을 들어 보세요.'}</span></div>{done?<span className="status-chip">완료 <Check size={13}/></span>:<ChevronRight size={18}/>}</button>})}</div><button className="primary" onClick={()=>goSpot('picnic')}>소풍 자리로 가기 <ArrowRight size={18}/></button></PanelShell>
 <PanelShell open={panel==='friends'} title="우리 섬의 여섯 친구" description="사진 속 모습에서 출발한 우리들. 게임 속 이름은 자유롭게 바꿀 수 있어요." onClose={close} wide><div className="friends-grid">{FRIENDS.map((f,i)=><div className="friend-card" key={i}><Avatar id={i}/><strong>{save.names[i]} {i===save.character&&<span>나</span>}</strong><small>{f.look}</small><div className="hearts">{[0,1,2,3,4].map(h=><Heart key={h} size={15} fill={h<save.hearts[i]?'currentColor':'none'}/>)}</div><button className="secondary small" onClick={()=>i===save.character?open('settings'):go({...f,id:String(i),type:'friend',label:`${save.names[i]}와 대화`})}>{i===save.character?'이름 바꾸기':'찾아가기'}</button></div>)}</div><div className="mayor-card"><MayorAvatar/><div><small>우리 마을의 촌장</small><strong>호현</strong><p>모험을 좋아하는 든든한 길잡이</p></div><button className="secondary small" onClick={goMayor}>찾아가기</button></div></PanelShell>
 <PanelShell open={panel==='dialogue'} title={save.names[npc]} description={FRIENDS[npc].look} onClose={close}><div className="dialogue-person" style={{background:FRIENDS[npc].color}}><Avatar id={npc}/></div><p className="speech">“{save.done.includes(npc)?'네 덕분에 준비가 끝났어. 다 같이 소풍 가는 거, 정말 기대돼!':save.accepted.includes(npc)?q.text:FRIENDS[npc].greeting}”</p>{!save.done.includes(npc)&&<div className="request-box"><small>🧺 {q.title}</small><p>{q.text}</p><strong>{ITEMS[q.item].emoji} {ITEMS[q.item].name} {save.bag[q.item]} / {q.count}</strong><span>보답 🌰 25 · ♥ 2</span></div>}{!save.done.includes(npc)?save.accepted.includes(npc)?<button className="primary" disabled={!canDeliver} onClick={deliver}>{canDeliver?'준비한 재료 건네기':'재료를 모아서 다시 올게!'}</button>:<button className="primary" onClick={accept}>내가 준비해 올게!</button>:<button className="primary" onClick={close}>이따 소풍에서 보자!</button>}<div className="gift-row"><span>작은 선물</span><button disabled={save.bag.apple<1||save.hearts[npc]>=5} onClick={()=>gift('apple')}>🍎 사과 1개</button><button disabled={save.bag.flower<1||save.hearts[npc]>=5} onClick={()=>gift('flower')}>🌼 들꽃 1개</button></div></PanelShell>
 <PanelShell open={panel==='shop'} title="도토리 상점" description="숲에서 모은 작은 것들이, 우리 섬의 새 가구가 돼요." onClose={close} wide><div className="shop-balance">내 도토리 <strong>🌰 {save.coins}</strong></div><div className="shop-grid">{DECOR.map(d=><div className="shop-item" key={d.id}><span>{d.emoji}</span><strong>{d.name}</strong><button className="secondary" disabled={save.coins<d.price} onClick={()=>purchase(d.id)}>🌰 {d.price} · 구입</button></div>)}</div><h3 className="section-label">하나씩 판매하기</h3><p className="muted">친구에게 줄 재료는 남겨 두세요. 채집물은 30초 뒤 다시 생겨요.</p><div className="sell-list">{(Object.keys(ITEMS) as Resource[]).map(k=><button key={k} disabled={!save.bag[k]} onClick={()=>sell(k)}><span>{ITEMS[k].emoji} {ITEMS[k].name} <small>×{save.bag[k]}</small></span><b>+{ITEMS[k].price} 🌰</b></button>)}</div></PanelShell>
 <PanelShell open={panel==='home'} title="우리 집 앞마당" description="마음에 드는 물건을 꺼내 우리 섬에 놓아 보세요." onClose={close}><div className="home-illustration">🏡</div><p className="speech">작은 집, 커다란 취향.<br/>오늘은 어디를 꾸며 볼까요?</p><div className="home-stats"><span>놓은 장식 <b>{save.placed.length}</b></span><span>주머니 속 장식 <b>{save.decor.length}</b></span></div><button className="primary" onClick={()=>open('bag')}>장식 꺼내 놓기</button><button className="secondary" onClick={()=>goSpot('shop')}>상점 둘러보기</button><p className="muted centered">놓은 장식은 가까이 다가가 E를 눌러 회수할 수 있어요.</p></PanelShell>
 <PanelShell open={panel==='fish'} title="물가에서, 잠깐의 느긋함" description="입질이 오면 초록 구간에 맞춰 낚싯대를 당겨 주세요." onClose={close}><div className={`fishing-scene ${fishPhase}`}><span className="fish-emoji">{fishPhase==='success'?'🐟':'🎣'}</span><span className="ripple r1"/><span className="ripple r2"/></div><p className="fish-message">{({ready:'여기엔 어떤 물고기가 살고 있을까?',waiting:'찌가 살랑살랑… 조금만 기다려요.',reel:'입질이다! 초록 구간에서 당겨요!',success:'잡았다! 물고기 1마리 · 도토리 +5',miss:'앗, 놓쳤다! 다음엔 더 쉽게 잡을 수 있어요.'})[fishPhase]}</p>{fishPhase==='reel'&&<div className="fishing-meter" aria-label="낚시 타이밍"><div className="success-zone" style={{left:`${greenStart}%`,width:`${greenWidth}%`}}/><span className="fishing-cursor" style={{left:`${fishCursor}%`}}/></div>}<button className="primary" disabled={fishPhase==='waiting'} onClick={fishPhase==='reel'?reel:startFishing}>{fishPhase==='waiting'?'물고기를 기다리는 중…':fishPhase==='reel'?'지금 당기기!':fishPhase==='success'?'한 번 더 낚아 볼까?':'낚싯대 던지기'}</button><span className="muted centered">버튼 또는 스페이스바 · 미끼는 필요 없어요</span></PanelShell>
 <PanelShell open={panel==='picnic'} title={save.picnic?'우리의 첫 소풍':'여섯이 모이는 자리'} description="다 같이 모이면 평범한 하루도 특별해져요." onClose={close}><div className="picnic-art">🧺 🌼 🍎</div>{save.picnic?<><p className="speech">웃음소리, 맛있는 간식, 그리고 우리 여섯.<br/>오래 기억할 하루가 되었어요.</p><button className="primary" onClick={()=>open('celebrate')}>우리의 소풍 다시 보기</button></>:<><div className="picnic-requirements"><p><span>친구들의 소풍 준비</span><b>{save.done.length} / 5</b></p><p><span>🍎 함께 먹을 사과</span><b>{save.bag.apple} / 2</b></p><p><span>🐟 오늘의 요리</span><b>{save.bag.fish} / 1</b></p></div><button className="primary" disabled={save.done.length<5||save.bag.apple<2||save.bag.fish<1} onClick={startPicnic}>다 같이 소풍 시작하기</button><button className="secondary" onClick={()=>open('journal')}>친구들의 부탁 확인하기</button></>}</PanelShell>
 <PanelShell open={panel==='celebrate'} title="함께여서, 참 좋은 하루." description="우리 여섯의 첫 번째 섬 소풍" onClose={close} wide><div className="celebration"><div className="confetti" aria-hidden="true">✦ · ✧ · ✦ · ✧ · ✦</div><div className="group-photo">{FRIENDS.map((_,i)=><div key={i}><Avatar id={i}/><span>{save.names[i]}</span></div>)}</div><div className="picnic-table">🌼 🧺 🍎 🐟 🍹</div></div><p className="speech">급할 것 없는 섬에서, 우리다운 하루를.<br/>내일도 여기서 만나자.</p><span className="completion-badge"><Check size={16}/> 첫 소풍 완료 · 도토리 100개 선물</span><button className="primary" onClick={close}>우리 섬에서 계속 놀기 <Heart size={17}/></button></PanelShell>
 <PanelShell open={panel==='help'} title="천천히, 섬 생활 안내" description="정답도 시간제한도 없어요. 마음 가는 대로 놀아 보세요." onClose={close}><div className="help-list"><p><kbd>W A S D</kbd><span>방향키로 걷거나, 바닥을 눌러 이동해요.</span></p><p><kbd>M</kbd><span>전체 지도에서 목적지를 고르면 자동으로 걸어가요.</span></p><p><kbd>Shift</kbd><span>이동하며 누르면 더 빠르게 달려요.</span></p><p><kbd>E</kbd><span>호현 촌장이나 친구와 대화하고, 반짝이는 재료를 주워요.</span></p><p><span>🎣</span><span>낚시터에서 초록 구간에 맞춰 버튼을 눌러요.</span></p><p><span>🧺</span><span>친구 5명의 부탁을 들어주고 소풍을 열어요.</span></p><p><span>🪴</span><span>상점에서 장식을 사고, 주머니에서 꺼내 놓아요.</span></p></div><p className="muted">진행은 현재 브라우저에 저장돼요. 기기를 옮길 때는 설정에서 저장 파일을 내보내 주세요.</p><button className="primary" onClick={close}>좋아, 산책하러 가자!</button></PanelShell>
 <PanelShell open={panel==='settings'} title="우리다운 섬으로" description="친구들의 실제 이름이나 좋아하는 별명을 적어 주세요." onClose={close} wide><div className="name-grid">{FRIENDS.map((_,i)=><label key={i}><Avatar id={i}/><span>{FRIENDS[i].look}<input aria-label={`${FRIENDS[i].look} 이름`} value={save.names[i]} maxLength={12} onChange={e=>{const value=e.target.value;update(s=>({...s,names:s.names.map((name,j)=>j===i?value:name)}))}} onBlur={()=>update(s=>({...s,names:s.names.map((name,j)=>name.trim()||FRIENDS[j].name)}))}/></span></label>)}</div><div className="setting-row"><span>섬의 시간</span><button className="secondary small" onClick={()=>setNight(!night)}>{night?<Moon size={16}/>:<Sun size={16}/>} {night?'달빛 저녁':'햇살 오후'}</button></div><div className="setting-row"><span>잔잔한 섬의 멜로디</span><button className="secondary small" onClick={()=>{setSound(!sound);music(!sound)}}>{sound?'켜짐':'꺼짐'}</button></div><div className="backup-actions"><button className="secondary" onClick={exportSave}>저장 파일 내보내기</button><label className="secondary file-label">저장 파일 불러오기<input type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1024*1024){tell('저장 파일이 너무 커요.');return}const generation=persistence.beginImport();const raw=await file.text();if(!persistence.isCurrentImport(generation))return;const loaded=hydrate(raw);if(!loaded){tell('여섯섬 저장 파일을 확인해 주세요.');return}multiplayer.leave();persistence.activate();update(()=>loaded);setWorldEpoch(n=>n+1);setHasSave(true);setSelected(loaded.character);tell('저장된 섬 생활을 불러왔어요.');close()}}/></label></div><div className="reset-section"><div><strong>섬 생활 초기화</strong><p>진행 상황을 지우고 새 캐릭터로 처음부터 시작해요.</p></div><button className="reset-button" onClick={()=>setResetOpen(true)}>처음부터 시작</button></div><p className="muted centered">{saveStatus} · 원본 사진은 게임에 포함되지 않아요.</p></PanelShell>
 <PanelShell open={panel==='map'} title="새로운 길이 기다리는 여섯섬" description="과수원부터 숲, 호수와 해변까지. 목적지를 골라 산책해요." onClose={close} wide><IslandMap save={{...save,position:world.current?.position()??save.position}} onRegion={goRegion} onMayor={goMayor}/></PanelShell>
 <PanelShell open={panel==='mayor'} title="촌장 호현" description={MAYOR.look} onClose={close}>
  <div className="mayor-portrait"><MayorAvatar/><span>여섯섬 마을 사무소</span></div>
  <p className="speech">“{save.explorationReward?'멋진 탐험이었어! 이제 이 섬의 길은 너도 훤히 알겠네. 언제든 놀러 와!':MAYOR.greeting}”</p>
  <div className="exploration-request"><strong>호현의 섬 한 바퀴</strong><p>다섯 지역을 모두 둘러보고 돌아와 줘. 탐험 선물을 준비해 둘게!</p><div className="exploration-stamps">{REGIONS.map(r=><span key={r.id} className={save.explored.includes(r.id)?'stamped':''} title={r.name}>{r.emoji}<small>{r.name}</small>{save.explored.includes(r.id)&&<Check size={13}/>}</span>)}</div><b>{save.explored.length} / {REGIONS.length} 방문 · 보답 🌰 100</b></div>
  {!save.explorationReward&&<button className="primary" disabled={save.explored.length<REGIONS.length} onClick={receiveExploration}>{save.explored.length===REGIONS.length?'촌장의 탐험 선물 받기':'섬을 더 둘러보고 올게!'}</button>}
  {save.explorationReward&&<span className="completion-badge"><Check size={16}/> 호현의 탐험 선물을 받았어요</span>}
  <button className="secondary" onClick={()=>open('map')}>촌장님의 섬 지도 보기 <MapPin size={17}/></button>
 </PanelShell>
 <PanelShell open={panel==='online'} title="친구와 함께 놀기" description="초대 링크 하나로, 같은 섬에서 만나세요." onClose={close} wide><MultiplayerPanel session={multiplayer} view={online} initialCode={invitation} onHost={hostRoom} onJoin={joinRoom} onWalk={close}/></PanelShell>
 <AlertDialog open={resetOpen} onOpenChange={setResetOpen}>
  <AlertDialogContent className="reset-dialog">
   <AlertDialogHeader><AlertDialogTitle>섬 생활을 처음부터 시작할까요?</AlertDialogTitle><AlertDialogDescription>소지품, 도토리, 가구, 친구 이름과 부탁, 탐험 기록을 모두 지우고 캐릭터 선택 화면으로 돌아갑니다. 저장 파일을 내보냈다면 나중에 다시 불러올 수 있어요.</AlertDialogDescription></AlertDialogHeader>
   <AlertDialogFooter><AlertDialogCancel>취소하고 계속하기</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={resetProgress}>초기화하고 새로 시작</AlertDialogAction></AlertDialogFooter>
  </AlertDialogContent>
 </AlertDialog>
 <KeyboardShortcuts disabled={resetOpen} panel={panel} onOpen={open} onClose={close} onCancelPlace={()=>setPlacing(null)}/>
 </main>
}
function KeyboardShortcuts({panel,onOpen,onClose,onCancelPlace,disabled}:{panel:Panel;disabled:boolean;onOpen:(p:Panel)=>void;onClose:()=>void;onCancelPlace:()=>void}){useEffect(()=>{const handle=(e:KeyboardEvent)=>{if(disabled)return;if((e.target as HTMLElement).matches('input,textarea,select'))return;if(e.key==='Escape'){if(panel==='start')return;onCancelPlace();onClose()}if(panel!==null)return;if(e.key.toLowerCase()==='b')onOpen('bag');if(e.key.toLowerCase()==='j')onOpen('journal');if(e.key.toLowerCase()==='m')onOpen('map')};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle)},[panel,onOpen,onClose,onCancelPlace,disabled]);return null}
