'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Check,Hammer,Home,Leaf,MapPin,Package,Plus,ShoppingBag,Sprout} from 'lucide-react';
import {ITEMS,type Resource,type Save} from './game-data';
import {COLLECTION,CROPS,DECOR,MEALS,RECIPES,buySeeds,cook,craft,cropProgress,dailyGift,donate,harvest,roomCapacity,seed,sellProduce,today,transfer,upgradeHome,water,type Crop,type RoomID} from './life-data';

export type LifePanelKind='life'|'craft'|'garden'|'museum'|'cafe'|'home';
export const LIFE_TITLES:Record<LifePanelKind,string>={life:'하고 싶은 일이 많은 섬',craft:'뚝딱뚝딱, 나만의 가구',garden:'햇살을 먹고 자라는 텃밭',museum:'차곡차곡, 여섯섬 박물관',cafe:'오늘의 노을 카페',home:'우리 집, 우리 취향'};
export function FurnitureIcon({id,className=''}:{id:string;className?:string}){const index=DECOR.findIndex(d=>d.id===id);return <span role="img" aria-label={DECOR[index]?.name||'가구'} className={'furniture-art '+className} style={{backgroundPosition:`${(index%4)*100/3}% ${Math.floor(index/4)*100/3}%`}}/>;}
type Apply=(fn:(s:Save)=>Save|null,message:string)=>void;
export function SeedShop({save,apply}:{save:Save;apply:Apply}){return <><h3 className="section-label">텃밭 씨앗</h3><div className="seed-shop">{(Object.keys(CROPS) as Crop[]).map(c=><div key={c}><span>{CROPS[c].emoji}</span><strong>{CROPS[c].name} 씨앗</strong><small>가지고 있는 씨앗 {save.life.seeds[c]}개</small><button className="secondary small" disabled={save.coins<CROPS[c].seedPrice} onClick={()=>apply(s=>buySeeds(s,c),'씨앗을 샀어요. 햇살 텃밭에 심어 보세요.')}><Plus size={14}/> 🌰 {CROPS[c].seedPrice}</button></div>)}</div></>;}
export function LifePanel({kind,save,apply,onNavigate,onBag,visiting,currentRoom,initialPlot=0}:{kind:LifePanelKind;save:Save;apply:Apply;onNavigate:(id:string)=>void;onBag:()=>void;visiting:boolean;currentRoom:RoomID;initialPlot?:number}){
 const [selected,setSelected]=useState(initialPlot),[crop,setCrop]=useState<Crop>('carrot'),[now,setNow]=useState(Date.now()),[category,setCategory]=useState('전체');
 useEffect(()=>{if(kind!=='garden')return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[kind]);
 useEffect(()=>setSelected(initialPlot),[initialPlot]);
 if(kind==='life')return <div className="life-hub"><div className="life-intro"><span>🌿</span><div><strong>오늘은 어떤 하루를 보낼까요?</strong><p>문을 열고 들어가서, 우리다운 섬을 만들어 봐요.</p></div></div><div className="life-destinations">{[{id:'home',title:'우리 집',text:'가구 배치 · 수납함',icon:Home},{id:'shop',title:'도토리 상점',text:'가구 16종 · 씨앗',icon:ShoppingBag},{id:'workshop',title:'뚝딱 공방',text:'모은 재료로 가구 만들기',icon:Hammer},{id:'garden',title:'햇살 텃밭',text:'씨앗 심기 · 물주기 · 수확',icon:Sprout},{id:'museum',title:'여섯섬 박물관',text:'12종 수집 · 기증',icon:Package},{id:'cafe',title:'노을 카페',text:'수확한 채소로 요리하기',icon:Leaf}].map(({id,title,text,icon:Icon})=><button key={id} onClick={()=>onNavigate(id)}><Icon/><strong>{title}</strong><small>{text}</small><ArrowRight size={17}/></button>)}</div><div className="daily-gift"><div><strong>오늘도 반가워요 🌰</strong><p>하루 한 번, 섬에서 보내는 작은 선물</p></div><button className="primary small" disabled={save.life.stamps.includes(today())} onClick={()=>apply(s=>dailyGift(s),'오늘의 출석 선물! 도토리 +40')}>{save.life.stamps.includes(today())?'오늘 선물 받음 ✓':'40개 받기'}</button></div><div className="life-stats"><span>만든 가구 <b>{save.life.crafted}</b></span><span>수확 <b>{save.life.harvests}</b></span><span>기증 <b>{save.life.donated.length}/12</b></span><span>요리 <b>{save.life.cooked}</b></span></div></div>;
 if(kind==='craft')return <><div className="material-strip">🪵 {save.bag.wood} <span/> 🌼 {save.bag.flower} <span/> 🐚 {save.bag.shell}</div><p className="muted">숲에서 모은 재료를 작업대에 올려 보세요. 만든 가구는 주머니에 담겨요.</p><div className="recipe-grid">{RECIPES.map(r=><div className="recipe-card" key={r.id}><FurnitureIcon id={r.id}/><strong>{r.name}</strong><p>🪵 {r.wood}{r.flower>0&&` · 🌼 ${r.flower}`}{r.shell>0&&` · 🐚 ${r.shell}`}</p><button className="secondary small" disabled={save.bag.wood<r.wood||save.bag.flower<r.flower||save.bag.shell<r.shell||save.decor.length+save.placed.length>=50} onClick={()=>apply(s=>craft(s,r.id),r.name+' 완성! 주머니에서 꺼내 놓아 보세요.')}><Hammer size={15}/> 만들기</button></div>)}</div><button className="primary" onClick={onBag}>만든 가구 꺼내 보기</button></>;
 if(kind==='garden'){
  const plot=save.life.plots[selected],progress=cropProgress(plot,now),ready=progress>=1;
  return <><p className="muted">한 번 심으면 채소 2개를 수확해요. 물을 주면 약 44–77초 만에 자라요. 게임을 꺼도 성장이 이어집니다.</p><div className="garden-grid">{save.life.plots.map((p,i)=><button key={i} className={selected===i?'selected':''} onClick={()=>setSelected(i)}><small>{i+1}번 밭</small><span>{p.crop?(cropProgress(p,now)>=1?CROPS[p.crop].emoji:'🌱'):'＋'}</span><strong>{p.crop?CROPS[p.crop].name:'빈 텃밭'}</strong><div className="crop-track"><i style={{width:cropProgress(p,now)*100+'%'}}/></div><small>{p.crop?(cropProgress(p,now)>=1?'수확할 수 있어요':p.watered?'촉촉하게 자라는 중':'물을 기다려요'):'씨앗을 심어 주세요'}</small></button>)}</div><div className="garden-actions"><strong>{selected+1}번 텃밭 돌보기</strong>{!plot.crop?<><div className="crop-choices">{(Object.keys(CROPS) as Crop[]).map(c=><button key={c} className={crop===c?'selected':''} onClick={()=>setCrop(c)}>{CROPS[c].emoji} {CROPS[c].name} <small>씨앗 {save.life.seeds[c]}</small></button>)}</div><button className="primary" disabled={save.life.seeds[crop]<1} onClick={()=>apply(s=>seed(s,selected,crop),CROPS[crop].name+' 씨앗을 심었어요. 물도 주세요!')}>씨앗 심기</button></>:ready?<button className="primary" onClick={()=>apply(s=>harvest(s,selected),'싱싱한 채소를 2개 수확했어요!')}>수확하기 {CROPS[plot.crop].emoji}</button>:<button className="primary" disabled={plot.watered} onClick={()=>apply(s=>water(s,selected),'물을 주었어요. 더 빨리 자랄 거예요.')}>{plot.watered?'물을 충분히 주었어요 ✓':'물 주기 💧'}</button>}</div><div className="inline-actions"><button className="secondary" onClick={()=>apply(s=>{let next=s;for(let i=0;i<6;i++)next=water(next,i)??next;return next===s?null:next;},'텃밭에 골고루 물을 주었어요.')}>모두 물 주기</button><button className="secondary" onClick={()=>apply(s=>{let next=s;for(let i=0;i<6;i++)next=harvest(next,i)??next;return next===s?null:next;},'다 자란 채소를 모두 수확했어요.')}>익은 채소 모두 수확</button></div><SeedShop save={save} apply={apply}/><button className="secondary" onClick={()=>onNavigate('cafe')}>수확한 채소로 요리하러 가기 →</button></>;
 }
 if(kind==='cafe')return <><div className="cafe-intro"><span>☕</span><strong>갓 수확한 채소, 따뜻한 한 접시.</strong><p>요리를 만들어 카페에 납품하면 도토리를 받아요.</p></div><div className="produce-strip">{(Object.keys(CROPS) as Crop[]).map(c=><span key={c}>{CROPS[c].emoji} {CROPS[c].name} <b>{save.life.produce[c]}</b></span>)}</div><div className="meal-grid">{MEALS.map(m=><div key={m.id}><span>{m.emoji}</span><strong>{m.name}</strong><p>{(Object.keys(CROPS) as Crop[]).filter(c=>m.needs[c]).map(c=>CROPS[c].emoji+' '+m.needs[c]).join(' · ')}</p><button className="primary small" disabled={(Object.keys(CROPS) as Crop[]).some(c=>save.life.produce[c]<m.needs[c])} onClick={()=>apply(s=>cook(s,m.id),m.name+'를 완성했어요! 도토리 +'+m.coins)}>만들고 납품 · 🌰 {m.coins}</button></div>)}</div><h3 className="section-label">채소 그대로 판매하기</h3><div className="inline-actions">{(Object.keys(CROPS) as Crop[]).map(c=><button className="secondary small" key={c} disabled={!save.life.produce[c]} onClick={()=>apply(s=>sellProduce(s,c),CROPS[c].name+'를 1개 판매했어요.')}>{CROPS[c].emoji} +{CROPS[c].price} 🌰</button>)}</div></>;
 if(kind==='museum')return <><div className="museum-progress"><span>🏛️</span><div><strong>우리 섬의 작은 자연사</strong><p>발견 {save.life.discovered.length} / 12 · 기증 {save.life.donated.length} / 12</p></div></div><div className="collection-tabs">{['전체','자연','물고기','곤충'].map(c=><button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>{currentRoom!=='museum'&&<button className="secondary" onClick={()=>onNavigate('museum')}><MapPin size={16}/> 박물관에 가서 기증하기</button>}<div className="collection-grid">{COLLECTION.filter(c=>category==='전체'||c.category===category).map(c=>{const found=save.life.discovered.includes(c.id),given=save.life.donated.includes(c.id),amount=Object.hasOwn(save.bag,c.id)?save.bag[c.id as Resource]:save.life.specimens[c.id]||0;return <div key={c.id} className={found?'':'undiscovered'}><span>{found||amount?c.emoji:'?'}</span><strong>{c.name}</strong><small>{c.note}</small><button className="secondary small" disabled={given||amount<1||currentRoom!=='museum'} onClick={()=>apply(s=>donate(s,c.id),c.name+' 기증 완료! 도토리 +30')}>{given?<><Check size={14}/> 기증 완료</>:amount>0?'1개 기증 · 🌰 +30':'아직 만나지 못했어요'}</button></div>;})}</div>{save.life.donated.length===12&&<button className="primary" disabled={save.life.museumReward} onClick={()=>apply(s=>s.life.museumReward?null:{...s,coins:s.coins+180,life:{...s.life,museumReward:true}},'박물관을 완성했어요! 도토리 +180')}>{save.life.museumReward?'박물관 완성 기념 선물 받음 ✓':'박물관 완성 선물 🌰 180'}</button>}</>;
 return <><div className="home-room-preview"><span>HOME, SWEET HOME</span></div>{visiting&&<p className="online-note">지금은 친구의 집에 놀러 왔어요. 가구 꾸미기는 방장이 할 수 있어요.</p>}<div className="life-stats"><span>집 단계 <b>{save.life.houseLevel}</b></span><span>실내 가구 <b>{save.life.roomPlaced.length}/{roomCapacity(save)}</b></span><span>야외 가구 <b>{save.placed.length}</b></span></div><div className="inline-actions"><button className="primary" disabled={visiting} onClick={onBag}>집에 가구 놓기</button><button className="secondary" disabled={visiting||save.life.houseLevel>=3||save.coins<(save.life.houseLevel===1?120:240)||save.bag.wood<8} onClick={()=>apply(upgradeHome,'가구를 놓을 수 있는 공간이 늘어났어요!')}>{save.life.houseLevel>=3?'가구 공간 최대 단계':'가구 공간 늘리기 · 🌰 '+(save.life.houseLevel===1?120:240)+' · 🪵 8'}</button></div><h3 className="section-label">내 수납함 <small>재료를 안전하게 보관해요</small></h3><div className="storage-list">{(Object.keys(ITEMS) as Resource[]).map(k=><div key={k}><span>{ITEMS[k].emoji} <strong>{ITEMS[k].name}</strong></span><small>주머니 {save.bag[k]} · 수납함 {save.life.storage[k]}</small><button className="secondary small" disabled={visiting||save.bag[k]<1} onClick={()=>apply(s=>transfer(s,k,true,true),'재료를 수납함에 보관했어요.')}>모두 넣기</button><button className="secondary small" disabled={visiting||save.life.storage[k]<1} onClick={()=>apply(s=>transfer(s,k,false,true),'재료를 주머니로 꺼냈어요.')}>모두 꺼내기</button></div>)}</div><p className="muted">가구에 다가가 E를 누르면 회수해요. 수납함과 가구는 이 기기에 자동 저장돼요.</p></>;
}
