'use client';
import {useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {ArrowLeft,ArrowRight,Bookmark,Check,ChevronRight,Clapperboard,Download,Heart,Image as ImageIcon,Play,RotateCcw,Shuffle,Sparkles,Star,Trash2,Undo2,Users,X} from 'lucide-react';
import {ACTORS,ACTOR_COLORS,CLOTHES,EPISODES,GLASSES,HAIRS,HATS,SAVE_KEY,advanceRun,costumeLine,defaultCostume,endingFor,freshTheater,loadTheater,newRun,outfitTitle,resultLine,type Costume,type Pose,type RecordEpisode,type Run,type Slot,type TheaterSave} from './theater-data';
import {THEATER_ASSETS} from './theater-assets';
import {GarmentArt,TheaterAvatar,TheaterArtReady} from './theater-avatar';
import {loadTheaterArt} from './theater-renderer';
import {TheaterRoom} from './theater-room';
import {WEB_URL,isDesktopApp} from './desktop-bridge';

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close();},[]);return <dialog ref={ref} className="t-modal" aria-label={title} onCancel={e=>{e.preventDefault();onClose();}}><header><h2>{title}</h2><button className="t-icon" aria-label="닫기" onClick={onClose}><X size={20}/></button></header>{children}</dialog>;}
const poseNames:{id:Pose;name:string}[]=[{id:'idle',name:'차렷'},{id:'sway',name:'두근두근'},{id:'bow',name:'꾸벅'},{id:'cheer',name:'신난다!'}];
const categories=[{id:'top',name:'상의'},{id:'bottom',name:'하의'},{id:'shoes',name:'신발'},{id:'hair',name:'머리'},{id:'extras',name:'소품'},{id:'saved',name:'저장한 룩'}];
export default function TheaterGame(){
 const [save,setSave]=useState<TheaterSave>(freshTheater),[loaded,setLoaded]=useState(false),[artReady,setArtReady]=useState(false),[artError,setArtError]=useState(''),[view,setView]=useState<'dress'|'stage'|'archive'>('dress'),[category,setCategory]=useState('top'),[pose,setPose]=useState<Pose>('idle'),[episode,setEpisode]=useState('trip'),[run,setRun]=useState<Run|null>(null),[replay,setReplay]=useState<RecordEpisode|null>(null),[toast,setToast]=useState(''),[modal,setModal]=useState<'room'|'reset'|null>(null),[code,setCode]=useState(''),[onlyFavorites,setOnlyFavorites]=useState(false),[storageError,setStorageError]=useState('');
 const [room]=useState(()=>new TheaterRoom()),online=useSyncExternalStore(room.subscribe,room.snapshot,room.snapshot),undo=useRef<{actor:number;costume:Costume}[]>([]),[undoCount,setUndoCount]=useState(0),recorded=useRef(new Set<string>());
 const loadArt=()=>{setArtError('');void loadTheaterArt().then(()=>setArtReady(true)).catch(e=>setArtError(String(e.message)));};
 useEffect(()=>{try{const s=loadTheater(localStorage.getItem(SAVE_KEY));setSave(s);s.records.forEach(r=>recorded.current.add(r.id));const invitation=new URLSearchParams(location.hash.slice(1)).get('theater');if(invitation){setCode(invitation);setModal('room');}}catch{setStorageError('이 브라우저에서는 저장할 수 없어요. 창을 닫기 전에 기념사진을 남겨 주세요.');}setLoaded(true);loadArt();return()=>room.leave();},[room]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));}catch{setStorageError('저장 공간이 부족해요. 공연 보관함을 정리해 주세요.');}},[loaded,save]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{if(online.status==='connected'&&online.run){setRun(online.run);setReplay(null);setView('stage');}else if(online.status==='connected'&&!online.run){setRun(null);setView(v=>v==='stage'?'dress':v);}},[online.status,online.run?.id,online.run?.step]);
 useEffect(()=>{if(online.status==='error'&&online.error){setToast(online.error);setRun(null);setReplay(null);setView('dress');}},[online.status,online.error]);
 useEffect(()=>{if(!run||run.step!==3||recorded.current.has(run.id)||replay)return;recorded.current.add(run.id);setSave(s=>({...s,records:[{...run,ending:endingFor(run)},...s.records].slice(0,24)}));},[run,replay]);
 const costumes=useMemo(()=>save.costumes.map((c,i)=>online.status==='connected'?online.players.find(p=>p.actor===i&&p.id!==online.self)?.costume??c:c),[save.costumes,online.status,online.players,online.self]);
 const selected=save.selected,current=costumes[selected],me=online.players.find(p=>p.id===online.self),locked=online.status==='connected'&&me?.actor!==selected,connected=online.status==='connected';
 const change=(patch:Partial<Costume>)=>{if(locked)return;undo.current.push({actor:selected,costume:{...save.costumes[selected]}});undo.current=undo.current.slice(-30);setUndoCount(undo.current.length);const next={...current,...patch};setSave(s=>({...s,costumes:s.costumes.map((c,i)=>i===selected?next:c)}));room.setCostume(selected,next);};
 const undoChange=()=>{const last=undo.current.at(-1);if(!last||connected&&me?.actor!==last.actor)return;undo.current.pop();setUndoCount(undo.current.length);setSave(s=>({...s,selected:last.actor,costumes:s.costumes.map((c,i)=>i===last.actor?last.costume:c)}));room.setCostume(last.actor,last.costume);};
 const randomize=()=>{const pick=(slot:Slot)=>{const list=CLOTHES.filter(c=>c.slot===slot);return list[Math.floor(Math.random()*list.length)].id;};change({top:pick('top'),bottom:pick('bottom'),shoes:pick('shoes')});setPose('cheer');};
 const saveLook=()=>{if(save.looks.length>=28){setToast('저장한 룩이 가득 찼어요. 사용하지 않는 룩을 지워 주세요.');return;}setSave(s=>({...s,looks:[{id:crypto.randomUUID(),actor:selected,name:`${ACTORS[selected]} · ${outfitTitle(current)}`,costume:{...current}},...s.looks]}));setToast('이 분장을 옷장에 저장했어요.');};
 const begin=()=>{const next=newRun(episode,selected,costumes);setReplay(null);setRun(next);setView('stage');if(connected)room.setRun(next);};
 const choose=(value:number)=>{if(!run)return;if(connected&&!replay){room.choose(value);return;}setRun(advanceRun(run,value));};
 const backToDress=()=>{if(connected&&online.role==='host')room.setRun(null);setRun(null);setReplay(null);setView('dress');};
 const favorite=(id:string)=>setSave(s=>({...s,favorites:s.favorites.includes(id)?s.favorites.filter(i=>i!==id):[...s.favorites,id]}));
 const poster=async(savedRun:Run|null=run)=>{try{const art=await loadTheaterArt(),c=document.createElement('canvas');c.width=1600;c.height=1000;const ctx=c.getContext('2d')!;ctx.drawImage(art.backdrop,0,0,c.width,c.height);ctx.fillStyle='#101521b8';ctx.fillRect(0,0,1600,160);ctx.textAlign='center';ctx.fillStyle='#f7e7c7';ctx.font='bold 46px "Malgun Gothic",sans-serif';ctx.fillText('호현지방 · 우당탕 극장',800,66);ctx.font='26px "Malgun Gothic",sans-serif';ctx.fillText(savedRun?.step===3?endingFor(savedRun):'일곱 친구의 오늘 분장',800,115);const looks=savedRun?.costumes??costumes;ACTORS.forEach((name,i)=>{art.actor(ctx,i,looks[i],140+i*220,850,290,'idle',0,true);ctx.fillStyle='#fff5e2';ctx.font='bold 24px "Malgun Gothic",sans-serif';ctx.fillText(name,140+i*220,900);});const blob=await new Promise<Blob|null>(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw new Error();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='호현지방-우당탕극장-'+Date.now()+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setToast('일곱 친구의 기념사진을 저장했어요.');}catch{setToast('사진을 저장하지 못했어요. 다시 시도해 주세요.');}};
 // In the desktop app location is tauri://localhost: link the public theater page instead.
 const invite=typeof location!=='undefined'?`${isDesktopApp()?new URL(location.pathname.replace(/^\/+/,''),WEB_URL).href:location.href.split('#')[0]}#theater=${online.code}`:'';
 const copyInvite=async()=>{try{await navigator.clipboard.writeText(invite);setToast('초대 링크를 복사했어요.');}catch{setToast('초대 링크를 길게 눌러 복사해 주세요.');}};
 const liveEpisode=EPISODES.find(e=>e.id===(run?.episode??episode))!,active=run?run.cast[Math.min(2,run.step)]:selected,canAct=!connected||!!replay||room.canChoose();
 if(!loaded)return <main className="theater-app t-loading"><Clapperboard/><p>분장실 문을 여는 중…</p></main>;
 return <TheaterArtReady.Provider value={artReady}><main className="theater-app">
  <header className="t-header"><div className="t-brand"><span className="t-brand-icon"><Clapperboard size={27}/></span><div><small>호현지방 · 일곱 친구의 작은 무대</small><h1>우당탕 극장<span>THE LITTLE PLAYHOUSE</span></h1></div></div><nav aria-label="극장 메뉴">{[{id:'dress',name:'분장실',icon:Sparkles},{id:'stage',name:'오늘의 공연',icon:Clapperboard},{id:'archive',name:'공연 보관함',icon:Bookmark}].map(({id,name,icon:Icon})=><button key={id} className={view===id?'active':''} onClick={()=>{if(id==='dress'){backToDress();return;}if(id==='stage'&&!run){begin();return;}setView(id as typeof view);}} disabled={id==='stage'&&(!artReady||connected&&online.role==='guest'&&!online.run)||id==='dress'&&connected&&online.role==='guest'&&!!online.run}><Icon size={17}/><span>{name}</span>{id==='archive'&&save.records.length>0&&<b>{save.records.length}</b>}</button>)}</nav><button className="t-friends-button" onClick={()=>setModal('room')}><Users size={17}/>{connected?`${online.players.length} / 7 함께하는 중`:'친구 초대'}</button></header>
  {storageError&&<div className="t-warning" role="status">{storageError}</div>}
  {artError&&<div className="t-warning" role="alert">{artError}<button onClick={loadArt}>그림 다시 불러오기</button></div>}
  {view==='dress'&&<div className="t-workspace">
   <aside className="t-cast"><div className="t-section-title"><span>오늘의 출연진</span><b>07</b></div><p>누구부터 꾸며 볼까요?</p><div className="t-cast-list">{ACTORS.map((name,i)=>{const owner=online.players.find(p=>p.actor===i);return <button key={name} aria-label={`${name} 꾸미기`} aria-pressed={selected===i} className={'t-cast-person '+(selected===i?'selected':'')} onClick={()=>{setSave(s=>({...s,selected:i}));setPose('idle');}}><span className="t-cast-portrait" style={{background:ACTOR_COLORS[i]}}><TheaterAvatar id={i} costume={costumes[i]}/></span><span><strong>{name}</strong><small>{owner?(owner.id===online.self?'내 배역':'친구가 분장 중'):i===6?'새로 합류한 친구':outfitTitle(costumes[i])}</small></span>{selected===i?<Check size={17}/>:<ChevronRight size={15}/>}</button>;})}</div><div className="t-cast-note"><Star size={18}/><span>누구나 주인공이 되는 곳.<br/>오늘은 {ACTORS[selected]} 차례!</span></div><button className="t-text-button" onClick={()=>setModal('reset')}><RotateCcw size={14}/> 처음부터 시작하기</button></aside>
   <section className="t-dressing" aria-label="분장 미리보기"><div className="t-dressing-heading"><div><span className="t-kicker">DRESS REHEARSAL</span><h2>{ACTORS[selected]}의 분장실</h2></div><span className="t-auto-save"><Check size={13}/>{storageError?'저장 확인 필요':'자동 저장'}</span></div><div className="t-mirror"><span className="t-studio-label">오늘의 주인공</span><div className="t-hero-avatar"><TheaterAvatar id={selected} costume={current} pose={pose} animated/></div>{!artReady&&<div className="t-art-loading">의상을 준비하고 있어요…</div>}<div className="t-role-label"><Sparkles size={15}/>{outfitTitle(current)}</div><div className="t-pose-picker" role="group" aria-label="포즈 선택">{poseNames.map(p=><button key={p.id} className={pose===p.id?'selected':''} aria-pressed={pose===p.id} onClick={()=>setPose(p.id)}>{p.name}</button>)}</div></div>
    <div className="t-outfit-tools"><button onClick={undoChange} disabled={!undoCount||locked} title="마지막 변경 되돌리기"><Undo2 size={17}/><span>되돌리기</span></button><button onClick={randomize} disabled={locked||!artReady}><Shuffle size={17}/><span>뜻밖의 분장</span></button><button onClick={saveLook} disabled={!artReady}><Bookmark size={17}/><span>룩 저장</span></button><button onClick={()=>void poster(null)} disabled={!artReady}><ImageIcon size={17}/><span>단체 사진</span></button></div>
    <div className="t-next-show"><div><span className="t-kicker">NEXT ON STAGE</span><select aria-label="공연 선택" value={episode} onChange={e=>setEpisode(e.target.value)}>{EPISODES.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><p>{EPISODES.find(e=>e.id===episode)!.subtitle}</p></div><button className="t-primary" onClick={begin} disabled={!artReady||connected&&online.role==='guest'}><Play size={17} fill="currentColor"/>{connected&&online.role==='guest'?'방장의 공연을 기다리는 중':'이 분장으로 무대에'}<ArrowRight size={17}/></button></div>
   </section>
   <aside className="t-closet"><header><div><span className="t-kicker">YOUR COSTUME RACK</span><h2>오늘은 어떤 역할?</h2></div><button className={'t-icon '+(onlyFavorites?'is-favorite':'')} aria-label="즐겨찾는 의상만 보기" aria-pressed={onlyFavorites} onClick={()=>setOnlyFavorites(v=>!v)}><Heart size={19} fill={onlyFavorites?'currentColor':'none'}/></button></header><div className="t-category" role="group" aria-label="옷장 종류">{categories.map(c=><button key={c.id} className={category===c.id?'selected':''} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</div>{locked&&<p className="t-lock-note">이 친구는 다른 사람이 분장 중이에요. 내 배역을 선택해 주세요.</p>}
    <div className="t-closet-body">{['top','bottom','shoes'].includes(category)&&<><div className="t-garment-grid">{CLOTHES.filter(c=>c.slot===category&&(!onlyFavorites||save.favorites.includes(c.id))).map(c=><article key={c.id} className={'t-garment '+(current[c.slot]===c.id?'selected':'')}><button className="t-garment-select" aria-label={`${c.name} 입기`} aria-pressed={current[c.slot]===c.id} onClick={()=>change({[c.slot]:c.id})} disabled={locked||!artReady}><span className="t-garment-picture"><GarmentArt cell={c.cell}/>{current[c.slot]===c.id&&<i><Check size={13}/></i>}</span><strong>{c.name}</strong><small>{c.tag}</small></button><button className="t-garment-heart" aria-label={`${c.name} 즐겨찾기`} aria-pressed={save.favorites.includes(c.id)} onClick={()=>favorite(c.id)}><Heart size={14} fill={save.favorites.includes(c.id)?'currentColor':'none'}/></button></article>)}</div>{onlyFavorites&&!CLOTHES.some(c=>c.slot===category&&save.favorites.includes(c.id))&&<p className="t-empty">아직 즐겨찾은 의상이 없어요.<br/>하트 버튼으로 마음에 드는 옷을 모아 보세요.</p>}</>}
    {category==='hair'&&<div className="t-hair-options"><h3>머리 색</h3><p>친구의 헤어스타일에 새 색을 입혀요.</p><div>{HAIRS.map(h=><button key={h.id} aria-label={`${h.name} 머리`} aria-pressed={current.hair===h.id} disabled={locked} onClick={()=>change({hair:h.id})}><i style={{background:h.hex}}>{current.hair===h.id&&<Check size={19}/>}</i><span>{h.name}</span></button>)}</div></div>}
    {category==='extras'&&<div className="t-extras"><h3>모자</h3><div>{HATS.map(h=><button key={h.id} className={current.hat===h.id?'selected':''} aria-pressed={current.hat===h.id} disabled={locked} onClick={()=>change({hat:h.id})}>{h.cell>=0?<i className="t-accessory"><GarmentArt cell={h.cell} accessory/></i>:<X size={25}/>}<span>{h.name}</span></button>)}</div><h3>안경</h3><div>{GLASSES.map(g=><button key={g.id} className={current.glasses===g.id?'selected':''} aria-pressed={current.glasses===g.id} disabled={locked} onClick={()=>change({glasses:g.id})}>{g.cell>=0?<i className="t-accessory"><GarmentArt cell={g.cell} accessory/></i>:<X size={25}/>}<span>{g.name}</span></button>)}</div><button className={'t-clip '+(current.clip?'selected':'')} aria-pressed={current.clip} disabled={locked} onClick={()=>change({clip:!current.clip})}><i className="t-accessory"><GarmentArt cell={7} accessory/></i>꽃 머리핀 {current.clip?'빼기':'달기'}</button></div>}
    {category==='saved'&&<div className="t-saved-looks">{save.looks.filter(l=>l.actor===selected).map(l=><article key={l.id}><button disabled={locked} onClick={()=>{change(l.costume);setToast('저장한 분장을 입었어요.');}}><TheaterAvatar id={selected} costume={l.costume}/><span>{l.name}</span></button><button className="t-icon" aria-label={`${l.name} 삭제`} onClick={()=>setSave(s=>({...s,looks:s.looks.filter(i=>i.id!==l.id)}))}><Trash2 size={15}/></button></article>)}{!save.looks.some(l=>l.actor===selected)&&<p className="t-empty">마음에 드는 분장을 완성했다면<br/>미리보기 아래 ‘룩 저장’을 눌러 주세요.</p>}</div>}
    </div><footer><button className="t-text-button" disabled={locked} onClick={()=>change(defaultCostume(selected))}><RotateCcw size={14}/>{ACTORS[selected]}의 기본 모습</button><p>옷에 정답은 없어요. 어울리는 이야기를 만들면 되니까.</p></footer>
   </aside>
  </div>}
  {view==='stage'&&run&&<section className="t-performance"><header><button className="t-text-button" onClick={backToDress} disabled={connected&&online.role==='guest'}><ArrowLeft size={17}/> 분장실</button><div><span className="t-kicker">{replay?'다시 보는 공연':liveEpisode.label}</span><h2>{liveEpisode.name}</h2></div><span className="t-scene-number">{run.step===3?'CURTAIN CALL':`SCENE 0${run.step+1} / 03`}</span></header><div className="t-stage"><img className="t-stage-backdrop" src={THEATER_ASSETS.backstage} alt=""/><div className="t-stage-caption">{run.step===3?'일곱 친구, 모두가 주인공':liveEpisode.intro}</div><div className={'t-stage-cast '+(run.step===3?'all':'')}>{(run.step===3?ACTORS.map((_,i)=>i):run.cast).map(i=><div key={i} className={i===active&&run.step<3?'speaking':''}><TheaterAvatar id={i} costume={run.costumes[i]} animated pose={run.step===3?'cheer':i===active?'sway':'idle'}/><span>{ACTORS[i]}<small>{outfitTitle(run.costumes[i])}</small></span></div>)}</div></div>
   {run.step<3?<div className="t-dialogue"><div className="t-dialogue-copy"><span className="t-speaker">{ACTORS[active]} <small>{outfitTitle(run.costumes[active])}의 특별 대사</small></span><p className="t-actor-line">“{costumeLine(run)}”</p>{run.step>0&&<p className="t-previous">{resultLine(run)}</p>}<h3>{liveEpisode.beats[run.step].question}</h3></div><div className="t-choices">{replay?<button onClick={()=>choose(replay.choices[run.step])}>기록된 다음 장면 <ArrowRight size={17}/></button>:liveEpisode.beats[run.step].options.map((text,i)=><button key={text} disabled={!canAct} onClick={()=>choose(i)}><span>{String(i+1).padStart(2,'0')}</span>{text}<ChevronRight size={17}/></button>)}{!canAct&&<p>{ACTORS[active]}를 맡은 친구의 선택을 기다리는 중이에요.</p>}</div></div>:<div className="t-ending"><span className="t-kicker">오늘의 에피소드</span><h2>{endingFor(run)}</h2><p>{resultLine(run)}<br/>공연은 보관함에 남겨 두었어요.</p><div><button className="t-primary" onClick={()=>void poster(run)}><Download size={17}/> 기념사진 저장</button><button className="t-secondary" onClick={backToDress} disabled={connected&&online.role==='guest'}>다른 분장으로 다시 만나기</button></div></div>}
  </section>}
  {view==='archive'&&<section className="t-archive"><header><span className="t-kicker">OUR LITTLE STORIES</span><h2>우리가 만든 장면들</h2><p>분장도, 선택도, 그날의 결말도 함께 남아요.</p></header>{save.records.length?<div className="t-record-grid">{save.records.map(r=><article className="t-record" key={r.id}><div className="t-record-art">{r.cast.map(i=><TheaterAvatar key={i} id={i} costume={r.costumes[i]}/>)}</div><div><small>{new Date(r.created).toLocaleDateString('ko-KR')} · {EPISODES.find(e=>e.id===r.episode)!.name}</small><h3>{r.ending}</h3><p>{r.cast.map(i=>ACTORS[i]).join(' · ')}</p><footer><button onClick={()=>{setReplay(r);setRun({...r,step:0,choices:[]});setView('stage');}} disabled={connected}><Play size={15}/> 다시 보기</button><button aria-label={`${r.ending} 사진 저장`} onClick={()=>void poster(r)}><Download size={16}/></button><button aria-label={`${r.ending} 기록 삭제`} onClick={()=>setSave(s=>({...s,records:s.records.filter(i=>i.id!==r.id)}))}><Trash2 size={15}/></button></footer></div></article>)}</div>:<div className="t-archive-empty"><Clapperboard size={42}/><h3>첫 번째 공연을 기다리고 있어요.</h3><p>마음에 드는 분장을 입고 작은 소동을 시작해 보세요.</p><button className="t-primary" onClick={()=>setView('dress')}>분장실로 가기 <ArrowRight size={17}/></button></div>}</section>}
  <footer className="t-app-footer"><span>HOHYEON PROVINCE PLAYHOUSE</span><span>서툴러도 괜찮아. 우리끼리 하는 공연이니까.</span><button className="t-text-button" onClick={()=>setModal('reset')}><RotateCcw size={14}/>처음부터 시작하기</button></footer>
  {toast&&<div className="t-toast" role="status"><Check size={17}/>{toast}</div>}
  {modal==='reset'&&<Modal title="극장을 처음부터 시작할까요?" onClose={()=>setModal(null)}><p>이 브라우저의 분장, 저장한 룩, 공연 기록이 지워집니다. 친구들의 기록과 이전 섬 저장은 그대로예요.</p><div className="t-modal-actions"><button className="t-secondary" onClick={()=>setModal(null)}>계속 간직하기</button><button className="t-primary" onClick={()=>{room.leave();setSave(freshTheater());setRun(null);setReplay(null);setView('dress');undo.current=[];setUndoCount(0);recorded.current.clear();setModal(null);setToast('새로운 첫 공연을 준비해요.');}}>내 극장 초기화</button></div></Modal>}
  {modal==='room'&&<Modal title="일곱 친구, 하나의 극장" onClose={()=>setModal(null)}><p>친구마다 한 명의 배역을 맡아요. 각자 분장하고 자기 장면에서 선택하면 하나의 공연이 완성됩니다.</p>{online.error&&<p className="t-room-error" role="alert">{online.error}</p>}{online.status==='connected'?<><div className="t-room-code"><small>초대 코드</small><strong>{online.code}</strong><input aria-label="극장 초대 링크" value={invite} readOnly onFocus={e=>e.target.select()}/><button className="t-secondary" onClick={()=>void copyInvite()}>초대 링크 복사</button></div><div className="t-room-members">{online.players.map(p=><span key={p.id}>{ACTORS[p.actor]} {p.id===online.self?'· 나':''}</span>)}</div><div className="t-modal-actions"><button className="t-primary" onClick={()=>{if(me)setSave(s=>({...s,selected:me.actor}));setModal(null);}}>분장하러 가기</button><button className="t-secondary" onClick={()=>{room.leave();setRun(null);setReplay(null);setView('dress');setModal(null);}}>극장 나가기</button></div></>:online.status==='selecting'?<><div className="t-room-roles">{ACTORS.map((name,i)=>{const taken=online.players.some(p=>p.actor===i);return <button key={name} disabled={taken||online.claiming!==null} aria-label={`${name} ${taken?'선택됨':'배역 맡기'}`} onClick={()=>room.claim(i,save.costumes[i])}><TheaterAvatar id={i} costume={save.costumes[i]}/><strong>{name}</strong><small>{taken?'친구가 선택했어요':online.claiming===i?'입장 중…':'이 배역 맡기'}</small></button>;})}</div><button className="t-secondary" onClick={()=>room.leave()}>참가 취소</button></>:online.status==='connecting'?<><p className="t-connecting">극장 문을 두드리고 있어요…</p><button className="t-secondary" onClick={()=>room.leave()}>연결 취소</button></>:<div className="t-room-start"><button className="t-primary" disabled={!artReady} onClick={()=>void room.start('host','',selected,current)}><Users size={18}/>{ACTORS[selected]}로 극장 열기</button><span>또는 친구의 극장에 참가하기</span><label>초대 코드 또는 링크<input value={code} onChange={e=>setCode(e.target.value)} maxLength={300} placeholder="초대받은 코드를 입력하세요"/></label><button className="t-secondary" disabled={!code.trim()||!artReady} onClick={()=>void room.start('guest',code,selected,current)}>배역 고르러 가기 <ArrowRight size={16}/></button></div>}</Modal>}
 </main></TheaterArtReady.Provider>;
}
