import {IslandRoom} from './multiplayer-transport.ts';
import {PEER_PREFIX,roomCode} from './multiplayer-protocol.ts';
import {readCostume,readRun,advanceRun,type Costume,type Run} from './theater-data.ts';
export type TheaterPlayer={id:string;actor:number;costume:Costume};
type View={status:'offline'|'connecting'|'selecting'|'connected'|'error';role:'host'|'guest'|null;code:string;self:string;players:TheaterPlayer[];run:Run|null;error:string;claiming:number|null};
const empty=():View=>({status:'offline',role:null,code:'',self:'',players:[],run:null,error:'',claiming:null});
const validActor=(v:unknown):v is number=>Number.isInteger(v)&&Number(v)>=0&&Number(v)<7;
function readPlayers(value:unknown):TheaterPlayer[]|null{if(!Array.isArray(value)||value.length>7)return null;const ids=new Set<string>(),actors=new Set<number>(),result:TheaterPlayer[]=[];for(const p of value){if(!p||typeof p.id!=='string'||p.id.length>100||!validActor(p.actor)||ids.has(p.id)||actors.has(p.actor))return null;ids.add(p.id);actors.add(p.actor);result.push({id:p.id,actor:p.actor,costume:readCostume(p.costume,p.actor)});}return result;}
export class TheaterRoom{
 view=empty();private listeners=new Set<()=>void>();private transport:IslandRoom|null=null;private members=new Map<string,TheaterPlayer>();private challenges=new Map<string,{nonce:string;time:number}>();private lastSeen=new Map<string,number>();private timer:ReturnType<typeof setInterval>|null=null;private deadline:ReturnType<typeof setTimeout>|null=null;private generation=0;private nonce='';private hostSeen=0;private pendingClaim:{actor:number;costume:Costume}|null=null;
 subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>{this.listeners.delete(fn);};};
 snapshot=()=>this.view;
 private update(patch:Partial<View>){this.view={...this.view,...patch};for(const fn of this.listeners)fn();}
 private hostSend(message:unknown){this.transport?.send(PEER_PREFIX+this.view.code,message);}
 private packet(){return {v:1,type:'theater-state',players:[...this.members.values()],run:this.view.run};}
 private sync(){const players=[...this.members.values()];this.transport?.retain(players.map(p=>p.id));this.update({players});this.transport?.send('*',this.packet());for(const id of this.challenges.keys())this.lobby(id);}
 private lobby(id:string,error=''){const challenge=this.challenges.get(id);if(challenge)this.transport?.send(id,{v:1,type:'theater-lobby',nonce:challenge.nonce,players:[...this.members.values()],error});}
 leave(error=''){this.generation++;if(this.timer)clearInterval(this.timer);if(this.deadline)clearTimeout(this.deadline);this.timer=null;this.deadline=null;this.transport?.close();this.transport=null;this.members.clear();this.challenges.clear();this.lastSeen.clear();this.nonce='';this.pendingClaim=null;this.view=empty();this.update({status:error?'error':'offline',error});}
 async start(role:'host'|'guest',input:string,actor:number,costume:Costume){this.leave();let code='';if(role==='guest'){try{const url=input.trim().startsWith('http')?new URL(input):null;code=roomCode(url?(new URLSearchParams(url.hash.slice(1)).get('theater')??''):input)??'';}catch{}if(!code){this.update({status:'error',error:'10자리 초대 코드 또는 극장 초대 링크를 확인해 주세요.'});return;}}
  if(!validActor(actor))return;const generation=++this.generation;this.update({status:'connecting',role,code});this.deadline=setTimeout(()=>{if(generation===this.generation)this.leave('극장에 연결하지 못했어요. 방장이 접속 중인지 확인해 주세요.');},25000);
  try{const room=await IslandRoom.create(role==='host',code,'hohyeon-theater-v1:');if(generation!==this.generation){room.close();return;}this.transport=room;this.update({code:room.code,self:room.id});await room.connect((from,data)=>{if(generation===this.generation)this.receive(from,data);},()=>{if(generation===this.generation)this.leave('실시간 연결이 끊겼어요. 다시 참가해 주세요.');});if(generation!==this.generation)return;this.hostSeen=Date.now();
   if(role==='host'){this.members.set(room.id,{id:room.id,actor,costume:readCostume(costume,actor)});if(this.deadline)clearTimeout(this.deadline);this.deadline=null;this.update({status:'connected'});this.sync();}else this.hostSend({v:1,type:'hello',theater:1});
   this.timer=setInterval(()=>this.tick(),4000);
  }catch{if(generation===this.generation)this.leave('극장에 연결하지 못했어요. 잠시 후 다시 시도해 주세요.');}
 }
 claim(actor:number,costume:Costume){if(this.view.status!=='selecting'||!validActor(actor)||this.view.players.some(p=>p.actor===actor))return false;this.pendingClaim={actor,costume:readCostume(costume,actor)};this.update({claiming:actor,error:''});this.hostSend({v:1,type:'join',nonce:this.nonce,...this.pendingClaim});return true;}
 setCostume(actor:number,costume:Costume){const me=this.view.players.find(p=>p.id===this.view.self);if(this.view.status!=='connected'||me?.actor!==actor)return false;const c=readCostume(costume,actor);if(this.view.role==='host'){this.members.set(me.id,{...me,costume:c});this.sync();}else this.hostSend({v:1,type:'costume',costume:c});return true;}
 setRun(run:Run|null){if(this.view.role!=='host'||this.view.status!=='connected')return false;const clean=run===null?null:readRun(run);if(run!==null&&!clean)return false;this.update({run:clean});this.sync();return true;}
 choose(choice:number){const run=this.view.run;if(!run||run.step>=3||![0,1].includes(choice)||!this.canChoose())return false;if(this.view.role==='host'){this.update({run:advanceRun(run,choice)});this.sync();}else this.hostSend({v:1,type:'choice',id:run.id,step:run.step,choice});return true;}
 canChoose(){const run=this.view.run;if(!run||run.step>=3)return false;const owner=this.view.players.find(p=>p.actor===run.cast[run.step]);return owner?owner.id===this.view.self:this.view.role==='host';}
 private tick(){if(this.view.role==='host'){for(const [id,time] of this.lastSeen)if(Date.now()-time>45000){this.members.delete(id);this.lastSeen.delete(id);}for(const [id,c] of this.challenges)if(Date.now()-c.time>20000)this.challenges.delete(id);this.sync();}else{if(Date.now()-this.hostSeen>45000){this.leave('방장이 극장을 나갔어요. 내 분장실로 돌아왔습니다.');return;}if(this.view.status==='connected')this.hostSend({v:1,type:'ping'});else{this.hostSend({v:1,type:'hello',theater:1});if(this.pendingClaim)this.hostSend({v:1,type:'join',nonce:this.nonce,...this.pendingClaim});}}}
 private receive(from:string,value:unknown){if(!value||typeof value!=='object')return;const p=value as Record<string,unknown>;if(p.v!==1)return;
  if(this.view.role==='host'){
   if(p.type==='hello'&&p.theater===1){if(this.members.has(from)){this.lastSeen.set(from,Date.now());this.transport?.send(from,this.packet());return;}const old=this.challenges.get(from),challenge=old&&Date.now()-old.time<20000?old:{nonce:crypto.randomUUID(),time:Date.now()};challenge.time=Date.now();this.challenges.set(from,challenge);if(this.challenges.size>16)this.challenges.delete(this.challenges.keys().next().value!);this.lobby(from);return;}
   if(p.type==='join'){if(this.members.has(from)){this.transport?.send(from,this.packet());return;}const challenge=this.challenges.get(from);if(!challenge||challenge.nonce!==p.nonce||Date.now()-challenge.time>20000||!validActor(p.actor))return;if([...this.members.values()].some(m=>m.actor===p.actor)){this.lobby(from,'다른 친구가 먼저 선택했어요. 남아 있는 친구를 골라 주세요.');return;}if(this.members.size>=7){this.lobby(from,'일곱 자리가 모두 찼어요.');return;}this.members.set(from,{id:from,actor:p.actor,costume:readCostume(p.costume,p.actor)});this.lastSeen.set(from,Date.now());this.challenges.delete(from);this.sync();return;}
   const member=this.members.get(from);if(!member)return;this.lastSeen.set(from,Date.now());if(p.type==='leave'){this.members.delete(from);this.lastSeen.delete(from);this.sync();}else if(p.type==='costume'){this.members.set(from,{...member,costume:readCostume(p.costume,member.actor)});this.sync();}else if(p.type==='choice'){const run=this.view.run;if(run&&p.id===run.id&&p.step===run.step&&run.cast[run.step]===member.actor&&(p.choice===0||p.choice===1)){this.update({run:advanceRun(run,p.choice)});this.sync();}}else if(p.type==='ping')this.transport?.send(from,this.packet());
  }else{
   this.hostSeen=Date.now();if(p.type==='closed'){this.leave('극장이 문을 닫았어요. 내 분장실로 돌아왔습니다.');return;}const players=readPlayers(p.players);if(!players)return;
   if(p.type==='theater-lobby'&&this.view.status!=='connected'&&typeof p.nonce==='string'&&p.nonce.length<80){this.nonce=p.nonce;if(this.deadline)clearTimeout(this.deadline);this.deadline=null;if(p.error)this.pendingClaim=null;this.update({status:'selecting',players,error:typeof p.error==='string'?p.error.slice(0,150):'',claiming:p.error?null:this.view.claiming});}
   if(p.type==='theater-state'){if(!players.some(m=>m.id===this.view.self)){if(this.view.status==='connected')this.leave('연결이 오래 끊겨 배역이 해제됐어요. 극장에 다시 참가해 주세요.');return;}const run=p.run===null?null:readRun(p.run);if(p.run!==null&&!run)return;this.pendingClaim=null;if(this.deadline)clearTimeout(this.deadline);this.deadline=null;this.transport?.retain(players.map(m=>m.id));this.update({status:'connected',players,run,error:'',claiming:null});}
  }
 }
}
