'use client';
import {useEffect,useRef} from 'react';
import {DECOR,FRIENDS,MAYOR,REGIONS,WORLD,ITEMS,NODES,SPOTS,distance,findPath,walkable,type Point,type Save} from './game-data';
import {loadSpriteSheet,loadMayorSprite} from './sprite-sheet';
import {canvasPixelRatio,visibleMapCrop} from './canvas-resolution';
export type Target = Point & {id:string;type:'node'|'friend'|'spot'|'decor'|'mayor'|'region';label:string};
export type WorldApi={go:(t:Target)=>boolean;key:(key:string,down:boolean)=>void;position:()=>Point;snapshot:()=>string|null};
export function targets(s:Save):Target[]{return [...NODES.filter(n=>Date.now()-(s.picked[n.id]||0)>30000).map(n=>({...n,type:'node' as const,label:`${ITEMS[n.kind].name} 줍기`})),...FRIENDS.flatMap((f,i)=>i===s.character?[]:[{...f,id:String(i),type:'friend' as const,label:`${s.names[i]}와 대화`}]),{...MAYOR,type:'mayor' as const,label:'호현 촌장과 대화'},...REGIONS.map(p=>({...p,type:'region' as const,label:p.name})),...SPOTS.map(p=>({...p,type:'spot' as const,label:p.name})),...s.placed.map(p=>({...p,type:'decor' as const,label:'장식 회수'}))]}
export default function World({save,paused,zoom,night,placing,onAct,onNear,onPlace,api,onReady,onRegion}:{save:Save;paused:boolean;zoom:number;night:boolean;placing:string|null;onAct:(t:Target)=>void;onNear:(t:Target|null)=>void;onPlace:(p:Point)=>void;api:React.RefObject<WorldApi|null>;onReady:(ok:boolean)=>void;onRegion:(id:string|null)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),state=useRef({save,paused,zoom,night,placing,onAct,onNear,onPlace,onReady,onRegion});state.current={save,paused,zoom,night,placing,onAct,onNear,onPlace,onReady,onRegion};
 useEffect(()=>{const c=canvas.current!;const ctx=c.getContext('2d')!;let alive=true,frame=0,last=0,clock=0;const pos={...state.current.save.position},camera={...pos},keys=new Set<string>();let path:Point[]=[],destination:Target|null=null,nearId='',regionId:string|null=null,scale=1,ox=0,oy=0,w=0,h=0,moving=false,facing=1,wasPaused=true;const bg=new Image();let sprites=new Image(),mayor=new Image();let loaded=0;const ready=()=>{loaded++;if(loaded===3&&alive)state.current.onReady(true)};bg.onload=()=>{document.documentElement.style.setProperty('--island-map',`url("${bg.src}")`);ready()};bg.onerror=()=>state.current.onReady(false);bg.src='/assets/island-expanded.png';loadMayorSprite().then(img=>{mayor=img;ready()}).catch(()=>state.current.onReady(false));loadSpriteSheet().then(img=>{sprites=img;ready()}).catch(()=>state.current.onReady(false));
 const resize=()=>{const rect=c.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=canvasPixelRatio(w,h,devicePixelRatio||1);c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);ctx.setTransform(c.width/Math.max(1,w),0,0,c.height/Math.max(1,h),0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high'};const observer=new ResizeObserver(resize);observer.observe(c);resize();
 const go=(t:Target)=>{path=findPath(pos,t);destination=t;if(distance(pos,t)<72){path=[];destination=null;state.current.onAct(t);return true}return path.length>0};
 api.current={go,key:(k,down)=>{if(down)keys.add(k);else keys.delete(k)},position:()=>({...pos}),snapshot:()=>{try{return c.toDataURL('image/png')}catch{return null}}};
 const keyDown=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select')||state.current.paused)return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','w','a','s','d','e','shift'].includes(k)){e.preventDefault();keys.add(k);if((k==='e'||k===' ')&&!e.repeat){const t=targets(state.current.save).sort((a,b)=>distance(pos,a)-distance(pos,b))[0];if(t&&distance(pos,t)<82)state.current.onAct(t)}}};
 const keyUp=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const blur=()=>keys.clear();window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);
 const click=(e:PointerEvent)=>{if(state.current.paused)return;const rect=c.getBoundingClientRect(),p={x:(e.clientX-rect.left-ox)/scale,y:(e.clientY-rect.top-oy)/scale};if(state.current.placing){if(walkable(p))state.current.onPlace(p);return;}const t=targets(state.current.save).sort((a,b)=>distance(p,a)-distance(p,b))[0];if(t&&distance(p,t)<54){go(t);return}destination=null;path=findPath(pos,p)};c.addEventListener('pointerdown',click);
 const pill=(text:string,x:number,y:number,color='#fff9e9',fg='#39513f')=>{ctx.font='bold 15px "Malgun Gothic", sans-serif';const size=ctx.measureText(text).width+22;ctx.fillStyle='rgba(44,65,40,.11)';ctx.beginPath();ctx.roundRect(x-size/2,y-15,size,29,13);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x-size/2,y-17,size,28,13);ctx.fill();ctx.fillStyle=fg;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x,y-3)};
 const drawPerson=(i:number,x:number,y:number,bob=0,player=false)=>{ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(36,75,46,.20)';ctx.beginPath();ctx.ellipse(0,-2,22,8,0,0,Math.PI*2);ctx.fill();if(player){ctx.strokeStyle='#fff9dc';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,0,28,10,0,0,Math.PI*2);ctx.stroke()}const sw=sprites.naturalWidth/3,sh=sprites.naturalHeight/2;if(sprites.complete&&sw){ctx.save();if(player)ctx.scale(facing,1);ctx.drawImage(sprites,(i%3)*sw,Math.floor(i/3)*sh,sw,sh,-47,-105+bob,94,110);ctx.restore()}ctx.restore();pill(state.current.save.names[i],x,y+22,player?'#406b4c':'#fffaeb',player?'#ffffff':'#435641');if(!player&&!state.current.save.done.includes(i)){ctx.fillStyle='#fbca60';ctx.beginPath();ctx.arc(x+26,y-91+Math.sin(clock*2+i)*3,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#694a24';ctx.font='bold 15px sans-serif';ctx.fillText(state.current.save.accepted.includes(i)?'♥':'!',x+26,y-90+Math.sin(clock*2+i)*3)}};
 const render=(t:number)=>{if(!alive)return;const dt=Math.min((t-last)/1000||.016,.05);last=t;clock+=dt;const st=state.current;if(st.paused&&!wasPaused){keys.clear();path=[];destination=null}wasPaused=st.paused;moving=false;if(!st.paused){let dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),dy=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));let followingPath=false;if(dx||dy){path=[];destination=null;}else if(path.length){followingPath=true;const q=path[0],dist=distance(pos,q);if(dist<8)path.shift();else{dx=(q.x-pos.x)/dist;dy=(q.y-pos.y)/dist;}}if(dx||dy){const len=Math.hypot(dx,dy),speed=keys.has('shift')?380:230,stride=followingPath?Math.min(speed*dt,distance(pos,path[0])):speed*dt,nx=pos.x+dx/len*stride,ny=pos.y+dy/len*stride;if(walkable({x:nx,y:pos.y}))pos.x=nx;if(walkable({x:pos.x,y:ny}))pos.y=ny;if(dx)facing=dx<0?-1:1;moving=true}if(destination&&distance(pos,destination)<65){const arrived=destination;destination=null;path=[];st.onAct(arrived)}const near=targets(st.save).sort((a,b)=>distance(pos,a)-distance(pos,b))[0];const id=near&&distance(pos,near)<82?`${near.type}${near.id}`:'';if(id!==nearId){nearId=id;st.onNear(id?near:null)}const region=REGIONS.find(r=>distance(pos,r)<260)?.id??null;if(region!==regionId){regionId=region;st.onRegion(region)}}
 scale=Math.max(w/WORLD.viewportWidth,h/WORLD.viewportHeight)*st.zoom;camera.x+=(pos.x-camera.x)*Math.min(1,dt*4);camera.y+=(pos.y-camera.y)*Math.min(1,dt*4);ox=w/2-camera.x*scale;oy=h*.56-camera.y*scale;ox=Math.min(0,Math.max(w-WORLD.width*scale,ox));oy=Math.min(0,Math.max(h-WORLD.height*scale,oy));ctx.clearRect(0,0,w,h);ctx.fillStyle='#66bebe';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);if(bg.complete&&bg.naturalWidth){const crop=visibleMapCrop(w,h,ox,oy,scale,bg.naturalWidth,bg.naturalHeight);if(crop.dw>0&&crop.dh>0)ctx.drawImage(bg,crop.sx,crop.sy,crop.sw,crop.sh,crop.dx,crop.dy,crop.dw,crop.dh);}
 if(path.length){ctx.setLineDash([3,13]);ctx.lineWidth=3;ctx.strokeStyle='rgba(255,255,234,.65)';ctx.beginPath();ctx.moveTo(pos.x,pos.y);path.forEach(q=>ctx.lineTo(q.x,q.y));ctx.stroke();ctx.setLineDash([])}
 for(const n of NODES){if(Date.now()-(st.save.picked[n.id]||0)<30000)continue;const bob=Math.sin(clock*2+n.x)*2;ctx.fillStyle='rgba(44,75,38,.1)';ctx.beginPath();ctx.ellipse(n.x,n.y+5,17,6,0,0,Math.PI*2);ctx.fill();ctx.font='28px "Segoe UI Emoji"';ctx.textAlign='center';ctx.fillText(ITEMS[n.kind].emoji,n.x,n.y+bob);ctx.fillStyle='rgba(255,252,212,.85)';ctx.font='15px sans-serif';ctx.fillText('✦',n.x+17,n.y-18+Math.sin(clock*3)*3)}
 for(const p of SPOTS)pill(`${p.emoji} ${p.name}`,p.x,p.y-8,'#fff8e7');
 for(const p of st.save.placed){ctx.font='56px "Segoe UI Emoji"';ctx.textAlign='center';ctx.fillText(DECOR.find(d=>d.id===p.kind)?.emoji||'🪴',p.x,p.y)}
 const people=[...FRIENDS.map((f,i)=>({i,x:i===st.save.character?pos.x:f.x,y:i===st.save.character?pos.y:f.y})),{i:6,x:MAYOR.x,y:MAYOR.y}].sort((a,b)=>a.y-b.y);people.forEach(p=>{if(p.i<6)drawPerson(p.i,p.x,p.y,p.i===st.save.character&&moving?Math.sin(clock*15)*5:Math.sin(clock*2+p.i)*1.5,p.i===st.save.character);else{const bob=Math.sin(clock*2)*2;ctx.fillStyle='rgba(36,75,46,.2)';ctx.beginPath();ctx.ellipse(p.x,p.y,25,8,0,0,Math.PI*2);ctx.fill();if(mayor.naturalHeight){const width=mayor.naturalWidth/mayor.naturalHeight*128;ctx.drawImage(mayor,p.x-width/2,p.y-128+bob,width,128)}pill('촌장 호현',p.x,p.y+24,'#ffd979','#674823');if(!st.save.mayorMet||(!st.save.explorationReward&&st.save.explored.length===REGIONS.length))pill('!',p.x+30,p.y-125,'#ffd979')}});
 for(let i=0;i<13;i++){const x=(i*131+clock*(3+i%3))%4200+300,y=300+(i*173)%2100+Math.sin(clock+i)*11;ctx.fillStyle=`rgba(255,254,201,${.25+(Math.sin(clock+i)+1)*.2})`;ctx.beginPath();ctx.arc(x,y,2,0,Math.PI*2);ctx.fill()}
 ctx.restore();if(st.night){ctx.fillStyle='rgba(35,37,94,.30)';ctx.fillRect(0,0,w,h);for(let i=0;i<28;i++){ctx.fillStyle=`rgba(255,243,144,${(Math.sin(clock*2+i)+1)*.4})`;ctx.beginPath();ctx.arc((i*97)%w,(i*83)%h,2,0,Math.PI*2);ctx.fill()}}frame=requestAnimationFrame(render)};frame=requestAnimationFrame(render);
 return()=>{alive=false;cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);c.removeEventListener('pointerdown',click);api.current=null};
 },[api]);
 return <canvas ref={canvas} className="world" aria-label="여섯섬 게임 지도. 방향키 또는 WASD로 이동하고 E로 상호작용합니다." tabIndex={0}/>;
}
