// 그웬 — 보송 미용실 원장 (원작: 리그 오브 레전드 그웬). 밝고 다정한 해요체, 칭찬이
// 끝이 없다. 바느질 인형이었다가 사람이 되어 세상 모든 게 처음이고 신기하다(단추 눈
// 시절 농담, 인형일 땐 냄새를 몰랐음). 실밥은 못 참음("싹둑!"), 가위 이름은 싹둑이,
// 바늘과 실, 이졸데 할머니에게 배운 손기술, 드라이어 김은 '착한 안개'. 쓰레쉬 가게
// 초록 안개는 살짝 경계(가볍게). 잔나·메르시·봉미선과 얽힌다. 원작 대사는 쓰지 않는다.
import type { NpcTalkBook } from './types.ts';

export const GWEN_TALK: NpcTalkBook = {
  npc: 'gwen',
  memories: {
    'scissors-name': '가위 싹둑이에게 인사했어요',
    'new-wonder': '처음 보는 것이 신기하다고 했어요',
    'thread-ok': '실밥을 떼어 줘서 고맙다고 했어요',
    'isolde-story': '이졸데 할머니 이야기를 들었어요',
    'good-mist': '드라이어 김이 착한 안개라고 맞장구쳤어요',
    'green-mist': '초록 안개는 드라이어로 막자고 했어요',
    'button-eyes': '단추 눈 시절 이야기를 들었어요',
    'fav-smell': '비 냄새가 좋다고 했어요',
    'braid-me': '땋은 머리를 해 보고 싶다고 했어요',
    'ribbon-bonus': '파마 값 대신 리본 이야기를 들었어요',
    'praise-back': '그웬도 예쁘다고 말해 줬어요',
    'camellia-love': '동백꽃이 좋다고 했어요',
    'strawberry': '딸기 우유색이 귀엽다고 했어요',
    'sunset-thread': '노을 색 실을 함께 찾았어요',
    'camellia-pin': '동백꽃을 선물했어요',
    'taste-heard': '내 취향으로 리본을 떠 준대요',
    'outing-talk': '함께 걸은 날을 이야기했어요',
    'bday-plan': '생일 머리를 해 주기로 했어요',
    'patch-scrap': '마을 조각보에 내 자투리도 넣기로 했어요',
    'bread-first': '처음 먹어 본 빵 이야기를 들었어요',
    'thresh-shop': '쓰레쉬 잡화점 단추가 최고라고 했어요',
    'janna-hair': '잔나의 날리는 머리를 같이 걱정했어요',
    'mercy-knot': '메르시의 붕대 매듭 이야기를 들었어요',
    'mirror-first': '처음 거울을 본 날 이야기를 들었어요',
    'dream-talk': '그웬이 처음 꾼 꿈 이야기를 들었어요',
    'ornn-whet': '오른 대장간에 싹둑이를 갈러 간대요',
    'first-tears': '너무 예뻐서 운 날 이야기를 들었어요',
    'color-talk': '좋아하는 색을 알려 줬어요',
    'hyungman-cut': '신형만 씨 머리 이야기에 같이 웃었어요',
    'sew-lesson': '바느질을 배워 보기로 했어요',
    'mist-lamp': '안개 낀 밤엔 등대 불이 고맙다고 했어요',
    'mend-ok': '터진 건 꿰매면 된다고 맞장구쳤어요',
    'heartbeat': '그웬의 심장 소리 이야기를 들었어요',
    'date-talk': '내 방에서 보낸 날을 이야기했어요',
    'mist-brave': '안개 낀 광장에서 손을 잡아 줬어요',
    'list-shared': '처음인 것들의 수첩을 같이 쓰기로 했어요',
    'quilt-done': '마을 조각보의 마지막 조각이 됐어요',
  },
  talks: [
    {
      id: 'scissors-name',
      open: ['{me} 님, 인사해요. 제 가위 싹둑이예요!', '이름 불러 주면 더 잘 잘려요. 진짜예요.'],
      replies: [
        { say: '안녕, 싹둑이!', tier: 'great', remember: 'scissors-name', face: 'laugh', answer: '와, 싹둑이가 반짝했어요! 방금 봤죠? 기분 좋대요.' },
        { say: '가위에도 이름이 있어?', tier: 'good', face: 'smile', answer: '그럼요! 매일 같이 일하는 친구인걸요. 바늘은 콕콕이예요.' },
        { say: '그냥 가위 아니야?', tier: 'meh', face: 'sorry', answer: '쉿, 싹둑이 들어요! …괜찮아요, 금방 풀려요.' },
      ],
    },
    {
      id: 'new-wonder',
      open: [
        '{me} 님, 오늘 아침에 이슬을 처음 만져 봤어요.',
        '차갑고 동글동글하고… 세상엔 아직 처음인 게 너무 많아요!',
      ],
      replies: [
        { say: '나도 같이 신기해할래', tier: 'great', remember: 'new-wonder', face: 'wow', answer: ['정말요? 그럼 내일은 둘이 처음인 걸 찾아봐요!', '신기한 건 둘이 보면 두 배 신기하거든요.'] },
        { say: '이슬은 금방 마르던데', tier: 'good', remember: 'new-wonder', face: 'think', answer: '그래서 더 예쁜가 봐요. 금방 사라지는 건 꼭 오래 봐 둬요.' },
        { say: '그냥 물방울이잖아', tier: 'meh', face: 'calm', answer: '그냥 물방울도 처음이면 보석이에요. 헤헤.' },
      ],
    },
    {
      id: 'loose-thread',
      open: ['어머, {me} 님 소매에 실밥이요! 가만있어 봐요.', '…싹둑! 됐어요. 이제 완벽해요.'],
      replies: [
        { say: '고마워, 감쪽같다', tier: 'great', remember: 'thread-ok', face: 'laugh', answer: '헤헤, 실밥은 보이면 못 참아요. 남의 옷이어도요!' },
        { say: '언제 봤어?', tier: 'good', face: 'smile', answer: '들어올 때부터요. 눈이 자꾸 그쪽으로 가더라고요.' },
        { say: '그 정도는 괜찮은데', tier: 'meh', face: 'sorry', answer: '저는 안 괜찮아요! 미안해요, 손이 먼저 가요.' },
      ],
    },
    {
      id: 'isolde',
      open: ['제 손재주는 다 이졸데 할머니한테 배웠어요.', '한 땀 한 땀, 서두르지 말라고 하셨어요.'],
      replies: [
        { say: '할머니 이야기 더 해 줘', tier: 'great', remember: 'isolde-story', face: 'smile', answer: ['할머니 손은 늘 따뜻했어요. 바늘보다 먼저요.', '제 첫 실밥도 할머니가 정리해 주셨어요.'] },
        { say: '그래서 손이 빠르구나', tier: 'good', face: 'laugh', answer: '빠른 게 아니라 꼼꼼한 거예요! 할머니가 들으면 혼내요.' },
        { say: '바느질은 어려워', tier: 'meh', face: 'think', answer: '처음엔 다 그래요. 저도 손가락 많이 찔렸어요.' },
      ],
    },
    {
      id: 'good-mist',
      open: '드라이어 틀면 김이 몽글몽글 나오죠? 저는 이걸 착한 안개라고 불러요.',
      replies: [
        { say: '따뜻해서 착한 안개구나', tier: 'great', remember: 'good-mist', face: 'wow', answer: '맞아요! 딱 알아주시네요. 따뜻한 안개는 다 착해요.' },
        { say: '나쁜 안개도 있어?', tier: 'good', face: 'think', answer: '음… 있어요. 차갑고 초록색인 거요. 그건 다음에 얘기해요.' },
        { say: '그냥 김이잖아', tier: 'meh', face: 'calm', answer: '김에도 이름이 있으면 더 다정해져요. 그런 거예요.' },
      ],
    },
    {
      id: 'green-mist',
      open: ['쓰레쉬 씨 가게 앞엔 초록 안개가 깔려요.', '나쁜 분은 아닌데… 그 안개는 좀 으스스해요.'],
      replies: [
        { say: '드라이어로 막자!', tier: 'great', remember: 'green-mist', face: 'laugh', answer: '그쵸! 착한 안개로 밀어내면 돼요. 미용실 앞은 제가 지켜요.' },
        { say: '쓰레쉬 씨는 친절하던데', tier: 'good', face: 'think', answer: '네, 인사는 잘 받아 줘요. 그래도 랜턴은 좀 멀리서 볼래요.' },
        { say: '난 하나도 안 무서워', tier: 'meh', face: 'wow', answer: '와, 용감해요! 저는 아직 지나갈 때 걸음이 빨라져요.' },
      ],
    },
    {
      id: 'button-eyes',
      open: ['옛날엔 제 눈이 단추였어요. 진짜로요!', '그래서 지금은 보이는 게 다 예뻐요.'],
      replies: [
        { say: '지금 눈이 더 반짝여', tier: 'great', remember: 'button-eyes', face: 'shy', answer: '어머, 그런 말은 처음 들어요! 단추 시절엔 못 들었을 말이에요.' },
        { say: '단추 눈도 귀여웠겠다', tier: 'good', remember: 'button-eyes', face: 'laugh', answer: '귀여웠죠! 근데 윙크는 못 했어요. 지금은 할 수 있어요, 봐요!' },
        { say: '농담이지?', tier: 'meh', face: 'smile', answer: '헤헤, 믿거나 말거나예요. 저는 믿어요.' },
      ],
    },
    {
      id: 'smells',
      open: ['인형이던 시절엔 냄새를 몰랐어요.', '{me} 님은 무슨 냄새가 제일 좋아요?'],
      replies: [
        { say: '비 오는 날 흙냄새', tier: 'great', remember: 'fav-smell', face: 'wow', answer: '저도요! 처음 맡았을 때 한참 서 있었어요. 우리 똑같아요!' },
        { say: '샴푸 냄새', tier: 'good', face: 'laugh', answer: '미용실 냄새네요! 그럼 매일 와야겠다. 헤헤.' },
        { say: '별로 신경 안 써', tier: 'meh', face: 'think', answer: '그럼 다음에 같이 맡아 봐요. 하나씩 좋아질 거예요.' },
      ],
    },
    {
      id: 'braid',
      open: '{me} 님 머리, 땋으면 엄청 예쁠 것 같아요. 해 봐도 돼요?',
      replies: [
        { say: '응, 맡길게', tier: 'great', remember: 'braid-me', face: 'laugh', answer: '와아! 세 갈래로 한 땀 한 땀. 다 하면 거울 보고 놀라요.' },
        { say: '짧게 자르고 싶은데', tier: 'good', face: 'smile', answer: '짧은 머리도 좋아요! 싹둑이가 신나겠어요.' },
        { say: '지금 그대로가 좋아', tier: 'meh', face: 'calm', answer: '그럼 그대로 예쁘게 빗어만 드릴게요. 그것도 좋아요.' },
      ],
    },
    {
      id: 'misun-ribbon',
      open: ['미선 씨가 또 파마 값 깎아 달래요.', '저는 절대 안 깎아요. 대신 리본을 하나 달아 드려요.'],
      replies: [
        { say: '그게 더 다정하다', tier: 'great', remember: 'ribbon-bonus', face: 'laugh', answer: '그쵸? 값은 그대로, 예쁨은 더! 이게 보송 미용실 규칙이에요.' },
        { say: '조금 깎아 주지', tier: 'good', face: 'think', answer: '한 번 깎으면 매번 깎아야 해요. 리본은 매번 달아 드려도 되고요.' },
        { say: '나도 깎아 줘', tier: 'meh', face: 'sorry', answer: '{me} 님도요? 헤헤, 안 돼요. 리본은 두 개 달아 드릴게요.' },
      ],
    },
    {
      id: 'praise',
      open: ['오늘 {me} 님 눈썹 결이 예뻐요. 아, 귀도 예뻐요.', '…칭찬이 멈추질 않네요. 미안해요!'],
      replies: [
        { say: '그웬도 예뻐', tier: 'great', remember: 'praise-back', face: 'shy', answer: '어, 저요? …칭찬 받는 건 아직 서툴러요. 귀가 뜨거워요.' },
        { say: '계속 해 줘', tier: 'good', face: 'laugh', answer: '좋아요! 손톱도 예쁘고, 웃는 것도 예쁘고, 그리고 또…' },
        { say: '좀 쑥스러워', tier: 'meh', face: 'smile', answer: '쑥스러워하는 것도 예뻐요. 아, 또 했다.' },
      ],
    },
    {
      id: 'flowers',
      open: '미용실 창가에 꽃을 꽂아요. {me} 님은 무슨 꽃이 좋아요?',
      replies: [
        { say: '동백꽃', tier: 'great', remember: 'camellia-love', face: 'wow', answer: '동백! 저도 제일 좋아해요. 빨간 게 꼭 리본 같아요.' },
        { say: '코스모스', tier: 'good', face: 'smile', answer: '코스모스도 좋아요! 바람에 살랑거리는 게 앞머리 같아요.' },
        { say: '꽃은 잘 몰라', tier: 'meh', face: 'think', answer: '그럼 미용실 창가에서 하나씩 알려 드릴게요.' },
      ],
    },
    {
      id: 'strawberry-dye',
      open: '딸기 우유색 염색, 어떨 것 같아요? 요즘 그 색에 빠졌어요.',
      replies: [
        { say: '완전 귀엽겠다', tier: 'great', remember: 'strawberry', face: 'laugh', answer: '그쵸! 먼저 리본부터 그 색으로 떠 볼게요. 기대해요!' },
        { say: '딸기는 먹는 게 좋아', tier: 'good', face: 'smile', answer: '헤헤, 저도 먹는 게 더 좋아요. 사실 그래서 생각났어요.' },
        { say: '너무 튀지 않아?', tier: 'meh', face: 'think', answer: '튀어도 예쁘면 돼요. 그래도 {me} 님은 차분한 색이 어울려요.' },
      ],
    },
    {
      id: 'pocket-heart',
      when: { ch: 3 },
      open: ['앞치마 안쪽에 작은 주머니를 하나 꿰맸어요.', '뭐 넣을지는 아직 비밀이에요. 맞혀 볼래요?'],
      replies: [
        { say: '동백꽃잎?', tier: 'great', face: 'shy', answer: '…어떻게 알았어요? 그날 받은 꽃잎이요. 꼭 넣어 둘래요.' },
        { say: '싹둑이 쉬는 자리?', tier: 'good', face: 'laugh', answer: '헤헤, 싹둑이는 너무 커요. 더 작은 거예요.' },
        { say: '사탕?', tier: 'meh', face: 'smile', answer: '사탕도 좋네요! 그건 다음 주머니에 넣을게요.' },
      ],
    },
    {
      id: 'red-thread',
      when: { love: 'dating' },
      open: '{me} 님, 손 줘 봐요. 새끼손가락에 빨간 실 한 바퀴만 감을게요.',
      replies: [
        { say: '절대 안 풀리게 묶어 줘', tier: 'great', face: 'shy', answer: '이졸데 할머니한테 배운 매듭이에요. 평생 안 풀려요.' },
        { say: '간지러워', tier: 'good', face: 'laugh', answer: '헤헤, 저도 간지러워요. 마음이요.' },
        { say: '실밥 생기면 어떡해?', tier: 'meh', face: 'smile', answer: '그건 제가 싹둑! 해 드려야죠. 매일요.' },
      ],
    },
    {
      id: 'patchwork',
      open: [
        '{me} 님, 이거 봐요. 손님들 옷 자투리를 모아 둔 상자예요.',
        '하나씩 이어서 마을 조각보를 만들고 있어요.',
        '잔나 씨 리본 끝, 메르시 씨 앞치마 끝… 다 들어가요.',
      ],
      replies: [
        { say: '내 자투리도 넣어 줘', tier: 'great', remember: 'patch-scrap', face: 'wow', answer: ['정말요? 그럼 제일 가운데 자리 비워 둘게요!', '조각보는 가운데가 제일 따뜻하거든요.'] },
        { say: '왜 다 이어 붙여?', tier: 'good', face: 'think', answer: ['떨어진 조각도 이으면 이불이 되잖아요.', '마을도 그래요. 한 땀씩 이으면 따뜻해져요.'] },
        { say: '버리면 안 돼?', tier: 'meh', face: 'sorry', answer: '안 돼요! 실 한 올도 쓸 데가 있어요. 할머니가 그랬어요.' },
      ],
    },
    {
      id: 'first-bread',
      open: ['프리렌 씨 빵집에서 처음 크림빵을 먹어 봤어요.', '입안에서 구름이 터지는 줄 알았어요!'],
      replies: [
        { say: '처음 맛본 기분 어땠어?', tier: 'great', remember: 'bread-first', face: 'laugh', answer: ['눈이 저절로 감겼어요. 인형일 땐 맛도 몰랐거든요.', '그날 수첩에 별을 세 개 그렸어요. 헤헤.'] },
        { say: '다음엔 딸기빵 먹어 봐', tier: 'good', remember: 'bread-first', face: 'wow', answer: '딸기빵이요? 딸기에 빵이라니, 세상은 정말 친절해요!' },
        { say: '빵은 다 비슷하지', tier: 'meh', face: 'calm', answer: '처음 먹는 사람한텐 하나하나 다 달라요. 정말이에요.' },
      ],
    },
    {
      id: 'thresh-buttons',
      open: [
        '단추 사러 쓰레쉬 씨 잡화점에 다녀왔어요.',
        '등불이 초록색이라 문 앞에서 숨 한 번 쉬고 들어가요.',
        '근데 단추는 마을에서 제일 예뻐요. 그게 문제예요.',
      ],
      replies: [
        { say: '예쁜 단추면 용기 내야지', tier: 'great', remember: 'thresh-shop', face: 'laugh', answer: ['그쵸! 단추 앞에선 저도 용감해져요.', '오늘은 진주 단추를 세 개나 샀어요.'] },
        { say: '같이 가 줄까?', tier: 'good', face: 'shy', answer: '정말요? 그럼 저는 {me} 님 소매 잡고 갈래요. 살짝만요.' },
        { say: '무서우면 가지 마', tier: 'meh', face: 'think', answer: '그러기엔 단추가 너무 예뻐요. 어쩔 수 없어요.' },
      ],
    },
    {
      id: 'janna-wind',
      open: [
        '잔나 씨는 취재 나가기 전에 꼭 미용실에 들러요.',
        '근데 문을 나서면 바람이 잔나 씨 머리부터 쓰다듬어요.',
      ],
      replies: [
        { say: '바람도 잔나를 좋아하나 봐', tier: 'great', remember: 'janna-hair', face: 'laugh', answer: ['저도 그렇게 생각해요! 질투 날 정도예요.', '그래서 요즘은 날려도 예쁜 머리를 연구해요.'] },
        { say: '핀을 더 꽂아 봐', tier: 'good', remember: 'janna-hair', face: 'think', answer: '벌써 일곱 개 꽂았어요. 다음엔 리본으로 꽉 묶어 볼래요.' },
        { say: '그냥 짧게 자르면 되지', tier: 'meh', face: 'sorry', answer: '잔나 씨 머리는 날리는 게 매력이에요. 그건 못 잘라요.' },
      ],
    },
    {
      id: 'mercy-knot',
      open: [
        '메르시 씨가 붕대 매듭을 보여 줬어요.',
        '제 바느질 매듭이랑 꼭 닮았어요. 둘 다 이어 주는 일이래요.',
      ],
      replies: [
        { say: '둘 다 낫게 해 주는 일이네', tier: 'great', remember: 'mercy-knot', face: 'wow', answer: ['맞아요! 메르시 씨는 몸을, 저는 머리를요.', '…그리고 기분도 조금요. 헤헤.'] },
        { say: '메르시도 바느질해?', tier: 'good', remember: 'mercy-knot', face: 'smile', answer: '상처 꿰매는 바느질이요. 그건 저도 무서워서 못 봐요.' },
        { say: '매듭은 다 똑같지', tier: 'meh', face: 'think', answer: '아니에요! 풀리라고 묶는 매듭, 안 풀리라고 묶는 매듭이 달라요.' },
      ],
    },
    {
      id: 'mirror-first',
      open: ['처음 거울을 봤을 때 누군지 몰라서 인사했어요.', '"안녕하세요" 했더니 거울 속 사람도 인사하더라고요.'],
      replies: [
        { say: '그때 그웬 귀여웠겠다', tier: 'great', remember: 'mirror-first', face: 'shy', answer: ['어머, 놀리는 거죠? …사실 저도 좀 귀여웠다고 생각해요.', '그래서 미용실을 하나 봐요. 거울이 좋아서요.'] },
        { say: '지금도 인사해?', tier: 'good', remember: 'mirror-first', face: 'laugh', answer: '가끔요! 아침마다 "오늘도 잘 부탁해요" 해요.' },
        { say: '그건 좀 이상한데', tier: 'meh', face: 'calm', answer: '처음이면 다 이상해요. 이상한 게 처음의 재미예요.' },
      ],
    },
    {
      id: 'heartbeat',
      open: [
        '손님 머리 감길 때 귀를 기울이면 쿵쿵 소리가 들려요.',
        '제 가슴에서도 같은 소리가 나요. 사람이 된 소리예요.',
      ],
      replies: [
        { say: '그 소리, 참 좋은 소리다', tier: 'great', remember: 'heartbeat', face: 'shy', answer: ['그쵸… 밤에 누우면 그 소리 세다가 잠들어요.', '솜 대신 들어온 제일 좋은 거예요.'] },
        { say: '내 소리도 들려?', tier: 'good', face: 'laugh', answer: '지금은 좀 빠른데요? 헤헤, 저 때문은 아니죠?' },
        { say: '다들 그래', tier: 'meh', face: 'calm', answer: '다들 그런 게 제일 신기한 거예요. 몰랐죠?' },
      ],
    },
    {
      id: 'first-dream',
      open: ['어젯밤에 꿈을 꿨어요. 인형일 땐 꿈을 안 꿨거든요.', '꿈에서 저는 큰 바늘을 들고 하늘을 꿰매고 있었어요.'],
      replies: [
        { say: '무슨 하늘이었어?', tier: 'great', remember: 'dream-talk', face: 'wow', answer: ['구멍 난 밤하늘이요. 별이 새지 않게 꿰매 줬어요.', '깨어 보니 손에 실이 감겨 있었어요. 신기하죠?'] },
        { say: '그웬다운 꿈이네', tier: 'good', remember: 'dream-talk', face: 'laugh', answer: '꿈에서도 바느질이라니요. 저는 진짜 이게 좋은가 봐요.' },
        { say: '난 꿈 잘 안 꿔', tier: 'meh', face: 'think', answer: '그럼 오늘 밤엔 제 꿈 얘기 생각하고 자요. 옮을지도요.' },
      ],
    },
    {
      id: 'ornn-whet',
      open: ['싹둑이 날이 조금 무뎌졌어요. 오른 씨한테 가야 해요.', '오른 씨는 말이 없는데 가위는 엄청 아껴 줘요.'],
      replies: [
        { say: '싹둑이 잘 다녀와', tier: 'great', remember: 'ornn-whet', face: 'laugh', answer: ['싹둑이가 신났어요. 대장간 불이 따뜻하대요.', '오른 씨한테는 동백 꽃잎 하나 드리고 와야지.'] },
        { say: '오른 씨 무섭지 않아?', tier: 'good', remember: 'ornn-whet', face: 'think', answer: '처음엔 수염이 무서웠어요. 근데 손이 할머니만큼 꼼꼼해요.' },
        { say: '새 가위 사면 되잖아', tier: 'meh', face: 'sorry', answer: '싹둑이는 하나뿐이에요! 친구를 바꾸는 사람은 없잖아요.' },
      ],
    },
    {
      id: 'first-tears',
      open: ['처음 울어 본 날이 언젠지 알아요?', '미용실 창으로 첫눈 오는 걸 본 날이에요. 너무 예뻐서요.'],
      replies: [
        { say: '예뻐서 우는 건 좋은 눈물이야', tier: 'great', remember: 'first-tears', face: 'shy', answer: ['그쵸? 저도 그때 알았어요. 눈물도 착한 게 있다는 걸요.', '착한 안개처럼요. 따뜻했어요.'] },
        { say: '놀랐겠다', tier: 'good', remember: 'first-tears', face: 'laugh', answer: '엄청요! 얼굴이 젖어서 실밥 터진 줄 알았어요.' },
        { say: '그 정도로 울어?', tier: 'meh', face: 'calm', answer: '처음이면 그래요. {me} 님도 처음엔 그랬을 거예요.' },
      ],
    },
    {
      id: 'fav-color',
      open: '실 상자를 새로 정리하는데요, {me} 님은 무슨 색 좋아해요?',
      replies: [
        { say: '동백 같은 빨강', tier: 'great', remember: 'color-talk', face: 'wow', answer: '저랑 같아요! 빨간 실은 제 실 상자 맨 앞자리예요.' },
        { say: '하늘 같은 파랑', tier: 'good', remember: 'color-talk', face: 'smile', answer: ['파랑도 좋아요. 잔나 씨 리본이 그 색이에요.', '{me} 님 칸도 만들어 둘게요.'] },
        { say: '색은 상관없어', tier: 'meh', face: 'think', answer: '그럼 제가 어울리는 색을 찾아 드릴게요. 그게 제 일이에요.' },
      ],
    },
    {
      id: 'hyungman-cut',
      open: [
        '미선 씨가 신형만 씨를 끌고 왔어요. 머리 좀 하라고요.',
        '신형만 씨는 의자에서 계속 "짧게만요" 하고요.',
        '근데 미선 씨는 뒤에서 "멋있게!" 하더라고요.',
      ],
      replies: [
        { say: '둘 다 맞춰 줬지?', tier: 'great', remember: 'hyungman-cut', face: 'laugh', answer: ['짧고 멋있게! 미선 씨가 거울 보고 웃었어요.', '신형만 씨 귀가 빨개졌어요. 귀여운 부부예요.'] },
        { say: '값은 깎았어?', tier: 'good', face: 'think', answer: '물론 안 깎았어요. 대신 미선 씨한테 리본 달아 드렸어요.' },
        { say: '그냥 짧게 자르지', tier: 'meh', face: 'sorry', answer: '그럼 미선 씨가 저를 혼내요. 그건 무서워요.' },
      ],
    },
    {
      id: 'sew-lesson',
      open: ['{me} 님, 바느질 배워 볼래요? 단추 다는 것부터요.', '단추 하나 달 줄 알면 세상이 조금 덜 무서워요.'],
      replies: [
        { say: '응, 가르쳐 줘', tier: 'great', remember: 'sew-lesson', face: 'laugh', answer: ['좋아요! 바늘은 천천히, 실은 넉넉히.', '이졸데 할머니가 저한테 처음 한 말이에요.'] },
        { say: '손가락 찔릴 것 같아', tier: 'good', remember: 'sew-lesson', face: 'smile', answer: '골무 빌려 드릴게요. 할머니 골무예요. 엄청 튼튼해요.' },
        { say: '그웬한테 맡길래', tier: 'meh', face: 'calm', answer: '그것도 좋아요. 대신 단추 떨어지면 꼭 저한테 와요.' },
      ],
    },
    {
      id: 'mist-lamp',
      open: [
        '바다 쪽에서 밤안개가 밀려오는 날이 있어요.',
        '검고 차가운 안개요. 그런 날은 가게 불을 늦게까지 켜 둬요.',
        '가붕 씨 등대 불이 보이면 그제야 안심이 돼요.',
      ],
      replies: [
        { say: '그웬 가게 불도 등대야', tier: 'great', remember: 'mist-lamp', face: 'shy', answer: ['어머… 그런 말 처음 들어요.', '그럼 앞으로도 불을 따뜻하게 켜 둘게요. 누구든 오게요.'] },
        { say: '무서우면 나 불러', tier: 'good', remember: 'mist-lamp', face: 'smile', answer: '정말 불러도 돼요? 그럼 드라이어 켜 놓고 기다릴게요.' },
        { say: '안개는 그냥 안개야', tier: 'meh', face: 'think', answer: '맞아요, 아마도요. 그래도 착한 안개 편이 좋아요.' },
      ],
    },
    {
      id: 'mend',
      open: ['오늘 손님 외투가 크게 터져 와서 다 꿰맸어요.', '터진 데는 꿰매면 돼요. 오히려 더 튼튼해지기도 하고요.'],
      replies: [
        { say: '사람 마음도 그렇겠다', tier: 'great', remember: 'mend-ok', face: 'smile', answer: ['맞아요. 할머니도 그렇게 말했어요.', '꿰맨 자리는 흉이 아니라 이야기래요.'] },
        { say: '바느질 자국 보여 줘', tier: 'good', remember: 'mend-ok', face: 'laugh', answer: '안 보여요! 안 보이게 꿰매는 게 실력이거든요. 헤헤.' },
        { say: '새로 사는 게 낫지', tier: 'meh', face: 'sorry', answer: '아끼던 옷은 바꿀 수 없어요. 그 옷에 든 날들이 있잖아요.' },
      ],
    },
    {
      id: 'bugs',
      open: '아까 미용실에 무당벌레가 들어왔어요. 저 의자 위로 올라갔어요.',
      replies: [
        { say: '내가 밖으로 보내 줄게', tier: 'great', face: 'laugh', answer: '고마워요! {me} 님은 오늘 보송 미용실의 영웅이에요.' },
        { say: '무당벌레는 귀엽잖아', tier: 'good', face: 'think', answer: '점은 귀여워요. 근데 다리가 많아서 좀 그래요.' },
        { say: '벌레 한 마리 갖고 뭘', tier: 'meh', face: 'sorry', answer: '저한텐 큰일이에요! 인형일 때 벌레가 솜을 파먹었거든요.' },
      ],
    },
    {
      id: 'tsunade-flowers',
      open: ['츠나데 할머니 텃밭에서 꽃을 한 아름 얻어 왔어요.', '할머니 손이 이졸데 할머니 손이랑 닮았어요. 따뜻해요.'],
      replies: [
        { say: '그래서 자꾸 찾아가는구나', tier: 'great', face: 'shy', answer: ['들켰네요. 할머니 손 잡으면 마음이 꿰매져요.', '대신 할머니 머리는 늘 제가 예쁘게 해 드려요.'] },
        { say: '꽃은 어디 꽂았어?', tier: 'good', face: 'smile', answer: '미용실 창가랑 거울 옆이요. 손님들이 다 물어봐요.' },
        { say: '할머니들은 다 비슷해', tier: 'meh', face: 'think', answer: '아니에요. 할머니마다 손 온도가 달라요. 만져 보면 알아요.' },
      ],
    },
    {
      id: 'quilt-progress',
      when: { ch: 2 },
      open: ['마을 조각보가 반쯤 됐어요! 노을 색 실로 테두리를 둘렀어요.', '가운데 자리는 아직 비어 있어요. 누구 자리인지 알죠?'],
      replies: [
        { say: '혹시 내 자리야?', tier: 'great', face: 'shy', answer: '…헤헤. 그건 다 되면 말해 줄게요. 아직 비밀이에요.' },
        { say: '테두리 색 예쁘다', tier: 'good', face: 'laugh', answer: '{me} 님이랑 찾은 색이잖아요. 당연히 예쁘죠!' },
        { say: '언제 다 돼?', tier: 'meh', face: 'calm', answer: '좋은 바느질은 서두르지 않아요. 천천히 기다려 줘요.' },
      ],
    },
    {
      id: 'list-together',
      when: { mem: 'list-shared' },
      open: ['우리 수첩에 오늘 새 줄을 썼어요.', '"처음으로 누군가를 기다려 본 날." {me} 님 오기 전이요.'],
      replies: [
        { say: '나도 한 줄 쓸게', tier: 'great', face: 'shy', answer: ['정말요? 뭐라고 쓸 거예요? …아, 보여 주지 마요. 떨려요.', '나중에 같이 읽어요. 아주 나중에요.'] },
        { say: '기다리게 해서 미안해', tier: 'good', face: 'smile', answer: '기다리는 것도 처음이라 좋았어요. 진짜예요.' },
        { say: '수첩 아직 써?', tier: 'meh', face: 'think', answer: '그럼요! 둘이 쓰기로 했잖아요. 잊으면 안 돼요.' },
      ],
    },
    {
      id: 'dating-comb',
      when: { love: 'dating' },
      open: ['{me} 님 전용 빗을 하나 깎아 달라고 오른 씨한테 부탁했어요.', '손잡이에 작은 동백을 새겨 달라고 했어요.'],
      replies: [
        { say: '그웬 것도 같이 만들자', tier: 'great', face: 'shy', answer: ['어머… 둘이 같은 빗이요? 좋아요. 너무 좋아요.', '그럼 빗질할 때마다 서로 생각나겠다.'] },
        { say: '오른 씨가 꽃을 새겨?', tier: 'good', face: 'laugh', answer: '투덜대면서 제일 예쁘게 새겨 줄 거예요. 그런 분이에요.' },
        { say: '빗은 하나 있는데', tier: 'meh', face: 'sorry', answer: '이건 그냥 빗이 아니에요. 연인 빗이에요. 달라요!' },
      ],
    },
    {
      id: 'engaged-veil',
      when: { love: 'engaged' },
      open: ['면사포 끝단을 몰래 꿰매고 있어요. 동백 무늬로요.', '한 땀마다 {me} 님 이름을 속으로 불러요.'],
      replies: [
        { say: '그날 머리도 그웬이 해 줘', tier: 'great', face: 'shy', answer: ['당연하죠! 제 머리도 제가 하고, {me} 님 머리도 제가 해요.', '그날은 싹둑이도 리본 달아 줄 거예요.'] },
        { say: '몰래라면서 말했네', tier: 'good', face: 'laugh', answer: '앗! …못 들은 걸로 해요. 아니, 들어 줘서 좋아요.' },
        { say: '너무 무리하지 마', tier: 'meh', face: 'smile', answer: '무리 아니에요. 제일 행복한 바느질이에요.' },
      ],
    },
    {
      id: 'married-curtain',
      when: { love: 'married' },
      open: ['우리 집 커튼 끝단, 어제 새로 꿰맸어요.', '아침마다 둘이 같이 걷는 커튼이니까 튼튼해야죠.'],
      replies: [
        { say: '그웬 손이 닿으면 다 예뻐', tier: 'great', face: 'shy', answer: ['또 칭찬이에요. 저 이제 칭찬 받는 거 좀 잘하죠?', '…그래도 아직 귀는 뜨거워요.'] },
        { say: '내일은 내가 걷을게', tier: 'good', face: 'laugh', answer: '좋아요! 그럼 저는 그동안 {me} 님 머리 빗을게요.' },
        { say: '커튼 그대로도 괜찮았는데', tier: 'meh', face: 'think', answer: '실밥이 하나 나와 있었어요. 그건 못 참아요. 알잖아요.' },
      ],
    },
  ],
  openers: [
    {
      id: 'op-rain',
      when: { weather: 'rain' },
      open: ['비 와요! {me} 님, 머리 젖었잖아요.', '얼른 앉아요. 착한 안개로 말려 드릴게요.'],
      replies: [
        { say: '비 냄새 좋다', tier: 'great', remember: 'fav-smell', face: 'wow', answer: '그쵸! 인형일 땐 이 냄새를 몰랐어요. 지금은 제일 좋아요.' },
        { say: '고마워, 따뜻하다', tier: 'good', face: 'smile', answer: '부스스해지기 전에 다 말려요. 그래야 예뻐요.' },
        { say: '금방 마를 거야', tier: 'meh', face: 'sorry', answer: '안 돼요! 젖은 채로 다니면 감기 걸려요.' },
      ],
    },
    {
      id: 'op-storm',
      when: { weather: 'storm' },
      open: '바람이 너무 세요! 오늘은 다들 머리 포기하는 날이에요.',
      replies: [
        { say: '리본으로 꽉 묶어 줘', tier: 'great', face: 'laugh', answer: '좋아요, 두 번 묶을게요! 잔나 씨처럼 날아가면 안 되니까요.' },
        { say: '미용실은 괜찮아?', tier: 'good', face: 'smile', answer: '창문은 꼭 닫았어요. 싹둑이랑 실 상자도 안쪽에 뒀어요.' },
        { say: '머리 포기할래', tier: 'meh', face: 'sorry', answer: '포기라뇨! 빗 하나만 챙겨요. 들어오면 바로 빗어 드릴게요.' },
      ],
    },
    {
      id: 'op-snow',
      when: { weather: 'snow' },
      open: ['눈이에요! 처음 봤을 땐 하늘에서 솜이 터진 줄 알았어요.', '누가 바느질하다 놓쳤나 봐요.'],
      replies: [
        { say: '구름 솜이 터졌나 봐', tier: 'great', face: 'laugh', answer: '그쵸? 그럼 제가 꿰매 드려야겠다. 바늘 큰 거 꺼내야겠어요.' },
        { say: '머리에 눈 앉았어', tier: 'good', face: 'shy', answer: '어디요? 헤헤, 머리핀 같죠? 녹기 전에 봐 둬요.' },
        { say: '추워…', tier: 'meh', face: 'sorry', answer: '얼른 들어와요! 드라이어 켜 둘게요. 착한 안개 바로 나와요.' },
      ],
    },
    {
      id: 'op-dawn',
      when: { time: 'dawn' },
      open: ['어머, 일찍 오셨네요! 싹둑이 갈아 두는 중이었어요.', '아침 머리는 솔직해요. 어디가 뻗치는지 다 보여요.'],
      replies: [
        { say: '내 뻗친 머리 좀 봐 줘', tier: 'great', face: 'laugh', answer: '여기, 여기, 또 여기! 헤헤, 오 분이면 반듯해져요.' },
        { say: '그웬도 일찍 일어나네', tier: 'good', face: 'smile', answer: '아침이 매일 신기해서요. 늦잠 자면 아깝잖아요.' },
        { say: '아직 졸려', tier: 'meh', face: 'calm', answer: '그럼 머리 감겨 드릴게요. 시원해서 눈이 번쩍 떠져요.' },
      ],
    },
    {
      id: 'op-evening',
      when: { time: 'evening' },
      open: '노을빛이 {me} 님 머리에 비치니까 염색한 것 같아요. 예뻐요!',
      replies: [
        { say: '노을 색 실 찾았어?', tier: 'great', face: 'wow', answer: '아직이요! 기억해 줬네요. 언젠가 꼭 수놓아 둘 거예요.' },
        { say: '그웬 머리도 빛나', tier: 'good', face: 'shy', answer: '어머, 칭찬을 돌려받았어요. 오늘 하루가 보송해졌어요.' },
        { say: '해가 지네', tier: 'meh', face: 'calm', answer: '네, 하루가 한 땀 끝났어요. 내일 또 한 땀이에요.' },
      ],
    },
    {
      id: 'op-festival',
      when: { festival: true },
      open: ['축제 날이에요! 다들 예쁘게 하고 오니까 제일 바쁜 날이에요.', '리본을 벌써 백 개는 묶었어요!'],
      replies: [
        { say: '나도 축제 머리 해 줘', tier: 'great', face: 'laugh', answer: '그럼요! 동백 핀 하나 꽂으면 광장에서 제일 예뻐요.' },
        { say: '좀 쉬면서 해', tier: 'good', face: 'smile', answer: '고마워요. 근데 신나서 손이 안 멈춰요. 이따 쉴게요!' },
        { say: '난 그냥 구경만', tier: 'meh', face: 'calm', answer: '구경도 좋아요. 그래도 리본 하나는 달고 가요!' },
      ],
    },
    {
      id: 'op-fish',
      when: { fish: true },
      open: ['{me} 님, 낚시했어요? 바닷바람에 머리가 엉켰어요!', '오늘 잡은 건 {fish} 맞죠? 대단해요.'],
      replies: [
        { say: '엉킨 머리 좀 빗어 줘', tier: 'great', face: 'laugh', answer: '앉아요! 소금기부터 털고, 살살 빗어 드릴게요.' },
        { say: '그웬도 같이 가자', tier: 'good', face: 'sorry', answer: '저는 벌레 미끼가 무서워요. 그래도 옆에서 응원은 할게요!' },
        { say: '별거 아니야', tier: 'meh', face: 'wow', answer: '별거예요! 저는 물고기 근처도 못 가는걸요.' },
      ],
    },
    {
      id: 'op-bigfish',
      when: { bigFish: true },
      open: '소문 들었어요! 엄청 큰 물고기를 낚았다면서요? 미용실까지 소문이 왔어요.',
      replies: [
        { say: '기념 머리 해 줄래?', tier: 'great', face: 'laugh', answer: '물론이죠! 물결 파마 어때요? 바다 기념이에요.' },
        { say: '소문이 빠르네', tier: 'good', face: 'smile', answer: '미용실은 소문이 제일 먼저 닿는 곳이거든요. 메르시 씨 의원이랑요.' },
        { say: '운이 좋았어', tier: 'meh', face: 'think', answer: '운도 실력이에요! 아, 이건 포츈 씨가 싫어하는 말이죠.' },
      ],
    },
    {
      id: 'op-harvest',
      when: { harvest: true },
      open: '밭일하고 왔어요? 머리에 지푸라기 붙었어요. 가만, 하나 둘…',
      replies: [
        { say: '고마워, 다 떼어 줘', tier: 'great', face: 'laugh', answer: '다 뗐어요! 지푸라기도 리본처럼 귀여웠지만요.' },
        { say: '흙냄새 나지?', tier: 'good', face: 'wow', answer: '좋은 냄새예요! 인형일 땐 흙냄새도 몰랐거든요.' },
        { say: '바빠서 그냥 갈래', tier: 'meh', face: 'sorry', answer: '잠깐만요, 하나만 더! …싹둑, 아니 쏙. 됐어요.' },
      ],
    },
    {
      id: 'op-gold',
      when: { gold: true },
      open: '금별 작물을 거뒀다면서요! 와, 그 반짝임으로 머리핀 만들고 싶어요.',
      replies: [
        { say: '그웬 머리핀 만들자', tier: 'great', face: 'wow', answer: '정말요? 금별 핀이라니! 거울 앞에서 계속 볼 거예요.' },
        { say: '열심히 키웠거든', tier: 'good', face: 'smile', answer: '한 땀 한 땀처럼요! 정성은 꼭 반짝여요.' },
        { say: '먹는 게 먼저야', tier: 'meh', face: 'laugh', answer: '헤헤, 맞아요. 반짝임은 마음에만 꽂아 둘게요.' },
      ],
    },
    {
      id: 'op-low',
      when: { mood: 'low' },
      open: ['{me} 님, 오늘 어깨가 축 처졌어요.', '앉아요. 머리 감겨 드릴게요. 개운해질 거예요.'],
      replies: [
        { say: '고마워. 좀 지쳤어', tier: 'great', face: 'smile', answer: ['그럼 오늘은 아무 말 안 해도 돼요.', '따뜻한 물이랑 착한 안개가 다 해 줄 거예요.'] },
        { say: '마음이 찢어진 기분이야', tier: 'good', face: 'sorry', answer: '터진 데는 꿰매면 돼요. 천천히, 한 땀씩요. 제가 옆에 있을게요.' },
        { say: '괜찮아', tier: 'meh', face: 'think', answer: '괜찮다는 얼굴이 아닌데요. 그래도 오늘은 제가 머리 빗어 줄게요.' },
      ],
    },
    {
      id: 'op-high',
      when: { mood: 'high' },
      open: '{me} 님, 오늘 얼굴이 반짝반짝해요! 좋은 일 있었죠?',
      replies: [
        { say: '그웬 보러 와서 그래', tier: 'great', face: 'shy', answer: '어머, 그런 말 하면 가위가 엇나가요! …그래도 좋아요.' },
        { say: '그냥 기분이 좋아', tier: 'good', face: 'laugh', answer: '그냥 좋은 날이 제일 좋은 날이에요. 리본 하나 달아 드릴게요!' },
        { say: '그래 보여?', tier: 'meh', face: 'smile', answer: '네! 거울 봐요. 제 말이 맞죠?' },
      ],
    },
    {
      id: 'op-bday',
      when: { bday: true },
      open: ['{me} 님, 생일 축하해요! 오늘은 공짜예요. 머리도, 리본도요!', '미선 씨한텐 비밀이에요.'],
      replies: [
        { say: '제일 예쁘게 해 줘', tier: 'great', face: 'laugh', answer: '맡겨 주세요! 오늘 {me} 님은 마을에서 제일 반짝일 거예요.' },
        { say: '공짜라니 미안한데', tier: 'good', face: 'smile', answer: '생일엔 미안한 거 아니에요. 받기만 하는 날이에요!' },
        { say: '생일 별로 안 챙겨', tier: 'meh', face: 'sorry', answer: '그럼 제가 챙길게요. 태어난 날은 신기한 날이잖아요.' },
      ],
    },
    {
      id: 'op-wedding',
      when: { news: 'wedding' },
      open: ['마을에 결혼 소식이 있대요! 신부 머리는 제가 하고 싶어요.', '면사포 끝단도 꿰매 드리고요.'],
      replies: [
        { say: '그웬 솜씨면 최고지', tier: 'great', face: 'shy', answer: '헤헤, 한 땀마다 행복하라고 빌면서 꿰맬 거예요.' },
        { say: '결혼식 가 봤어?', tier: 'good', face: 'wow', answer: '딱 한 번요! 다들 울면서 웃어서 깜짝 놀랐어요. 신기했어요.' },
        { say: '난 잘 모르는 사람이야', tier: 'meh', face: 'smile', answer: '그래도 축하는 해 줘요. 좋은 소식은 마을 모두의 거예요.' },
      ],
    },
    {
      id: 'op-janna',
      when: { bond: 'janna' },
      open: ['{other} 씨 만났어요? 아침에 방송 전 머리 해 드렸거든요.', '나가자마자 바람에 다 날아갔대요. 또요!'],
      replies: [
        { say: '바람 담당이라 그래', tier: 'great', face: 'laugh', answer: '그쵸! 다음엔 바람에 날려도 예쁜 머리로 해 드릴 거예요.' },
        { say: '그래도 예뻤어', tier: 'good', face: 'smile', answer: '다행이다! 잔나 씨는 머리가 날려도 예쁘긴 해요.' },
        { say: '그냥 묶으면 되잖아', tier: 'meh', face: 'think', answer: '묶어도 풀리던데요. 바람이 잔나 씨를 너무 좋아해요.' },
      ],
    },
    {
      id: 'op-mercy',
      when: { bond: 'mercy' },
      open: ['{other} 씨 의원 다녀왔어요? 거기랑 여기, 소문이 제일 빨라요.', '혹시 제 얘기 들었어요?'],
      replies: [
        { say: '칭찬만 하던데', tier: 'great', face: 'shy', answer: '정말요? 메르시 씨도 참. 다음에 머리 공짜로 해 드려야겠다.' },
        { say: '소문 뭐 있어?', tier: 'good', face: 'laugh', answer: '그건 비밀이에요! 미용 의자에서 들은 건 미용 의자에 남겨요.' },
        { say: '그냥 진료만 받았어', tier: 'meh', face: 'smile', answer: '아프지 마요! 아프면 머리도 같이 축 처져요.' },
      ],
    },
    {
      id: 'op-misun',
      when: { bond: 'misun' },
      open: ['{other} 씨 만났죠? 또 파마 값 얘기 했을 거예요.', '저는 안 깎아요. 리본은 달아 드려요!'],
      replies: [
        { say: '리본이 더 이득이래', tier: 'great', face: 'laugh', answer: '그쵸! 미선 씨도 실은 리본 받으러 오는 거예요. 헤헤.' },
        { say: '조금만 깎아 줘', tier: 'good', face: 'think', answer: '안 돼요. 대신 앞머리는 덤으로 다듬어 드릴게요.' },
        { say: '둘이 싸워?', tier: 'meh', face: 'smile', answer: '아뇨! 단골이랑 원장의 놀이예요. 매번 즐거워요.' },
      ],
    },
    {
      id: 'op-cloudy',
      when: { weather: 'cloudy' },
      open: ['흐린 날은 머리가 차분해서 다듬기 좋아요.', '근데 안개까지 끼면 좀 긴장돼요. 드라이어 옆에 꼭 붙어요.'],
      replies: [
        { say: '착한 안개로 맞서자', tier: 'great', face: 'laugh', answer: '그쵸! 몽글몽글 따뜻한 쪽이 이겨요. 언제나요.' },
        { say: '오늘 다듬어 줄래?', tier: 'good', face: 'smile', answer: '좋아요! 흐린 날 다듬은 머리는 오래가요.' },
        { say: '흐린 날 싫어', tier: 'meh', face: 'think', answer: '그럼 밝은 핀 하나 꽂아요. 기분이 바로 맑아져요.' },
      ],
    },
    {
      id: 'op-sunny',
      when: { weather: 'sunny' },
      open: '해 좋은 날엔 창가에서 바느질해요. 바늘귀가 반짝반짝 잘 보여요.',
      replies: [
        { say: '나도 옆에 앉아도 돼?', tier: 'great', face: 'shy', answer: '그럼요! 해님 자리 반 나눠 드릴게요. 따뜻하죠?' },
        { say: '뭐 만들고 있어?', tier: 'good', face: 'smile', answer: '리본이요. 오늘 날씨 같은 노란색이에요.' },
        { say: '눈 부시겠다', tier: 'meh', face: 'calm', answer: '조금요. 그래도 햇빛은 처음부터 지금까지 계속 좋아요.' },
      ],
    },
    {
      id: 'op-spring',
      when: { season: 'spring' },
      open: ['봄이에요! 진달래 색 실로 리본을 새로 떴어요.', '세상이 다시 꿰매진 것처럼 반짝해요.'],
      replies: [
        { say: '그 리본 나도 달아 줘', tier: 'great', face: 'laugh', answer: '그럴 줄 알고 하나 더 떴어요! 자, 고개 살짝 숙여요.' },
        { say: '봄은 처음 아니잖아', tier: 'good', face: 'think', answer: '그래도 매번 처음 같아요. 봄은 그런 계절인가 봐요.' },
        { say: '꽃가루 때문에 싫어', tier: 'meh', face: 'sorry', answer: '아, 재채기! 메르시 씨한테 가 봐요. 저는 손수건 드릴게요.' },
      ],
    },
    {
      id: 'op-summer',
      when: { season: 'summer' },
      open: '여름이에요! 싹둑이가 제일 바쁜 계절이에요. 다들 짧게 해 달래요.',
      replies: [
        { say: '나도 시원하게 해 줘', tier: 'great', face: 'laugh', answer: '맡겨요! 목덜미에 바람 지나가게 싹둑싹둑!' },
        { say: '그웬은 안 더워?', tier: 'good', face: 'smile', answer: '덥지만 신기해요. 땀이 난다는 것도 사람이 돼서 알았어요.' },
        { say: '난 길게 둘래', tier: 'meh', face: 'calm', answer: '그럼 올림머리 해 드릴게요. 그것도 시원해요.' },
      ],
    },
    {
      id: 'op-autumn',
      when: { season: 'autumn' },
      open: ['코스모스가 폈어요! 꽃잎을 앞치마에 수놓았어요.', '보여요? 바람 부는 쪽으로 살짝 기울였어요.'],
      replies: [
        { say: '진짜 꽃 같아', tier: 'great', face: 'wow', answer: '헤헤, 벌이 앉을 뻔했어요. 그건 좀 무서웠어요.' },
        { say: '단풍색 염색도 해?', tier: 'good', face: 'smile', answer: '요즘 제일 인기예요. {me} 님한테도 어울릴 거예요.' },
        { say: '가을은 쓸쓸해', tier: 'meh', face: 'think', answer: '그럼 따뜻한 색 실로 목도리 떠 드릴게요. 덜 쓸쓸하게요.' },
      ],
    },
    {
      id: 'op-winter',
      when: { season: 'winter' },
      open: ['겨울이에요. 동백이 피는 계절이에요!', '털실 감다가 손이 따뜻해지는 게 너무 좋아요.'],
      replies: [
        { say: '동백 같이 보러 가자', tier: 'great', face: 'wow', answer: '좋아요! 눈 위에 빨간 동백, {me} 님이랑 보고 싶었어요.' },
        { say: '목도리 떠 줄 수 있어?', tier: 'good', face: 'laugh', answer: '벌써 반 떴어요. 누구 건지는 비밀이에요. 헤헤.' },
        { say: '추워서 싫어', tier: 'meh', face: 'sorry', answer: '얼른 들어와요. 착한 안개로 녹여 드릴게요.' },
      ],
    },
    {
      id: 'op-night',
      when: { time: 'night' },
      open: ['밤엔 실 정리를 해요. 색깔별로, 길이별로요.', '조용해서 실이 하는 말이 들리는 것 같아요.'],
      replies: [
        { say: '실이 뭐라고 해?', tier: 'great', face: 'laugh', answer: '"오늘도 잘 이었어" 래요. 헤헤, 제가 지어낸 거예요.' },
        { say: '같이 정리할게', tier: 'good', face: 'smile', answer: '고마워요! 빨강은 여기, 파랑은 저기요. 엉키면 안 돼요.' },
        { say: '얼른 자야지', tier: 'meh', face: 'calm', answer: '네, 이것만 감고요. {me} 님도 머리 말리고 자요!' },
      ],
    },
    {
      id: 'op-festival-night',
      when: { festival: true, time: 'night' },
      open: ['축제 밤이에요. 리본이 다 풀리기 전에 다들 집에 갔으면 좋겠어요.', '저는 오늘 리본을 정말 많이 묶었어요.'],
      replies: [
        { say: '수고했어, 그웬', tier: 'great', face: 'shy', answer: '그 말 들으니까 손가락이 하나도 안 아파요. 진짜로요.' },
        { say: '내 리본은 아직 있어', tier: 'good', face: 'laugh', answer: '와, 끝까지 버텼네요! 이졸데 할머니 매듭이에요.' },
        { say: '축제 끝나서 아쉽다', tier: 'meh', face: 'calm', answer: '아쉬우면 내년이 더 신나요. 그것도 처음 배웠어요.' },
      ],
    },
    {
      id: 'op-voyage',
      when: { recent: 'voyage' },
      open: ['먼바다 다녀왔다면서요? 소금기에 머리가 뻣뻣해요.', '바다 안개는 괜찮았어요? 저는 그게 제일 걱정돼요.'],
      replies: [
        { say: '그웬 생각하며 버텼어', tier: 'great', face: 'shy', answer: ['어머… 그럼 다음엔 리본 하나 들고 가요. 부적이에요.', '착한 안개 냄새 배어 있을 거예요.'] },
        { say: '머리 좀 살려 줘', tier: 'good', face: 'laugh', answer: '앉아요! 미지근한 물로 소금기부터 싹 헹궈요.' },
        { say: '안개쯤이야', tier: 'meh', face: 'wow', answer: '용감해요. 그래도 무사히 와 줘서 고마워요.' },
      ],
    },
    {
      id: 'op-casino-lose',
      when: { recent: 'casinoLose' },
      open: '카지노에서 잃었어요? 주머니에 구멍 났나 봐요. 이리 줘 봐요.',
      replies: [
        { say: '마음 구멍도 꿰매 줘', tier: 'great', face: 'smile', answer: ['그건 머리 감기면서 꿰매요. 따뜻한 물이 실이에요.', '한 땀이면 돼요. 금방이에요.'] },
        { say: '다음엔 딸 거야', tier: 'good', face: 'think', answer: '미스 포츈 씨가 들으면 좋아하겠다. 저는 걱정돼요.' },
        { say: '말하기 싫어', tier: 'meh', face: 'sorry', answer: '알았어요. 아무 말 안 하고 빗질만 할게요.' },
      ],
    },
    {
      id: 'op-stock-up',
      when: { recent: 'stockUp' },
      open: '증권에서 좋은 일 있었죠? 얼굴에 다 쓰여 있어요!',
      replies: [
        { say: '축하 머리 해 줘', tier: 'great', face: 'laugh', answer: '좋아요! 축하 리본은 금색으로요. 반짝반짝!' },
        { say: '무잔 씨가 알려 줬어', tier: 'good', face: 'think', answer: '무잔 씨는 머리를 늘 자기가 해요. 언젠가 제 의자에 앉힐 거예요.' },
        { say: '운이 좋았지', tier: 'meh', face: 'smile', answer: '좋은 운은 좋은 머리에 붙어요. 제가 지어낸 말이에요.' },
      ],
    },
    {
      id: 'op-museum',
      when: { news: 'museum' },
      open: '박물관에 새 기증품이 들어왔대요! 저 그런 거 처음 봐요. 보러 갈래요?',
      replies: [
        { say: '같이 가서 구경하자', tier: 'great', face: 'wow', answer: '좋아요! 신기한 거 보면 제 손을 꼭 잡아 줘요. 놀라니까요.' },
        { say: '뭐가 들어왔대?', tier: 'good', face: 'think', answer: '반짝이는 거래요. 머리핀으로 쓰면 안 되겠죠? 헤헤.' },
        { say: '박물관은 지루해', tier: 'meh', face: 'calm', answer: '처음 보는 게 잔뜩인데요? 저한텐 놀이터예요.' },
      ],
    },
    {
      id: 'op-legend',
      when: { news: 'legend' },
      open: ['전설의 물고기가 잡혔대요! 비늘이 무지갯빛이래요.', '그 색 실이 있으면 좋겠다… 상상만 해도 떨려요.'],
      replies: [
        { say: '그 색 같이 찾아보자', tier: 'great', face: 'wow', answer: '노을 색처럼요? 좋아요. {me} 님이랑 찾으면 찾아져요.' },
        { say: '럭스 어시장 가 봐', tier: 'good', face: 'smile', answer: '맞다, 럭스 씨! 비늘 하나만 얻을 수 있을까요?' },
        { say: '물고기는 비린데', tier: 'meh', face: 'sorry', answer: '그건 맞아요. 비늘만, 아주 깨끗한 비늘만요.' },
      ],
    },
    {
      id: 'op-friend-wedding',
      when: { friendNews: 'wedding' },
      open: ['{me} 님 친구가 결혼한대요! 신부 머리 맡겨 줄까요?', '면사포 끝단은 벌써 머릿속에서 꿰매고 있어요.'],
      replies: [
        { say: '그웬한테 꼭 부탁할게', tier: 'great', face: 'laugh', answer: '맡겨 줘요! 한 땀마다 행복하라고 빌게요.' },
        { say: '축하 리본 하나 떠 줘', tier: 'good', face: 'smile', answer: '흰색이랑 분홍 섞어서요. 내일까지 해 둘게요.' },
        { say: '나는 언제 하지', tier: 'meh', face: 'shy', answer: '어머… 그건 제가 대답할 게 아닌 것 같아요. 헤헤.' },
      ],
    },
    {
      id: 'op-sulk',
      when: { sulk: true },
      open: ['{other} 씨랑 어제 좀 서먹해졌어요.', '실이 한 번 엉킨 것 같아요. 어떻게 풀죠?'],
      replies: [
        { say: '천천히 풀면 돼', tier: 'great', face: 'smile', answer: ['맞아요. 엉킨 실은 당기면 더 엉켜요.', '내일 리본 하나 들고 가서 천천히 풀래요.'] },
        { say: '먼저 사과해 봐', tier: 'good', face: 'think', answer: '용기가 필요하네요. {me} 님이 응원해 주면 할 수 있어요.' },
        { say: '싹둑 잘라 버려', tier: 'meh', face: 'sorry', answer: '사람 사이 실은 자르면 안 돼요. 그건 싹둑이도 반대래요.' },
      ],
    },
    {
      id: 'op-with-janna',
      when: { with: 'janna' },
      open: ['{other} 씨 머리 봐요. 오늘은 아직 안 날아갔어요!', '핀을 일곱 개 꽂았거든요. 쉿, 바람 들어요.'],
      replies: [
        { say: '오늘은 바람이 졌네', tier: 'great', face: 'laugh', answer: '그쵸! 보송 미용실이 이겼어요. 기록해 둬야지.' },
        { say: '잔나 머리 예쁘다', tier: 'good', face: 'smile', answer: '{other} 씨, 들었죠? 칭찬은 바람에 안 날아가요.' },
        { say: '곧 날아갈 것 같은데', tier: 'meh', face: 'sorry', answer: '그런 말 하면 진짜 날아가요! 바람이 듣고 있다니까요.' },
      ],
    },
    {
      id: 'op-with-thresh',
      when: { with: 'thresh' },
      open: ['{other} 씨랑 단추 고르는 중이에요. 등불이 가까워서 좀…', '아, 아니에요! 단추가 너무 예뻐서 떨리는 거예요.'],
      replies: [
        { say: '내가 옆에 있을게', tier: 'great', face: 'shy', answer: '고마워요. {me} 님 옆이면 초록 불빛도 조금 덜 차가워요.' },
        { say: '쓰레쉬 단추 최고지', tier: 'good', face: 'laugh', answer: '맞아요. 이 진주 단추 봐요. 바다 안개 색이에요.' },
        { say: '무서우면 나가자', tier: 'meh', face: 'think', answer: '조금만요. 이 단추만 고르고요. 단추가 먼저예요.' },
      ],
    },
    {
      id: 'op-with-mercy',
      when: { with: 'mercy' },
      open: ['{other} 씨랑 차 마시는 중이었어요. 마을 소문 정리 시간이에요.', '아, 나쁜 소문은 없어요! 다 예쁜 소문이에요.'],
      replies: [
        { say: '나도 끼워 줘', tier: 'great', face: 'laugh', answer: '좋아요! 오늘의 소문은요… {me} 님 머리가 예쁘다는 거예요.' },
        { say: '둘이 친하구나', tier: 'good', face: 'smile', answer: '의원이랑 미용실은 이웃 같아요. 둘 다 사람을 낫게 하니까요.' },
        { say: '소문은 별로야', tier: 'meh', face: 'sorry', answer: '그럼 소문 말고 꽃 얘기 할게요. 그건 괜찮죠?' },
      ],
    },
    {
      id: 'op-with-misun',
      when: { with: 'misun' },
      open: ['{other} 씨가 또 파마 값 얘기 꺼내려던 참이에요.', '{me} 님, 제 편 들어 줄 거죠?'],
      replies: [
        { say: '리본 두 개면 되잖아', tier: 'great', face: 'laugh', answer: '그거예요! 값은 그대로, 리본은 두 개. 미선 씨 웃었어요.' },
        { say: '이번만 깎아 줘', tier: 'good', face: 'think', answer: '{me} 님까지! 그럼 앞머리 덤으로 다듬어 드릴게요. 끝!' },
        { say: '난 빠질게', tier: 'meh', face: 'sorry', answer: '도망가면 안 돼요! 둘이서 미선 씨 상대는 무리예요.' },
      ],
    },
  ],
  callbacks: [
    {
      id: 'cb-scissors',
      when: { mem: 'scissors-name' },
      use: 'scissors-name',
      open: '싹둑이가 {me} 님 오면 꼭 인사하래요. 지난번 인사가 좋았대요.',
      replies: [
        { say: '싹둑아, 잘 지냈어?', tier: 'great', face: 'laugh', answer: '방금 반짝했어요! 오늘은 더 잘 잘릴 거예요.' },
        { say: '콕콕이도 잘 지내?', tier: 'good', face: 'wow', answer: '바늘 이름까지 기억했어요? 콕콕이도 반가워해요!' },
        { say: '가위가 말을 해?', tier: 'meh', face: 'smile', answer: '마음으로 해요. 들을 줄 아는 사람한테만요.' },
      ],
    },
    {
      id: 'cb-isolde',
      when: { mem: 'isolde-story' },
      use: 'isolde-story',
      open: ['이졸데 할머니 얘기 들어 줬던 거 기억나요.', '어젯밤 할머니 바늘 쌈지를 오랜만에 열어 봤어요.'],
      replies: [
        { say: '할머니가 기뻐하셨겠다', tier: 'great', face: 'shy', answer: '그럴까요? …바늘이 아직 반짝했어요. 할머니 손 같았어요.' },
        { say: '안에 뭐가 있었어?', tier: 'good', face: 'smile', answer: '빨간 실 한 타래랑 단추 두 개요. 제 옛날 눈인가 봐요. 헤헤.' },
        { say: '오래된 거네', tier: 'meh', face: 'calm', answer: '오래돼서 더 소중해요. 한 땀씩 쌓인 거니까요.' },
      ],
    },
    {
      id: 'cb-good-mist',
      when: { mem: 'good-mist' },
      use: 'good-mist',
      open: '착한 안개라고 같이 불러 줬잖아요. 그 뒤로 드라이어 켤 때마다 웃음 나요.',
      replies: [
        { say: '오늘도 착한 안개 부탁해', tier: 'great', face: 'laugh', answer: '맡겨 주세요! 오늘은 특별히 몽글몽글하게요.' },
        { say: '나도 집에서 그렇게 불러', tier: 'good', face: 'wow', answer: '정말요? 착한 안개가 마을에 퍼지고 있어요!' },
        { say: '그런 말 했었나?', tier: 'meh', face: 'smile', answer: '했어요! 저는 다 기억해요. 칭찬은 특히요.' },
      ],
    },
    {
      id: 'cb-button',
      when: { mem: 'button-eyes' },
      use: 'button-eyes',
      open: ['단추 눈 얘기 기억해요? 오늘 손님 외투에서 똑같은 단추를 봤어요.', '깜짝 놀라서 거울을 봤어요. 헤헤.'],
      replies: [
        { say: '지금 눈이 훨씬 예뻐', tier: 'great', face: 'shy', answer: '…또 그 말. 단추일 땐 이렇게 볼이 뜨거워질 줄 몰랐어요.' },
        { say: '그 단추 받아 왔어?', tier: 'good', face: 'laugh', answer: '아뇨, 손님 거니까요! 대신 단단히 다시 달아 드렸어요.' },
        { say: '단추가 다 비슷하지', tier: 'meh', face: 'think', answer: '비슷해도 다 달라요. 꿰매 본 사람은 알아요.' },
      ],
    },
    {
      id: 'cb-green-mist',
      when: { mem: 'green-mist' },
      use: 'green-mist',
      open: ['드라이어로 막자고 했던 거, 진짜 해 봤어요.', '쓰레쉬 씨가 웃었어요. 그 안개는 그냥 장식이래요.'],
      replies: [
        { say: '용감했네, 그웬', tier: 'great', face: 'laugh', answer: '헤헤, {me} 님 덕분이에요. 이제 지나갈 때 인사도 해요.' },
        { say: '장식이라니 다행이다', tier: 'good', face: 'smile', answer: '그래도 좀 으스스한 장식이에요. 거기까지는 양보 못 해요.' },
        { say: '쓰레쉬 씨 놀랐겠다', tier: 'meh', face: 'sorry', answer: '조금요… 다음엔 리본 하나 들고 사과하러 갈래요.' },
      ],
    },
    {
      id: 'cb-taste',
      when: { mem: '@taste', noMem: 'taste-heard' },
      open: '{me} 님 좋아하는 게 {taste} 맞죠? 그 색으로 리본을 떠 볼까 해요.',
      replies: [
        { say: '그웬 리본이면 다 좋아', tier: 'great', remember: 'taste-heard', face: 'shy', answer: '어머… 그럼 더 정성껏 떠야겠다. 한 땀마다 {me} 님 생각할게요.' },
        { say: '그걸 어떻게 알았어?', tier: 'good', remember: 'taste-heard', face: 'laugh', answer: '미용 의자에선 다 들려요. 손님이 좋아하는 건 꼭 기억해요.' },
        { say: '리본은 좀 부끄러운데', tier: 'meh', remember: 'taste-heard', face: 'smile', answer: '그럼 가방 손잡이에 달아요. 아무도 몰라요.' },
      ],
    },
    {
      id: 'cb-outing',
      when: { mem: '@outing', noMem: 'outing-talk' },
      open: ['같이 걸었던 날이요. 처음 보는 골목이 너무 많아서 신났어요.', '{me} 님은 길을 다 알더라고요.'],
      replies: [
        { say: '다음엔 새 길로 가자', tier: 'great', remember: 'outing-talk', face: 'wow', answer: '좋아요! 처음 가는 길은 {me} 님이랑 가는 게 제일 좋아요.' },
        { say: '그웬 덕에 나도 신났어', tier: 'good', remember: 'outing-talk', face: 'smile', answer: '헤헤, 신나는 건 옮는대요. 좋은 병이에요.' },
        { say: '다리 아프지 않았어?', tier: 'meh', remember: 'outing-talk', face: 'laugh', answer: '하나도요! 인형 다리보다 훨씬 튼튼해요.' },
      ],
    },
    {
      id: 'cb-bday',
      when: { mem: '@bday-soon', noMem: 'bday-plan' },
      open: ['{me} 님 생일 곧이죠? 그날은 미용실 첫 손님 자리 비워 둘게요.', '어떤 머리 하고 싶어요?'],
      replies: [
        { say: '그웬이 골라 줘', tier: 'great', remember: 'bday-plan', face: 'laugh', answer: '맡겨 주세요! 아무한테도 안 한 머리로 해 드릴게요.' },
        { say: '동백 핀 꽂아 줘', tier: 'good', remember: 'bday-plan', face: 'shy', answer: '좋아요! 제일 예쁜 동백으로 제가 직접 만들게요.' },
        { say: '그냥 평소대로', tier: 'meh', remember: 'bday-plan', face: 'smile', answer: '평소대로라도 리본 하나는 꼭 달 거예요. 생일이니까요.' },
      ],
    },
    {
      id: 'cb-patch',
      when: { mem: 'patch-scrap' },
      use: 'patch-scrap',
      open: ['조각보에 {me} 님 자투리 넣기로 했잖아요.', '소매 끝 실밥 하나만 주면 돼요. 싹둑, 아니 살살요.'],
      replies: [
        { say: '마음껏 가져가', tier: 'great', face: 'laugh', answer: '고마워요! 이 조각은 제일 가운데, 제일 따뜻한 자리예요.' },
        { say: '실밥 하나로 돼?', tier: 'good', face: 'smile', answer: '실 한 올이면 충분해요. 이을 줄만 알면요.' },
        { say: '그거 아직 해?', tier: 'meh', face: 'think', answer: '그럼요! 조각보는 마을이 다 모일 때까지 계속돼요.' },
      ],
    },
    {
      id: 'cb-bread',
      when: { mem: 'bread-first' },
      use: 'bread-first',
      open: '크림빵 얘기 기억해요? 오늘은 프리렌 씨가 새 빵을 줬어요. 또 처음이에요!',
      replies: [
        { say: '이번엔 별 몇 개야?', tier: 'great', face: 'laugh', answer: ['네 개요! 수첩 칸이 모자랐어요.', '힘멜 씨가 옆에서 같이 박수 쳐 줬어요.'] },
        { say: '반 나눠 줄래?', tier: 'good', face: 'smile', answer: '그럼요! 처음인 맛은 나누면 두 번 처음이에요.' },
        { say: '빵 또 먹었어?', tier: 'meh', face: 'shy', answer: '…네. 처음인 걸 어떻게 참아요.' },
      ],
    },
    {
      id: 'cb-thresh',
      when: { mem: 'thresh-shop' },
      use: 'thresh-shop',
      open: ['쓰레쉬 씨 가게에서 산 진주 단추, {me} 님 외투에 달아 드릴까요?', '용기 내서 산 거니까 의미 있는 데 달고 싶어요.'],
      replies: [
        { say: '그웬이 달아 주면 좋지', tier: 'great', face: 'shy', answer: '그럼 한 땀 한 땀 정성껏요. 절대 안 떨어지게요.' },
        { say: '쓰레쉬 씨 뭐래?', tier: 'good', face: 'laugh', answer: '"좋은 눈을 가졌군요" 래요. 단추 눈 시절 생각나서 웃었어요.' },
        { say: '그웬 옷에 달아', tier: 'meh', face: 'smile', answer: '저는 벌써 하나 달았어요. 그럼 짝꿍 단추네요!' },
      ],
    },
    {
      id: 'cb-janna',
      when: { mem: 'janna-hair' },
      use: 'janna-hair',
      open: ['잔나 씨 머리 대작전, 드디어 성공했어요!', '반나절이나 안 날아갔대요. 신문에 날 일이래요.'],
      replies: [
        { say: '그웬 솜씨 최고다', tier: 'great', face: 'laugh', answer: '헤헤, 비결은 땋은 머리예요. 바람이 풀 틈이 없게요.' },
        { say: '진짜 신문에 났어?', tier: 'good', face: 'wow', answer: '잔나 씨가 쓰겠대요. 제목은 "바람, 처음으로 지다" 래요.' },
        { say: '반나절 뒤엔?', tier: 'meh', face: 'sorry', answer: '…날아갔어요. 그래도 반나절은 이긴 거예요!' },
      ],
    },
    {
      id: 'cb-mercy',
      when: { mem: 'mercy-knot' },
      use: 'mercy-knot',
      open: ['메르시 씨한테 바느질 매듭을 하나 가르쳐 드렸어요.', '대신 저는 붕대 감는 법을 배웠어요. 서로 바꾼 거예요.'],
      replies: [
        { say: '마을을 같이 돌보는구나', tier: 'great', face: 'shy', answer: '그렇게 말해 주니까 좋다. 둘이 같이 이어 주는 거예요.' },
        { say: '붕대 감는 거 어려워?', tier: 'good', face: 'think', answer: '바느질보다 어려워요. 너무 꽉 감으면 혼나요.' },
        { say: '난 다치기 싫은데', tier: 'meh', face: 'smile', answer: '다치지 마요! 배운 건 안 쓰는 게 제일 좋아요.' },
      ],
    },
    {
      id: 'cb-mirror',
      when: { mem: 'mirror-first' },
      use: 'mirror-first',
      open: '거울에 인사한 얘기, 기억하죠? 오늘 아침엔 거울이 저보다 먼저 웃었어요.',
      replies: [
        { say: '그웬이 먼저 웃은 거야', tier: 'great', face: 'laugh', answer: '그런가요? 그럼 {me} 님 생각하다 웃은 거예요. 헤헤.' },
        { say: '거울도 친구가 됐네', tier: 'good', face: 'smile', answer: '싹둑이, 콕콕이, 그리고 거울이요. 친구가 늘어요.' },
        { say: '그건 기분 탓이야', tier: 'meh', face: 'calm', answer: '기분 탓이어도 좋아요. 좋은 기분이었으니까요.' },
      ],
    },
    {
      id: 'cb-dream',
      when: { mem: 'dream-talk' },
      use: 'dream-talk',
      open: ['하늘 꿰매는 꿈, 또 꿨어요.', '이번엔 {me} 님이 옆에서 실을 들어 줬어요.'],
      replies: [
        { say: '꿈에서도 도와줄게', tier: 'great', face: 'shy', answer: '그래서 바늘이 하나도 안 무거웠나 봐요. 고마워요.' },
        { say: '별은 안 샜어?', tier: 'good', face: 'laugh', answer: '하나도요! 둘이 꿰매니까 훨씬 촘촘했어요.' },
        { say: '꿈은 꿈이지', tier: 'meh', face: 'think', answer: '네. 그래도 깨고 나서 하루 종일 기분이 좋았어요.' },
      ],
    },
    {
      id: 'cb-ornn',
      when: { mem: 'ornn-whet' },
      use: 'ornn-whet',
      open: ['싹둑이 다녀왔어요! 오른 씨가 날을 반짝반짝 갈아 줬어요.', '들어 봐요. 싹, 둑. 소리가 맑아졌죠?'],
      replies: [
        { say: '노래처럼 맑다', tier: 'great', face: 'laugh', answer: '그쵸! 오늘 손님들 머리가 다 노래하는 것 같아요.' },
        { say: '오른 씨한테 꽃 줬어?', tier: 'good', face: 'smile', answer: '동백 꽃잎이요. 아무 말 없이 화덕 옆에 두더라고요.' },
        { say: '소리 차이 모르겠어', tier: 'meh', face: 'think', answer: '귀를 가까이 대 봐요. 아, 너무 가까이는 말고요!' },
      ],
    },
    {
      id: 'cb-sew',
      when: { mem: 'sew-lesson' },
      use: 'sew-lesson',
      open: ['바느질 배우기로 했죠? 오늘 첫 수업이에요.', '단추 구멍 네 개, 바늘은 천천히, 실은 넉넉히.'],
      replies: [
        { say: '잘 봐 줘, 선생님', tier: 'great', face: 'laugh', answer: ['선생님이래! …좋아요. 손 이리 줘요.', '오, 첫 땀이 반듯해요. 소질 있어요!'] },
        { say: '실이 엉켰어', tier: 'good', face: 'smile', answer: '괜찮아요. 엉킨 실 푸는 것도 바느질이에요.' },
        { say: '역시 어렵다', tier: 'meh', face: 'think', answer: '처음엔 다 그래요. 저도 할머니 앞에서 많이 울었어요.' },
      ],
    },
    {
      id: 'cb-camellia',
      when: { mem: 'camellia-love' },
      use: 'camellia-love',
      open: '동백 좋아한다고 했죠? 창가 동백이 오늘 아침에 한 송이 더 폈어요.',
      replies: [
        { say: '보러 가도 돼?', tier: 'great', face: 'wow', answer: '물론이죠! {me} 님 오면 더 활짝 필 거예요.' },
        { say: '그웬 머리에 꽂아', tier: 'good', face: 'shy', answer: '어머, 그럼 오늘은 제가 꽃 손님이네요. 헤헤.' },
        { say: '금방 지겠다', tier: 'meh', face: 'calm', answer: '그래서 오늘 꼭 봐 둬야 해요. 금방 지는 건 오래 봐요.' },
      ],
    },
    {
      id: 'cb-braid',
      when: { mem: 'braid-me' },
      use: 'braid-me',
      open: ['땋은 머리 해 보고 싶다고 했잖아요. 오늘 손이 근질근질해요.', '세 갈래, 한 땀 한 땀처럼요.'],
      replies: [
        { say: '오늘 해 줘', tier: 'great', face: 'laugh', answer: ['자, 고개 똑바로요. 하나, 둘, 셋, 다시 하나…', '다 됐어요! 거울 봐요. 놀랐죠?'] },
        { say: '리본도 같이 달아 줘', tier: 'good', face: 'smile', answer: '당연하죠. 노을 색 리본으로 끝을 묶을게요.' },
        { say: '다음에 할래', tier: 'meh', face: 'sorry', answer: '알았어요. 손은 근질거리지만 참을게요.' },
      ],
    },
    {
      id: 'cb-smell',
      when: { mem: 'fav-smell' },
      use: 'fav-smell',
      open: ['비 냄새 좋아한다고 했죠? 그 냄새를 향주머니에 담아 보려고요.', '젖은 흙을 조금 말려서 꿰매면 될까요?'],
      replies: [
        { say: '그웬이면 할 수 있어', tier: 'great', face: 'laugh', answer: '그쵸? 다 되면 {me} 님한테 제일 먼저 줄게요.' },
        { say: '흙 냄새가 날까?', tier: 'good', face: 'think', answer: '음, 그냥 흙 냄새가 날지도요. 그래도 해 볼래요.' },
        { say: '비 오는 날 맡으면 되지', tier: 'meh', face: 'smile', answer: '맞아요. 근데 맑은 날에도 꺼내 맡고 싶었어요.' },
      ],
    },
    {
      id: 'cb-mist-lamp',
      when: { mem: 'mist-lamp' },
      use: 'mist-lamp',
      open: ['어젯밤에 바다 안개가 왔어요. 그래서 불을 켜 뒀어요.', '{me} 님 말대로 등대처럼요. 손님이 셋이나 들렀어요.'],
      replies: [
        { say: '그웬 불이 사람을 불렀네', tier: 'great', face: 'shy', answer: '다들 따뜻해서 들렀대요. 착한 안개랑 불빛 덕분이에요.' },
        { say: '무섭진 않았어?', tier: 'good', face: 'smile', answer: '조금요. 근데 불 켜고 있으니까 하나도 안 혼자였어요.' },
        { say: '잠은 잤어?', tier: 'meh', face: 'calm', answer: '조금 늦게요. 그래도 오늘 아침도 신기했어요.' },
      ],
    },
    {
      id: 'cb-date',
      when: { mem: '@date', noMem: 'date-talk' },
      open: ['{me} 님 방에 갔던 날, 커튼 끝단 봤어요.', '꿰매 드리고 싶은 걸 꾹 참았어요. 데이트잖아요.'],
      replies: [
        { say: '다음엔 꿰매 줘', tier: 'great', remember: 'date-talk', face: 'laugh', answer: '정말요? 그럼 다음엔 바늘 쌈지 챙겨 갈게요!' },
        { say: '참느라 고생했어', tier: 'good', remember: 'date-talk', face: 'shy', answer: '조금요. 그래도 {me} 님만 봤어요. 진짜예요.' },
        { say: '커튼 멀쩡한데', tier: 'meh', remember: 'date-talk', face: 'think', answer: '실밥 하나 있어요. 왼쪽 아래요. 다음에 보여 줄게요.' },
      ],
    },
  ],
  chapters: [
    {
      title: '보송 미용실의 첫 손님',
      hint: '한 번 이야기를 나누면 그웬이 미용 의자를 돌려 줘요.',
      need: { days: 1 },
      scene: [
        '보송 미용실 문을 열자 작은 종이 딸랑 울린다.',
        '그웬이 미용 의자를 빙그르르 돌려 내 쪽으로 세운다.',
        '"어서 오세요! 보송 미용실 원장 그웬이에요."',
        '"앉아 봐요. 와, 머릿결 좋다. 귀 모양도 예쁘고요."',
        '그녀가 가위를 들어 보인다. "이 친구는 싹둑이예요."',
        '거울 옆 선반엔 알록달록한 자투리 천이 상자 가득이다.',
        '"아, 저건 손님들 옷 자투리예요. 버리지 않고 모아요."',
        '"언젠가 다 이어서 마을 조각보를 만들 거예요."',
        '그녀가 내 소매 끝 실밥을 보더니 눈을 반짝인다.',
        '"…싹둑! 첫 조각은 이걸로 할게요. 괜찮죠?"',
        '"오늘부터 {me} 님 머리는 제가 제일 잘 알게 될 거예요."',
      ],
      replies: [
        { say: '잘 부탁해, 원장님', tier: 'great', face: 'laugh', answer: '원장님이라니! 그냥 그웬이라고 불러요. 그게 더 좋아요.' },
        { say: '실밥이 첫 조각이라니', tier: 'good', remember: 'patch-scrap', face: 'smile', answer: ['작은 실밥도 이으면 이불이 돼요.', '{me} 님 조각은 가운데 자리로 비워 둘게요.'] },
        { say: '그냥 구경 왔어', tier: 'meh', face: 'calm', answer: '구경도 환영이에요. 다음엔 앉아 줘요!' },
      ],
    },
    {
      title: '노을 색 실',
      hint: '저녁(게임 시각 오후 다섯 시부터 여덟 시) 마을 광장에 가 보세요. 그웬이 노을 색 실을 찾는대요.',
      need: { days: 3, points: 20, visit: { area: 'village', from: 17, to: 20 } },
      scene: [
        '마을 광장, 해가 기울 무렵. 그웬이 실타래를 하늘에 대 보고 있다.',
        '"아, 왔네요! 노을 색 실을 찾는 중이에요."',
        '"조각보 테두리를 노을 색으로 두르고 싶거든요."',
        '"이건 너무 빨갛고, 이건 너무 노랗고… 하늘은 둘 다예요."',
        '그녀가 실 두 가닥을 겹쳐 꼬아 본다.',
        '그때 바다 쪽에서 잿빛 안개가 광장 끝으로 밀려든다.',
        '그웬의 손이 멈춘다. 실타래를 가슴에 꼭 안는다.',
        '"…저 안개는 좀 싫어요. 차갑고, 색을 다 지워요."',
        '내가 옆에 서자 그녀가 작게 숨을 내쉰다.',
        '"할머니가 그랬어요. 무서울 땐 손에 쥔 걸 보라고."',
        '그녀가 꼰 실을 노을에 다시 대 본다. 색이 살아난다.',
        '"봐요, 안개가 와도 실 색은 그대로예요."',
        '"이렇게 꼬면 될까요? 처음 해 보는 색이라 떨려요."',
      ],
      replies: [
        { say: '딱 노을 색이야', tier: 'great', remember: 'sunset-thread', face: 'wow', answer: ['정말요? 와… {me} 님이랑 찾으니까 찾아졌어요!', '안개도 이제 하나도 안 무서워요. 조금만요.'] },
        { say: '안개 올 땐 손 잡아', tier: 'good', remember: 'mist-brave', face: 'shy', answer: '…네. 손 잡으니까 실보다 따뜻하네요. 신기해요.' },
        { say: '그냥 빨간 실 같은데', tier: 'meh', remember: 'sunset-thread', face: 'think', answer: '음… 해가 다 지면 다시 대 볼게요. 색은 금방 변하니까요.' },
      ],
    },
    {
      title: '동백 핀',
      hint: '그웬이 동백꽃 이야기를 했어요. 동백꽃 한 송이를 가지고 찾아가 보세요.',
      need: { days: 6, points: 40, bring: { item: 'camellia', take: true } },
      scene: [
        '동백꽃을 내밀자 그웬이 두 손으로 받는다. 손이 조금 떨린다.',
        '"동백이다… 이 빨강, 꼭 리본 같아요."',
        '"인형이던 시절엔 꽃 냄새를 몰랐어요. 지금은 알아요."',
        '그녀가 꽃을 코끝에 대고 한참 눈을 감는다.',
        '"이졸데 할머니가 제게 처음 달아 준 것도 빨간 리본이었어요."',
        '"그때 저는 단추 눈이라 색을 몰랐는데요."',
        '"할머니 손이 따뜻해서 빨강이 따뜻한 색인 줄 알았어요."',
        '그녀가 바늘 쌈지를 열고 가는 철사와 붉은 실을 꺼낸다.',
        '꽃잎이 흩어지지 않게 한 장 한 장 실로 엮는다.',
        '"이걸로 핀을 만들래요. 반은 제 거, 반은 {me} 님 거요."',
        '"남은 꽃잎 하나는 조각보 가운데에 꿰매 둘게요."',
      ],
      replies: [
        { say: '같이 꽂고 다니자', tier: 'great', remember: 'camellia-pin', face: 'shy', answer: '…좋아요. 마을 사람들이 눈치채도 몰라요. 헤헤.' },
        { say: '그웬한테 어울려', tier: 'good', remember: 'camellia-pin', face: 'laugh', answer: '칭찬을 받으니까 꽃이 더 빨개 보여요. 아, 제 볼인가?' },
        { say: '마침 있어서 가져왔어', tier: 'meh', remember: 'camellia-pin', face: 'smile', answer: '마침이어도 좋아요. 마침이 쌓이면 인연이래요.' },
      ],
    },
    {
      title: '처음인 것들의 목록',
      hint: '평소 이야기에서 그웬과 함께 처음 보는 것을 신기해해 보세요. 다음 이야기가 열려요.',
      need: { days: 9, points: 60, mem: 'new-wonder' },
      scene: [
        '문 닫은 미용실. 그웬이 작은 수첩을 펼친다. 빼곡하다.',
        '"이건 제가 처음 해 본 것들 목록이에요."',
        '"이슬, 비 냄새, 눈. 크림빵, 거울 속 인사, 첫 꿈."',
        '"사람이 되고 나서 하나도 빼먹지 않고 적었어요."',
        '그녀가 한 줄을 짚는다. "처음 무서웠던 것, 바다 안개."',
        '"그 옆엔 이렇게 적었어요. 그래도 손을 잡아 준 사람."',
        '그녀가 책장을 넘긴다. 노을 색 실 한 가닥이 끼워져 있다.',
        '"신기한 건요, 무서운 것도 적어 두면 덜 무서워져요."',
        '"꿰매 놓은 것처럼 제자리에 얌전히 있거든요."',
        '그녀가 마지막 줄을 손끝으로 짚는다. 내 이름이 있다.',
        '"이건… 처음 생긴 단골이요. 아니, 처음 생긴 소중한 사람이요."',
        '그녀가 수첩을 내 쪽으로 반쯤 민다. 빈 줄이 많다.',
      ],
      replies: [
        { say: '앞으로도 같이 채우자', tier: 'great', remember: 'list-shared', face: 'shy', answer: '…네. 이 수첩, 이제 둘이서 쓰는 거예요. 약속이에요.' },
        { say: '목록이 길다', tier: 'good', face: 'laugh', answer: '세상이 너무 신기해서요! 아직 반도 안 적었어요.' },
        { say: '나도 처음이야?', tier: 'meh', face: 'smile', answer: '그럼요. 처음이고, 아직도 매일 신기해요.' },
      ],
    },
    {
      title: '엇박자',
      hint: '그웬과 아주 가까워지면 가위 소리가 이상해진대요. 그 뒤엔 꽃다발도 반길지 몰라요.',
      need: { days: 13, points: 96 },
      scene: [
        '오후의 미용실. 착한 안개가 몽글몽글 창가로 번진다.',
        '머리를 다듬던 그웬의 가위가 갑자기 멈춘다.',
        '"…이상해요. 싹둑이 소리가 엇박자가 나요."',
        '"다른 손님 땐 안 그래요. {me} 님 머리만 만지면 이래요."',
        '그녀가 가위를 귀에 대 본다. 고개를 갸웃한다.',
        '"오른 씨가 날을 잘 갈아 줬는데. 싹둑이는 멀쩡해요."',
        '"메르시 씨한테 물어봤더니 웃기만 하더라고요."',
        '"잔나 씨는 내일 예보가 맑음이래요. 그게 무슨 상관이죠?"',
        '그녀가 거울 너머로 나를 보다가 얼른 눈을 피한다.',
        '"…아, 알 것 같아요. 엇박자 나는 건 가위가 아니라요."',
        '그녀가 가슴에 손을 얹는다. 쿵, 쿵, 빠르게.',
        '"동백이나 코스모스를 한 다발 받으면… 심장도 엇박자가 날 거예요."',
        '"아, 지금 그 말 한 거 아니에요! 아니, 맞아요."',
      ],
      replies: [
        { say: '그 엇박자, 내가 맞출게', tier: 'great', face: 'shy', answer: '…그럼 꽃 들고 와요. 그날은 싹둑이도 쉬게 할게요.' },
        { say: '그웬 얼굴 빨개', tier: 'good', face: 'laugh', answer: '노을 때문이에요! …아직 낮이네요. 헤헤.' },
        { say: '가위 고장 난 거 아냐?', tier: 'meh', face: 'sorry', answer: '싹둑이는 멀쩡해요. 고장 난 건… 다른 데예요.' },
      ],
    },
    {
      title: '두 사람 사이의 한 땀',
      hint: '그웬과 연인이 되면 마지막 이야기가 열려요.',
      need: { days: 16, love: 'dating' },
      scene: [
        '저녁, 미용실 바닥에 커다란 조각보가 펼쳐져 있다.',
        '잔나의 파란 리본, 메르시의 흰 앞치마 끝, 미선의 꽃무늬.',
        '쓰레쉬 가게 진주 단추와 오른 대장간 앞치마 가죽도 있다.',
        '테두리엔 노을 색 실. 가운데만 아직 비어 있다.',
        '"마을 조각보예요. 다 모였어요. 한 자리만 빼고요."',
        '그웬이 바늘에 빨간 실을 꿴다. 이졸데 할머니의 바늘이다.',
        '"사람과 사람 사이에도 실이 있대요. 할머니가 그랬어요."',
        '"안개가 와도 끊기지 않는 실이요. 저는 그걸 믿어요."',
        '그녀가 첫날 자른 내 실밥과 동백 꽃잎을 가운데에 놓는다.',
        '한 땀, 또 한 땀. 마지막 조각이 제자리를 찾는다.',
        '"다 됐어요. 이제 마을이 하나로 이어졌어요."',
        '그녀가 내 소매와 자기 소매를 한 땀으로 잇는다.',
        '"이 실밥은 안 자를 거예요. 평생 두는 실이에요."',
        '"다음엔… 손가락에 반짝이는 걸로 꿰매 줄래요?"',
      ],
      replies: [
        { say: '반지로 꼭 잇자', tier: 'great', remember: 'quilt-done', face: 'shy', answer: ['…네. 그날 머리는 제가 할게요.', '제 것도, {me} 님 것도요. 조각보는 우리 집에 깔아요.'] },
        { say: '소매가 붙어서 못 걸어', tier: 'good', remember: 'quilt-done', face: 'laugh', answer: '그럼 같이 걸으면 되죠! 발도 맞춰요. 하나, 둘.' },
        { say: '천천히 생각해 볼게', tier: 'meh', remember: 'quilt-done', face: 'smile', answer: '천천히요. 좋은 바느질은 서두르지 않는 거예요.' },
      ],
    },
  ],
  after: [
    '오늘 실타래는 여기까지! 내일 또 풀어요.',
    '머리 말리고 자요! 꼭이요.',
    '싹둑이가 손 흔들어요. 내일 또 와요!',
    '할 말 다 했는데 또 보니까 좋네요. 헤헤.',
    '실밥 생기면 바로 와요. 싹둑! 해 드릴게요.',
    '또 왔네요! 오늘 수첩에 한 줄 더 써야겠다.',
    '드라이어 켜 둘게요. 착한 안개 필요하면 들러요.',
    '조각보에 한 땀 더 하고 있었어요. 어서 와요!',
    '오늘 이야기는 꿰매 두었어요. 안 풀리게요.',
  ],
};
