// 예림이 — 범마을 회관 화투방 마담. 느긋하고 낮게 깔리는 반말("~거든", "~잖니",
// "~지?", 가끔 "자기"). 판과 사람을 한눈에 읽고, 돈과 의리는 차갑게 셈하고,
// 차와 집밥은 따뜻하게. 광·비광·쌍피·고/스톱·밑장 같은 판 말을 섞는다. 밑장
// 빼는 사람은 질색, 정직하게 치는 사람은 은근히 감싼다. 원작 대사는 쓰지 않는다.
// 장 줄기: 큰 판을 떠돌며 남의 패만 읽던 사람이, 콩 한 줌 거는 마을 판을 깔고,
// 처음으로 자기 패(엎어 둔 마지막 한 장, 팔월 공산)를 보여 주는 이야기.
import type { NpcTalkBook } from './types.ts';

export const MAEHWA_TALK: NpcTalkBook = {
  npc: 'maehwa',
  memories: {
    'honest-hand': '정직하게 치는 게 좋다고 했어요',
    'go-player': '늘 고를 외치는 쪽이라고 했어요',
    'stop-player': '적당히 멈출 줄 안다고 했어요',
    'tea-lover': '차를 좋아한다고 했어요',
    'homecook': '집밥이 제일이라고 했어요',
    'rain-pancake': '비 오는 날 부침개를 같이 먹기로 했어요',
    'bi-gwang': '비광에 정이 간다고 했어요',
    'face-read': '얼굴을 읽혀 봤어요',
    'secret-kept': '비밀 하나를 지켜 주기로 했어요',
    'learn-hwatu': '화투를 배우고 싶다고 했어요',
    'songpyeon': '송편을 같이 빚자고 했어요',
    'night-stall': '시장 거리 포장마차에서 한잔했어요',
    'flower-tea': '꽃차를 대접했어요',
    'last-hand': '마지막 패 이야기를 들었어요',
    'quiet-win': '조용히 이기는 게 멋있다고 했어요',
    'taste-heard': '내 취향을 기억해 줬어요',
    'outing-talk': '함께 걸은 날을 이야기했어요',
    'bday-plan': '생일상 이야기를 나눴어요',
    'date-talk': '데이트한 날을 이야기했어요',
    'plum-name': '판에서 쓰던 옛 이름이 매화였다고 들었어요',
    'eye-first': '눈이 손보다 먼저라는 판 예의를 배웠어요',
    'old-road': '큰 판을 떠돌던 시절 이야기를 들었어요',
    'fav-month': '좋아하는 화투 달 이야기를 나눴어요',
    'read-her': '예림이의 얼굴을 거꾸로 읽어 봤어요',
    'kimjang': '김장을 같이 하기로 했어요',
    'scarf-color': '목도리 색을 골라 줬어요',
    'bean-stake': '콩 한 줌 판에 앉아 보기로 했어요',
    'lose-well': '잘 지는 법을 이야기했어요',
  },
  talks: [
    {
      id: 'go-or-stop',
      open: '{me}, 하나 묻자. 판이 잘 풀릴 때 너는 고야, 스톱이야?',
      replies: [
        { say: '멈출 때를 아는 게 실력이지', tier: 'great', remember: 'stop-player', answer: ['…괜찮네. 그 말 할 줄 아는 사람, 이 회관에 셋도 안 돼.', '판은 이기는 사람보다 오래 앉는 사람이 무서운 거야.'] },
        { say: '당연히 고!', tier: 'good', remember: 'go-player', face: 'laugh', answer: ['후후, 시원하다. 그 배짱은 사 줄게.', '근데 자기, 세 번째 고부터는 내가 말린다?'] },
        { say: '화투 잘 몰라', tier: 'meh', face: 'calm', answer: '모르면 구경부터 해. 판 보는 눈이 먼저 생겨야 손도 따라오거든.' },
      ],
    },
    {
      id: 'honest',
      open: '오늘도 밑장 빼다 걸린 손님이 있었어. 넌 그런 거 어떻게 생각하니?',
      replies: [
        { say: '지더라도 정직하게 치는 게 좋아', tier: 'great', remember: 'honest-hand', face: 'smile', answer: ['…그래. 그런 사람 손은 내가 안 놔.', '기억해 둘게, {me}. 판에선 그런 말이 제일 귀하거든.'] },
        { say: '안 걸리면 실력 아냐?', tier: 'meh', face: 'think', answer: '후후, 그 말 회관 밖에서만 해. 내 앞에선 다 보이거든.' },
        { say: '걸리면 어떻게 돼?', tier: 'good', answer: ['판에서 빠지지. 영원히.', '때리고 부수는 판은 옛날 얘기야. 내 판은 그냥 두 번 안 받아.'] },
      ],
    },
    {
      id: 'tea',
      open: '차 우렸어. 보리차, 유자차, 국화차. 뭐 마실래?',
      replies: [
        { say: '언니가 골라 줘', tier: 'great', remember: 'tea-lover', face: 'smile', answer: ['…얼굴 보니 오늘은 국화차네.', '마음이 좀 뜨겁거든, 자기. 식혀 가.'] },
        { say: '유자차!', tier: 'good', remember: 'tea-lover', answer: '단 거 좋아하는구나. 꿀 한 숟갈 더 넣어 줄게. 오늘만.' },
        { say: '차는 별로야', tier: 'meh', face: 'calm', answer: '그럼 물. 회관에선 목마른 채로 판 앞에 앉는 거 아니야.' },
      ],
    },
    {
      id: 'homecook',
      open: '저녁 뭐 먹었니? 바깥 밥만 먹으면 판에서 손이 떨려.',
      replies: [
        { say: '직접 해 먹었어', tier: 'great', remember: 'homecook', face: 'wow', answer: ['어머, 기특해라.', '다음엔 나도 한 숟갈 줘. 남이 한 밥이 제일 맛있거든.'] },
        { say: '아직 안 먹었어', tier: 'good', answer: ['그럴 줄 알았다. 얼굴이 빈 그릇이야.', '부엌에 된장국 남았어. 앉아, 데워 줄게.'] },
        { say: '과자로 때웠어', tier: 'meh', face: 'sorry', answer: '…자기, 그러면 판에서 진다. 내일은 밥 먹고 와.' },
      ],
    },
    {
      id: 'bi-gwang',
      open: '다들 비광을 싫어하잖니. 광인데 대접을 못 받아. 넌 어때?',
      replies: [
        { say: '그래서 더 정이 가', tier: 'great', remember: 'bi-gwang', face: 'smile', answer: ['…나랑 똑같네.', '비 맞으면서도 우산 쓰고 버티는 패라서 좋아.'] },
        { say: '점수 깎이니까 싫어', tier: 'good', answer: '솔직하네. 판에선 그게 맞아. 정은 판 밖에서 주는 거고.' },
        { say: '무슨 패인지 모르겠어', tier: 'meh', answer: '비 오는 날 우산 쓴 사람 그려진 패. 다음에 보여 줄게.' },
      ],
    },
    {
      id: 'read-face',
      open: '자기 얼굴 한번 읽어 볼까? 거짓말은 못 하겠다, 내 앞에선.',
      replies: [
        { say: '읽어 봐. 숨길 거 없어', tier: 'great', remember: 'face-read', face: 'think', answer: ['음… 오늘 좋은 일 하나, 걱정 하나. 걱정은 별거 아니고.', '…맞지? 후후, 패보다 얼굴이 쉬워.'] },
        { say: '무서워, 하지 마', tier: 'good', face: 'laugh', answer: '후후, 겁먹은 얼굴도 다 읽혀. 괜찮아, 나쁜 건 안 보여.' },
        { say: '그런 거 안 믿어', tier: 'meh', answer: '믿든 말든 판은 그렇게 돌아가. 언젠가 내 말 생각날 거야.' },
      ],
    },
    {
      id: 'learn',
      open: '판 구경만 하는 사람이 제일 많이 배워. 너, 한 수 배워 볼래?',
      replies: [
        { say: '언니한테 배우고 싶어', tier: 'great', remember: 'learn-hwatu', face: 'smile', answer: ['좋아. 첫 수업은 손 씻기야.', '패는 깨끗한 손에서 정직해지거든. 비누는 문 옆에.'] },
        { say: '돈 잃을까 봐 싫어', tier: 'good', answer: ['현명하다. 그럼 콩으로 해.', '콩 잃는 건 안 아프잖니. 내일 콩밥 해 먹으면 되고.'] },
        { say: '난 이미 잘 쳐', tier: 'meh', face: 'think', answer: '…그 말 하는 사람치고 잘 치는 사람 못 봤어. 후후.' },
      ],
    },
    {
      id: 'quiet-win',
      open: '판에서 제일 무서운 사람이 누군 줄 알아? 소리치는 사람? 아니야.',
      replies: [
        { say: '조용히 이기는 사람', tier: 'great', remember: 'quiet-win', face: 'wow', answer: ['…맞아. 너 생각보다 판을 아네.', '이기고도 찻잔부터 드는 사람. 그런 사람이 제일 무서워.'] },
        { say: '돈 많은 사람?', tier: 'good', answer: '돈 많은 사람은 오히려 쉬워. 잃어도 웃으니까 얼굴이 다 보이거든.' },
        { say: '언니?', tier: 'meh', face: 'laugh', answer: '후후, 그건 판 밖에서 하는 말이고. 판 안에선 나도 조심해.' },
      ],
    },
    {
      id: 'secret',
      open: '회관에선 별말이 다 들려. 근데 난 들은 걸 안 옮겨. 너는 비밀 잘 지키니?',
      replies: [
        { say: '언니 비밀은 무덤까지', tier: 'great', remember: 'secret-kept', face: 'shy', answer: ['…그럼 하나 말해 줄까.', '나 사실 화투보다 뜨개질이 더 좋아. 비밀이다.'] },
        { say: '노력은 해', tier: 'good', answer: '노력이면 됐어. 지키겠다고 큰소리치는 사람이 제일 먼저 흘려.' },
        { say: '난 입이 가벼워', tier: 'meh', face: 'laugh', answer: '후후, 솔직해서 좋다. 그럼 너한텐 날씨 이야기만 할게.' },
      ],
    },
    {
      id: 'songpyeon',
      open: '명절엔 회관 사람들이랑 송편을 빚거든. 자기도 빚어 볼래?',
      replies: [
        { say: '같이 빚자!', tier: 'great', remember: 'songpyeon', face: 'smile', answer: ['좋아. 예쁘게 빚으면 예쁜 짝 만난대.', '너는 신경 좀 써야겠다. 후후.'] },
        { say: '먹는 것만 할게', tier: 'good', face: 'laugh', answer: '먹는 사람도 있어야지. 대신 맛 평가는 정직하게 해.' },
        { say: '손이 둔해서…', tier: 'meh', answer: '괜찮아. 못생긴 송편이 더 기억에 남거든.' },
      ],
    },
    {
      id: 'bad-day',
      open: '오늘 판이 좀 험했어. 다들 독해서. …너는 오늘 어땠니?',
      replies: [
        { say: '언니 얘기 먼저 들을게', tier: 'great', face: 'shy', answer: ['…자기 참.', '그럼 차 한 잔 마실 동안만 털어놓을게. 딱 그만큼만.'] },
        { say: '나도 별로였어', tier: 'good', answer: '그럼 오늘은 둘 다 스톱. 내일 새 판 돌리자.' },
        { say: '난 좋았는데!', tier: 'meh', face: 'calm', answer: '그래, 다행이다. 좋은 기운 좀 나눠 줘. 여기 놓고 가.' },
      ],
    },
    {
      id: 'rain-pancake',
      open: '비 오는 날엔 부침개 부쳐서 회관 사람들이랑 나눠 먹거든. 넌 뭐가 좋아?',
      replies: [
        { say: '김치전!', tier: 'great', remember: 'rain-pancake', answer: ['역시. 김치전 아는 사람이랑은 말이 통해.', '다음 비 오면 불러 줄게. 제일 바삭한 가장자리는 네 거.'] },
        { say: '파전!', tier: 'good', remember: 'rain-pancake', answer: '미쿠가 들으면 좋아하겠다. 파 얘기만 나오면 걔가 달려오거든.' },
        { say: '기름진 건 싫어', tier: 'meh', answer: '그럼 너는 차 담당. 부침개 옆엔 꼭 따뜻한 차가 있어야 하거든.' },
      ],
    },
    {
      id: 'outside-table',
      when: { ch: 3 },
      open: '{me}, 요즘은 판 끝나고 네 얼굴부터 찾게 돼. …이상하지?',
      replies: [
        { say: '나도 언니부터 찾아', tier: 'great', face: 'shy', answer: ['…그 말은 판에서 쓰는 패가 아니야.', '그러니까 믿을게. 판 밖의 말은 내가 안 읽거든.'] },
        { say: '내가 보고 싶었구나', tier: 'good', face: 'laugh', answer: '후후, 그렇게 대놓고 읽으면 반칙이야. 그래도 틀린 말은 아니고.' },
        { say: '피곤해서 그래', tier: 'meh', face: 'calm', answer: '…그런가. 차나 마시자.' },
      ],
    },
    {
      id: 'plum-name',
      open: ['이월 매조 알지? 매화 가지에 새 한 마리 앉은 패.', '옛날 큰 판에선 다들 날 매화라고 불렀어. 진짜 이름 대신.'],
      replies: [
        { say: '어울리는 이름이네', tier: 'good', remember: 'plum-name', face: 'smile', answer: ['그래? 추울 때 제일 먼저 피는 꽃이라서 붙었대.', '난 그냥 손이 차가워서 그런 줄 알았어.'] },
        { say: '난 예림이가 더 좋아', tier: 'great', remember: 'plum-name', face: 'shy', answer: ['…그래? 그 이름 불러 주는 사람이 이 마을에서 생겼네.', '매화는 판에 두고 왔어. 여기선 예림이야.'] },
        { say: '별명이 왜 필요해?', tier: 'meh', face: 'think', answer: '진짜 이름을 판에 걸면 안 되거든. 잃으면 못 찾아.' },
      ],
    },
    {
      id: 'eye-first',
      open: '판에서 누가 그러더라. 손이 눈보다 빠르다고. 넌 어떻게 생각해?',
      replies: [
        { say: '눈이 더 빠를 것 같아', tier: 'great', remember: 'eye-first', face: 'wow', answer: ['…맞아. 내 판에선 늘 눈이 먼저야.', '손이 아무리 빨라도 보는 눈은 못 이겨. 그게 판 예의고.'] },
        { say: '손이 빠르면 이기지', tier: 'meh', face: 'calm', answer: '그런 손은 내 판에 못 앉아. 빠른 손은 다 읽히거든.' },
        { say: '둘 다 느려, 난', tier: 'good', face: 'laugh', answer: ['후후, 그게 제일 좋아.', '느린 손은 속일 생각이 없다는 뜻이거든. 앉아.'] },
      ],
    },
    {
      id: 'school-of-hand',
      open: ['나 이래 봬도 배울 만큼 배운 여자야.', '어디서 배웠냐고? 판에서. 졸업 안 시켜 주는 학교.'],
      replies: [
        { say: '수석 졸업 같은데?', tier: 'great', face: 'laugh', answer: ['후후, 말은 잘해.', '근데 거기 수석은 박수 대신 빚을 받아. 일찍 나온 게 다행이지.'] },
        { say: '무슨 과목을 배웠어?', tier: 'good', answer: ['사람 얼굴, 손버릇, 숨 고르는 소리.', '제일 어려운 과목은 일어날 때를 아는 거였어.'] },
        { say: '자랑하는 거야?', tier: 'meh', face: 'calm', answer: '자랑이면 차라리 장아찌 솜씨를 하지. 그건 진짜 자신 있어.' },
      ],
    },
    {
      id: 'old-road',
      open: '나 이 마을 오기 전엔 큰 판을 따라 떠돌았어. 들어 볼래?',
      replies: [
        { say: '천천히 얘기해 줘', tier: 'great', remember: 'old-road', face: 'calm', answer: ['항구 도시, 기찻길 옆 여관, 불 꺼진 다방 뒷방.', '어딜 가도 판은 똑같았어. 사람만 바뀌고, 나만 그대로였지.'] },
        { say: '멋있었겠다', tier: 'good', remember: 'old-road', face: 'think', answer: ['멋있어 보였겠지. 진주 목걸이에 화투 부채.', '근데 밤마다 혼자 국수 먹는 사람이었어. 그건 안 멋있어.'] },
        { say: '지난 얘긴 됐어', tier: 'meh', face: 'calm', answer: '그래. 엎은 패는 엎은 채로 두는 것도 예의지.' },
      ],
    },
    {
      id: 'why-here',
      when: { ch: 2 },
      open: '왜 하필 이 작은 마을에 판을 깔았냐고들 묻더라. 넌 왜일 것 같아?',
      replies: [
        { say: '여기 판은 웃으면서 치니까', tier: 'great', face: 'wow', answer: ['…어떻게 알았어?', '콩 한 줌 걸고, 진 사람이 밥 사고. 그런 판이 처음이었어.'] },
        { say: '차가 맛있어서?', tier: 'good', face: 'laugh', answer: ['후후, 반은 맞아. 여기 물이 좋거든.', '나머지 반은… 나중에 알려 줄게.'] },
        { say: '돈이 되니까?', tier: 'meh', face: 'calm', answer: '돈이 됐으면 큰 판에 남았지. 여긴 콩밖에 안 남아.' },
      ],
    },
    {
      id: 'fav-month',
      open: '화투는 열두 달이야. 솔, 매화, 벚꽃… 넌 무슨 달 패가 좋아?',
      replies: [
        { say: '팔월 공산, 달 뜬 패', tier: 'great', remember: 'fav-month', face: 'shy', answer: ['…너도? 나도 그 패가 제일 좋아.', '혼자 보던 달이라서. 이유는 묻지 마. 아직은.'] },
        { say: '삼월 벚꽃이 예뻐', tier: 'good', remember: 'fav-month', face: 'smile', answer: ['벚꽃 광은 들어오면 판이 환해지지.', '대신 금방 져. 예쁜 건 다 그래.'] },
        { say: '시월 단풍 사슴!', tier: 'good', remember: 'fav-month', face: 'laugh', answer: '사슴이 고개 돌린 패. 외면하는 게 귀엽잖니. 꼭 누구 같아.' },
      ],
    },
    {
      id: 'read-her',
      when: { ch: 1 },
      open: ['맨날 내가 네 얼굴만 읽었지.', '오늘은 거꾸로 해 봐. 내 얼굴, 뭐가 보여?'],
      replies: [
        { say: '…조금 외로워 보여', tier: 'great', remember: 'read-her', face: 'sorry', answer: ['…', '…그거, 아무한테도 들킨 적 없는데. 너 판에 앉으면 무섭겠다.'] },
        { say: '배고파 보여', tier: 'good', remember: 'read-her', face: 'laugh', answer: ['후후, 맞아. 점심 걸렀어.', '같이 먹을래? 읽어 준 값이야.'] },
        { say: '하나도 모르겠어', tier: 'meh', face: 'calm', answer: '그게 정답이야. 판에선 그렇게 보이게 사는 거거든.' },
      ],
    },
    {
      id: 'kimjang',
      open: '초겨울엔 회관 마당에서 김장해. 배추 백 포기. 손 보탤래?',
      replies: [
        { say: '고무장갑 끼고 갈게', tier: 'great', remember: 'kimjang', face: 'laugh', answer: ['좋아. 속 넣는 건 내가 가르쳐 줄게.', '김장도 판이랑 같아. 손 빠른 사람보다 꼼꼼한 사람이 이겨.'] },
        { say: '수육만 먹으러 갈게', tier: 'good', face: 'smile', answer: '그것도 일이야. 다 먹으면 설거지 판이다. 후후.' },
        { say: '매운 건 못 먹어', tier: 'meh', face: 'think', answer: '그럼 백김치 따로 담가 줄게. 너 몫으로 한 통만.' },
      ],
    },
    {
      id: 'bean-stake',
      open: '회관 판돈은 콩이야. 콩 한 줌. 이기면 콩밥, 지면 콩자반.',
      replies: [
        { say: '그런 판이면 앉아 볼래', tier: 'great', remember: 'bean-stake', face: 'smile', answer: ['좋아. 콩은 내가 대 줄게. 첫판은.', '대신 콩 세는 손은 천천히. 눈이 먼저라고 했지?'] },
        { say: '콩으로 재미있어?', tier: 'good', answer: ['재미는 판돈에서 안 나와.', '사람 얼굴 읽는 데서 나오지. 콩이면 다들 얼굴이 솔직해져.'] },
        { say: '진짜 돈은 안 걸어?', tier: 'meh', face: 'calm', answer: '그건 카지노 가서 미스 포츈한테 물어. 내 판은 콩까지야.' },
      ],
    },
    {
      id: 'lose-well',
      open: '지는 법도 배워야 해. 잘 지는 사람이 다음 판에 또 와. 넌 어떻게 져?',
      replies: [
        { say: '웃으면서 밥 살게', tier: 'great', remember: 'lose-well', face: 'laugh', answer: ['후후, 그게 이 마을 법이야.', '진 사람이 밥 사면 이긴 사람이 차 사. 그럼 둘 다 남아.'] },
        { say: '한 판만 더 하자 할 듯', tier: 'meh', face: 'sorry', answer: '그 말에 사람들이 다 털렸어. 그땐 내가 판을 접어 줄게.' },
        { say: '조용히 일어날래', tier: 'good', remember: 'lose-well', face: 'smile', answer: '그것도 좋아. 의자 소리 안 내고 일어나는 사람, 다음엔 꼭 이겨.' },
      ],
    },
    {
      id: 'fan',
      open: '이 화투 부채 말이야. 다들 멋 부리는 줄 아는데, 사실 이유가 있어.',
      replies: [
        { say: '표정 가리려고?', tier: 'great', face: 'wow', answer: ['…날카롭네.', '남의 얼굴은 읽고, 내 얼굴은 가리고. 그러라고 들어.'] },
        { say: '더워서?', tier: 'good', face: 'laugh', answer: '후후, 그것도 맞아. 판이 달아오르면 회관이 한여름이거든.' },
        { say: '그냥 멋인데?', tier: 'meh', face: 'calm', answer: '멋도 있지. 근데 멋만 있는 물건은 안 들고 다녀, 난.' },
      ],
    },
    {
      id: 'pearl',
      open: '진주가 어떻게 생기는지 아니? 조개가 아픈 데를 감싸서 생긴대.',
      replies: [
        { say: '언니 목걸이도 그래?', tier: 'great', face: 'think', answer: ['…그런 셈이지.', '아픈 데 하나씩 감쌀 때마다 한 알씩. 그렇게 생각하고 걸어.'] },
        { say: '예쁘기만 한 줄 알았어', tier: 'good', answer: '예쁜 건 다 사연이 있어. 사연 없는 건 금방 질리고.' },
        { say: '조개는 먹어 봤어', tier: 'meh', face: 'laugh', answer: '후후, 조개구이는 나도 좋아. 익힌 건 괜찮아.' },
      ],
    },
    {
      id: 'raw-fish',
      open: '날생선은 왜 싫냐고들 묻더라. 내가 비린 거에 좀 예민하거든.',
      replies: [
        { say: '구워서 먹으면 되지', tier: 'great', face: 'smile', answer: ['맞아. 소금 쳐서 구우면 내가 밥은 해.', '날것은 패든 생선이든 속을 몰라서 싫어.'] },
        { say: '회가 얼마나 맛있는데', tier: 'meh', face: 'sorry', answer: '그건 선장님이랑 먹어. 난 옆에서 차 마실게.' },
        { say: '나도 비린 건 싫어', tier: 'good', face: 'laugh', answer: '그럼 우리 둘은 생선구이 동맹이다.' },
      ],
    },
    {
      id: 'bugs',
      open: '어제 화투방에 귀뚜라미가 들어왔어. 패 위로 톡 뛰는데…',
      replies: [
        { say: '내가 내보내 줄게', tier: 'great', face: 'shy', answer: ['…고마워. 판에선 안 떨리는데 그건 떨리더라.', '이건 비밀이야. 회관 사람들 알면 안 돼.'] },
        { say: '소리 예쁘잖아', tier: 'good', face: 'think', answer: '밖에서 우는 건 예쁘지. 패 위에서 뛰는 건 반칙이고.' },
        { say: '잡아서 키울래', tier: 'meh', face: 'sorry', answer: '…회관엔 데려오지 마. 그날로 출입 금지야.' },
      ],
    },
    {
      id: 'lumi-love',
      open: '미쿠가 또 연애 상담을 해 달래. 퇴근길에 한 시간이야. 넌 누가 들어 줘?',
      replies: [
        { say: '언니가 들어 주면 좋겠다', tier: 'great', face: 'shy', answer: ['…들어 줄게. 차 값은 안 받아.', '대신 미쿠처럼 노래로 하지는 마. 그건 못 읽어.'] },
        { say: '혼자 정리하는 편이야', tier: 'good', answer: '그것도 방법이지. 근데 혼자 정리한 패는 꼭 한 장이 비더라.' },
        { say: '연애는 관심 없어', tier: 'meh', face: 'calm', answer: '후후, 그런 사람이 제일 먼저 빠져. 판에서 많이 봤어.' },
      ],
    },
    {
      id: 'captain-snack',
      open: '샹크스가 판 끝나고 또 안주 들고 왔어. 이긴 날은 매운 거, 진 날은 국물.',
      replies: [
        { say: '오늘은 뭐였어?', tier: 'great', face: 'laugh', answer: ['국물. 그것도 두 그릇.', '그 사람 진 날이 더 즐거워 보여. 이상한 사람이야.'] },
        { say: '둘이 친해 보여', tier: 'good', answer: '친구라기보다 단골이야. 근데 단골이 친구보다 오래 가더라.' },
        { say: '술은 안 마셔?', tier: 'meh', face: 'calm', answer: '회관에선 안 돼. 주점 가서 마시라고 쫓아내.' },
      ],
    },
    {
      id: 'nasera-tea',
      open: '나세라랑 차 모임 하는데, 걘 찻잔 들고도 배추 시세 얘기를 해.',
      replies: [
        { say: '둘이 잘 맞는 것 같아', tier: 'great', face: 'smile', answer: ['맞아. 셈 밝은 사람끼리는 편하거든.', '서로 속을 안 읽어도 돼. 이미 다 계산했으니까.'] },
        { say: '시세 얘기 재미있잖아', tier: 'good', face: 'laugh', answer: '후후, 너도 나세라 과구나. 그럼 다음 모임에 와.' },
        { say: '차 마실 땐 쉬어야지', tier: 'good', face: 'think', answer: '나도 그 말 했어. 그랬더니 쉬는 시간도 시세래.' },
      ],
    },
    {
      id: 'rose-ledger',
      open: '카지노 미스 포츈이랑 나는 셈하는 법이 달라. 걘 이자를 세고, 난 사람을 세.',
      replies: [
        { say: '사람 세는 게 더 어려워', tier: 'great', face: 'think', answer: ['맞아. 이자는 틀리지 않거든.', '사람은 날마다 달라. 그래서 질리지가 않아.'] },
        { say: '둘 다 무서워', tier: 'good', face: 'laugh', answer: '후후, 정답이야. 우리 둘한텐 빚지지 마.' },
        { say: '이자가 더 확실하지', tier: 'meh', face: 'calm', answer: '확실한 걸 좋아하면 저쪽 창구로 가. 난 안 말려.' },
      ],
    },
    {
      id: 'water-temp',
      open: '녹차는 끓는 물에 바로 부으면 써져. 조금 식혀야 해. 사람도 그렇고.',
      replies: [
        { say: '사람도 식혀야 해?', tier: 'great', face: 'smile', answer: ['화났을 때 바로 말하면 써지잖니.', '한 김 빼고 말해. 그럼 단맛이 나.'] },
        { say: '난 뜨거운 게 좋아', tier: 'good', face: 'laugh', answer: '그럼 보리차. 보리차는 펄펄 끓여도 착해.' },
        { say: '차는 다 똑같던데', tier: 'meh', face: 'calm', answer: '…그럼 오늘 두 잔 비교해 봐. 다르다고 할 거야.' },
      ],
    },
    {
      id: 'scarf-color',
      when: { mem: 'secret-kept' },
      open: '그 목도리 말이야. 색을 못 정했어. 남색이랑 자주색 중에.',
      replies: [
        { say: '남색. 언니한테 어울려', tier: 'good', remember: 'scarf-color', face: 'smile', answer: '…나한테? 내 거 뜨는 거 아닌데. 후후, 그래도 참고할게.' },
        { say: '받는 사람 따라 골라', tier: 'great', remember: 'scarf-color', face: 'shy', answer: ['받는 사람이라…', '그 사람 얼굴은 다 외웠는데. …그럼 자주색이다.'] },
        { say: '그냥 사면 안 돼?', tier: 'meh', face: 'calm', answer: '산 건 따뜻하기만 해. 뜬 건 따뜻하고 무거워. 그게 달라.' },
      ],
    },
    {
      id: 'own-hand',
      when: { love: 'dating' },
      open: ['{me}, 요즘 내가 좀 이상하대. 회관 사람들이.', '판 돌리다가 혼자 웃는대. 패도 안 보고.'],
      replies: [
        { say: '내 생각 하느라 그렇지?', tier: 'great', face: 'shy', answer: ['…그렇게 대놓고 까면 어떡해.', '맞아. 판에선 질 패인데, 이상하게 하나도 안 아까워.'] },
        { say: '좋은 일 있나 보다', tier: 'good', face: 'laugh', answer: '후후, 모르는 척 잘하네. 그것도 판에서 배운 거야?' },
        { say: '피곤한 거 아냐?', tier: 'meh', face: 'calm', answer: '…자기는 가끔 너무 정직해. 그래서 좋긴 하지만.' },
      ],
    },
    {
      id: 'two-cups',
      when: { love: 'married' },
      open: '요즘 회관 문 닫을 때 찻잔을 두 개 씻어. 그게 제일 좋은 시간이야.',
      replies: [
        { say: '내가 씻을게, 오늘은', tier: 'great', face: 'shy', answer: ['…그럼 난 닦을게.', '같이 하면 금방이야. 판도, 설거지도.'] },
        { say: '세 개가 될 날도 오겠지', tier: 'good', face: 'laugh', answer: '후후, 손님 찻잔 말하는 거지? 그렇다고 해 둘게.' },
        { say: '하나로 같이 마시자', tier: 'good', face: 'smile', answer: '…자기는 가끔 셈을 너무 쉽게 해. 좋아.' },
      ],
    },
    {
      id: 'peony-garden',
      open: '회관 뒤뜰에 모란을 심었어. 유월 패처럼 피면 다들 보러 오라고.',
      replies: [
        { say: '피면 제일 먼저 보러 올게', tier: 'great', face: 'smile', answer: ['약속했다. 첫 꽃 필 때 찻상 내놓을게.', '꽃 앞에선 다들 판 얘길 안 해. 그래서 심었어.'] },
        { say: '나비도 오겠다', tier: 'good', face: 'think', answer: '모란 패엔 나비가 있지. 진짜 나비는 반만 반가워.' },
        { say: '꽃은 금방 지잖아', tier: 'meh', face: 'calm', answer: '그러니까 피었을 때 봐야지. 판이랑 같아.' },
      ],
    },
  ],
  openers: [
    {
      id: 'op-rain',
      when: { weather: ['rain', 'storm'] },
      open: '비 온다. 부침개 냄새 나지? 회관 부엌에서 지금 막 부쳤어.',
      replies: [
        { say: '한 장만 줘!', tier: 'great', remember: 'rain-pancake', answer: ['한 장은 무슨, 두 장 가져가.', '비 오는 날 인심은 넉넉해야지. 간장은 내가 따로 만든 거야.'] },
        { say: '비광 생각난다', tier: 'good', remember: 'bi-gwang', face: 'smile', answer: '…너도? 오늘 같은 날엔 그 패가 제일 예뻐 보여.' },
        { say: '비 싫어', tier: 'meh', answer: '그래도 오늘은 손님이 많아. 비 피하러 다들 판으로 오거든.' },
      ],
    },
    {
      id: 'op-snow',
      when: { weather: 'snow' },
      open: '눈 오네. 소나무에 눈 쌓이면 일월 송학 같지 않니?',
      replies: [
        { say: '첫 광이네', tier: 'great', face: 'wow', answer: ['…알아듣는구나.', '그럼 오늘 첫 차는 네 몫이야. 유자차.'] },
        { say: '그냥 추워', tier: 'meh', face: 'calm', answer: '그래, 춥지. 난롯가 앉아. 판은 손이 녹은 다음이야.' },
        { say: '학은 어디 있어?', tier: 'good', face: 'laugh', answer: '눈 감고 봐. 판 오래 본 사람한텐 보여.' },
      ],
    },
    {
      id: 'op-night',
      when: { time: 'night' },
      open: '밤 깊은 판은 사람을 잡아먹어. {me}, 너는 왜 아직 안 들어갔니?',
      replies: [
        { say: '언니 보러 왔지', tier: 'great', face: 'shy', answer: ['…말은 잘해.', '보리차 한 잔만 하고 들어가. 판은 안 된다.'] },
        { say: '잠이 안 와서', tier: 'good', answer: '그럼 국화차. 마음 가라앉히는 데는 그만한 게 없거든.' },
        { say: '한 판만 하고 갈래', tier: 'meh', face: 'think', answer: '…안 돼. 이 시간에 잡는 패는 다 독이야. 내일 와.' },
      ],
    },
    {
      id: 'op-dawn',
      when: { time: 'dawn' },
      open: '새벽이네. 패 닦던 참이야. 마흔여덟 장, 한 장씩.',
      replies: [
        { say: '나도 같이 닦을게', tier: 'great', face: 'smile', answer: ['그래. 앞면 말고 뒷면부터.', '뒷면에 손때가 묻으면 그게 표시가 되거든. 깨끗이.'] },
        { say: '왜 매일 닦아?', tier: 'good', face: 'think', answer: '깨끗한 패는 거짓말을 못 해. 그래서 매일.' },
        { say: '졸려…', tier: 'meh', face: 'laugh', answer: '후후, 첫물 차 마셔. 눈이 번쩍 떠질걸.' },
      ],
    },
    {
      id: 'op-day',
      when: { time: 'day' },
      open: '한낮 회관은 조용하지? 판은 해 떨어져야 열어. 지금은 반찬 하는 시간.',
      replies: [
        { say: '간 좀 봐 줄까?', tier: 'great', remember: 'homecook', face: 'laugh', answer: ['좋지. 자, 아.', '…표정 보니 싱겁구나. 소금 한 꼬집. 고마워.'] },
        { say: '무슨 반찬이야?', tier: 'good', answer: '멸치볶음이랑 콩자반. 어제 판에서 남은 콩이야.' },
        { say: '판은 언제 열어?', tier: 'meh', face: 'calm', answer: '해 지면. 서두르는 손님은 판도 서둘러서 져.' },
      ],
    },
    {
      id: 'op-evening',
      when: { time: 'evening' },
      open: '노을이네. 시월 단풍 패처럼 붉다. 이 시간엔 손님들 눈빛이 바뀌어.',
      replies: [
        { say: '언니 눈빛도 바뀌어?', tier: 'great', face: 'think', answer: ['바뀌지. 차가워져.', '…근데 너 보고는 아직 안 바뀌었네. 이상하다.'] },
        { say: '저녁은 먹었어?', tier: 'good', face: 'smile', answer: '그건 내가 할 말인데. 응, 먹었어. 너도 먹고 와.' },
        { say: '노을 예쁘다', tier: 'good', answer: '예쁘지. 사슴이 고개 돌릴 만해.' },
      ],
    },
    {
      id: 'op-spring',
      when: { season: 'spring' },
      open: '봄이야. 이월 매조, 삼월 벚꽃. 봄 패는 예쁜데 점수는 박하지.',
      replies: [
        { say: '예쁘면 됐지', tier: 'great', face: 'smile', answer: ['후후, 너다운 셈이다.', '봄엔 그게 맞아. 쑥떡 줄게, 판 대신.'] },
        { say: '점수가 중요하지', tier: 'meh', face: 'calm', answer: '그럼 가을까지 기다려. 봄 판에선 손해만 봐.' },
        { say: '벚꽃 보러 갈래?', tier: 'good', face: 'shy', answer: '…회관 비우면 안 되는데. 잠깐이면 괜찮겠지.' },
      ],
    },
    {
      id: 'op-summer',
      when: { season: 'summer' },
      open: '덥지? 수박화채 해 놨어. 더운 날엔 성질이 먼저 끓거든.',
      replies: [
        { say: '한 그릇 부탁해', tier: 'great', face: 'smile', answer: ['얼음 많이 넣었어.', '천천히 먹어. 머리 띵해지면 판에서도 실수해.'] },
        { say: '판도 더워?', tier: 'good', face: 'laugh', answer: '더워. 다들 부채질하느라 패를 떨어뜨려. 그날은 다 무효야.' },
        { say: '난 더위 안 타', tier: 'meh', answer: '부럽네. 그래도 물은 마셔. 얼굴이 벌겋다.' },
      ],
    },
    {
      id: 'op-autumn',
      when: { season: 'autumn' },
      open: '가을이야. 구월 국화, 시월 단풍. 가을 패는 화려해서 사람을 홀려.',
      replies: [
        { say: '국화차 마시고 싶다', tier: 'great', remember: 'tea-lover', face: 'smile', answer: ['그럴 줄 알고 말려 뒀어.', '올해 첫 국화야. 첫 잔은 네 거.'] },
        { say: '언니도 홀려?', tier: 'good', face: 'shy', answer: '…가끔. 패 말고 다른 것한테.' },
        { say: '가을은 쓸쓸해', tier: 'good', face: 'calm', answer: '그래서 햇밤 삶고 송편 빚어. 쓸쓸할 틈이 없게.' },
      ],
    },
    {
      id: 'op-winter',
      when: { season: 'winter' },
      open: '겨울엔 아랫목이 명당이야. 거기 앉은 사람이 판을 오래 버텨.',
      replies: [
        { say: '그 자리 나 줘', tier: 'great', face: 'laugh', answer: ['후후, 배짱 좋다.', '그래, 줄게. 대신 귤 까는 건 네 일이다.'] },
        { say: '언니는 어디 앉아?', tier: 'good', face: 'think', answer: '난 문가. 찬바람 맞아야 정신이 서거든.' },
        { say: '추워서 못 나가', tier: 'meh', answer: '그래도 왔잖니. 생강차 줄게, 손 녹여.' },
      ],
    },
    {
      id: 'op-sunny',
      when: { weather: 'sunny' },
      open: '볕 좋다. 회관 창 다 열었어. 판에 바람이 들어야 사람이 덜 독해져.',
      replies: [
        { say: '나물 말리는 거 도울게', tier: 'great', face: 'smile', answer: ['어머, 눈치 빠르다.', '고사리는 뒤집어 줘. 손 바쁘면 판 생각이 덜 나.'] },
        { say: '오늘 운 좋을 것 같아', tier: 'meh', face: 'think', answer: '볕 좋은 날은 다들 그래. 그게 함정이야.' },
        { say: '산책 가자', tier: 'good', answer: '판 열기 전까지만. 과수원 길 어때?' },
      ],
    },
    {
      id: 'op-cloudy',
      when: { weather: 'cloudy' },
      open: '흐리네. 이런 날은 다들 표정이 무거워. 읽기는 쉽고.',
      replies: [
        { say: '내 표정은 어때?', tier: 'great', remember: 'face-read', face: 'think', answer: ['음… 구름은 꼈는데 비는 안 와.', '괜찮다는 뜻이야. 진한 차 한 잔이면 개.'] },
        { say: '흐린 날 좋아', tier: 'good', face: 'smile', answer: '나도. 해가 없으면 그림자도 없잖니. 숨기 좋아.' },
        { say: '비 올 것 같아', tier: 'good', answer: '그럼 부침개 반죽 미리 해 둘까.' },
      ],
    },
    {
      id: 'op-storm',
      when: { weather: 'storm' },
      open: '바람 세다. 회관 덧문 좀 같이 닫아 줄래? 패 날아가겠어.',
      replies: [
        { say: '내가 잡고 있을게', tier: 'great', face: 'smile', answer: ['고마워. 손이 든든하네.', '이런 날엔 판 대신 다 같이 모여 앉아 차 마셔.'] },
        { say: '패가 날아가면?', tier: 'good', face: 'laugh', answer: '한 장이라도 비면 판은 무효야. 그러니까 꽉.' },
        { say: '무서워…', tier: 'meh', face: 'calm', answer: '괜찮아. 회관은 튼튼해. 판보다 오래 버틴 집이야.' },
      ],
    },
    {
      id: 'op-festival',
      when: { festival: true },
      open: '축제날엔 판을 안 열어. 다들 밖에서 웃고 있잖니. 그게 더 큰 판이야.',
      replies: [
        { say: '언니도 같이 나가자', tier: 'great', face: 'smile', answer: ['…그럴까. 오늘만.', '대신 사진은 찍지 마. 판 밖 얼굴은 비싸거든.'] },
        { say: '심심하지 않아?', tier: 'good', answer: '심심한 게 좋아. 일 년에 며칠 안 되는 휴가거든.' },
        { say: '윷놀이 하자!', tier: 'good', face: 'laugh', answer: '윷은 나도 못 속여. 그래서 좋아. 한 판 하자.' },
      ],
    },
    {
      id: 'op-harvest',
      when: { harvest: true },
      open: '손끝에 흙이 묻었네. 오늘 밭일했구나? 그 손은 정직한 손이야.',
      replies: [
        { say: '언니 반찬 하라고 가져올게', tier: 'great', remember: 'homecook', face: 'smile', answer: ['…자기 참.', '그럼 나는 밥을 지어 놓을게. 같이 먹자.'] },
        { say: '힘들었어', tier: 'good', answer: '그럼 오늘은 판 말고 차. 몸 쓴 날엔 머리를 쉬게 해야 해.' },
        { say: '손 씻는 거 깜빡했다', tier: 'meh', face: 'laugh', answer: '후후, 흙은 괜찮아. 흙 묻은 손은 밑장을 못 빼거든.' },
      ],
    },
    {
      id: 'op-gold',
      when: { gold: true },
      open: '금별 작물 나왔다며? 판으로 치면 광 세 장 들어온 거야.',
      replies: [
        { say: '삼광이다!', tier: 'great', face: 'laugh', answer: ['후후, 맞아.', '근데 그럴 때일수록 스톱할 줄 알아야 해. 오늘은 쉬어.'] },
        { say: '운이 좋았어', tier: 'good', answer: '운은 준비된 손에만 와. 너 손이 좋은 거야.' },
        { say: '고 한 번 더!', tier: 'meh', face: 'think', answer: '밭에서는 고 해도 돼. 판에서는 내가 말린다.' },
      ],
    },
    {
      id: 'op-fish',
      when: { fish: true },
      open: '…비린내. {me}, 오늘 {fish} 잡았지? 미안한데 회관엔 안 들고 와 줄래?',
      replies: [
        { say: '구워서 가져올게', tier: 'great', answer: ['…구우면 얘기가 달라지지.', '생선구이엔 흰밥이야. 밥은 내가 할게.'] },
        { say: '미안, 손 씻고 올게', tier: 'good', face: 'smile', answer: '착하네. 비누는 문 옆에 있어. 판 앞엔 깨끗한 손만.' },
        { say: '날생선도 맛있는데', tier: 'meh', face: 'sorry', answer: '…그건 너나 먹어. 난 날 건 패든 생선이든 싫어.' },
      ],
    },
    {
      id: 'op-bigfish',
      when: { bigFish: true },
      open: '마을이 떠들썩하더라. 큰 거 낚았다며? 판으로 치면 오광이네.',
      replies: [
        { say: '언니한테 제일 먼저 자랑', tier: 'great', face: 'wow', answer: ['…나한테? 비린내 나는 자랑을?', '후후, 그래도 좋다. 축하해. 구우면 한 점만 줘.'] },
        { say: '운이 좋았어', tier: 'good', face: 'smile', answer: '오래 기다린 사람한테 오는 운이야. 판이랑 같아.' },
        { say: '회 떠 줄까?', tier: 'meh', face: 'sorry', answer: '…그건 선장님한테 가져가. 난 박수만 칠게.' },
      ],
    },
    {
      id: 'op-high',
      when: { mood: 'high' },
      open: '{me}, 오늘 얼굴에 광이 들었네. 좋은 일 있었지? 다 보여.',
      replies: [
        { say: '언니 보러 와서 그래', tier: 'great', face: 'shy', answer: ['…그 패는 반칙이야.', '그래도 받을게. 오늘은 내가 졌어.'] },
        { say: '그냥 기분이 좋아', tier: 'good', face: 'smile', answer: '이유 없이 좋은 날이 제일 좋아. 판에 앉지 말고 그냥 가.' },
        { say: '판 하나 하자!', tier: 'meh', face: 'think', answer: '좋은 날일수록 판은 짧게. 한 판만. 콩으로.' },
      ],
    },
    {
      id: 'op-low',
      when: { mood: 'low' },
      open: '{me}, 오늘 얼굴에 패가 다 보여. 안 좋은 패. 무슨 일 있었니?',
      replies: [
        { say: '그냥 좀 힘들어', tier: 'great', face: 'smile', answer: ['…그럼 오늘은 이야기하지 마.', '차 우리는 소리만 듣고 있어. 그것도 쉬는 거야.'] },
        { say: '언니한텐 못 숨기네', tier: 'good', answer: '못 숨기지. 대신 아무한테도 안 말해. 그게 내 판 규칙이야.' },
        { say: '아무 일도 없어', tier: 'meh', face: 'sorry', answer: '…그래. 엎어 둔 패는 안 까. 대신 죽 한 그릇은 먹고 가.' },
      ],
    },
    {
      id: 'op-wedding',
      when: { news: 'wedding' },
      open: '광장에서 결혼식 올렸다며? 판에선 평생 같이 칠 짝을 만난 거지.',
      replies: [
        { say: '언니는 짝 없어?', tier: 'good', face: 'shy', answer: '…그건 패 까 보기 전엔 모르는 거야. 후후.' },
        { say: '진심으로 축하할 일이야', tier: 'great', answer: ['그래. 오늘은 회관에서 떡 돌리자.', '좋은 날엔 다 같이 먹어야지.'] },
        { say: '결혼은 도박이래', tier: 'meh', face: 'calm', answer: '도박은 속이는 판이고, 결혼은 같이 치는 판이야. 달라.' },
      ],
    },
    {
      id: 'op-birthday-news',
      when: { news: 'birthday' },
      open: '오늘 마을에 생일인 사람 있다며. 미역국 한 솥 끓였어. 나눠 주려고.',
      replies: [
        { say: '배달은 내가 할게', tier: 'great', face: 'smile', answer: ['고마워. 뚜껑 꼭 닫고.', '생일상은 남이 차려 줘야 맛있어. 그게 셈이야.'] },
        { say: '나도 한 그릇!', tier: 'good', face: 'laugh', answer: '생일 아닌 사람은 반 그릇. 후후, 농담이야.' },
        { say: '선물은 뭐 해?', tier: 'meh', face: 'think', answer: '선물보다 밥. 밥은 안 남아도 기억이 남거든.' },
      ],
    },
    {
      id: 'op-festival-news',
      when: { news: 'festival' },
      open: '축제 준비한다며 광장이 시끄럽더라. 회관에선 전 부치기 담당이야, 난.',
      replies: [
        { say: '반죽 젓는 거 도울게', tier: 'great', face: 'smile', answer: ['좋아. 한쪽으로만 저어.', '이리저리 저으면 전이 질겨져. 사람 마음도 그렇고.'] },
        { say: '화투 대회는 안 해?', tier: 'good', face: 'laugh', answer: '하면 내가 심판이야. 그럼 다들 무서워서 안 나와.' },
        { say: '시끄러운 건 싫어', tier: 'meh', answer: '그럼 회관 와. 여긴 축제 때가 제일 조용해.' },
      ],
    },
    {
      id: 'op-legend',
      when: { news: 'legend' },
      open: '전설의 물고기가 잡혔다고 마을이 난리야. 판보다 더 시끄러워.',
      replies: [
        { say: '언니도 보러 갈래?', tier: 'great', face: 'think', answer: ['…멀리서만. 비린내 나잖니.', '그래도 그런 날은 구경해야지. 평생 한 번일지 모르니까.'] },
        { say: '판보다 대단해?', tier: 'good', face: 'laugh', answer: '판은 매일 돌아. 그건 평생 한 번이야. 비교가 안 돼.' },
        { say: '물고기가 뭐가 대단해', tier: 'meh', face: 'calm', answer: '…그 말 럭스 앞에선 하지 마. 큰일 나.' },
      ],
    },
    {
      id: 'op-record',
      when: { news: 'record' },
      open: '누가 마을 기록을 깼다며. 기록은 판으로 치면 독박이야. 다들 쫓아오거든.',
      replies: [
        { say: '쫓기는 게 재밌잖아', tier: 'great', face: 'wow', answer: ['…너 판에 앉으면 큰일 나겠다.', '그런 배짱은 좋아. 대신 지킬 때도 웃어.'] },
        { say: '기록은 깨지라고 있지', tier: 'good', face: 'smile', answer: '맞아. 그래서 난 기록 대신 사람을 기억해.' },
        { say: '관심 없어', tier: 'meh', answer: '그것도 편해. 쫓을 것도 쫓길 것도 없으니까.' },
      ],
    },
    {
      id: 'op-museum-news',
      when: { news: 'museum' },
      open: '박물관에 새 물건이 들어왔대. 옛날 화투패도 있으면 좋겠는데.',
      replies: [
        { say: '언니 패 하나 기증해', tier: 'great', face: 'think', answer: ['…어떤 패를?', '비광이면 할게. 제일 오래 같이 다닌 패거든.'] },
        { say: '같이 구경 가자', tier: 'good', face: 'smile', answer: '조용한 데는 좋아. 판 닫는 날 가자.' },
        { say: '화투가 무슨 유물이야', tier: 'meh', face: 'calm', answer: '백 년 전 사람들도 이걸로 웃고 울었어. 유물 맞아.' },
      ],
    },
    {
      id: 'op-friend-wedding',
      when: { friendNews: 'wedding' },
      open: '네 친구 결혼한다며? 축의금은 정직하게 내. 판돈처럼 아끼지 말고.',
      replies: [
        { say: '언니가 봉투 써 줘', tier: 'great', face: 'smile', answer: ['글씨는 내가 좀 쓰지.', '봉투 앞엔 이름, 안엔 마음. 그 순서가 맞아.'] },
        { say: '얼마가 적당해?', tier: 'good', face: 'think', answer: '받은 만큼, 아니면 앞으로 받을 만큼. 셈은 그거면 돼.' },
        { say: '부럽기만 해', tier: 'meh', face: 'sorry', answer: '…부러운 마음도 패야. 엎어 두지 말고 축하해 줘.' },
      ],
    },
    {
      id: 'op-recent-fishing',
      when: { recent: 'fishing' },
      open: '요즘 낚시 자주 다니지? 손이 물에 불었어. 다 보여.',
      replies: [
        { say: '기다리는 연습 중이야', tier: 'great', face: 'wow', answer: ['…좋은 연습이네.', '패도 물고기도 서두르면 안 들어와.'] },
        { say: '생선 좀 줄까?', tier: 'meh', face: 'sorry', answer: '…마음만 받을게. 진짜로.' },
        { say: '재밌어', tier: 'good', face: 'smile', answer: '재밌는 거 하나 있는 사람은 판에 안 빠져. 다행이다.' },
      ],
    },
    {
      id: 'op-recent-voyage',
      when: { recent: 'voyage' },
      open: '먼바다 다녀왔다며. 무사히 왔으면 그 판은 이긴 거야.',
      replies: [
        { say: '언니 국이 그리웠어', tier: 'great', face: 'shy', answer: ['…말은. 끓여 놨어. 앉아.', '배 위에선 뭐든 흔들리잖니. 국은 안 흔들리게 해 줄게.'] },
        { say: '배멀미 했어', tier: 'good', answer: '그럼 생강차. 속이 판처럼 뒤집혔을 거야.' },
        { say: '별거 아니었어', tier: 'meh', face: 'calm', answer: '그래도 얼굴은 탔네. 고생한 건 다 보여.' },
      ],
    },
    {
      id: 'op-stock-up',
      when: { recent: 'stockUp' },
      open: '주식 올랐다며? 얼굴에 광이 들었네. 딴 날일수록 지갑은 닫아.',
      replies: [
        { say: '떡 돌릴게', tier: 'great', face: 'laugh', answer: ['후후, 이 마을 법을 아는구나.', '딴 사람이 떡 돌리면 다음 판에 아무도 안 미워해.'] },
        { say: '더 넣어 볼까?', tier: 'meh', face: 'think', answer: '…그게 세 번째 고야. 내가 말린다.' },
        { say: '운이 좋았지', tier: 'good', answer: '운이라고 말하는 사람은 오래 가. 실력이라고 하면 금방 털려.' },
      ],
    },
    {
      id: 'op-stock-down',
      when: { recent: 'stockDown' },
      open: '주식 내렸구나. 밥은 먹었니? 셈은 그다음이야.',
      replies: [
        { say: '아직… 밥 줘', tier: 'great', face: 'smile', answer: ['그럴 줄 알았다. 죽 쒀 놨어.', '잃은 날엔 따뜻한 걸 먹어야 해. 그래야 다음 패를 봐.'] },
        { say: '본전 찾을 거야', tier: 'meh', face: 'sorry', answer: '그 말이 제일 무서워. 본전 생각은 판을 길게 만들어.' },
        { say: '괜찮아, 기다릴래', tier: 'good', face: 'calm', answer: '그래. 뻑 한 번 났다고 판이 끝나진 않아.' },
      ],
    },
    {
      id: 'op-casino-win',
      when: { recent: 'casinoWin' },
      open: '카지노에서 땄다며. 미쿠가 그러더라. 딴 사람은 일찍 일어나는 게 예의야.',
      replies: [
        { say: '그래서 일어났어', tier: 'great', face: 'wow', answer: ['…잘했어. 그게 제일 어려운 거야.', '오늘 차는 내가 살게. 일어날 줄 아는 사람한테.'] },
        { say: '내일 또 갈래', tier: 'meh', face: 'think', answer: '내일의 너는 오늘의 너를 다 잃을 거야. 알지?' },
        { say: '미쿠가 잘 돌려 줬어', tier: 'good', face: 'laugh', answer: '걔는 노래 부르며 돌리잖니. 그 박자에 다들 홀려.' },
      ],
    },
    {
      id: 'op-casino-lose',
      when: { recent: 'casinoLose' },
      open: '카지노에서 잃었구나. 얼굴에 써 있어. 괜찮아, 다들 한 번은 그래.',
      replies: [
        { say: '언니 말 들을걸', tier: 'great', face: 'sorry', answer: ['…다음엔 들어.', '오늘은 잔소리 대신 국수 말아 줄게.'] },
        { say: '다음엔 딸 거야', tier: 'meh', face: 'calm', answer: '그 말 하는 사람 다 봤어. 다음엔 안 가는 게 이기는 거야.' },
        { say: '재미값이라 쳐', tier: 'good', face: 'smile', answer: '그렇게 셈하면 돼. 재미값은 딱 거기까지만.' },
      ],
    },
    {
      id: 'op-recent-museum',
      when: { recent: 'museum' },
      open: '박물관 다녀왔지? 조용한 데 다녀온 얼굴이야. 차분해졌어.',
      replies: [
        { say: '옛날 패도 있었어', tier: 'great', face: 'wow', answer: ['정말? 어떤 그림이었어?', '…다음에 같이 가자. 그건 꼭 보고 싶어.'] },
        { say: '그냥 구경했어', tier: 'good', answer: '구경도 공부야. 판 구경하는 사람이 제일 많이 배우잖니.' },
        { say: '지루했어', tier: 'meh', face: 'laugh', answer: '후후, 정직하네. 그럼 오늘은 부침개로 달래.' },
      ],
    },
    {
      id: 'op-lumi',
      when: { bond: 'lumi' },
      open: '미쿠 만났니? 걔 오늘 퇴근길에 할 말 있다더라. 연애 얘기겠지, 또.',
      replies: [
        { say: '무슨 얘긴지 궁금해', tier: 'good', face: 'laugh', answer: '후후, 그건 비밀. 들은 건 안 옮긴다고 했잖니.' },
        { say: '둘이 정말 친하구나', tier: 'great', face: 'smile', answer: ['같은 밤을 일하는 사이니까.', '해 뜰 때 같이 퇴근하는 사람은 각별해.'] },
        { say: '언니 연애 얘기는?', tier: 'meh', face: 'shy', answer: '…그건 미쿠도 몰라. 너도 모르고.' },
      ],
    },
    {
      id: 'op-captain',
      when: { bond: 'captain' },
      open: '샹크스 만나고 왔구나. 그 사람 또 외상 늘렸지? 얼굴 보니 알겠어.',
      replies: [
        { say: '판 끝나고 안주 나눈다며?', tier: 'great', face: 'smile', answer: ['…그 사람 입 가볍다.', '응, 이긴 날엔 매운 거. 진 날엔 국물.'] },
        { say: '외상은 몰라', tier: 'good', answer: '모르는 게 나아. 그 사람 장부는 미스 포츈 담당이야. 난 안 엮일래.' },
        { say: '선장님 멋있던데', tier: 'meh', face: 'calm', answer: '멋있지. 지면서도 웃는 사람. 그래서 판에선 위험해.' },
      ],
    },
    {
      id: 'op-nasera',
      when: { bond: 'nasera' },
      open: '나세라 봤니? 오늘 차 모임 날인데, 또 장부 들고 오겠지.',
      replies: [
        { say: '다과는 내가 준비할게', tier: 'great', face: 'smile', answer: ['어머, 그럼 셋이 하자.', '나세라가 다과 값 계산하면 그냥 웃어 줘.'] },
        { say: '조합장님 바쁘던데', tier: 'good', face: 'think', answer: '바빠도 차는 마셔. 그게 우리 약속이야.' },
        { say: '차 모임 지루하지 않아?', tier: 'meh', face: 'calm', answer: '지루한 게 좋아. 판에선 늘 긴장하니까.' },
      ],
    },
    {
      id: 'op-with-lumi',
      when: { with: 'lumi' },
      open: '{other}, 오늘 퇴근 같이 하자. …아, {me}. 우리 수다 떠는 중이었어.',
      replies: [
        { say: '나도 끼워 줘', tier: 'great', face: 'laugh', answer: ['후후, 연애 얘기 중인데 괜찮아?', '미쿠, 얘 입 무거운 사람이야. 내가 보증해.'] },
        { say: '무슨 얘기였어?', tier: 'good', face: 'shy', answer: '비밀. 딜러 둘이 패 까는 거 봤니? 안 까.' },
        { say: '방해했나?', tier: 'meh', answer: '아니야. 판에선 늦게 온 사람도 패 받아.' },
      ],
    },
    {
      id: 'op-with-captain',
      when: { with: 'captain' },
      open: '{other}, 오늘은 무슨 안주야? …{me}, 너도 앉아. 한 젓가락씩.',
      replies: [
        { say: '국물이면 진 날이네?', tier: 'great', face: 'laugh', answer: ['후후, 다 알아 버렸네.', '선장님, 들켰어요. 이 사람 판에 앉히면 안 되겠다.'] },
        { say: '잘 먹을게', tier: 'good', face: 'smile', answer: '천천히 먹어. 밥 먹을 땐 판 얘기 금지.' },
        { say: '생선이면 난 패스', tier: 'meh', face: 'calm', answer: '…나도야. 오늘은 고기 안주래. 다행이지.' },
      ],
    },
    {
      id: 'op-with-nasera',
      when: { with: 'nasera' },
      open: '{other}랑 차 마시는 중이야. 오늘은 유자차. {me}, 너도 한 잔?',
      replies: [
        { say: '좋아, 같이 마실래', tier: 'great', face: 'smile', answer: ['잔 하나 더. 나세라, 시세 얘긴 잠깐 쉬자.', '…응, 쉬는 시간도 시세라고? 못 말려.'] },
        { say: '유자 시세는 어때?', tier: 'good', face: 'laugh', answer: '…너까지. 나세라가 신났다. 한 시간짜리야.' },
        { say: '나중에 올게', tier: 'meh', answer: '그래. 찻잔은 엎어 둘게. 네 자리.' },
      ],
    },
    {
      id: 'op-sulk',
      when: { sulk: true },
      open: '{other}랑 좀 틀어졌어. 판 끝나고 말이 엇갈렸거든. 티 나니?',
      replies: [
        { say: '차 한 잔 들고 가 봐', tier: 'great', face: 'think', answer: ['…그게 맞겠지.', '먼저 잔 내미는 쪽이 지는 게 아니야. 그건 판에서만 그래.'] },
        { say: '언니가 먼저 미안해 해', tier: 'good', face: 'sorry', answer: '…알아. 아는데 손이 안 가. 셈은 빠른데 이건 느려.' },
        { say: '내버려 둬', tier: 'meh', face: 'calm', answer: '하루는 그럴게. 이틀은 안 돼. 식은 차는 다시 안 데워지거든.' },
      ],
    },
    {
      id: 'op-bday',
      when: { bday: true },
      open: '{me}, 생일이지? 수첩 안 봐도 알아. 얼굴이 들떠 있거든. 축하해.',
      replies: [
        { say: '언니 미역국 먹고 싶어', tier: 'great', face: 'smile', answer: ['끓여 놨지. 소고기 넉넉히.', '오늘은 판도 패도 네 거야. 먹고 가.'] },
        { say: '어떻게 알았어?', tier: 'good', face: 'laugh', answer: '사람 읽는 게 내 일이야. 생일 얼굴은 제일 쉬워.' },
        { say: '나이 먹기 싫어', tier: 'meh', face: 'calm', answer: '…나이는 피 같은 거야. 모이면 점수가 돼.' },
      ],
    },
  ],
  callbacks: [
    {
      id: 'cb-honest',
      when: { mem: ['honest-hand', 'face-read'] },
      use: 'face-read',
      open: '저번에 지더라도 정직하게 친다고 했지? 그 뒤로 네 판을 몰래 봤어. 진짜더라.',
      replies: [
        { say: '언니 앞이라서가 아니야', tier: 'great', face: 'shy', answer: ['…알아. 그래서 좋은 거야.', '그런 손은 오래 봐도 질리지 않거든.'] },
        { say: '몰래 보지 마!', tier: 'good', face: 'laugh', answer: '후후, 그게 내 일이야. 대신 네 판은 이제 안 볼게. 믿으니까.' },
      ],
    },
    {
      id: 'cb-go',
      when: { mem: 'go-player' },
      use: 'go-player',
      open: '고만 외친다던 {me}. 요즘도 고니? 얼굴 보니 아직 안 다쳤나 보네.',
      replies: [
        { say: '요즘은 스톱도 해', tier: 'great', remember: 'stop-player', face: 'wow', answer: ['어머, 컸네.', '멈출 줄 아는 사람이 판을 오래 앉아 있어.'] },
        { say: '여전히 고!', tier: 'good', face: 'laugh', answer: '후후, 못 말려. 그래도 세 번째 고는 내가 말린다. 약속 기억하지?' },
      ],
    },
    {
      id: 'cb-stop',
      when: { mem: 'stop-player' },
      use: 'stop-player',
      open: '멈출 줄 안다고 했지? 어제 판에서 너 같은 사람이 한 명도 없더라.',
      replies: [
        { say: '언니한테 배운 거야', tier: 'great', face: 'shy', answer: ['…내가 가르친 적 없는데.', '그래도 그렇다고 해 둘게. 기분 좋네.'] },
        { say: '다들 고만 했어?', tier: 'good', face: 'laugh', answer: ['고, 고, 고. 그러다 다 뻑.', '내가 콩 다 돌려줬어. 판은 웃으면서 끝내야지.'] },
        { say: '가끔은 고도 해', tier: 'good', face: 'smile', answer: '그래야 사람이지. 멈추는 것도 고르는 것도 네 손이야.' },
      ],
    },
    {
      id: 'cb-tea',
      when: { mem: 'tea-lover' },
      use: 'tea-lover',
      open: '차 좋아한다고 했잖니. 오늘 새로 들어온 꽃차가 있어. 너 먼저 줄게.',
      replies: [
        { say: '언니가 기억해 줘서 좋다', tier: 'great', face: 'smile', answer: ['…자기 취향은 판보다 쉽게 외워져.', '이상하지. 남의 패는 금방 잊는데.'] },
        { say: '무슨 꽃이야?', tier: 'good', answer: '국화랑 동백. 겨울 패 두 장 섞은 맛이야. 마셔 봐.' },
      ],
    },
    {
      id: 'cb-homecook',
      when: { mem: 'homecook' },
      use: 'homecook',
      open: '집밥이 제일이라던 {me}. 오늘 반찬 좀 싸 왔어. 장조림이랑 나물.',
      replies: [
        { say: '언니 밥이 제일이야', tier: 'great', face: 'shy', answer: ['…그런 말은 판에서 못 들어.', '통은 안 돌려줘도 돼. 다음에 네 반찬 담아 와.'] },
        { say: '나도 뭐 해 올게', tier: 'good', face: 'smile', answer: '좋아. 반찬 바꿔 먹는 사이, 그게 이 마을 판이야.' },
        { say: '고기 반찬은 없어?', tier: 'good', face: 'laugh', answer: '장조림이 고기야. 후후, 눈이 판보다 빠르네.' },
      ],
    },
    {
      id: 'cb-pancake',
      when: { mem: 'rain-pancake', weather: ['rain', 'storm'] },
      use: 'rain-pancake',
      open: '비 오면 부침개 같이 먹자고 했던 거 기억나? 오늘이 그날이야. 앉아.',
      replies: [
        { say: '기억해 줘서 고마워', tier: 'great', face: 'smile', answer: ['약속은 패랑 달라서 버리는 게 아니거든.', '뜨거울 때 먹어.'] },
        { say: '막걸리는?', tier: 'good', face: 'laugh', answer: '후후, 회관에선 안 돼. 대신 식혜 줄게. 내가 담근 거야.' },
      ],
    },
    {
      id: 'cb-bigwang',
      when: { mem: 'bi-gwang' },
      use: 'bi-gwang',
      open: '비광에 정이 간다고 했지. 그 패 하나 줄게. 오래 써서 귀가 닳은 거야.',
      replies: [
        { say: '소중히 간직할게', tier: 'great', face: 'shy', answer: ['…그 패, 나랑 제일 오래 다녔어.', '떠돌 때도 그 패만은 안 바꿨지. 이제 네 거야.'] },
        { say: '판에서 쓰면 안 돼?', tier: 'good', face: 'laugh', answer: '한 장 빠지면 판이 무효잖니. 그러니까 판 밖에서만.' },
      ],
    },
    {
      id: 'cb-secret',
      when: { mem: 'secret-kept' },
      use: 'secret-kept',
      open: '그 비밀, 아직 안 옮겼더라. 회관에 아무 소문도 없어. …고마워.',
      replies: [
        { say: '뜨개질한 거 보여 줘', tier: 'great', face: 'shy', answer: ['…이거. 목도리야. 아직 반밖에 못 떴어.', '다 뜨면 누구 줄지 고민 중이고.'] },
        { say: '당연하지', tier: 'good', answer: '당연한 걸 지키는 사람이 드물어. 그래서 고마운 거야.' },
      ],
    },
    {
      id: 'cb-learn',
      when: { mem: 'learn-hwatu' },
      use: 'learn-hwatu',
      open: '화투 배우고 싶다고 했지? 오늘 두 번째 수업. 패 섞는 법.',
      replies: [
        { say: '천천히 가르쳐 줘', tier: 'great', face: 'smile', answer: ['그래. 섞을 땐 패가 보이게, 손은 느리게.', '보는 사람이 안심해야 좋은 손이야. 잘하네.'] },
        { say: '빨리 섞는 법 알려 줘', tier: 'meh', face: 'think', answer: '빠른 손은 의심받아. 내 판에선 느린 게 실력이야.' },
        { say: '첫 수업은 손 씻기였지', tier: 'good', face: 'laugh', answer: '후후, 기억하네. 그럼 씻고 와. 그것부터.' },
      ],
    },
    {
      id: 'cb-songpyeon',
      when: { mem: 'songpyeon', season: 'autumn' },
      use: 'songpyeon',
      open: '송편 빚자고 했던 거 기억하지? 반죽 해 놨어. 소는 깨랑 밤이야.',
      replies: [
        { say: '예쁘게 빚어 볼게', tier: 'great', face: 'smile', answer: ['…오, 제법이다. 반달이 예쁘네.', '예쁜 짝 만나겠다. 후후, 누군지는 안 물을게.'] },
        { say: '밤 소가 좋아', tier: 'good', answer: '나도. 깨는 달고, 밤은 따뜻해.' },
        { say: '터졌어…', tier: 'good', face: 'laugh', answer: '괜찮아. 터진 건 네가 먹어. 그게 법이야.' },
      ],
    },
    {
      id: 'cb-night-stall',
      when: { mem: 'night-stall' },
      use: 'night-stall',
      open: '포장마차 아저씨가 너 안부 묻더라. 그날 같이 온 사람 누구냐고.',
      replies: [
        { say: '뭐라고 했어?', tier: 'great', face: 'shy', answer: ['…판 밖 손님이라고 했어.', '그 말이 무슨 뜻인지는, 너도 알지?'] },
        { say: '또 같이 가자', tier: 'good', face: 'smile', answer: '좋아. 이번엔 네가 사. 국수 두 그릇이면 돼.' },
      ],
    },
    {
      id: 'cb-flower-tea',
      when: { mem: 'flower-tea' },
      use: 'flower-tea',
      open: '네가 준 꽃차, 아까워서 조금씩 마셨어. 오늘 마지막 잔이야.',
      replies: [
        { say: '또 만들어 올게', tier: 'great', face: 'shy', answer: ['…그럼 이번 잔은 둘이 나눠 마시자.', '반씩. 셈은 정확하게.'] },
        { say: '그냥 마시지', tier: 'good', face: 'laugh', answer: '받은 차는 빨리 못 마셔. 그런 성격이야.' },
      ],
    },
    {
      id: 'cb-quiet',
      when: { mem: 'quiet-win' },
      use: 'quiet-win',
      open: '조용히 이기는 사람이 무섭다고 했지. 어제 네가 그랬다며? 콩 판에서.',
      replies: [
        { say: '언니 흉내 낸 거야', tier: 'great', face: 'laugh', answer: ['후후, 들켰다.', '찻잔부터 들었다며. 그건 내 버릇인데.'] },
        { say: '운이 좋았어', tier: 'good', face: 'smile', answer: '그렇게 말하는 것까지 조용하네. 합격.' },
      ],
    },
    {
      id: 'cb-plum',
      when: { mem: 'plum-name' },
      use: 'plum-name',
      open: '매화 얘기 기억해? 회관 뒤에 매화나무 심었어. 내 옛 이름 거기 묻으려고.',
      replies: [
        { say: '꽃 피면 같이 보자', tier: 'great', face: 'shy', answer: ['…그래. 추울 때 피니까, 늦겨울쯤.', '그때도 날 예림이라고 불러 줘.'] },
        { say: '이름을 왜 묻어?', tier: 'good', face: 'think', answer: '판에서 쓰던 이름은 판에 두는 거야. 이제 안 쓸 거니까.' },
      ],
    },
    {
      id: 'cb-eye',
      when: { mem: 'eye-first' },
      use: 'eye-first',
      open: '눈이 손보다 먼저라고 했던 거. 어제 그 말 그대로 써먹었어. 손님 하나 내보냈지.',
      replies: [
        { say: '역시 언니 눈이야', tier: 'great', face: 'laugh', answer: ['후후, 칭찬은 받을게.', '근데 네가 맞혀서 생각난 말이야. 반은 네 공.'] },
        { say: '그 손님은 괜찮아?', tier: 'good', face: 'calm', answer: '괜찮아. 다음 날 찾아와서 사과하더라. 차 한 잔 줬어.' },
      ],
    },
    {
      id: 'cb-old-road',
      when: { mem: 'old-road' },
      use: 'old-road',
      open: '떠돌던 얘기 해 줬잖니. 그 뒤로 이상하게 그 시절 꿈을 안 꿔.',
      replies: [
        { say: '이제 여기가 집이라서', tier: 'great', face: 'shy', answer: ['…그런가 봐.', '짐을 다 풀었어. 가방도 버렸고. 이상하게 가볍다.'] },
        { say: '말하면 가벼워지지', tier: 'good', face: 'smile', answer: '맞아. 엎어 둔 패보다 깐 패가 덜 무거워.' },
      ],
    },
    {
      id: 'cb-month',
      when: { mem: 'fav-month' },
      use: 'fav-month',
      open: '좋아하는 달 패 얘기 했었지. 그 패만 골라서 너 주려고 따로 뒀어.',
      replies: [
        { say: '판에서 빼면 어떡해?', tier: 'great', face: 'laugh', answer: ['새 목으로 바꿨어. 이건 은퇴한 패.', '판 밖에선 아무 패나 좋아해도 돼.'] },
        { say: '고마워, 간직할게', tier: 'good', face: 'smile', answer: '지갑에 넣어 다녀. 부적처럼.' },
      ],
    },
    {
      id: 'cb-read-her',
      when: { mem: 'read-her' },
      use: 'read-her',
      open: '저번에 내 얼굴 읽었잖니. 오늘 다시 해 봐. 지금은 뭐가 보여?',
      replies: [
        { say: '조금 덜 외로워 보여', tier: 'great', face: 'shy', answer: ['…맞아.', '누구 덕인지는 말 안 할게. 너도 알잖니.'] },
        { say: '오늘은 배불러 보여', tier: 'good', face: 'laugh', answer: '후후, 점심 먹었어. 너 말 듣고 꼬박꼬박.' },
      ],
    },
    {
      id: 'cb-kimjang',
      when: { mem: 'kimjang', season: 'winter' },
      use: 'kimjang',
      open: '김장 날이야. 고무장갑 낀다며? 배추 절여 놨어. 앉아.',
      replies: [
        { say: '속 넣는 거 가르쳐 줘', tier: 'great', face: 'smile', answer: ['잎 사이사이, 고르게.', '한쪽에만 몰면 익을 때 맛이 달라. 판도 그래.'] },
        { say: '수육은 언제 나와?', tier: 'good', face: 'laugh', answer: '다 끝나면. 먼저 먹는 사람은 설거지 판이다.' },
      ],
    },
    {
      id: 'cb-bean',
      when: { mem: 'bean-stake' },
      use: 'bean-stake',
      open: '콩 판에 앉아 본다고 했지? 오늘 자리 비었어. 콩은 내가 대.',
      replies: [
        { say: '언니 옆자리면 좋아', tier: 'great', face: 'shy', answer: ['…판에선 옆자리가 제일 안 보여.', '그래서 앉힌다. 너 얼굴 안 보고 쳐야 공평하니까.'] },
        { say: '다 잃으면 어떡해?', tier: 'good', face: 'laugh', answer: '콩자반 해 먹으면 돼. 이 판은 잃어도 반찬이 남아.' },
      ],
    },
    {
      id: 'cb-lose-well',
      when: { mem: 'lose-well' },
      use: 'lose-well',
      open: '잘 지는 법 얘기했었지. 어제 선장님이 딱 그렇게 지더라. 국물 두 그릇.',
      replies: [
        { say: '언니는 져 본 적 있어?', tier: 'great', face: 'think', answer: ['…크게 한 번.', '그 얘긴 언젠가 해 줄게. 오늘은 국물이나 먹자.'] },
        { say: '선장님답다', tier: 'good', face: 'laugh', answer: '그 사람은 지는 것도 잔치야. 부러운 재주지.' },
      ],
    },
    {
      id: 'cb-last-hand',
      when: { mem: 'last-hand' },
      use: 'last-hand',
      open: '그 엎어 둔 패 말이야. 아직 안 깠어. 너 기다리느라.',
      replies: [
        { say: '꽃 들고 올게', tier: 'great', face: 'shy', answer: ['…말은. 그럼 기다릴게.', '판에선 기다리는 게 제일 어려운데, 이건 괜찮네.'] },
        { say: '궁금해 죽겠어', tier: 'good', face: 'laugh', answer: '후후, 궁금한 얼굴 좋다. 조금 더 보고 싶어.' },
      ],
    },
    {
      id: 'cb-taste',
      when: { mem: '@taste', noMem: 'taste-heard' },
      open: '{me}, 좋아하는 게 {taste}라며? 수첩에 적혀 있더라. 판보다 쉽게 읽혀.',
      replies: [
        { say: '다음엔 언니 취향도 알려 줘', tier: 'great', remember: 'taste-heard', face: 'shy', answer: ['…내 건 비밀.', '대신 하나만. 따뜻한 거면 다 좋아.'] },
        { say: '들켰네', tier: 'good', remember: 'taste-heard', face: 'laugh', answer: '후후, 숨길 생각도 없었잖니. 그런 정직함이 좋아.' },
      ],
    },
    {
      id: 'cb-outing',
      when: { mem: '@outing', noMem: 'outing-talk' },
      open: '저번에 같이 걸은 거, 생각보다 좋더라. 회관 밖 공기도 나쁘지 않네.',
      replies: [
        { say: '다음엔 과수원 길 가자', tier: 'great', remember: 'outing-talk', face: 'smile', answer: ['…좋아. 거긴 바람에서 단내가 나.', '셈을 안 해도 되는 길이야. 너랑 걸으면 더.'] },
        { say: '언니가 계속 차 얘기만 했어', tier: 'good', remember: 'outing-talk', face: 'laugh', answer: '후후, 차 얘기가 제일 안전하거든. 다음엔 다른 얘기도 해 볼게.' },
        { say: '항구도 가 볼까?', tier: 'meh', remember: 'outing-talk', face: 'sorry', answer: '…비린내 나는 데는 오래 못 있어. 미안.' },
      ],
    },
    {
      id: 'cb-bday',
      when: { mem: '@bday-soon', noMem: 'bday-plan' },
      open: '{me}, 생일 얼마 안 남았지? 생일상 뭐 차려 줄까. 미리 물어보는 거야.',
      replies: [
        { say: '언니가 차려 주면 뭐든', tier: 'great', remember: 'bday-plan', face: 'shy', answer: ['…제일 어려운 주문이네.', '그럼 내 맘대로 할게. 미역국은 기본이고.'] },
        { say: '잡채랑 갈비!', tier: 'good', remember: 'bday-plan', face: 'laugh', answer: '후후, 정직한 입맛이다. 적어 둘게.' },
        { say: '회 한 접시?', tier: 'meh', remember: 'bday-plan', face: 'sorry', answer: '…그건 선장님한테 부탁해. 나는 나머지 다 할게.' },
      ],
    },
    {
      id: 'cb-date',
      when: { mem: '@date', noMem: 'date-talk' },
      open: '네 방에서 마신 차 말이야. 회관 차보다 맛있었어. 왜인지 모르겠네.',
      replies: [
        { say: '같이 마셔서 그래', tier: 'great', remember: 'date-talk', face: 'shy', answer: ['…알아.', '그래서 모르는 척한 거야. 후후.'] },
        { say: '내 찻잎이 좋아서?', tier: 'good', remember: 'date-talk', face: 'laugh', answer: '그건 아니야. 찻잎은 내 게 더 좋아. 그러니까… 알지?' },
      ],
    },
  ],
  chapters: [
    {
      title: '첫 패',
      hint: '한 번 이야기를 나누면 예림이가 패 한 장을 뒤집어 보여 줘요.',
      need: { days: 1 },
      scene: [
        '회관 화투방 문을 열자 보리차 냄새와 패 섞는 소리가 먼저 난다.',
        '창가 자리, 단발머리 여자가 화투 부채를 접으며 고개를 든다.',
        '"어서 와. 처음 보는 얼굴이네. 예림이야. 이 방은 내 손을 거쳐."',
        '그녀가 찻잔 하나를 내 앞에 밀어 놓고, 패 한 장을 엎어 둔다.',
        '"처음 오는 사람한테 늘 하는 거야. 이 패가 뭔지 맞혀 봐."',
        '"맞히든 못 맞히든 상관없어. 대답하는 얼굴을 보는 거니까."',
        '진주 목걸이가 등불에 반짝인다. 입은 웃는데 눈은 웃지 않는다.',
        '옆 판에서 누가 "고!" 하고 외치자, 그녀가 눈도 안 돌리고 말한다.',
        '"세 번째 고는 내가 말린다. 알지?" 그 판이 금세 조용해진다.',
        '"자, 이제 네 차례. 천천히 생각해. 차 식기 전까지만."',
        '엎어진 패 위를 그녀의 손가락이 톡, 톡 가볍게 두드린다.',
      ],
      replies: [
        { say: '모르겠어. 솔직히', tier: 'great', remember: 'face-read', face: 'smile', answer: ['…좋은 얼굴이네. 모르는 걸 모른다고 하는 사람, 오랜만이야.', '이건 이월 매조. 추울 때 제일 먼저 피는 꽃.', '앉아. 네 찻잔은 오늘부터 따로 둘게.'] },
        { say: '광이다!', tier: 'good', face: 'laugh', answer: ['후후, 틀렸어.', '근데 자신 있는 얼굴은 나쁘지 않아. 판에선 그것도 무기야.'] },
        { say: '이런 거 왜 해?', tier: 'meh', face: 'calm', answer: ['판에 앉힐 사람인지 보려고.', '넌… 일단 차부터 마시자. 판은 그다음.'] },
      ],
    },
    {
      title: '포장마차의 밤',
      hint: '밤(게임 시각 저녁 여덟 시부터 자정)에 시장 거리로 가 보세요. 예림이가 퇴근길에 들른대요.',
      need: { days: 3, points: 20, visit: { area: 'market', from: 20, to: 24 } },
      scene: [
        '밤 시장 거리 끝, 포장마차 비닐 천막 안으로 김이 자욱하다.',
        '예림이가 구석 자리에서 국수 그릇을 두 손으로 감싸고 있다.',
        '"왔네. 판 끝나면 여기서 국수 한 그릇 해. 아무도 날 안 읽거든."',
        '그녀가 젓가락 한 벌을 건넨다. 화투 부채는 가방 속에 접혀 있다.',
        '"옛날엔 큰 판을 따라 떠돌았어. 항구 도시, 기찻길 옆 여관방."',
        '"어디를 가도 밤엔 이런 데서 혼자 먹었어. 김 서린 데가 편했지."',
        '주인이 어묵 꼬치를 하나 더 얹어 주자, 그녀가 작게 고개를 숙인다.',
        '"그땐 남의 패만 읽었어. 내 국수가 불어 터지는 줄도 모르고."',
        '천막 위로 밤이슬이 톡톡 떨어지고, 국물에서 멸치 냄새가 오른다.',
        '"…회관에선 마담이지만, 여기선 그냥 국수 먹는 사람이야."',
        '"오늘은 판 얘기 금지. 내가 살게. 국물부터 마셔."',
      ],
      replies: [
        { say: '판 말고 언니 얘기 해 줘', tier: 'great', remember: 'night-stall', face: 'shy', answer: ['…어려운 주문이네.', '그럼 국수 다 먹을 때까지만. 천천히 먹어. 나도 천천히 할게.'] },
        { say: '잘 먹을게!', tier: 'good', remember: 'night-stall', face: 'smile', answer: ['후후, 맛있게 먹는 얼굴이 제일 읽기 쉬워.', '좋다. 이 집 국수는 둘이 먹어야 제맛이었나 봐.'] },
        { say: '국수 별로야', tier: 'meh', remember: 'night-stall', face: 'calm', answer: ['그럼 어묵 국물.', '밤바람엔 따뜻한 게 필요해. 그건 판이든 아니든 같아.'] },
      ],
    },
    {
      title: '꽃차 한 잔',
      hint: '예림이가 꽃차 이야기를 했어요. 꽃차를 한 잔 가지고 회관에 가 보세요.',
      need: { days: 6, points: 40, bring: { item: 'flowertea', take: true } },
      scene: [
        '오후의 회관. 판이 쉬는 시간, 예림이가 찻주전자를 닦고 있다.',
        '꽃차를 내밀자 그녀의 손이 주전자 위에서 잠깐 멈춘다.',
        '"…이걸 나한테? 회관에서 차는 내가 우리는 거야."',
        '"생각해 보니 누가 나한테 차를 준 건 처음이네. 이 마을 와서."',
        '그녀가 찻잔을 두 손으로 감싼다. 판에서는 못 본 손 모양이다.',
        '꽃잎이 찻물 위에서 천천히 펴진다. 마당에서 참새 소리가 난다.',
        '"늘 남의 잔만 채웠어. 얼굴 보고, 그 사람한테 맞는 걸로."',
        '"그러다 보니 내가 뭘 좋아하는지 잊어버렸지 뭐야. 우습지."',
        '그녀가 한 모금 마시고, 오래 눈을 감는다.',
        '"…달다. 조금 쓰고, 많이 달아. 이게 내 입맛이었나 봐."',
        '"고마워, {me}. 오늘은 네 얼굴 안 읽을게. 그냥 마실게."',
      ],
      replies: [
        { say: '언니도 쉬어야지', tier: 'great', remember: 'flower-tea', face: 'shy', answer: ['…자기 때문에 판 밖 얼굴이 자꾸 나와.', '곤란한데. 싫진 않아.'] },
        { say: '맛은 어때?', tier: 'good', remember: 'flower-tea', face: 'smile', answer: ['조금 쓰고, 많이 따뜻해.', '딱 좋은 차야. 우린 사람 얼굴이 보이는 맛.'] },
        { say: '그냥 남아서 줬어', tier: 'meh', remember: 'flower-tea', face: 'calm', answer: ['…후후, 거짓말 서툴다.', '얼굴에 다 쓰여 있어. 그래도 고맙게 마실게.'] },
      ],
    },
    {
      title: '밑장의 기억',
      hint: '예림이에게 정직하게 치는 사람이 좋다고 말해 보세요. 그녀가 옛이야기를 꺼낼 거예요.',
      need: { days: 9, points: 60, mem: 'honest-hand' },
      scene: [
        '판이 끝난 밤 회관. 방석이 흩어져 있고 등불 하나만 남았다.',
        '예림이가 마흔여덟 장을 한 장씩 세다가 손을 멈춘다.',
        '"…정직하게 친다고 했지. 그 말이 자꾸 생각나더라."',
        '"옛날에 나도 한 사람 손을 믿었어. 같이 판을 돌던 사람."',
        '"그 손이 밑장을 빼더라. 내 판에서. 나만 몰랐어."',
        '그녀가 패 한 장을 등불에 비춰 본다. 손때 하나 없이 깨끗하다.',
        '"돈은 금방 다시 모였어. 근데 사람 믿는 셈은 다시 안 서더라."',
        '"그래서 판을 쥐었어. 아무도 속지 않는 판을, 내 손으로."',
        '"큰 판 다 접고 여기 왔어. 콩 한 줌 걸고 웃는 판이 좋아서."',
        '"여기 사람들은 지면 밥을 사. 이기면 떡을 돌리고. 그게 좋더라."',
        '그녀가 세던 패를 가지런히 모아 상자에 넣고, 뚜껑을 닫는다.',
        '"…이 얘기, 처음 해. 네가 정직하다고 해서 반가웠어. 그뿐이야."',
      ],
      replies: [
        { say: '언니 판은 내가 지킬게', tier: 'great', face: 'shy', answer: ['…말은.', '그래도 그 말, 패처럼 엎어 두지 않고 잘 간직할게.', '내 판에 지키는 사람이 생긴 건 처음이야.'] },
        { say: '말해 줘서 고마워', tier: 'good', face: 'smile', answer: ['이 얘기 아는 사람 이제 둘이야. 나랑 너.', '판에선 이걸 동맹이라고 해.'] },
        { say: '다 지난 일이야', tier: 'meh', face: 'calm', answer: ['…그래. 지난 패는 다시 안 섞여.', '맞는 말이야. 근데 가끔은 그냥 들어 주는 게 더 좋아.'] },
      ],
    },
    {
      title: '마지막 패',
      hint: '예림이와 아주 가까워지면 그녀가 엎어 둔 마지막 패를 보여 줘요. 그 뒤엔 꽃다발도 받아 줄지 몰라요.',
      need: { days: 13, points: 96 },
      scene: [
        '보름 무렵 늦은 저녁, 회관 툇마루에 달빛이 길게 깔린다.',
        '예림이가 무릎 위에 패 한 장을 엎어 둔 채 앉아 있다.',
        '"판마다 마지막 한 장은 안 까고 두는 버릇이 있어. 아무도 몰라."',
        '"그 패가 뭔지는 나도 안 봐. 보면 판이 끝나 버리니까."',
        '"평생 남의 패만 읽었어. 읽히는 건 질색이라, 내 건 늘 엎었지."',
        '귀뚜라미 소리 사이로, 그녀가 부채를 폈다 접었다 한다.',
        '"근데 요즘은… 이 패를 누가 같이 까 줬으면 해. 이상하지?"',
        '그녀가 웃는다. 이번엔 눈까지 같이 웃는다.',
        '"판에선 먼저 패 보여 주는 쪽이 지는 거야. 알고 하는 말이야."',
        '"…자기, 나 지금 지고 있는 것 같아."',
      ],
      replies: [
        { say: '같이 까 볼까?', tier: 'great', remember: 'last-hand', face: 'shy', answer: ['…아직. 이건 판이 아니라서 순서가 있어.', '꽃이라도 한 다발 들고 오면, 그때 같이 까자. 후후.'] },
        { say: '안 까도 괜찮아', tier: 'good', remember: 'last-hand', face: 'smile', answer: ['그 말이 제일 듣고 싶었어.', '근데 이상하게 더 까고 싶어지네. 꽃 냄새라도 나면 모를까.'] },
        { say: '무슨 패인데?', tier: 'meh', remember: 'last-hand', face: 'think', answer: ['모른다니까. 그러니까 마지막 패지.', '…궁금하면 기다려. 판은 기다리는 사람 편이야.'] },
      ],
    },
    {
      title: '판 밖의 약속',
      hint: '예림이와 연인이 되면 마지막 이야기가 열려요.',
      need: { days: 16, love: 'dating' },
      scene: [
        '첫서리 내린 밤, 회관 문을 닫은 뒤 예림이가 나를 툇마루로 부른다.',
        '찻상에는 찻잔 둘, 그리고 엎어 둔 패 한 장.',
        '"같이 까자며. 꽃다발 받은 날부터 이날만 기다렸어."',
        '그녀가 내 손등 위에 자기 손을 얹는다. 패 만지던 손이 조금 떨린다.',
        '"하나, 둘…" 패를 뒤집자 팔월 공산, 달이 뜬 광이다.',
        '"…역시. 늘 이거였을 것 같았어. 떠돌던 밤마다 혼자 보던 달."',
        '하늘에도 똑같은 달이 걸려 있다. 패 속 달과 하늘의 달이 겹친다.',
        '"이제 내 패는 다 보여 줬어. 숨긴 거 하나도 없어."',
        '"판에선 이걸 다 걸었다고 해. 무섭네. 근데 싫지 않아."',
        '그녀가 진주 목걸이를 만지작거리다, 작게 웃는다.',
        '"반지는 패처럼 돌리는 게 아니야. 끼워 주는 거지. 알지, 자기?"',
        '"…그런 날이 오면, 그날 찻상은 내가 제일 정성껏 차릴게."',
      ],
      replies: [
        { say: '이제 달은 같이 보자', tier: 'great', face: 'shy', answer: ['…응.', '이건 판에서 하는 약속 아니야. 그러니까 평생 가.', '찻잔 둘, 달 하나. 셈이 딱 맞네.'] },
        { say: '광이네! 이겼다', tier: 'good', face: 'laugh', answer: ['후후, 그래.', '이번 판은 둘 다 이긴 걸로 하자. 그런 판은 처음이야.'] },
        { say: '천천히 가자', tier: 'meh', face: 'smile', answer: ['좋아. 급하게 치는 판은 늘 아쉽거든.', '대신 너무 늦지는 마. 찻물은 식으니까.'] },
      ],
    },
  ],
  after: [
    '오늘 이야기는 여기까지. 차 식기 전에 마시고 가.',
    '또 왔네. 얼굴만 봐도 됐어. 판은 내일.',
    '자기, 할 말 다 했잖니. 들어가서 쉬어.',
    '후후, 오늘은 패 다 깠어. 남은 건 없어.',
    '찻잔은 엎어 둘게. 내일 네 자리.',
    '판 돌리는 중이야. 눈은 여기, 마음은 잠깐 거기.',
    '밥 먹었지? 그럼 됐어. 오늘 셈은 끝.',
    '또 오면 반찬 싸 줄게. 오늘은 그만 가 봐.',
  ],
};
