// 나모 — 범마을 은행원, 스물여섯. 『사니양 연구실』의 푸른 머리 늑대 계열 수인 대학원생을
// 은행 창구의 '프로 은행원'으로 옮겼다. 차분한 해요체. 시크해 보이지만 나사가 하나 빠져 있고
// (머리 위 안경, 손에 든 도장, 거꾸로 든 서류), 체력은 바닥(계단 → 헥헥). 야근·마감·결산에
// 쫓기고, 쉬는 날엔 소설·영화·게임 덕질. 주민들로 이야기를 지어내다 "아무것도 아니에요".
// 수인 중에선 머리가 좋은 편이라고 은근히 어필. 귀·꼬리가 먼저 반응하고("못 본 걸로 해요")
// 코가 예민하다. 생선이면 다 좋고(고등어!) 매운 건 못 먹는다. 마음도 장부·금고·이자로 셈한다.
// 신짜장(서류 배달, 빵 냄새), 미스 포츈(대부 창구 이자 맞수), 무잔(예금이냐 투자냐 금리 논쟁).
// 원작 대사는 옮기지 않은 오리지널 대사예요.
import type { NpcTalkBook } from './types.ts';

export const NYAMO_TALK: NpcTalkBook = {
  npc: 'nyamo',
  memories: {
    'novel-pal': '소설 이야기를 같이 했어요',
    'mackerel-fan': '고등어가 제일이라고 맞장구쳤어요',
    'no-spicy': '매운 걸 못 먹는 걸 알아줬어요',
    'slow-walk': '계단은 천천히 같이 오르자고 했어요',
    'glasses-find': '머리 위 안경을 찾아 줬어요',
    'overtime-cheer': '야근하는 나모를 응원했어요',
    'story-ears': '나모가 지어낸 이야기를 들어 줬어요',
    'smart-wolf': '나모가 머리 좋다고 인정했어요',
    'tail-secret': '꼬리 흔드는 걸 못 본 걸로 해 줬어요',
    'saver': '예금이 든든하다고 했어요',
    'nose-test': '나모의 코가 대단하다고 했어요',
    'moon-howl': '보름달 이야기를 나눴어요',
    'game-night': '밤새 게임한 이야기를 들었어요',
    'moon-hill': '뒷산에서 달을 함께 봤어요',
    'mackerel-gift': '고등어를 선물했어요',
    'taste-heard': '내 취향을 장부에 적어 뒀대요',
    'outing-talk': '함께 걸은 날을 이야기했어요',
    'bday-heard': '생일이 다가온다는 걸 나모가 알아챘어요',
    'lab-tale': '연구실 시절 이야기를 들었어요',
    'story-cast': '나모 소설에 나를 넣어도 된다고 했어요',
    'saving-goal': '나모와 적금 목표를 같이 세웠어요',
    'mild-recipe': '안 매운 생선 요리법을 나눴어요',
    'riddle-win': '나모의 수수께끼를 맞혔어요',
    'coffee-care': '커피 대신 물 마시라고 잔소리했어요',
    'ear-manners': '귀는 함부로 안 만지기로 약속했어요',
    'scent-map': '나모의 냄새 지도 이야기를 들었어요',
    'novel-asked': '나모 소설의 다음 권을 물어봤어요',
    'date-heard': '내 방에서 보낸 날을 나모가 기억했어요',
    'harbor-wish': '항구 어시장을 같이 기다리기로 했어요',
    'frieren-calc': '프리렌 통장 이자 이야기에 웃었어요',
  },
  talks: [
    {
      id: 'novel',
      open: '{me} 님, 요즘 무슨 책 읽어요? 저는 어젯밤 소설 한 권을 끝냈어요.',
      replies: [
        { say: '나도 소설 좋아해! 무슨 책이야?', tier: 'great', remember: 'novel-pal', face: 'wow', answer: ['…같은 편이네요. 귀가 쫑긋했어요.', '추리 소설이에요. 범인은 은행원이었어요. 저 아니에요.'] },
        { say: '밤새 읽은 거야?', tier: 'good', face: 'shy', answer: '네. 한 장만 더, 하다가 해가 떴어요. 장부엔 안 적을게요.' },
        { say: '책은 잘 안 읽어', tier: 'meh', answer: '괜찮아요. 줄거리는 제가 이야기해 드릴게요. 길어요.' },
      ],
    },
    {
      id: 'mackerel',
      open: '생선은 다 좋지만 하나만 고르라면요… {me} 님은 뭐 같아요?',
      replies: [
        { say: '고등어지!', tier: 'great', remember: 'mackerel-fan', face: 'laugh', answer: ['…맞혔어요. 꼬리가 멋대로 흔들려요.', '아, 못 본 걸로 해요. 고등어 얘기라서 그래요.'] },
        { say: '은어 아니야?', tier: 'good', face: 'think', answer: '은어도 좋아요. 봄에만 있어서 더 소중해요. 근데 일 등은 아니에요.' },
        { say: '생선은 다 똑같지 않아?', tier: 'meh', face: 'sorry', answer: '…장부에 숫자가 다 똑같다는 말이랑 같아요. 조금 슬퍼요.' },
      ],
    },
    {
      id: 'spicy',
      open: '점심에 누가 매운탕을 권했어요. 냄새만 맡았는데 코가 먼저 도망갔어요.',
      replies: [
        { say: '다음엔 안 매운 걸로 챙겨 줄게', tier: 'great', remember: 'no-spicy', face: 'shy', answer: '…고마워요. 그 말, 이자 붙여서 갚을게요.' },
        { say: '조금씩 먹다 보면 익숙해져', tier: 'good', face: 'think', answer: '그런 말 들은 지 이십 년째예요. 아직도 안 익숙해요.' },
        { say: '매운 게 맛있는데', tier: 'meh', answer: '취향은 존중해요. 근데 제 앞에선 뚜껑 덮어 주세요.' },
      ],
    },
    {
      id: 'stairs',
      open: '은행 이 층 서류실 다녀왔어요. 헥, 헥… 잠깐만요. 숨 좀 고를게요.',
      replies: [
        { say: '다음엔 천천히 같이 올라가자', tier: 'great', remember: 'slow-walk', face: 'shy', answer: '…같이요? 그럼 계단이 조금 짧아질 것 같아요.' },
        { say: '늑대인데 체력이 없어?', tier: 'good', face: 'sorry', answer: '날렵해 보인다는 말은 들어요. 겉모습만요. 장부만큼 정직하죠.' },
        { say: '운동 좀 해', tier: 'meh', answer: '알아요. 내일부터 할게요. …그 내일이 삼 년째예요.' },
      ],
    },
    {
      id: 'glasses',
      open: '안경이 어디 갔지… {me} 님, 혹시 제 안경 봤어요?',
      replies: [
        { say: '머리 위에 있어', tier: 'great', remember: 'glasses-find', face: 'shy', answer: ['…아. 있네요.', '머리는 좋은데요. 진짜예요. 못 본 걸로 해요.'] },
        { say: '같이 찾아볼게', tier: 'good', face: 'smile', answer: '고마워요. 서랍, 금고, 장부 사이… 아, 머리 위였어요.' },
        { say: '그 손에 든 건 도장이야?', tier: 'meh', face: 'wow', answer: '…도장도 찾고 있었어요. 하나는 해결됐네요.' },
      ],
    },
    {
      id: 'overtime',
      open: '이번 주 야근이 사흘째예요. 결산은 왜 꼭 금요일에 몰릴까요.',
      replies: [
        { say: '고생 많아. 야근 간식 사 올게', tier: 'great', remember: 'overtime-cheer', face: 'wow', answer: '…정말요? 생선 과자면 오늘 밤은 버틸 수 있어요.' },
        { say: '일찍 들어가서 자', tier: 'good', face: 'sorry', answer: '그러고 싶어요. 장부가 안 놓아줘요. 저도 장부를 못 놓고요.' },
        { say: '은행원은 편할 줄 알았는데', tier: 'meh', answer: '다들 그렇게 말해요. 창구 뒤를 보면 생각이 바뀔 거예요.' },
      ],
    },
    {
      id: 'stories',
      open: '아까 광장에서 두 분이 우산 하나를 같이 쓰더라고요. 제 머릿속에선 벌써 삼 권째예요.',
      replies: [
        { say: '그 이야기 들려줘!', tier: 'great', remember: 'story-ears', face: 'laugh', answer: ['첫 권은 우산 하나로 시작해요. 둘째 권에서 오해가…', '…아, 아무것도 아니에요. 지어낸 거예요.'] },
        { say: '누구랑 누군데?', tier: 'good', face: 'shy', answer: '그건 비밀이에요. 은행원은 입이 무거워요. 머릿속만 가볍죠.' },
        { say: '그냥 비 와서 같이 쓴 거겠지', tier: 'meh', face: 'think', answer: '…그렇죠. 현실은 소설보다 이자가 적어요.' },
      ],
    },
    {
      id: 'smart',
      open: '이자 계산은 암산으로 해요. 수인 중에선 머리 좋은 편이거든요. 어디까지나 편이에요.',
      replies: [
        { say: '편이 아니라 진짜 똑똑해', tier: 'great', remember: 'smart-wolf', face: 'shy', answer: '…그렇게 말해 주면 귀가 뜨거워져요. 계산이 틀릴 것 같아요.' },
        { say: '그럼 이거 계산해 봐', tier: 'good', face: 'laugh', answer: '이미 했어요. {me} 님 이번 달 이자, 머릿속에 다 있어요.' },
        { say: '안경은 맨날 잃어버리면서', tier: 'meh', face: 'sorry', answer: '…그건 머리 문제가 아니라 머리 위 문제예요.' },
      ],
    },
    {
      id: 'tail',
      open: '방금 꼬리가 흔들렸죠. 아니에요. 바람이에요. 은행 안에 바람이 좀 불어요.',
      replies: [
        { say: '응, 못 본 걸로 할게', tier: 'great', remember: 'tail-secret', face: 'shy', answer: '…고마워요. 이 비밀은 금고에 넣어 둘게요. 둘만 아는 걸로요.' },
        { say: '나 와서 좋은 거지?', tier: 'good', face: 'wow', answer: '그, 그건… 창구 손님이 와서 반가운 거예요. 업무예요.' },
        { say: '창문 닫아 줄까?', tier: 'meh', face: 'think', answer: '…네, 닫아 주세요. 바람 탓이라고 해야 하니까요.' },
      ],
    },
    {
      id: 'deposit',
      open: '{me} 님은 돈이 생기면 예금해요, 투자해요? 무잔 씨는 투자래요.',
      replies: [
        { say: '예금. 든든하잖아', tier: 'great', remember: 'saver', face: 'laugh', answer: '…좋아요. 정말 좋아요. 무잔 씨한테 전해 주고 싶을 만큼요.' },
        { say: '반은 예금, 반은 투자', tier: 'good', face: 'think', answer: '현명해요. 근데 반 중에 예금이 조금 더 크면 좋겠어요.' },
        { say: '다 투자해야지', tier: 'meh', face: 'sorry', answer: '…무잔 씨가 기뻐하겠네요. 저는 장부를 조용히 덮을게요.' },
      ],
    },
    {
      id: 'nose',
      open: '{me} 님, 오늘 아침에 빵 드셨죠. 버터 들어간 거요. 냄새로 알아요.',
      replies: [
        { say: '와, 맞아! 코가 대단하다', tier: 'great', remember: 'nose-test', face: 'laugh', answer: '수인이니까요. 금고 안에 지폐가 몇 장인지도 냄새로… 반쯤은 농담이에요.' },
        { say: '좀 무서운데', tier: 'good', face: 'sorry', answer: '아, 죄송해요. 아무한테나 안 해요. {me} 님 냄새는 익숙해서요.' },
        { say: '아닌데, 떡이었어', tier: 'meh', face: 'think', answer: '…떡이었어요? 버터 떡이었을 거예요. 그렇다고 해 줘요.' },
      ],
    },
    {
      id: 'moon',
      open: '보름달 뜨는 밤엔 좀 들떠요. 목이 간질간질해요. 근무 중이라 참지만요.',
      replies: [
        { say: '참지 말고 한 번 불러 봐', tier: 'great', remember: 'moon-howl', face: 'shy', answer: '…은행에서요? 안 돼요. 언젠가 아무도 없는 데서라면 몰라도요.' },
        { say: '달 보면 기분 좋지', tier: 'good', face: 'smile', answer: '네. 결산 끝난 밤에 보는 달이 제일 좋아요. 보통 새벽이지만요.' },
        { say: '그냥 감기 아니야?', tier: 'meh', face: 'think', answer: '…그럴 수도 있어요. 수인 감기는 귀부터 와요.' },
      ],
    },
    {
      id: 'games',
      open: '쉬는 날에 게임을 시작했는데요, 정신 차려 보니 출근 시간이었어요.',
      replies: [
        { say: '무슨 게임인데? 나도 할래', tier: 'great', remember: 'game-night', face: 'wow', answer: '…같이 해 줘요? 마을 키우는 게임이에요. 은행도 지었어요.' },
        { say: '그래서 오늘 졸린 거구나', tier: 'good', face: 'sorry', answer: '들켰어요. 커피 세 잔째예요. 장부는 맞았어요. 아마요.' },
        { say: '게임은 시간 낭비 아니야?', tier: 'meh', answer: '저축이에요. 추억 저축. 이자는 좀 이상하게 붙지만요.' },
      ],
    },
    {
      id: 'films',
      open: '영화 볼 때 생선 나오는 장면만 기억나요. 줄거리는 친구가 말해 줘요.',
      replies: [
        { say: '그래도 즐거우면 됐지', tier: 'great', face: 'laugh', answer: '…그쵸. 이 말 장부 맨 앞장에 적어 둘게요.' },
        { say: '나랑 같이 보면 줄거리 말해 줄게', tier: 'good', face: 'shy', answer: '…생선 장면에선 조용히 해 줘요. 집중해야 하니까요.' },
        { say: '그건 영화를 안 본 거야', tier: 'meh', face: 'sorry', answer: '…맞아요. 저는 생선을 본 거예요.' },
      ],
    },
    {
      id: 'ledger-page',
      when: { ch: 3 },
      open: '{me} 님, 제 장부 맨 뒷장 본 적 있어요? …아니에요. 거긴 업무용이 아니라서요.',
      replies: [
        { say: '뭐라고 적혀 있는지 궁금하다', tier: 'great', face: 'shy', answer: ['{me} 님 이름이요. 날짜랑. 이자는 안 적었어요.', '…셀 수가 없어서요. 못 본 걸로 해요.'] },
        { say: '비밀 장부야?', tier: 'good', face: 'think', answer: '비밀이라기보다… 금고에 넣기엔 너무 자주 펼쳐 보는 장부예요.' },
        { say: '업무 아니면 됐어', tier: 'meh', answer: '네. 됐어요. …조금 아쉽지만요.' },
      ],
    },
    {
      id: 'dating-lunch',
      when: { love: 'dating' },
      open: '{me} 님, 오늘 점심은 고등어 두 마리예요. 하나는 {me} 님 거예요.',
      replies: [
        { say: '가시는 내가 발라 줄게', tier: 'great', face: 'shy', answer: '…그럼 저는 접시를 데워 둘게요. 꼬리는 못 본 걸로 해요.' },
        { say: '둘 다 나모가 먹어', tier: 'good', face: 'laugh', answer: '안 돼요. 같이 먹는 게 이자예요. 맛이 두 배가 되거든요.' },
        { say: '난 고기가 좋은데', tier: 'meh', face: 'sorry', answer: '…그럼 다음엔 고기도 하나 살게요. 고등어 옆에요.' },
      ],
    },
    {
      id: 'lab-days',
      open: ['은행 오기 전엔 연구실에 있었어요. 밤새 자료 정리하는 곳이요.', '…지금이랑 뭐가 다르냐고 물으면 할 말이 없어요.'],
      replies: [
        { say: '연구실 시절 얘기 더 해 줘', tier: 'great', remember: 'lab-tale', face: 'think', answer: ['교수님 몰래 통조림 따 먹고, 마감 전날엔 다 같이 쓰러지고요.', '힘들었는데요. 이상하게 그리워요. 이자 붙은 추억이에요.'] },
        { say: '그래서 야근에 강하구나', tier: 'good', face: 'laugh', answer: '강한 게 아니라 익숙한 거예요. 몸은 아직도 싫대요.' },
        { say: '공부가 싫어서 그만뒀어?', tier: 'meh', face: 'sorry', answer: '…싫진 않았어요. 장부가 좀 더 좋았을 뿐이에요. 맞아떨어지니까요.' },
      ],
    },
    {
      id: 'bread-papers',
      open: '신짜장 씨가 가져온 서류를 넘기면 빵가루가 떨어져요. 장부 사이에서요.',
      replies: [
        { say: '서류에 빵 냄새라니 맛있겠다', tier: 'great', face: 'laugh', answer: ['그쵸. 결산서에서 소보로 냄새가 나요.', '덕분에 야근 중에 배가 자꾸 고파요. 이건 손실이에요.'] },
        { say: '한마디 해 주지 그래', tier: 'good', face: 'think', answer: '했어요. 다음 날 서류에서 단팥빵 냄새가 났어요. 메뉴만 바뀌었어요.' },
        { say: '그냥 털어 내면 되잖아', tier: 'meh', face: 'calm', answer: '털었어요. 제 코는 못 털어요.' },
      ],
    },
    {
      id: 'rose-rate',
      open: '미스 포츈 씨가 이자를 또 내렸대요. 저희보다 조금 낮게요. 조금이요.',
      replies: [
        { say: '그래도 나모 장부가 더 믿음 가', tier: 'great', face: 'shy', answer: ['…그 말은 금리보다 세요.', '내일 아침 창구 문, 평소보다 일찍 열게요. 기분이 좋아서요.'] },
        { say: '둘이 이자 싸움 재밌다', tier: 'good', face: 'laugh', answer: '싸움 아니에요. 정확함과 빠름의 차이예요. 저는 정확함 쪽이요.' },
        { say: '그럼 거기로 가야겠다', tier: 'meh', face: 'sorry', answer: '…가세요. 대신 계약서는 꼭 세 번 읽어요. 그분 글씨가 작아요.' },
      ],
    },
    {
      id: 'muzan-coffee',
      open: '무잔 씨가 은행에 커피 마시러 와요. 마시면서 투자 얘기를 해요. 제 커피로요.',
      replies: [
        { say: '커피값으로 예금하라고 해', tier: 'great', face: 'laugh', answer: ['…좋은 생각이에요. 장부에 커피 한 잔당 예금 한 칸요.', '다음엔 그렇게 말할게요. 아마 웃기만 하겠지만요.'] },
        { say: '둘이 사이좋아 보이는데', tier: 'good', face: 'think', answer: '금리 얘기로만 사이가 좋아요. 다른 얘기는 해 본 적이 없어요.' },
        { say: '무잔 말이 맞을 때도 있잖아', tier: 'meh', face: 'sorry', answer: '…있어요. 장부엔 안 적어요. 기록이 남으면 안 되니까요.' },
      ],
    },
    {
      id: 'story-cast',
      open: ['요즘 지어내는 이야기에 은행 단골이 나와요. 이름은 아직 없어요.', '혹시… {me} 님 이름 빌려도 돼요? 아, 아무것도 아니에요.'],
      replies: [
        { say: '써도 돼. 멋있게 써 줘', tier: 'great', remember: 'story-cast', face: 'shy', answer: ['…허락받았어요. 귀가 뜨거워요.', '멋있게 쓸게요. 생선도 잘 굽는 걸로요.'] },
        { say: '무슨 역할인데?', tier: 'good', face: 'think', answer: '주인공 옆에서 계단을 같이 올라 주는 역할이에요. 중요한 역할이에요.' },
        { say: '부끄러우니까 빼 줘', tier: 'meh', face: 'sorry', answer: '…네. 그럼 고등어로 바꿀게요. 말하는 고등어요.' },
      ],
    },
    {
      id: 'saving-goal',
      open: '{me} 님, 적금 하나 들어 볼래요? 목표가 있으면 돈이 더 잘 모여요.',
      replies: [
        { say: '좋아. 목표 같이 정해 줘', tier: 'great', remember: 'saving-goal', face: 'laugh', answer: ['…같이요? 좋아요. 장부를 새로 펼게요.', '목표 칸엔 {me} 님 이름이랑 꿈을 적어요. 금액은 그다음이에요.'] },
        { say: '나모는 뭐 모으고 있어?', tier: 'good', face: 'shy', answer: '저는 소설 사려고 모아요. 한정판이요. 이건 비밀 적금이에요.' },
        { say: '적금은 답답해', tier: 'meh', face: 'calm', answer: '답답한 게 장점이에요. 쉽게 못 꺼내니까 쌓이거든요.' },
      ],
    },
    {
      id: 'mild-recipe',
      open: '고등어 조림을 해 봤는데요, 고춧가루 없이 하니까 맛이 비어요. 방법 없을까요?',
      replies: [
        { say: '간장이랑 무로 졸여 봐', tier: 'great', remember: 'mild-recipe', face: 'wow', answer: ['…간장이랑 무요. 받아 적었어요.', '오늘 해 볼게요. 성공하면 {me} 님 몫도 남길게요.'] },
        { say: '그냥 구워 먹는 게 제일이야', tier: 'good', face: 'laugh', answer: '맞아요. 결국 구이로 돌아와요. 고등어는 정직하니까요.' },
        { say: '고춧가루 조금만 넣어', tier: 'meh', face: 'sorry', answer: '…조금이 제일 무서워요. 조금이 늘 많거든요.' },
      ],
    },
    {
      id: 'riddle',
      open: ['머리 좀 쓰는 거 해 볼래요? 수수께끼예요.', '금고는 열수록 비고, 장부는 넘길수록 두꺼워져요. 왜게요?'],
      replies: [
        { say: '나모가 밤마다 일해서?', tier: 'great', remember: 'riddle-win', face: 'laugh', answer: ['…맞혔어요. 정답은 야근이에요.', '사실 수수께끼가 아니라 하소연이었어요. 들켰네요.'] },
        { say: '음… 모르겠어', tier: 'good', face: 'smile', answer: '괜찮아요. 저도 답을 몰라요. 그래서 매일 야근해요.' },
        { say: '그게 무슨 수수께끼야', tier: 'meh', face: 'sorry', answer: '…수인 중에선 머리 좋은 편인데, 수수께끼는 좀 약해요.' },
      ],
    },
    {
      id: 'coffee',
      open: '오늘 커피 몇 잔째인지 세다가 그만뒀어요. 숫자는 잘 세는데요, 이건 무서워서요.',
      replies: [
        { say: '이제 물 마셔. 내가 떠 올게', tier: 'great', remember: 'coffee-care', face: 'shy', answer: ['…잔소리예요? 잔소리 맞네요.', '근데 왜 기분이 좋죠. 물 마실게요.'] },
        { say: '나도 한 잔 줄래?', tier: 'good', face: 'laugh', answer: '좋아요. 그럼 이 잔은 {me} 님 장부에 적을게요. 제 잔 수가 줄어요.' },
        { say: '커피 없인 못 버티지', tier: 'meh', face: 'calm', answer: '그쵸. 그래서 문제예요. 맞장구는 위험해요.' },
      ],
    },
    {
      id: 'ears',
      open: '가끔 손님들이 귀 한번 만져 봐도 되냐고 해요. …{me} 님은 안 물어봐서 좋아요.',
      replies: [
        { say: '허락 없인 안 만질게', tier: 'great', remember: 'ear-manners', face: 'shy', answer: ['…고마워요. 그 말 금고에 넣어 둘게요.', '언젠가 허락할지도요. 아, 지금 말 못 들은 걸로 해요.'] },
        { say: '사실 궁금하긴 했어', tier: 'good', face: 'wow', answer: '…솔직하네요. 그럼 오늘은 보는 것만요. 쫑긋, 이렇게요.' },
        { say: '그냥 귀잖아', tier: 'meh', face: 'think', answer: '그냥 귀예요. 금고 소리도 듣는 그냥 귀요.' },
      ],
    },
    {
      id: 'scent-map',
      open: '눈 감고도 마을을 다닐 수 있어요. 빵집, 대장간, 항구… 냄새로 지도가 있거든요.',
      replies: [
        { say: '그 지도에 나도 있어?', tier: 'great', remember: 'scent-map', face: 'shy', answer: ['…있어요. 은행 바로 옆에 작게요.', '햇볕 냄새예요. 지도에서 제일 자주 들르는 데예요.'] },
        { say: '매운 냄새는 어떻게 표시해?', tier: 'good', face: 'laugh', answer: '빨간 줄로 그어요. 가지 말 것. 주점 뒤 골목이 제일 빨개요.' },
        { say: '눈 뜨고 다니는 게 낫지 않아?', tier: 'meh', face: 'sorry', answer: '…맞아요. 지난번에 눈 감고 걷다 문에 부딪혔어요.' },
      ],
    },
    {
      id: 'harbor-wish',
      open: '항구 어시장이 크게 열리면 좋겠어요. 새벽마다 갓 잡은 고등어가 줄 서 있는 데요.',
      replies: [
        { say: '열리면 첫날 같이 가자', tier: 'great', remember: 'harbor-wish', face: 'wow', answer: ['…약속이에요? 장부에 적었어요. 지울 수 없게요.', '그날은 휴가 낼게요. 은행 생기고 처음으로요.'] },
        { say: '내가 많이 낚아 올게', tier: 'good', face: 'laugh', answer: '그럼 {me} 님이 제 어시장이에요. 개점 축하해요.' },
        { say: '새벽은 너무 이르지', tier: 'meh', face: 'calm', answer: '저는 그 시간에 아직 안 잤으니까 괜찮아요.' },
      ],
    },
    {
      id: 'frieren-book',
      open: '프리렌 씨 통장을 정리했는데요, 처음 넣은 날짜가 은행보다 오래됐어요.',
      replies: [
        { say: '이자가 어마어마하겠다', tier: 'great', remember: 'frieren-calc', face: 'laugh', answer: ['계산하다 장부가 모자랐어요. 두 권 이어 붙였어요.', '본인은 이자가 뭐냐고 물었어요. 그게 제일 놀라웠어요.'] },
        { say: '그걸 어떻게 처리했어?', tier: 'good', face: 'think', answer: '밤새 옛날 서류를 뒤졌어요. 연구실 시절 실력이 살아났어요.' },
        { say: '그냥 새로 만들지', tier: 'meh', face: 'sorry', answer: '…그건 은행원으로서 못 해요. 장부는 이어져야 하거든요.' },
      ],
    },
    {
      id: 'groom',
      open: '그웬 씨 미용실에서 꼬리털 다듬고 왔어요. …아무도 모를 줄 알았는데 물어보네요.',
      replies: [
        { say: '윤기가 나서 바로 알았어', tier: 'great', face: 'shy', answer: ['…알아봐 줬어요. 꼬리가, 아, 못 본 걸로 해요.', '그웬 씨가 칭찬을 너무 해서 계속 흔들렸어요.'] },
        { say: '귀도 다듬었어?', tier: 'good', face: 'laugh', answer: '귀는 안 돼요. 가위 소리가 너무 가까워서 무서워요.' },
        { say: '별로 달라진 건 모르겠는데', tier: 'meh', face: 'sorry', answer: '…그쵸. 저만 아는 차이예요. 장부 끝자리 같은 거요.' },
      ],
    },
    {
      id: 'collect',
      open: '좋아하는 소설 한정판 표지가 나왔대요. 같은 책을 세 권째 사도 이상하지 않죠?',
      replies: [
        { say: '좋아하면 당연하지', tier: 'great', face: 'laugh', answer: ['…같은 편이네요. 장부엔 문화 투자로 적을게요.', '무잔 씨한테 말하면 이건 인정할 거예요. 아마요.'] },
        { say: '한 권은 나 빌려줘', tier: 'good', face: 'think', answer: '빌려 드릴게요. 읽는 용으로요. 보관용은 금고에 있어요.' },
        { say: '그건 좀 낭비 아니야?', tier: 'meh', face: 'sorry', answer: '…예금 이야기에선 제가 할 말인데요. 오늘만은 못 들은 걸로 할게요.' },
      ],
    },
    {
      id: 'vault-key',
      when: { ch: 5 },
      open: '금고 열쇠가 두 개예요. 하나는 제가 갖고, 하나는 아직 서랍에 있어요.',
      replies: [
        { say: '그 하나, 내가 가져도 돼?', tier: 'great', face: 'shy', answer: ['…물어봐 주길 기다렸어요.', '잃어버리지 마요. 저처럼 머리 위에 두지 말고요.'] },
        { say: '예비 열쇠구나', tier: 'good', face: 'think', answer: '예비라기보다… 같이 여는 사람을 위한 거예요.' },
        { say: '열쇠는 잘 챙겨', tier: 'meh', face: 'calm', answer: '네. 하나는 손에, 하나는… 아직 서랍에요.' },
      ],
    },
    {
      id: 'night-shift-pair',
      when: { love: 'dating' },
      open: '{me} 님이 야근 옆에 있어 주면 장부가 빨리 맞아요. 이상하죠. 계산이 안 돼요.',
      replies: [
        { say: '오늘도 옆에 있을게', tier: 'great', face: 'shy', answer: ['…그럼 오늘 야근은 짧게 할게요.', '대신 끝나면 항구까지 걸어요. 천천히요.'] },
        { say: '내가 서류 넘겨 줄게', tier: 'good', face: 'laugh', answer: '거꾸로 든 거 있으면 말해 줘요. 저 자주 그래요.' },
        { say: '야근을 안 하면 되잖아', tier: 'meh', face: 'sorry', answer: '…정답이에요. 근데 그 정답은 장부에 없어요.' },
      ],
    },
  ],
  openers: [
    {
      id: 'op-rain',
      when: { weather: 'rain' },
      open: '비 오는 날은 꼬리털이 눅눅해요. 아, 방금 말은 못 들은 걸로 해요.',
      replies: [
        { say: '수건 빌려줄까?', tier: 'great', face: 'shy', answer: '…고마워요. 창구 뒤에서 몰래 말릴게요. 손님 눈엔 안 띄게요.' },
        { say: '빗소리 좋지 않아?', tier: 'good', face: 'smile', answer: '좋아요. 빗소리 들으며 장부 넘기는 거, 제일 좋아해요.' },
        { say: '털이 많아서 그래', tier: 'meh', face: 'think', answer: '…알아요. 겨울엔 그 털 덕분에 버티니까 참을게요.' },
      ],
    },
    {
      id: 'op-storm',
      when: { weather: 'storm' },
      open: '바람 소리에 귀가 자꾸 납작해져요. 금고는 튼튼한데 저는 안 튼튼해요.',
      replies: [
        { say: '바람 그칠 때까지 같이 있을게', tier: 'great', face: 'shy', answer: '…그럼 귀가 좀 펴질 것 같아요. 의자 하나 더 가져올게요.' },
        { say: '금고에 들어가 있어', tier: 'good', face: 'laugh', answer: '…그 생각 저도 했어요. 진짜로요. 들어가진 않았어요.' },
        { say: '폭풍 별거 아니야', tier: 'meh', face: 'sorry', answer: '{me} 님 귀는 작아서 그래요. 저는 다 들려요.' },
      ],
    },
    {
      id: 'op-snow',
      when: { weather: 'snow' },
      open: '눈 와요. 뛰어나가고 싶은데요… 열 걸음이면 지칠 걸 알아서 창밖만 봐요.',
      replies: [
        { say: '열 걸음만 같이 뛰자', tier: 'great', face: 'laugh', answer: '…열 걸음이요? 좋아요. 열한 걸음째엔 업어 줘야 해요.' },
        { say: '창밖 구경도 좋지', tier: 'good', face: 'smile', answer: '네. 눈 위 발자국 세는 거 좋아해요. 장부 버릇이에요.' },
        { say: '추운데 왜 나가?', tier: 'meh', face: 'think', answer: '수인은 눈 보면 그래요. 이유는 장부에도 없어요.' },
      ],
    },
    {
      id: 'op-night',
      when: { time: 'night' },
      open: '늦었네요. 은행은 닫았는데 저는 아직 안 닫았어요. 서류가 남아서요.',
      replies: [
        { say: '서류 정리 도와줄게', tier: 'great', face: 'wow', answer: '…정말요? 그럼 저는 도장, 아니 도장 찾는 걸 할게요.' },
        { say: '그만하고 집에 가', tier: 'good', face: 'sorry', answer: '조금만요. 이 장만 맞추면… 아까도 그렇게 말했죠.' },
        { say: '나도 잠이 안 와서', tier: 'meh', answer: '그럼 같이 깨어 있어요. 커피는 없어요. 제가 다 마셨어요.' },
      ],
    },
    {
      id: 'op-dawn',
      when: { time: 'dawn' },
      open: '이른 시간이네요. 저는… 퇴근을 안 한 거예요. 결산이라서요.',
      replies: [
        { say: '밤새운 거야? 아침 먹으러 가자', tier: 'great', face: 'wow', answer: '…생선 파는 데로요? 그럼 체력이 조금 남아 있어요.' },
        { say: '새벽 공기 좋지', tier: 'good', face: 'smile', answer: '네. 새벽엔 장부도 조용하고, 고등어 배 냄새도 들어와요.' },
        { say: '눈 밑이 까매', tier: 'meh', face: 'sorry', answer: '…털 색이에요. 그렇다고 해 줘요.' },
      ],
    },
    {
      id: 'op-festival',
      when: { festival: true },
      open: '축제 날엔 은행도 쉬어요. 생선 좌판 돌고, 밀린 소설 읽을 거예요.',
      replies: [
        { say: '좌판 같이 돌자', tier: 'great', face: 'laugh', answer: '좋아요. 꼬치는 제가 살게요. 매운 양념 빼고요.' },
        { say: '오늘은 장부 덮어', tier: 'good', face: 'smile', answer: '네. 오늘만은 덮었어요. …가방에 하나 넣어 오긴 했지만요.' },
        { say: '축제엔 사람 많아서 싫어', tier: 'meh', face: 'think', answer: '저도 냄새가 너무 많아서 코가 바빠요. 조금만 돌아요.' },
      ],
    },
    {
      id: 'op-fish',
      when: { fish: ['mackerel', 'crucian', 'sweetfish', 'horsemackerel'] },
      open: '{me} 님, 오늘 {fish} 낚았죠. 문 열리기 전에 코가 먼저 알았어요.',
      replies: [
        { say: '나모 주려고 낚았지', tier: 'great', face: 'shy', answer: '…꼬리가 멋대로 흔들려요. 못 본 걸로 해요. 정말 고마워요.' },
        { say: '냄새로 그걸 알아?', tier: 'good', face: 'laugh', answer: '수인이니까요. 크기도 대충 알아요. 그건 반쯤 농담이에요.' },
        { say: '팔러 가는 길이야', tier: 'meh', face: 'sorry', answer: '…그렇군요. 좋은 값 받으세요. 귀는 조금 처졌지만요.' },
      ],
    },
    {
      id: 'op-bigfish',
      when: { bigFish: true },
      open: '큰 놈 낚으셨다면서요. 소문이 창구까지 왔어요. 마을 장부에 적을 일이에요.',
      replies: [
        { say: '나모한테 제일 먼저 자랑하고 싶었어', tier: 'great', face: 'shy', answer: '…저한테요? 그럼 제 장부엔 특별 칸을 만들게요.' },
        { say: '운이 좋았어', tier: 'good', face: 'smile', answer: '운도 실력이라고 하던데요. 미스 포츈 씨는 아니라겠지만요.' },
        { say: '손이 아직 떨려', tier: 'meh', face: 'wow', answer: '저도 계단 오르면 떨려요. 그거랑은 다르겠지만요.' },
      ],
    },
    {
      id: 'op-gold',
      when: { gold: true },
      open: '금별 작물을 거두셨다고요. 이건 거의 금고에 넣어야 하는 물건이에요.',
      replies: [
        { say: '나모 금고에 맡길게', tier: 'great', face: 'laugh', answer: '맡아 드릴게요. 이자 대신 매일 한 번씩 보러 와도 돼요.' },
        { say: '시장에 팔 거야', tier: 'good', face: 'smile', answer: '좋은 값 받으세요. 판 돈은 예금하러 오시고요. 꼭이요.' },
        { say: '먹을 거야', tier: 'meh', face: 'think', answer: '…그것도 좋아요. 매운 요리에만 넣지 마세요.' },
      ],
    },
    {
      id: 'op-harvest',
      when: { harvest: true },
      open: '밭일하고 오셨네요. 흙냄새가 나요. 좋은 냄새예요. 생선 다음으로요.',
      replies: [
        { say: '생선 다음이면 일 등이나 마찬가지네', tier: 'great', face: 'laugh', answer: '…맞아요. 생선은 순위 밖이니까요. 영예의 일 등이에요.' },
        { say: '오늘 꽤 많이 거뒀어', tier: 'good', face: 'smile', answer: '수확은 저축이랑 비슷해요. 꾸준히 하면 쌓여요.' },
        { say: '씻고 올게', tier: 'meh', answer: '괜찮아요. 제 코는 흙냄새엔 관대해요. 매운 냄새만 아니면요.' },
      ],
    },
    {
      id: 'op-low',
      when: { mood: 'low' },
      open: '{me} 님, 오늘은 귀가 처져 보여요. …아, 인간은 귀가 안 처지죠. 얼굴이요.',
      replies: [
        { say: '좀 지쳤어', tier: 'great', face: 'sorry', answer: ['그런 날은 장부 덮어요. 저도 덮을게요.', '생선 사탕 하나 드릴게요. 단골 손님 비상용이에요.'] },
        { say: '나모도 늘 지쳐 보여', tier: 'good', face: 'laugh', answer: '…저는 기본값이 그래요. 오늘은 {me} 님이 우선이에요.' },
        { say: '괜찮아', tier: 'meh', face: 'think', answer: '괜찮다는 말은 장부에서 제일 안 맞는 숫자예요. 쉬어요.' },
      ],
    },
    {
      id: 'op-high',
      when: { mood: 'high' },
      open: '오늘 {me} 님 발소리가 가벼워요. 문 열리기 전에 들렸어요. 좋은 일 있어요?',
      replies: [
        { say: '나모 보러 오는 길이라서', tier: 'great', face: 'shy', answer: '…그런 말은 장부에 적을 칸이 없어요. 새로 만들게요.' },
        { say: '그냥 날씨가 좋아서', tier: 'good', face: 'smile', answer: '좋아요. 그 기분 예금해 두세요. 이자 붙여 드릴게요.' },
        { say: '그렇게 티 나?', tier: 'meh', face: 'laugh', answer: '제 귀엔요. 다른 분들은 모를 거예요.' },
      ],
    },
    {
      id: 'op-bday',
      when: { bday: true },
      open: '{me} 님, 오늘 생일이죠. 장부에 동그라미 쳐 뒀어요. …업무용 장부 아니에요.',
      replies: [
        { say: '기억해 줬구나, 고마워', tier: 'great', face: 'shy', answer: ['생일 축하해요.', '생선 모양 사탕, 오늘은 한 봉지 다 드릴게요.'] },
        { say: '케이크는 있어?', tier: 'good', face: 'laugh', answer: '케이크는 없고… 고등어 케이크는 어때요? 농담이에요. 반쯤요.' },
        { say: '생일 별거 아니야', tier: 'meh', face: 'think', answer: '별거예요. 일 년에 한 번 붙는 이자 같은 날이에요.' },
      ],
    },
    {
      id: 'op-wedding',
      when: { news: 'wedding' },
      open: '마을에 결혼 소식이 있대요. 제 머릿속에선 둘의 이야기가 벌써 다섯 권째예요.',
      replies: [
        { say: '마지막 권은 어떻게 끝나?', tier: 'great', face: 'laugh', answer: ['둘이 같은 금고 열쇠를 나눠 갖는 걸로 끝나요.', '…아, 아무것도 아니에요. 지어낸 거예요.'] },
        { say: '축하할 일이네', tier: 'good', face: 'smile', answer: '네. 은행에선 공동 통장을 준비해 둘게요. 업무예요.' },
        { say: '결혼은 아직 먼 얘기야', tier: 'meh', face: 'think', answer: '…그쵸. 저한테도요. 아마도요.' },
      ],
    },
    {
      id: 'op-record',
      when: { news: 'record' },
      open: '오늘 마을 소식 봤어요? 장부에 적을 일이 또 생겼어요. 야근 확정이에요.',
      replies: [
        { say: '야근 간식은 내가 챙길게', tier: 'great', face: 'wow', answer: '…그럼 야근이 조금 덜 길어질 것 같아요. 진짜로요.' },
        { say: '마을이 북적이네', tier: 'good', face: 'smile', answer: '좋은 일이에요. 은행은 바빠지지만 장부가 즐거워해요.' },
        { say: '난 잘 모르겠어', tier: 'meh', answer: '괜찮아요. 제가 요약해 드릴게요. 세 줄이에요. 길어질 수도 있어요.' },
      ],
    },
    {
      id: 'op-sinjjajang',
      when: { bond: 'sinjjajang' },
      open: '신짜장 씨 만났죠. 아까 가져온 서류에서 또 빵 냄새가 났어요. 코는 못 속여요.',
      replies: [
        { say: '서류보다 빵을 먼저 배달했나 봐', tier: 'great', face: 'laugh', answer: '…그런 것 같아요. 다음엔 빵도 같이 배달해 달라고 할까요.' },
        { say: '부지런한 우체부잖아', tier: 'good', face: 'smile', answer: '맞아요. 서류는 늘 제시간이에요. 빵 부스러기도요.' },
        { say: '그냥 기분 탓 아니야?', tier: 'meh', face: 'think', answer: '제 코는 기분을 안 타요. 버터에 밀가루, 확실해요.' },
      ],
    },
    {
      id: 'op-rose',
      when: { bond: 'rose' },
      open: '미스 포츈 씨 창구 다녀왔죠. 이자 얘기 들었어요? 저희가 조금 더 싸요.',
      replies: [
        { say: '나모 창구가 더 따뜻하던데', tier: 'great', face: 'shy', answer: '…따뜻한 건 이자에 안 붙지만, 장부엔 적을게요. 고마워요.' },
        { say: '둘이 경쟁하는 거 재밌어', tier: 'good', face: 'laugh', answer: '경쟁이요? 저는 정확할 뿐이에요. 그분도 그렇게 말하겠지만요.' },
        { say: '포츈 쪽이 빠르던데', tier: 'meh', face: 'sorry', answer: '…빠른 건 인정해요. 저는 계단에서 시간을 좀 써요.' },
      ],
    },
    {
      id: 'op-muzan',
      when: { bond: 'muzan' },
      open: '무잔 씨 만났죠. 또 투자가 최고라고 했겠죠. 예금이 얼마나 든든한데요.',
      replies: [
        { say: '난 나모 편이야', tier: 'great', face: 'shy', answer: '…한 표 얻었어요. 장부에 굵게 적을게요. 무잔 씨한텐 비밀로요.' },
        { say: '둘 다 일리가 있던데', tier: 'good', face: 'think', answer: '공정하네요. 그래도 비 오는 날엔 예금이 우산이에요.' },
        { say: '무잔 말이 그럴듯하던데', tier: 'meh', face: 'sorry', answer: '…그분 말솜씨는 인정해요. 금리는 제가 이길 거예요.' },
      ],
    },
    {
      id: 'op-stockdown',
      when: { recent: 'stockDown' },
      open: '주식이 내려갔다면서요. 예금은 안 내려가요. …지금 말할 건 아니었죠. 미안해요.',
      replies: [
        { say: '아니야, 위로가 돼', tier: 'great', face: 'smile', answer: '…그럼 다행이에요. 손해 본 날엔 생선구이 드세요. 나아져요.' },
        { say: '다음엔 예금할게', tier: 'good', face: 'laugh', answer: '창구는 늘 열려 있어요. 저도요. 야근 중이라서요.' },
        { say: '다시 오를 거야', tier: 'meh', face: 'think', answer: '그러길 바라요. 무잔 씨도 그렇게 말하겠죠.' },
      ],
    },
    {
      id: 'op-cloudy',
      when: { weather: 'cloudy' },
      open: '흐린 날은 이상하게 안 졸려요. 장부가 술술 맞아요. 일 년에 몇 번 없는 날이에요.',
      replies: [
        { say: '그럼 오늘은 칼퇴근이네', tier: 'great', face: 'wow', answer: ['…칼퇴근. 소설에서만 본 단어예요.', '오늘 해 볼게요. 성공하면 장부에 별 그려요.'] },
        { say: '흐린 날 분위기 좋지', tier: 'good', face: 'smile', answer: '네. 추리 소설 속 같아요. 범인은 늘 장부 오차예요.' },
        { say: '난 흐리면 처져', tier: 'meh', face: 'think', answer: '그럼 오늘은 제가 대신 기운 낼게요. 드문 기회예요.' },
      ],
    },
    {
      id: 'op-summer-sun',
      when: { season: 'summer', weather: 'sunny' },
      open: '헥… 더워요. 털옷을 못 벗는 게 수인의 슬픔이에요. 금고 안이 그리워요.',
      replies: [
        { say: '시원한 물 떠 올게', tier: 'great', face: 'shy', answer: ['…고마워요. 혀 내미는 건 참을게요.', '아, 이미 나왔어요. 못 본 걸로 해요.'] },
        { say: '부채질해 줄까?', tier: 'good', face: 'laugh', answer: '좋아요. 장부도 같이 부쳐 주세요. 종이가 땀에 붙어요.' },
        { say: '털 좀 깎아', tier: 'meh', face: 'sorry', answer: '…그웬 씨도 그렇게 말했어요. 겨울을 생각하면 못 깎아요.' },
      ],
    },
    {
      id: 'op-spring',
      when: { season: 'spring', time: 'day' },
      open: '봄이라 털갈이 중이에요. 창구에 털이 날리면 그건 꽃가루예요. 그렇게 해 줘요.',
      replies: [
        { say: '응, 파란 꽃가루네', tier: 'great', face: 'laugh', answer: ['…파란 꽃가루. 좋아요, 그걸로 해요.', '봄엔 마을에 파란 꽃이 핀다고 적어 둘게요.'] },
        { say: '빗질해 줄까?', tier: 'good', face: 'shy', answer: '…그건 너무 사적인 업무예요. 생각은 해 볼게요.' },
        { say: '청소 힘들겠다', tier: 'meh', face: 'sorry', answer: '힘들어요. 서류보다 털이 더 많아요. 요즘은요.' },
      ],
    },
    {
      id: 'op-autumn-evening',
      when: { season: 'autumn', time: 'evening' },
      open: '가을 저녁이에요. 어디서 고등어 굽는 냄새가 나요. 장부가 눈에 안 들어와요.',
      replies: [
        { say: '그 냄새 따라가 보자', tier: 'great', face: 'laugh', answer: ['…업무 시간인데요. 아니, 방금 끝났어요. 가요.', '코가 앞장설게요. 천천히 따라와요.'] },
        { say: '퇴근하고 구워 먹어', tier: 'good', face: 'smile', answer: '그럴게요. 오늘은 야근 대신 고등어예요. 결심했어요.' },
        { say: '난 아무 냄새 안 나는데', tier: 'meh', face: 'think', answer: '인간 코는 짧으니까요. 세 집 건너요.' },
      ],
    },
    {
      id: 'op-winter-night',
      when: { season: 'winter', time: 'night' },
      open: '연말 결산이에요. 은행 불은 저 혼자 켜고 있어요. 밖에 눈 오는 소리까지 들려요.',
      replies: [
        { say: '따뜻한 국 사 왔어. 안 매운 거', tier: 'great', face: 'wow', answer: ['…안 매운 거까지요. 장부보다 정확하네요.', '같이 먹어요. 결산은 국 다 먹고 할게요.'] },
        { say: '같이 장부 맞춰 줄게', tier: 'good', face: 'shy', answer: '…두 사람이 맞추면 한 번에 맞을 것 같아요. 기분이요.' },
        { say: '그러다 쓰러져', tier: 'meh', face: 'sorry', answer: '알아요. 한 장만 더요. …아까도 그렇게 말했죠.' },
      ],
    },
    {
      id: 'op-evening',
      when: { time: 'evening', mood: 'high' },
      open: '금고 문 닫는 시간이에요. 철컥. 이 소리 들으면 하루가 맞아떨어진 기분이에요.',
      replies: [
        { say: '오늘 하루도 수고했어', tier: 'great', face: 'shy', answer: ['…그 말 들으니까 장부가 다 맞은 것 같아요.', '실은 하나 안 맞았어요. 내일 할게요.'] },
        { say: '그 소리 나도 좋다', tier: 'good', face: 'smile', answer: '그쵸. 문 닫히는 소리가 이렇게 좋을 수가 없어요.' },
        { say: '이제 퇴근이야?', tier: 'meh', face: 'calm', answer: '금고만 퇴근이에요. 저는 아니에요.' },
      ],
    },
    {
      id: 'op-fish-any',
      when: { fish: true, time: ['day', 'evening'] },
      open: '{me} 님 손에서 {fish} 냄새가 나요. 아까부터 귀가 그쪽으로만 가요.',
      replies: [
        { say: '구경할래? 싱싱해', tier: 'great', face: 'wow', answer: ['…보기만 할게요. 진짜로요.', '꼬리는 못 본 걸로 해요. 생선 앞에선 어쩔 수 없어요.'] },
        { say: '코가 정말 좋구나', tier: 'good', face: 'laugh', answer: '수인 중에서도 좋은 편이에요. 머리도요. 편이에요.' },
        { say: '씻고 올걸 그랬네', tier: 'meh', face: 'sorry', answer: '아니에요! 씻지 마요. 아, 그런 뜻은 아니고요.' },
      ],
    },
    {
      id: 'op-voyage',
      when: { recent: 'voyage' },
      open: '먼바다 다녀오셨죠. 바다 냄새가 아직 묻어 있어요. 저는 물이 무서워서 못 가요.',
      replies: [
        { say: '다음엔 같이 가자. 손 잡아 줄게', tier: 'great', face: 'shy', answer: ['…손이요? 그럼 배 끝까지는 갈 수 있을지도요.', '생선이 그렇게 많다던데요. 귀가 벌써 갔어요.'] },
        { say: '큰 생선 많더라', tier: 'good', face: 'wow', answer: '…다 듣고 싶어요. 크기, 색, 냄새까지요.' },
        { say: '멀미 나서 힘들었어', tier: 'meh', face: 'sorry', answer: '그쵸. 그래서 저는 항구까지만 가요. 거기가 딱 좋아요.' },
      ],
    },
    {
      id: 'op-casino-win',
      when: { recent: 'casinoWin' },
      open: '카지노에서 따셨다고요. 미스 포츈 씨 쪽 소식은 빨라요. 오늘 바로 예금하러 와요.',
      replies: [
        { say: '그래서 나모한테 왔지', tier: 'great', face: 'laugh', answer: ['…잘 왔어요. 이자 계산은 암산으로 할게요.', '금고가 제일 안전해요. 운은 금고에 안 들어가지만요.'] },
        { say: '조금은 쓰고 싶은데', tier: 'good', face: 'think', answer: '반은 예금, 반은 생선구이 어때요. 균형이 좋아요.' },
        { say: '또 하러 갈 거야', tier: 'meh', face: 'sorry', answer: '…그 말은 장부에 빨간 줄로 적을게요.' },
      ],
    },
    {
      id: 'op-casino-lose',
      when: { recent: 'casinoLose', mood: 'low' },
      open: '카지노에서 잃으셨군요. 귀가 처진 얼굴이에요. 아, 인간은 귀가 안 처지죠.',
      replies: [
        { say: '이번엔 예금할게', tier: 'great', face: 'smile', answer: ['…그 말 기다렸어요. 장부는 다시 시작할 수 있어요.', '새 칸 펼게요. 깨끗한 칸이요.'] },
        { say: '위로해 줘', tier: 'good', face: 'shy', answer: '생선 사탕 두 개 드릴게요. 단골 비상용이에요.' },
        { say: '다음엔 딸 거야', tier: 'meh', face: 'think', answer: '…미스 포츈 씨가 들으면 좋아하겠네요. 저는 아니에요.' },
      ],
    },
    {
      id: 'op-museum',
      when: { recent: 'museum' },
      open: '박물관에 기증하셨다면서요. 혹시 물고기 화석이었어요? 그럼 꼭 보러 갈래요.',
      replies: [
        { say: '물고기 화석 맞아', tier: 'great', face: 'wow', answer: ['…정말요? 냄새는 안 나겠지만 그래도 보고 싶어요.', '쉬는 날에 갈게요. 계단만 없으면요.'] },
        { say: '다른 거였어', tier: 'good', face: 'smile', answer: '그래도 마을 장부에 남을 일이에요. 멋져요.' },
        { say: '박물관 별로야', tier: 'meh', face: 'calm', answer: '조용해서 좋은데요. 소설 읽기 좋은 데예요.' },
      ],
    },
    {
      id: 'op-birthday-news',
      when: { friendNews: 'birthday' },
      open: '오늘 마을에 생일인 분이 있대요. 은행에선 축하 통장을 만들어 드려요. 업무예요.',
      replies: [
        { say: '나모는 생일 언제야?', tier: 'great', face: 'shy', answer: ['…저요? 장부에 적어 두면 잊으니까 안 알려 줄래요.', '농담이에요. 다음에 알려 줄게요. 이자 붙여서요.'] },
        { say: '축하 통장 귀엽다', tier: 'good', face: 'laugh', answer: '통장 표지에 생선 그림을 그려요. 제 취향이에요.' },
        { say: '그냥 축하만 하면 되지', tier: 'meh', face: 'calm', answer: '그것도 좋아요. 저는 표현이 장부로 나와서요.' },
      ],
    },
    {
      id: 'op-with-muzan',
      when: { with: 'muzan' },
      open: '{other} 씨랑 또 금리 얘기 중이었어요. {me} 님, 예금 쪽에 한 표 주세요.',
      replies: [
        { say: '난 늘 예금 편이야', tier: 'great', face: 'laugh', answer: ['…들었죠? 두 표예요. 장부에 굵게요.', '아, 꼬리는 못 본 걸로 해요. 이겨서 그래요.'] },
        { say: '둘이 잘 어울리는데', tier: 'good', face: 'sorry', answer: '…그건 아니에요. 금리만 어울려요.' },
        { say: '투자 쪽 얘기도 듣고 싶어', tier: 'meh', face: 'think', answer: '…공정하시네요. 저는 장부를 조용히 덮을게요.' },
      ],
    },
    {
      id: 'op-with-rose',
      when: { with: 'rose' },
      open: '{other} 씨랑 이자 얘기 하던 중이에요. 싸우는 거 아니에요. 정확함 대결이에요.',
      replies: [
        { say: '나모가 이길 것 같은데', tier: 'great', face: 'shy', answer: ['…그쵸. 저는 계산이 틀린 적이 없어요.', '세 번 다시 보는 것도 실력이에요.'] },
        { say: '둘 다 대단해', tier: 'good', face: 'smile', answer: '그분은 빠르고 저는 정확해요. 마을엔 둘 다 필요해요.' },
        { say: '난 빠진다', tier: 'meh', face: 'calm', answer: '현명해요. 이 대결은 해가 져도 안 끝나요.' },
      ],
    },
    {
      id: 'op-with-sinjjajang',
      when: { with: 'sinjjajang' },
      open: '{other} 씨가 서류를 가져왔어요. …그리고 빵도요. 이번엔 진짜로 빵을요.',
      replies: [
        { say: '드디어 같이 배달됐네', tier: 'great', face: 'laugh', answer: ['…그러니까요. 오늘 서류는 하나도 안 미워요.', '반 나눠 드릴게요. 버터 들어간 거예요.'] },
        { say: '서류는 제대로 왔어?', tier: 'good', face: 'think', answer: '네, 제시간에 왔어요. 빵 부스러기도 제시간이에요.' },
        { say: '빵보다 생선이지', tier: 'meh', face: 'sorry', answer: '…그건 맞는데요. 지금 그 말은 좀 미안해요.' },
      ],
    },
    {
      id: 'op-sulk',
      when: { sulk: true },
      open: '{other} 씨랑 좀 어긋났어요. 장부라면 한 줄씩 다시 맞추면 되는데, 사람은요.',
      replies: [
        { say: '사람도 한 줄씩이면 돼', tier: 'great', face: 'think', answer: ['…한 줄씩. 그렇네요.', '내일 생선 사탕 하나 들고 가 볼게요. 첫 줄이요.'] },
        { say: '무슨 일이었어?', tier: 'good', face: 'sorry', answer: '사소한 거예요. 근데 사소한 게 제일 오래 남아요. 이자처럼요.' },
        { say: '그냥 두면 풀려', tier: 'meh', face: 'calm', answer: '그럴 수도요. 근데 저는 미결 서류를 못 견뎌요.' },
      ],
    },
  ],
  callbacks: [
    {
      id: 'cb-mackerel',
      when: { mem: 'mackerel-fan' },
      use: 'mackerel-fan',
      open: '고등어가 제일이라던 {me} 님. 오늘 시장에 고등어 들어왔대요. 같이 가 볼래요?',
      replies: [
        { say: '좋아, 지금 가자', tier: 'great', face: 'laugh', answer: '…지금요? 장부 덮을게요. 계단은 천천히 내려가요.' },
        { say: '그걸 기억했구나', tier: 'good', face: 'shy', answer: '고등어 얘기는 잊을 수가 없어요. 장부보다 잘 기억해요.' },
        { say: '오늘은 바빠', tier: 'meh', face: 'sorry', answer: '…괜찮아요. 한 마리 사서 반 남겨 둘게요.' },
      ],
    },
    {
      id: 'cb-spicy',
      when: { mem: 'no-spicy' },
      use: 'no-spicy',
      open: '안 매운 거 챙겨 준다던 말, 아직 장부에 있어요. 오늘 점심도 매운 거였어요.',
      replies: [
        { say: '지금 순한 거 사 올게', tier: 'great', face: 'wow', answer: '…정말 사 왔네요. 이 빚은 이자까지 쳐서 갚을게요.' },
        { say: '그 말 기억했어?', tier: 'good', face: 'shy', answer: '은행원은 약속을 잊지 않아요. 특히 먹는 약속은요.' },
        { say: '조금은 먹어 봐', tier: 'meh', face: 'sorry', answer: '…한 숟갈 먹었어요. 귀까지 빨개졌어요.' },
      ],
    },
    {
      id: 'cb-glasses',
      when: { mem: 'glasses-find' },
      use: 'glasses-find',
      open: '{me} 님, 이번엔 안경 어디 있는지 알아요. 머리 위요. …아, 없네요.',
      replies: [
        { say: '목에 걸려 있어', tier: 'great', face: 'shy', answer: '…목걸이 줄을 샀거든요. 그걸 잊었어요. 머리는 좋은데요.' },
        { say: '또 찾아 줄까?', tier: 'good', face: 'laugh', answer: '네. {me} 님은 제 안경 담당이에요. 정식 업무예요.' },
        { say: '안경 하나 더 사', tier: 'meh', face: 'think', answer: '샀어요. 두 개 다 어디 있는지 몰라요.' },
      ],
    },
    {
      id: 'cb-overtime',
      when: { mem: 'overtime-cheer' },
      use: 'overtime-cheer',
      open: '야근 간식 사 온다던 거요. 그 말 듣고 진짜로 장부가 한 번에 맞았어요.',
      replies: [
        { say: '오늘은 진짜 사 왔어', tier: 'great', face: 'wow', answer: '…생선 과자예요? 꼬리가… 못 본 걸로 해요. 고마워요.' },
        { say: '말만으로도 효과가 있네', tier: 'good', face: 'laugh', answer: '그러니까요. {me} 님 말은 이자가 높아요.' },
        { say: '그래도 야근은 줄여', tier: 'meh', face: 'sorry', answer: '노력할게요. 결산이 허락하면요.' },
      ],
    },
    {
      id: 'cb-stories',
      when: { mem: 'story-ears' },
      use: 'story-ears',
      open: '지난번에 들려준 우산 이야기, 넷째 권까지 갔어요. 이번엔 주인공이 은행원이에요.',
      replies: [
        { say: '그 은행원, 혹시 나모야?', tier: 'great', face: 'shy', answer: '…아무것도 아니에요. 지어낸 거예요. 상대역 이름은 아직 비워 뒀어요.' },
        { say: '다섯째 권도 기대할게', tier: 'good', face: 'laugh', answer: '야근 없는 날에 쓸게요. 그러니까… 언젠가요.' },
        { say: '진짜 소설로 내 봐', tier: 'meh', face: 'think', answer: '머릿속에만 있어서 좋은 거예요. 장부랑 반대예요.' },
      ],
    },
    {
      id: 'cb-smart',
      when: { mem: 'smart-wolf' },
      use: 'smart-wolf',
      open: '똑똑하다고 해 줬던 거요. 그날 계산이 진짜 틀렸어요. 세 번 다시 봤어요.',
      replies: [
        { say: '내 탓이네, 미안', tier: 'great', face: 'laugh', answer: '…네, {me} 님 탓이에요. 근데 기분 좋은 오답이었어요.' },
        { say: '그래도 맞췄잖아', tier: 'good', face: 'smile', answer: '맞췄어요. 수인 중에선 머리 좋은 편이니까요. 편이요.' },
        { say: '세 번이나?', tier: 'meh', face: 'sorry', answer: '…네 번이었어요. 거짓말했어요.' },
      ],
    },
    {
      id: 'cb-taste',
      when: { mem: '@taste', noMem: 'taste-heard' },
      open: '{me} 님 좋아하는 게 {taste} 맞죠. 장부 구석에 적어 뒀어요. 업무용 아니에요.',
      replies: [
        { say: '나모 장부에 내가 있네', tier: 'great', remember: 'taste-heard', face: 'shy', answer: '…돈 말고 다른 걸로 적힌 건 {me} 님이 처음이에요.' },
        { say: '그걸 왜 적어?', tier: 'good', remember: 'taste-heard', face: 'think', answer: '언젠가 쓸 데가 있을 것 같아서요. 저축 같은 거예요.' },
        { say: '생선은 아니야', tier: 'meh', remember: 'taste-heard', face: 'sorry', answer: '…알아요. 그래도 고등어 칸은 비워 둘게요.' },
      ],
    },
    {
      id: 'cb-outing',
      when: { mem: '@outing', noMem: 'outing-talk' },
      open: '같이 걸었던 날 기억해요? 제가 세 번 쉬자고 했죠. 사실 네 번이었어요.',
      replies: [
        { say: '난 천천히 걸어서 좋았어', tier: 'great', remember: 'outing-talk', face: 'shy', answer: '…그 말, 금고에 넣어 둘게요. 다음엔 다섯 번 쉬어도 돼요?' },
        { say: '다음엔 업어 줄게', tier: 'good', remember: 'outing-talk', face: 'laugh', answer: '…그건 소설에서나 나오는 장면이에요. 좀 기대할게요.' },
        { say: '네 번이었어?', tier: 'meh', remember: 'outing-talk', face: 'sorry', answer: '네. 한 번은 몰래 쉬었어요. 못 본 걸로 해요.' },
      ],
    },
    {
      id: 'cb-bday',
      when: { mem: '@bday-soon', noMem: 'bday-heard' },
      open: '{me} 님 생일 곧이죠. 장부 달력에 표시해 뒀어요. 날짜 계산은 자신 있어요.',
      replies: [
        { say: '기억해 주는 거야?', tier: 'great', remember: 'bday-heard', face: 'shy', answer: '…네. 그날은 야근 안 할게요. 장부에도 그렇게 적었어요.' },
        { say: '선물은 고등어로 줘', tier: 'good', remember: 'bday-heard', face: 'laugh', answer: '그건 제가 받고 싶은 거예요. 다른 걸로 고민해 볼게요.' },
        { say: '굳이 안 챙겨도 돼', tier: 'meh', remember: 'bday-heard', face: 'think', answer: '챙길 거예요. 은행원은 기념일을 놓치지 않아요.' },
      ],
    },
    {
      id: 'cb-date',
      when: { mem: '@date', noMem: 'date-heard' },
      open: '{me} 님 방에 갔던 날요. 책장 소설 제목, 아직 다 외우고 있어요.',
      replies: [
        { say: '다음엔 나모가 고른 책 꽂아 둘게', tier: 'great', remember: 'date-heard', face: 'shy', answer: ['…그럼 제 책이 {me} 님 방에 사는 거네요.', '좋아요. 한정판 말고 읽는 용으로 가져갈게요.'] },
        { say: '그날 꼬리 다 봤어', tier: 'good', remember: 'date-heard', face: 'wow', answer: '…못 본 걸로 하기로 했잖아요. 장부엔 안 적었어요.' },
        { say: '책장은 정리 안 했는데', tier: 'meh', remember: 'date-heard', face: 'laugh', answer: '알아요. 저도 안 했어요. 그래서 편했어요.' },
      ],
    },
    {
      id: 'cb-novel',
      when: { mem: 'novel-pal', noMem: 'novel-asked' },
      open: '같이 소설 얘기했던 거요. 그 추리 소설, 둘째 권이 나왔어요. 범인이 또 은행원이에요.',
      replies: [
        { say: '이번에도 나모 아니지?', tier: 'great', remember: 'novel-asked', face: 'laugh', answer: ['…저 아니에요. 저는 장부를 맞추는 쪽이에요.', '다 읽으면 빌려 드릴게요. 결말은 말 안 할게요.'] },
        { say: '다 읽으면 빌려줘', tier: 'good', remember: 'novel-asked', face: 'smile', answer: '네. 생선 기름 안 묻게 읽을게요. 약속이에요.' },
        { say: '은행원이 왜 자꾸 범인이야', tier: 'meh', remember: 'novel-asked', face: 'think', answer: '…장부를 다 아니까요. 은행원은 무서운 직업이에요.' },
      ],
    },
    {
      id: 'cb-slow-walk',
      when: { mem: 'slow-walk' },
      use: 'slow-walk',
      open: '계단 천천히 같이 오르자던 말요. 오늘 서류실 갈 일이 있는데… 시간 돼요?',
      replies: [
        { say: '응, 한 칸씩 같이 가자', tier: 'great', face: 'shy', answer: ['…한 칸씩. 그럼 오늘은 한 번만 쉴게요.', '아, 두 번이에요. 거짓말 못 하겠어요.'] },
        { say: '내가 서류 들어 줄게', tier: 'good', face: 'laugh', answer: '그럼 저는 숨만 쉬면 되네요. 그게 제일 어려워요.' },
        { say: '혼자 다녀와도 되잖아', tier: 'meh', face: 'sorry', answer: '…되죠. 근데 같이 가면 계단이 짧아져요. 계산상으론요.' },
      ],
    },
    {
      id: 'cb-tail',
      when: { mem: 'tail-secret' },
      use: 'tail-secret',
      open: '꼬리 못 본 걸로 해 준 거요. 그 뒤로 {me} 님 앞에선 좀 덜 숨겨요.',
      replies: [
        { say: '숨기지 않아도 돼', tier: 'great', face: 'shy', answer: ['…그럼 오늘은 바람 핑계 안 댈게요.', '아, 지금 흔들리는 건 진짜 바람이에요. 아마요.'] },
        { say: '그래서 요즘 잘 흔들리는구나', tier: 'good', face: 'laugh', answer: '…들켰어요. 이 비밀도 금고에 넣어 주세요.' },
        { say: '난 이미 다 알았는데', tier: 'meh', face: 'sorry', answer: '…알면서 못 본 척해 준 거였어요? 더 부끄러워요.' },
      ],
    },
    {
      id: 'cb-saver',
      when: { mem: 'saver' },
      use: 'saver',
      open: '예금이 든든하다고 했던 거, 무잔 씨한테 말했어요. 표정이 굳더라고요.',
      replies: [
        { say: '잘했어. 우리 편이 이겼네', tier: 'great', face: 'laugh', answer: ['…우리 편. 좋은 말이에요.', '장부에 동맹이라고 적을게요. 무잔 씨한텐 비밀로요.'] },
        { say: '무잔이 뭐래?', tier: 'good', face: 'think', answer: '그건 아직 몰라서 하는 소리래요. 저는 아직 몰라도 든든해요.' },
        { say: '굳이 말할 필요 있었어?', tier: 'meh', face: 'sorry', answer: '…있었어요. 금리 논쟁은 근거가 필요하거든요. {me} 님이 근거였어요.' },
      ],
    },
    {
      id: 'cb-nose',
      when: { mem: 'nose-test' },
      use: 'nose-test',
      open: '코가 대단하다고 해 준 뒤로 연습했어요. {me} 님, 오늘 점심 맞혀 볼까요?',
      replies: [
        { say: '맞혀 봐!', tier: 'great', face: 'laugh', answer: ['…밥이랑 국. 국엔 파가 들었고요.', '그리고 디저트를 숨겼어요. 주머니에요. 맞죠?'] },
        { say: '연습까지 했어?', tier: 'good', face: 'shy', answer: '칭찬받으면 이자를 붙여야 하니까요. 은행원 버릇이에요.' },
        { say: '그건 좀 부끄러워', tier: 'meh', face: 'sorry', answer: '…아, 죄송해요. 그럼 맞힌 건 장부에만 적을게요.' },
      ],
    },
    {
      id: 'cb-moon',
      when: { mem: 'moon-howl' },
      use: 'moon-howl',
      open: '보름달에 한 번 불러 보라고 했던 거요. 어젯밤 아무도 없는 데서 아주 작게 했어요.',
      replies: [
        { say: '다음엔 나도 듣고 싶어', tier: 'great', face: 'shy', answer: ['…{me} 님 앞에선 더 작게 될 것 같아요.', '그래도 생각해 볼게요. 다음 보름달까지요.'] },
        { say: '기분 좋았어?', tier: 'good', face: 'smile', answer: '네. 장부 한 권을 덮은 기분이었어요. 시원했어요.' },
        { say: '누가 들었으면 어떡해', tier: 'meh', face: 'sorry', answer: '…다음 날 신짜장 씨가 개 짖는 소리 들었냐고 물었어요.' },
      ],
    },
    {
      id: 'cb-game',
      when: { mem: 'game-night' },
      use: 'game-night',
      open: '그 마을 키우는 게임요. 제 마을 은행이 너무 커져서 집이 들어갈 데가 없어요.',
      replies: [
        { say: '내 마을이랑 이어 보자', tier: 'great', face: 'wow', answer: ['…같이 하는 거예요? 은행 하나로 두 마을을 맡을게요.', '이번 주말은 밤새면 안 되는데요. 이미 안 될 것 같아요.'] },
        { say: '은행만 짓고 있었구나', tier: 'good', face: 'laugh', answer: '은행이랑 생선 가게요. 주민은 아직 두 명이에요.' },
        { say: '그 시간에 좀 자', tier: 'meh', face: 'sorry', answer: '…맞는 말이에요. 저장하고 잘게요. 한 판만 더 하고요.' },
      ],
    },
    {
      id: 'cb-mackerel-gift',
      when: { mem: 'mackerel-gift' },
      use: 'mackerel-gift',
      open: '{me} 님이 가져온 고등어 있잖아요. 그 맛을 장부처럼 다 기억해요. 아직도요.',
      replies: [
        { say: '또 가져올게', tier: 'great', face: 'laugh', answer: ['…꼬리, 이번엔 안 숨길게요.', '굽는 건 제가 해요. 창문은 열고요.'] },
        { say: '기름이 잘 올랐었지', tier: 'good', face: 'wow', answer: '네, 등이 반짝였어요. 생선 장면은 잊을 수가 없어요.' },
        { say: '그냥 시장에서 산 건데', tier: 'meh', face: 'calm', answer: '어디서 왔든 {me} 님 손으로 온 게 중요해요.' },
      ],
    },
    {
      id: 'cb-moon-hill',
      when: { mem: 'moon-hill' },
      use: 'moon-hill',
      open: '뒷산에서 달 봤던 밤요. 그날 내려와서 장부를 펴니까 처음으로 졸리지 않았어요.',
      replies: [
        { say: '다음 보름에도 같이 가자', tier: 'great', face: 'shy', answer: ['…네. 이번엔 두 번만 쉴게요.', '목표예요. 체력 적금이에요.'] },
        { say: '달 기운이었나 봐', tier: 'good', face: 'think', answer: '그럴지도요. 아니면 같이 올라간 기운이거나요.' },
        { say: '그래서 또 야근했어?', tier: 'meh', face: 'sorry', answer: '…네. 기운을 그렇게 써 버렸어요.' },
      ],
    },
    {
      id: 'cb-lab',
      when: { mem: 'lab-tale' },
      use: 'lab-tale',
      open: '연구실 친구한테서 편지가 왔어요. 아직도 통조림으로 버틴대요. 반가워서 웃었어요.',
      replies: [
        { say: '고등어 한 상자 보내 주자', tier: 'great', face: 'laugh', answer: ['…진짜 고등어로요? 받으면 울 거예요. 걔도 저도요.', '주소는 제가 쓸게요. 거꾸로 안 쓰게 봐 줘요.'] },
        { say: '그 친구도 보고 싶겠다', tier: 'good', face: 'shy', answer: '…조금요. 마을 얘기 쓰다 보니 {me} 님 얘기만 썼어요.' },
        { say: '답장은 했어?', tier: 'meh', face: 'sorry', answer: '…쓰고 있어요. 결산 끝나면요. 그러니까 언젠가요.' },
      ],
    },
    {
      id: 'cb-cast',
      when: { mem: 'story-cast' },
      use: 'story-cast',
      open: '{me} 님 이름 빌린 이야기요. 그 인물이 자꾸 제가 안 쓴 대사를 해요. 멋대로요.',
      replies: [
        { say: '뭐라고 하는데?', tier: 'great', face: 'shy', answer: ['…"계단은 같이 오르자." 그런 거요.', '아, 아무것도 아니에요. 지어낸 거예요. 진짜로요.'] },
        { say: '인물이 살아 있는 거네', tier: 'good', face: 'wow', answer: '그쵸. 장부는 제 말을 듣는데 소설은 안 들어요.' },
        { say: '나 그런 말 안 해', tier: 'meh', face: 'laugh', answer: '알아요. 그러니까 지어낸 거예요.' },
      ],
    },
    {
      id: 'cb-saving',
      when: { mem: 'saving-goal' },
      use: 'saving-goal',
      open: '같이 정한 적금 목표요. 장부 보니까 벌써 반을 넘었어요. 제가 더 신나요.',
      replies: [
        { say: '나모 덕분이야', tier: 'great', face: 'shy', answer: ['…아니에요. {me} 님이 꾸준해서예요.', '그래도 칭찬은 금고에 넣어 둘게요.'] },
        { say: '나머지 반도 같이 보자', tier: 'good', face: 'laugh', answer: '네. 만기 날은 생선구이로 축하해요.' },
        { say: '벌써 깨고 싶은데', tier: 'meh', face: 'sorry', answer: '…안 돼요. 그 말은 못 들은 걸로 할게요. 은행원으로서요.' },
      ],
    },
    {
      id: 'cb-recipe',
      when: { mem: 'mild-recipe' },
      use: 'mild-recipe',
      open: '간장에 무 넣고 고등어 졸이라던 거, 해 봤어요. …성공했어요. {me} 님 몫 남겼어요.',
      replies: [
        { say: '지금 먹으러 갈게', tier: 'great', face: 'laugh', answer: ['…밥도 해 둘게요. 아, 밥솥 어디 뒀지.', '찾았어요. 손에 들고 있었어요.'] },
        { say: '진짜 해 봤구나', tier: 'good', face: 'shy', answer: '받아 적은 건 다 해 봐요. 장부랑 같아요.' },
        { say: '나도 레시피 까먹었어', tier: 'meh', face: 'think', answer: '괜찮아요. 제가 장부에 적어 뒀으니까요.' },
      ],
    },
    {
      id: 'cb-coffee',
      when: { mem: 'coffee-care' },
      use: 'coffee-care',
      open: '물 마시라던 잔소리요. 그날부터 커피 한 잔에 물 한 잔씩 마셔요. 장부처럼요.',
      replies: [
        { say: '잘했어. 칭찬해', tier: 'great', face: 'shy', answer: ['…칭찬받았어요. 꼬리가 아, 못 본 걸로 해요.', '오늘은 물 한 잔 더 마실게요.'] },
        { say: '그럼 커피도 두 배야?', tier: 'good', face: 'laugh', answer: '…예리하네요. 회계 감사관 하셔도 되겠어요.' },
        { say: '난 그런 말 했었나', tier: 'meh', face: 'calm', answer: '했어요. 저는 다 적어 둬요. 장부에요.' },
      ],
    },
    {
      id: 'cb-harbor',
      when: { mem: 'harbor-wish' },
      use: 'harbor-wish',
      open: '어시장 열리면 첫날 같이 가자던 약속요. 아직 안 열렸지만 매일 장부에서 확인해요.',
      replies: [
        { say: '열리면 제일 먼저 알려 줄게', tier: 'great', face: 'wow', answer: ['…그럼 저는 귀를 항구 쪽으로 세워 둘게요.', '휴가 신청서는 이미 써 놨어요. 날짜만 비어 있어요.'] },
        { say: '그 전에 항구 산책은 어때?', tier: 'good', face: 'smile', answer: '좋아요. 고등어 배 냄새만 맡고 와도 행복해요.' },
        { say: '언제 열릴지 모르겠다', tier: 'meh', face: 'calm', answer: '괜찮아요. 기다리는 것도 적금 같아요.' },
      ],
    },
    {
      id: 'cb-ears',
      when: { mem: 'ear-manners' },
      use: 'ear-manners',
      open: '허락 없인 귀 안 만진다고 했던 거요. …그 약속, 오늘은 좀 풀어도 돼요.',
      replies: [
        { say: '정말? 살짝만 만질게', tier: 'great', face: 'shy', answer: ['……', '…생각보다 부드럽죠. 못 본 걸로, 아니 못 만진 걸로 해요.'] },
        { say: '천천히 해도 돼', tier: 'good', face: 'smile', answer: '…그 말이 더 고마워요. 그럼 다음에요. 꼭이요.' },
        { say: '난 괜찮아', tier: 'meh', face: 'sorry', answer: '…그렇군요. 귀가 조금 처졌어요. 이건 진짜 바람 탓 아니에요.' },
      ],
    },
  ],
  chapters: [
    {
      title: '창구의 새 장부',
      hint: '한 번 이야기를 나누면 나모가 새 장부를 펼쳐요.',
      need: { days: 1 },
      scene: [
        '범마을 은행. 창구 위에 서류가 산처럼 쌓여 있다.',
        '서류 산 너머로 푸른 머리카락과 뾰족한 귀 한 쌍이 보인다.',
        '나모가 창구에서 고개를 든다. 안경은 머리 위에 걸려 있다.',
        '"어서 와요. 처음 오셨죠. 나모예요. 범마을 은행원이에요."',
        '목소리는 차분하고, 눈매는 날카롭다. 일 잘하는 사람 같다.',
        '그녀가 새 장부를 펼치고 도장을 찾는다. 서랍, 금고, 장부 사이.',
        '도장은 처음부터 그녀 손에 들려 있다.',
        '"…아, 여기 있었네요. 못 본 걸로 해요."',
        '귀 끝이 살짝 붉어진다. 그녀는 아무렇지 않은 척 도장을 찍는다.',
        '"{me} 님. 이름 적었어요. 장부는 한 번에 맞추는 게 제 규칙이에요."',
        '"예금, 인출, 보관함. 모르는 건 다 물어봐요. 설명은 자신 있어요."',
        '"조금 길 뿐이에요." 그녀의 꼬리가 의자 뒤에서 한 번 흔들린다.',
      ],
      replies: [
        { say: '잘 부탁해, 나모', tier: 'great', face: 'smile', answer: '네, 잘 부탁해요. 귀가 쫑긋했어요. 반가워서요.' },
        { say: '도장, 손에 있어', tier: 'good', face: 'shy', answer: '…알아요. 방금 찾았어요. 그러니까 못 본 걸로요.' },
        { say: '은행은 처음이야', tier: 'meh', face: 'calm', answer: '괜찮아요. 설명은 자신 있어요. 조금 길 뿐이에요.' },
      ],
    },
    {
      title: '뒷산의 보름달',
      hint: '밤(게임 시각 밤 여덟 시부터 자정 전까지) 뒷산에 올라 보세요. 나모가 달을 보러 온대요.',
      need: { days: 3, points: 20, visit: { area: 'hill', from: 20, to: 24 } },
      scene: [
        '밤의 뒷산. 풀벌레 소리 사이로 거친 숨소리가 들린다.',
        '꼭대기 바위에 나모가 앉아 숨을 고르고 있다. 가방엔 장부가 있다.',
        '"헥, 헥… 아, {me} 님. 올라오는 데 세 번 쉬었어요."',
        '"…네 번이요. 한 번은 몰래 쉬었어요. 장부엔 안 적어요."',
        '"보름달은 은행 창문으로 늘 봤는데요. 오늘은 가까이서 보고 싶었어요."',
        '구름이 걷히고 둥근 달이 떠오른다. 마을 지붕들이 은빛이 된다.',
        '나모의 귀가 곧게 선다. 꼬리가 천천히, 크게 흔들린다.',
        '그녀가 목을 들었다가, 입을 꾹 다문다.',
        '"…참았어요. 여기선 소리가 마을까지 내려가거든요."',
        '"연구실 시절엔 옥상에서 달 보면서 마감했어요. 혼자서요."',
        '"그래도 이 달은 그때랑 달라요. 혼자보단 낫고요."',
        '바람이 분다. 그녀의 푸른 머리카락과 꼬리털이 같이 흔들린다.',
      ],
      replies: [
        { say: '참지 마. 나만 들을게', tier: 'great', remember: 'moon-hill', face: 'shy', answer: ['…아주 작게요. 정말 작게요.', '…못 들은 걸로 해요. 아니, 들은 걸로 해 줘요.'] },
        { say: '달 진짜 밝다', tier: 'good', remember: 'moon-hill', face: 'smile', answer: '네. 결산 끝난 밤 같은 달이에요. 마음이 맞아떨어져요.' },
        { say: '내려갈 땐 업어 줄까?', tier: 'meh', remember: 'moon-hill', face: 'laugh', answer: '…내리막은 괜찮아요. 아마요. 손만 잡아 줘요.' },
      ],
    },
    {
      title: '고등어 한 마리',
      hint: '나모는 생선 중에서도 고등어를 제일 좋아해요. 고등어 한 마리를 가지고 찾아가 보세요.',
      need: { days: 6, points: 40, bring: { item: 'mackerel', take: true } },
      scene: [
        '점심시간의 은행. 나모가 창구에 엎드려 장부를 베고 졸고 있다.',
        '문이 열리자마자 그녀의 코가 먼저 움직인다. 눈은 아직 감겨 있다.',
        '"…고등어예요. 맞죠. 등 푸른 거, 기름 오른 거."',
        '그제야 눈을 뜬다. 볼에 장부 줄무늬가 찍혀 있다.',
        '고등어를 내밀자 꼬리가 의자 뒤에서 마구 흔들린다.',
        '"아, 이건… 바람이에요. 아니, 못 본 걸로 해요."',
        '그녀가 고등어를 두 손으로 받는다. 서류보다 조심스럽게.',
        '"사실 연구실 시절엔 고등어 통조림으로 버텼어요. 마감 때마다요."',
        '"밤새 자료 정리하고, 새벽에 통조림 따고. 그게 제일 좋은 시간이었어요."',
        '"마을에 와서도 똑같을 줄 알았어요. 장부, 야근, 통조림."',
        '"오늘은 통조림이 아니라 진짜예요. {me} 님이 가져온 진짜."',
        '그녀가 창구 서랍에서 작은 석쇠를 꺼낸다. 언제부터 있었을까.',
      ],
      replies: [
        { say: '같이 구워 먹자', tier: 'great', remember: 'mackerel-gift', face: 'laugh', answer: '…네! 굽는 건 제가 할게요. 연기는 창문 열고요. 은행이니까요.' },
        { say: '통조림 시절 이야기 해 줘', tier: 'good', remember: 'mackerel-gift', face: 'think', answer: '밤새 논문 쓰고, 새벽에 통조림 따고… 지금이랑 별로 안 다르네요.' },
        { say: '그냥 생선이야', tier: 'meh', remember: 'mackerel-gift', face: 'calm', answer: '…그냥 생선이 제일 좋은 선물일 때도 있어요. 고마워요.' },
      ],
    },
    {
      title: '덮지 못한 소설',
      hint: '나모와 소설 이야기를 같이 해 보세요. 읽는 책을 물어보면 다음 이야기가 열려요.',
      need: { days: 9, points: 60, mem: 'novel-pal' },
      scene: [
        '퇴근한 은행. 불은 창구 위 하나만 켜져 있다.',
        '나모가 장부 대신 두꺼운 공책을 펼치고 있다. 안경은 코끝에 있다.',
        '문 여는 소리에 귀가 먼저 돌아가고, 공책이 탁 덮인다.',
        '"아, {me} 님. 이건… 업무용이 아니에요."',
        '잠깐의 침묵. 그녀가 천천히 공책을 다시 연다.',
        '"제가 쓰는 소설이에요. 마을 사람들로 지어낸 이야기요."',
        '"광장에서 우산 하나 같이 쓰던 두 분. 서류에서 빵 냄새 나는 우체부."',
        '"이자로 싸우는 창구 둘, 예금과 투자로 싸우는 창구 둘."',
        '"대부분 아무것도 아닌 이야기예요. 그래서 좋아요."',
        '"장부는 틀리면 안 되는데, 이건 틀려도 돼요. 제가 고치면 되니까요."',
        '그녀가 마지막 장을 넘긴다. 주인공 칸 옆이 비어 있다.',
        '"…이 칸은 아직 못 채웠어요. 누굴 쓸지 알 것 같은데, 펜이 안 움직여요."',
        '꼬리가 의자 아래에서 조용히 바닥을 쓴다.',
      ],
      replies: [
        { say: '천천히 써도 돼. 기다릴게', tier: 'great', face: 'shy', answer: '…기다려 준대요. 그럼 이 소설은 끝까지 쓸 수 있을 것 같아요.' },
        { say: '내가 거기 들어가도 돼?', tier: 'good', face: 'wow', answer: '…그건 작가 마음이에요. 그리고 작가는 지금 귀가 뜨거워요.' },
        { say: '마을 사람들이 알면 어떡해', tier: 'meh', face: 'sorry', answer: '…그래서 금고에 넣어 둬요. 비밀번호는 아무도 몰라요.' },
      ],
    },
    {
      title: '금고의 빈 칸',
      hint: '나모와 아주 가까워지면 그녀가 금고 속 장부를 보여 줘요. 그 뒤엔 꽃다발도 반길지 몰라요.',
      need: { days: 13, points: 96 },
      scene: [
        '결산이 끝난 밤. 나모가 드물게 일찍 장부를 덮는다.',
        '"오늘은 한 번에 맞았어요. {me} 님한테 보여 줄 게 있어요."',
        '나모가 은행 금고 문을 연다. 철컥, 소리에 귀가 쫑긋한다.',
        '금화와 서류 상자 사이, 안쪽 선반에 얇은 장부 하나가 따로 놓여 있다.',
        '"{me} 님 이름 적힌 장부예요. 업무용이 아니라서 여기 뒀어요."',
        '펼친 장에는 날짜가 줄줄이 적혀 있다. 처음 만난 날, 달 본 날, 고등어.',
        '금액 칸은 모두 비어 있다.',
        '"날마다 이자가 붙어요. 마음 쪽 이자요. 계산이 안 끝나요."',
        '"머리 좋은 편이라고 했죠. 이것만은 아무리 해도 답이 안 나와요."',
        '그녀가 장부를 가슴께에 안는다. 귀가 천천히 뒤로 눕는다.',
        '"…요즘엔 꽃 냄새만 맡아도 꼬리가 먼저 반응할 것 같아요."',
        '"누가 꽃다발이라도 들고 오면, 꼬리를 숨길 자신이 없어요."',
        '"아, 아무것도 아니에요. 지어낸 거예요. …이번엔 아니에요."',
      ],
      replies: [
        { say: '그 꼬리, 보고 싶은데', tier: 'great', face: 'shy', answer: '…그럼 숨기지 않을게요. 꽃 냄새가 나면 문 앞까지 마중 나갈게요.' },
        { say: '그 장부, 나도 보고 싶어', tier: 'good', face: 'wow', answer: '…아직은 결산 중이에요. 다 맞으면 제일 먼저 보여 드릴게요.' },
        { say: '꽃 알레르기 있어?', tier: 'meh', face: 'laugh', answer: '…없어요. 그런 얘기가 아니었어요. 못 들은 걸로 해요.' },
      ],
    },
    {
      title: '평생 예금',
      hint: '나모와 연인이 되면 마지막 이야기가 열려요.',
      need: { days: 16, love: 'dating' },
      scene: [
        '저녁 은행. 창밖으로 노을이 금고 문을 금빛으로 물들인다.',
        '오늘 나모는 야근이 없다. 장부도 서랍에 넣어 두었다.',
        '"{me} 님, 잠깐만요. 도장… 아니, 이번엔 손에 있는 거 알아요."',
        '나모가 금고 앞에서 서류 한 장을 내민다. 이번엔 거꾸로가 아니다.',
        '"예금 신청서예요. 이름 칸에 둘 다 적었어요. 만기 칸이 비어 있어요."',
        '"보통은 일 년, 삼 년, 그렇게 적어요. 근데 이건 못 정하겠어요."',
        '"소설에선 이런 장면에 멋진 대사가 나와요. 다 읽었는데 하나도 생각 안 나요."',
        '그녀가 안경을 찾는 척 머리 위를 더듬는다. 안경은 제자리에 있다.',
        '"금고 맨 안쪽 칸은 아직 비어 있어요. 작은 상자 하나 들어갈 크기예요."',
        '"…반지 같은 거요. 아, 아무것도 아니에요. 지어낸 거예요."',
        '"…아니요. 이번엔 지어낸 거 아니에요. 정정할게요."',
        '꼬리가 그녀 등 뒤에서 조용히, 오래 흔들린다. 숨기지 않는다.',
      ],
      replies: [
        { say: '만기는 평생으로 하자', tier: 'great', face: 'shy', answer: ['…평생. 이자 계산이 끝나지 않는 상품이네요.', '좋아요. 도장 찍을게요. 이번엔 손에 있는 거 알아요.'] },
        { say: '그 칸, 내가 채울게', tier: 'good', face: 'wow', answer: '…기다릴게요. 금고 문은 {me} 님한테만 열려 있어요.' },
        { say: '서류가 바로 들려 있네', tier: 'meh', face: 'laugh', answer: '…세 번 확인했어요. 오늘만은 틀리고 싶지 않아서요.' },
      ],
    },
  ],
  after: [
    '오늘 이야기는 했어요. 장부 마저 맞출게요.',
    '또 왔네요. 귀가 먼저 알았어요. 내일 또 와요.',
    '창구는 닫았어요. 저는 아직 야근이에요. 조심히 가요.',
    '못 본 걸로 해요, 꼬리요. 그럼 내일 봐요.',
    '하암… 아, 죄송해요. 잘 가요, {me} 님.',
    '또 오면 이자 붙여서 반겨 줄게요. 오늘은 여기까지요.',
    '계단 조심해요. 저는 여기서 손만 흔들게요. 체력 아껴야 해서요.',
    '이야기 하나 더 떠올랐는데요… 아니에요. 아무것도 아니에요.',
    '생선 냄새 나면 또 들러요. 아니, 안 나도 들러요.',
  ],
};
