// 쓰레쉬 — 시장 거리 잡화점 주인(스물아홉). 상냥하게 웃는 해요체 장사꾼("후후",
// "어머"). 안개 짙은 그림자 군도 출신의 수집광: 등불·사슬·갈고리·초록 불빛·검은
// 안개, 열두 권째 수집 목록과 단골 명단. 손님이 판 물건은 절대 버리지 않는다("제
// 등불 안에 잘 모셔 두죠"). 섬뜩하게 들려도 흥정하고, 주점에서 수다 떨고, 밤
// 해변에서 물건 줍는 동네 사람. 밤과 흐린 날을 좋아하고 해바라기처럼 밝은 건
// 질색. 잔인한 말이나 진짜 위협은 쓰지 않는다. 원작 대사는 쓰지 않는다.
import type { NpcTalkBook } from './types.ts';

export const THRESH_TALK: NpcTalkBook = {
  npc: 'thresh',
  memories: {
    'night-owl': '밤이 좋다고 했어요',
    'day-person': '낮이 더 좋다고 했어요',
    'regular': '단골 명단에 이름을 올리기로 했어요',
    'keep-all': '물건을 버리지 못한다고 했어요',
    'lantern-peek': '등불 안이 궁금하다고 했어요',
    'mist-home': '그림자 군도의 안개 이야기를 들었어요',
    'haggle': '흥정은 웃으면서 하는 거라고 배웠어요',
    'beach-comb': '밤 해변에서 함께 줍기로 했어요',
    'chain-keys': '사슬이 사실 열쇠 꾸러미라고 들었어요',
    'no-sunflower': '해바라기 이야기를 듣고 웃었어요',
    'story-price': '물건값엔 사연이 붙는다고 들었어요',
    'tavern-gossip': '주점 수다 이야기를 들었어요',
    'firefly-woods': '숲에서 반딧불이 등불을 함께 봤어요',
    'shell-gift': '바닷조개를 건넸어요',
    'taste-heard': '내 취향을 수집 목록에 적어 뒀대요',
    'outing-talk': '함께 걸은 날을 이야기했어요',
    'bday-heard': '생일 선물을 골라 두겠대요',
    'archive-keeper': '고향에서 기록 보관소 문지기였대요',
    'lost-found': '분실물 선반을 함께 지키기로 했어요',
    'real-smile': '장사용 말고 진짜 웃음이 좋다고 했어요',
    'fog-walk': '안개 낀 밤엔 등불을 꼭 잡기로 했어요',
    'jar-label': '유리병 이름표를 같이 쓰기로 했어요',
    'winter-love': '긴 겨울밤이 좋다고 했어요',
    'night-fish': '밤에 잡은 물고기를 가져오기로 했어요',
    'fossil-talk': '화석에 담긴 오래된 시간을 이야기했어요',
    'my-collection': '나도 모으는 게 있다고 털어놨어요',
    'ghost-story': '주점의 으스스한 이야기를 들었어요',
    'gwen-truce': '그웬 씨와 화해할 방법을 같이 궁리했어요',
    'green-light': '초록 불빛이 예쁘다고 했어요',
    'clean-day': '봄 대청소 날 같이 돌기로 했어요',
    'cloud-wish': '흐린 날을 같이 기다리기로 했어요',
    'new-notebook': '새 공책에 둘의 이야기를 적기로 했어요',
    'night-heard': '밤의 단골 이야기를 다시 나눴어요',
    'date-heard': '내 방에서 보낸 밤을 수집했대요',
  },
  talks: [
    {
      id: 'night-or-day',
      open: '{me}, 하나 여쭤봐도 돼요? 밤이 좋아요, 낮이 좋아요?',
      replies: [
        { say: '밤이요. 조용해서 좋아요', tier: 'great', remember: 'night-owl', face: 'laugh', answer: ['어머, 같은 편이네요. 후후.', '밤엔 물건들도 사람도 솔직해져요. 수집 목록에 적어 둘게요.'] },
        { say: '저는 낮이 좋아요', tier: 'good', remember: 'day-person', face: 'smile', answer: '그럼 낮엔 당신이 가게를 밝혀 주세요. 전 그늘에 있을게요.' },
        { say: '잠잘 수 있으면 아무 때나', tier: 'meh', face: 'calm', answer: '후후, 정직하시네요. 잠도 수집할 수 있으면 좋을 텐데.' },
      ],
    },
    {
      id: 'regulars',
      open: ['수집 목록이 벌써 열두 권째예요.', '맨 뒤엔 단골 명단도 있어요. 이름 올려 드릴까요?'],
      replies: [
        { say: '올려 주세요. 자주 올게요', tier: 'great', remember: 'regular', face: 'laugh', answer: '좋아요. 펜으로 적었어요. 단골은 지워지지 않아요. 후후.' },
        { say: '명단에 오르면 뭐가 좋아요?', tier: 'good', face: 'think', answer: '덤이요. 사슬 고리 하나, 아니면 사연 하나. 고르세요.' },
        { say: '조금 무서운데요', tier: 'meh', face: 'sorry', answer: '어머, 그냥 명단이에요. 안 물어요. 대부분은.' },
      ],
    },
    {
      id: 'never-throw',
      open: '손님이 판 물건은 하나도 안 버려요. 당신은 물건 잘 버리세요?',
      replies: [
        { say: '저도 못 버려요', tier: 'great', remember: 'keep-all', face: 'wow', answer: ['어머, 동지시네요.', '버리지 못하는 사람은 기억을 아끼는 사람이에요. 좋아요.'] },
        { say: '팔 거면 여기 가져올게요', tier: 'good', face: 'smile', answer: '현명하시네요. 제 등불 안에 잘 모셔 두죠. 값은 흥정이고요.' },
        { say: '다 버려요. 깔끔하게', tier: 'meh', face: 'calm', answer: '…그 버린 것들, 다음엔 저한테 주세요. 아까워요.' },
      ],
    },
    {
      id: 'lantern',
      open: '이 등불이요? 안 팔아요. 안에 뭐가 있는지 궁금하세요?',
      replies: [
        { say: '궁금해요. 살짝만요', tier: 'great', remember: 'lantern-peek', face: 'laugh', answer: ['후후, 솔직한 분이네요.', '단추, 조개, 장화 끈, 손님들 사연. 다 반짝여요.'] },
        { say: '모르는 게 나을 것 같아요', tier: 'good', face: 'smile', answer: '현명해요. 모르는 게 값이 더 나가는 물건도 있거든요.' },
        { say: '등불 말고 물건 보러 왔어요', tier: 'meh', face: 'calm', answer: '그럼요. 진열장은 이쪽이에요. 셋째 칸만 빼고요.' },
      ],
    },
    {
      id: 'mist-home',
      open: '제 고향 섬은 낮에도 안개가 안 걷혔어요. 지도에도 잘 안 나와요.',
      replies: [
        { say: '그 섬 이야기 더 해 주세요', tier: 'great', remember: 'mist-home', face: 'smile', answer: ['그림자 군도요. 조용하고, 늘 초록빛이 어른거렸죠.', '…이런 얘긴 손님한테 잘 안 하는데. 후후.'] },
        { say: '안개 속에서 길은 어떻게 찾아요?', tier: 'good', face: 'think', answer: '등불이요. 그래서 이걸 안 놓고 다녀요. 습관이에요.' },
        { say: '음침한 곳 같아요', tier: 'meh', face: 'calm', answer: '어머, 칭찬으로 들을게요. 저한텐 아늑했거든요.' },
      ],
    },
    {
      id: 'haggle',
      open: '흥정 좋아하세요? 전 값 깎는 손님이 제일 좋아요. 재밌거든요.',
      replies: [
        { say: '웃으면서 깎아 볼게요', tier: 'great', remember: 'haggle', face: 'laugh', answer: '후후, 그게 정석이에요. 웃는 쪽이 늘 조금 더 얻어 가요.' },
        { say: '정가로 살게요', tier: 'good', face: 'wow', answer: '어머, 귀한 손님. 그럼 덤은 제가 알아서 얹어 드릴게요.' },
        { say: '흥정은 피곤해요', tier: 'meh', face: 'calm', answer: '그럼 값은 제가 정해요. 그것도 나름 재밌어요. 후후.' },
      ],
    },
    {
      id: 'beach',
      open: '밤바다 해변엔 별게 다 밀려와요. 갈고리로 건지러 같이 가실래요?',
      replies: [
        { say: '좋아요. 등불은 제가 들게요', tier: 'great', remember: 'beach-comb', face: 'laugh', answer: '어머, 등불을 맡기다니 처음이에요. 떨어뜨리지만 마세요.' },
        { say: '뭐가 밀려오는데요?', tier: 'good', face: 'think', answer: '병, 조개, 누가 잃어버린 장화. 다 사연이 있어요.' },
        { say: '밤바다는 추워요', tier: 'meh', face: 'calm', answer: '그렇죠. 외투 하나 싸게 드릴까요? 장사 얘기예요.' },
      ],
    },
    {
      id: 'chains',
      open: '제 사슬이 무섭다는 분들이 있어요. 사실 이거, 뭔지 아세요?',
      replies: [
        { say: '열쇠 꾸러미 같은데요', tier: 'great', remember: 'chain-keys', face: 'wow', answer: '어머, 맞혔어요. 열 곳이 많아서 길어졌을 뿐이에요. 후후.' },
        { say: '진열장 장식이요?', tier: 'good', face: 'smile', answer: '반은 맞아요. 반짝이면 손님들이 한 번 더 보거든요.' },
        { say: '그냥 무서워요', tier: 'meh', face: 'sorry', answer: '괜찮아요. 아무도 안 묶어요. 상자만 묶어요.' },
      ],
    },
    {
      id: 'sunflower',
      open: '나세라 씨가 해바라기 씨를 팔라고 하더라고요. 전 좀 곤란해요.',
      replies: [
        { say: '너무 밝아서 그렇죠?', tier: 'great', remember: 'no-sunflower', face: 'laugh', answer: '어머, 들켰네요. 그 꽃은 저를 너무 빤히 봐요. 후후.' },
        { say: '그래도 잘 팔리잖아요', tier: 'good', face: 'think', answer: '그렇죠. 장사는 장사니까 들이긴 할게요. 구석에.' },
        { say: '해바라기 예쁜데요', tier: 'meh', face: 'calm', answer: '예쁘죠. 멀리서 보면요. 아주 멀리서.' },
      ],
    },
    {
      id: 'story-price',
      open: '이 낡은 장화 한 짝, 얼마일 것 같아요? 힌트는, 사연이 있어요.',
      replies: [
        { say: '사연 들으면 값을 매길게요', tier: 'great', remember: 'story-price', face: 'laugh', answer: ['후후, 장사를 아시네요.', '물건값의 절반은 사연이에요. 나머지 반은 분위기고요.'] },
        { say: '공짜 아니에요?', tier: 'good', face: 'smile', answer: '어머, 과감하시네요. 공짜는 사연 없는 물건만이에요.' },
        { say: '장화는 안 사요', tier: 'meh', face: 'calm', answer: '그렇죠. 한 짝이니까요. 나머지 한 짝도 언젠가 올 거예요.' },
      ],
    },
    {
      id: 'tavern',
      open: '어젯밤 주점에서 마을 소식을 잔뜩 들었어요. 궁금하세요?',
      replies: [
        { say: '조금만 알려 주세요', tier: 'great', remember: 'tavern-gossip', face: 'laugh', answer: ['후후, 소문도 수집품이에요.', '누가 누구한테 꽃을 샀는지 정도만요. 이름은 비밀이고요.'] },
        { say: '주점에선 뭐 하세요?', tier: 'good', face: 'smile', answer: '수집품 자랑이요. 샹크스 선장님이 제일 잘 들어 줘요.' },
        { say: '남 얘긴 별로예요', tier: 'meh', face: 'calm', answer: '어머, 점잖으시네요. 그럼 제 얘기만 할게요.' },
      ],
    },
    {
      id: 'cloudy',
      open: '흐린 날이 제일 좋아요. 등불이 예쁘게 보이거든요. 당신은요?',
      replies: [
        { say: '흐린 날 등불, 보고 싶어요', tier: 'great', face: 'laugh', answer: '그럼 흐린 날 오세요. 제일 좋은 자리에 등불 걸어 둘게요.' },
        { say: '맑은 날이 좋아요', tier: 'good', face: 'smile', answer: '그럼 맑은 날은 당신이 즐기세요. 전 가게 안쪽에 있을게요.' },
        { say: '날씨는 신경 안 써요', tier: 'meh', face: 'calm', answer: '편하시겠네요. 전 햇볕만 보면 눈부터 찡그려져요.' },
      ],
    },
    {
      id: 'appraise',
      open: '{me}, 주머니에서 딸그락 소리가 나요. 감정해 드릴까요? 공짜로요.',
      replies: [
        { say: '공짜면 부탁드려요', tier: 'great', face: 'laugh', answer: '후후, 조약돌이네요. 흔한 돌은 별로지만, 당신 거니까 반짝여요.' },
        { say: '그냥 동전이에요', tier: 'good', face: 'smile', answer: '동전도 사연이 있어요. 언제 누구한테 받았는지요.' },
        { say: '안 팔 거예요', tier: 'meh', face: 'calm', answer: '어머, 아쉬워라. 마음 바뀌면 언제든 오세요.' },
      ],
    },
    {
      id: 'second-shelf',
      when: { ch: 3 },
      open: '진열장 셋째 칸, 비매품 칸이에요. 요즘 거기 자리를 하나 비웠어요.',
      replies: [
        { say: '누구 자리예요?', tier: 'great', face: 'shy', answer: '…후후, 그건 비밀이에요. 근데 당신이 판 조개가 옆에 있어요.' },
        { say: '새 보물이 들어와요?', tier: 'good', face: 'smile', answer: '들어오면 좋겠어요. 아직 값을 못 매기는 거라서요.' },
        { say: '청소한 거 아니에요?', tier: 'meh', face: 'laugh', answer: '어머, 그렇게 볼 수도 있죠. 반은 맞아요.' },
      ],
    },
    {
      id: 'archive-keys',
      open: ['이 사슬에 달린 열쇠, 반은 이 가게 거예요.', '나머지 반은… 고향 섬 기록 보관소 열쇠예요.'],
      replies: [
        { say: '거기서 일하셨어요?', tier: 'great', remember: 'archive-keeper', face: 'think', answer: ['문지기였어요. 아무것도 밖에 안 내보내는.', '들어온 건 다 지켰죠. 그 버릇이 지금 이 가게예요. 후후.'] },
        { say: '열쇠가 엄청 많네요', tier: 'good', face: 'smile', answer: '문이 많았거든요. 지금은 열 문이 없어도 못 버려요.' },
        { say: '그 열쇠 팔아요?', tier: 'meh', face: 'calm', answer: '어머, 그건 비매품이에요. 열쇠는 주인을 기억하거든요.' },
      ],
    },
    {
      id: 'lost-found',
      open: '계산대 밑에 분실물 선반이 있어요. 주인이 찾으러 올 때까지 모셔 둬요.',
      replies: [
        { say: '저도 같이 지켜 드릴게요', tier: 'great', remember: 'lost-found', face: 'laugh', answer: ['어머, 든든하네요.', '지난주엔 신짜장 씨 모자가 사흘 만에 주인을 찾았어요. 후후.'] },
        { say: '주인이 안 오면요?', tier: 'good', face: 'think', answer: '계속 기다려요. 물건은 기다리는 걸 잘해요. 저도요.' },
        { say: '그냥 팔면 되잖아요', tier: 'meh', face: 'sorry', answer: '…그건 안 돼요. 주인 있는 물건은 값을 안 매겨요.' },
      ],
    },
    {
      id: 'shop-smile',
      open: '거울 보고 장사용 미소를 연습해요. 이가 좀 많이 보인대요. 어때요?',
      replies: [
        { say: '안 웃을 때가 더 좋아요', tier: 'great', remember: 'real-smile', face: 'shy', answer: ['…어머. 그런 말은 장사엔 안 좋은데요.', '그래도 수집 목록엔 적을게요. 비매품 칸에.'] },
        { say: '친절해 보여요', tier: 'good', face: 'laugh', answer: '후후, 다행이에요. 연습한 보람이 있네요.' },
        { say: '솔직히 조금 무서워요', tier: 'meh', face: 'sorry', answer: '역시요. 그웬 씨도 그렇게 말했어요. 더 연습할게요.' },
      ],
    },
    {
      id: 'fog-lantern',
      open: ['안개 낀 밤엔 골목에서 길 잃는 분이 있어요.', '그럴 땐 등불을 내밀어요. 잡으면 가게 앞으로 모셔 오죠.'],
      replies: [
        { say: '저도 길 잃으면 잡을게요', tier: 'great', remember: 'fog-walk', face: 'laugh', answer: '후후, 꼭 잡으세요. 등불 손잡이는 안 미끄러워요.' },
        { say: '그래서 등불을 안 놓는군요', tier: 'good', face: 'smile', answer: '맞아요. 이 마을에선 안개 안내원도 겸하고 있어요.' },
        { say: '그냥 집에 일찍 갈게요', tier: 'meh', face: 'calm', answer: '그것도 현명하죠. 그래도 등불은 늘 켜 둘게요.' },
      ],
    },
    {
      id: 'jar-labels',
      open: '유리병마다 이름표를 붙여요. 오늘 들어온 병엔 뭐라고 쓸까요?',
      replies: [
        { say: '비 냄새 담긴 병 어때요?', tier: 'great', remember: 'jar-label', face: 'wow', answer: ['어머, 시인이시네요.', '그대로 쓸게요. 당신 이름은 작게 옆에. 후후.'] },
        { say: '그냥 빈 병이라고요', tier: 'good', face: 'smile', answer: '정직하네요. 빈 병도 사연은 하나쯤 담고 있어요.' },
        { say: '뭐든 상관없어요', tier: 'meh', face: 'calm', answer: '그럼 제가 정할게요. 잘 모르는 병. 이것도 이름이죠.' },
      ],
    },
    {
      id: 'long-winter',
      open: '계절 중에 겨울이 제일 좋아요. 밤이 길거든요. 당신은요?',
      replies: [
        { say: '긴 겨울밤 좋아요', tier: 'great', remember: 'winter-love', face: 'laugh', answer: '어머, 반가워요. 겨울밤엔 등불 옆에서 목록 정리해요. 같이요.' },
        { say: '저는 봄이 좋아요', tier: 'good', face: 'smile', answer: '봄도 좋죠. 대청소 날에 물건이 쏟아지거든요. 후후.' },
        { say: '추운 건 싫어요', tier: 'meh', face: 'calm', answer: '그럼 겨울엔 가게 안으로 오세요. 춥진 않아요. 아마.' },
      ],
    },
    {
      id: 'night-fish',
      open: '밤에 잡힌 물고기는 눈빛이 달라요. 뱀장어나 달빛 갈치 같은 거요.',
      replies: [
        { say: '밤낚시 하면 가져올게요', tier: 'great', remember: 'night-fish', face: 'laugh', answer: '후후, 약속이에요. 등불 하나 빌려 드릴게요. 물고기가 좋아해요.' },
        { say: '눈빛이 어떻게 달라요?', tier: 'good', face: 'think', answer: '뭔가 알고 있는 눈이요. 밤바다 사연을 본 눈이죠.' },
        { say: '밤엔 자야죠', tier: 'meh', face: 'calm', answer: '어머, 건강하시네요. 그럼 꿈에서라도 낚아 오세요.' },
      ],
    },
    {
      id: 'fossil',
      open: '화석 좋아하세요? 돌 속에 아주 오래된 시간이 갇혀 있어요.',
      replies: [
        { say: '시간을 수집하는 거네요', tier: 'great', remember: 'fossil-talk', face: 'wow', answer: ['어머, 제가 하고 싶던 말이에요.', '광산에서 나오면 꼭 보여 주세요. 사연은 제가 지어 줄게요.'] },
        { say: '그냥 돌 아니에요?', tier: 'good', face: 'smile', answer: '흔한 돌이랑은 달라요. 흔한 돌은 저도 별로예요.' },
        { say: '갇혀 있다니 무서워요', tier: 'meh', face: 'calm', answer: '후후, 표현이 그랬나요. 잘 쉬고 있다고 할게요.' },
      ],
    },
    {
      id: 'your-collection',
      open: '{me}, 당신도 뭔가 모으죠? 수집가는 수집가를 알아봐요.',
      replies: [
        { say: '사실 저도 모아요', tier: 'great', remember: 'my-collection', face: 'laugh', answer: ['역시요. 눈빛이 그랬어요.', '뭔지는 다음에 알려 주세요. 수집 목록 한 칸 비워 둘게요.'] },
        { say: '추억 정도요', tier: 'good', face: 'shy', answer: '…그게 제일 비싼 수집품이에요. 잘 아시네요.' },
        { say: '아무것도 안 모아요', tier: 'meh', face: 'calm', answer: '어머, 깔끔하시네요. 그럼 버리는 건 다 저한테요.' },
      ],
    },
    {
      id: 'ghost-story',
      open: '주점에서 으스스한 이야기를 하면 다들 제 쪽을 봐요. 왜일까요?',
      replies: [
        { say: '등불 때문 아닐까요?', tier: 'great', remember: 'ghost-story', face: 'laugh', answer: ['후후, 그렇겠죠. 근데 제 이야기가 제일 무섭긴 해요.', '결말은 늘 같아요. 물건이 주인을 찾아가요. 따뜻하죠?'] },
        { say: '이야기를 잘하셔서요', tier: 'good', face: 'smile', answer: '어머, 칭찬이죠? 샹크스 선장님은 매번 웃어요.' },
        { say: '그런 얘긴 싫어요', tier: 'meh', face: 'sorry', answer: '그럼 오늘은 단추 이야기만 할게요. 하나도 안 무서워요.' },
      ],
    },
    {
      id: 'gwen-mist',
      open: ['그웬 씨는 우리 가게 초록 안개를 보면 가위부터 들어요.', '해칠 생각은 없는데, 어떻게 하면 좋을까요?'],
      replies: [
        { say: '리본 하나 선물해 보세요', tier: 'great', remember: 'gwen-truce', face: 'think', answer: ['어머, 리본이요. 그분은 바느질을 좋아하니까.', '진열장에서 제일 고운 걸 골라 볼게요. 후후.'] },
        { say: '안개를 좀 줄이면요?', tier: 'good', face: 'sorry', answer: '…노력해 볼게요. 습관이라 잘 안 되지만요.' },
        { say: '그웬 씨 마음 알 것 같아요', tier: 'meh', face: 'calm', answer: '어머, 당신까지요. 섭섭하지만 이해해요.' },
      ],
    },
    {
      id: 'nasera-seeds',
      open: '나세라 씨가 또 씨앗 가격표를 들고 왔어요. 우리 가게가 싸다고요.',
      replies: [
        { say: '싸게 파는 게 죄는 아니죠', tier: 'great', face: 'laugh', answer: '후후, 그렇죠? 근데 그분 눈빛은 꼭 장부 감사예요.' },
        { say: '농협 씨앗이 더 좋대요', tier: 'good', face: 'think', answer: '품질은 그쪽이 낫다고 인정해요. 사연은 제 쪽이 많고요.' },
        { say: '싸우지 마세요', tier: 'meh', face: 'smile', answer: '싸우는 거 아니에요. 서로 웃으면서 노려볼 뿐이에요.' },
      ],
    },
    {
      id: 'ornn-ore',
      open: '산기슭 오른 씨는 광석 값을 한 푼도 안 깎아 줘요. 망치로 대답해요.',
      replies: [
        { say: '좋은 물건이라 그렇죠', tier: 'great', face: 'smile', answer: '맞아요. 그래서 저도 안 깎아 드려요. 공평하죠. 후후.' },
        { say: '망치로요?', tier: 'good', face: 'laugh', answer: '모루를 쾅. 그게 거절이에요. 그 소리도 수집했어요.' },
        { say: '깎지 마세요', tier: 'meh', face: 'calm', answer: '어머, 흥정은 인사예요. 안 하면 서운해하실걸요.' },
      ],
    },
    {
      id: 'green-glow',
      open: '제 등불은 초록빛이에요. 다들 왜 초록이냐고 물어요.',
      replies: [
        { say: '그래서 더 예뻐요', tier: 'great', remember: 'green-light', face: 'shy', answer: '…어머. 고향 바다 색이에요. 예쁘다고 해 준 사람은 드물어요.' },
        { say: '왜 초록이에요?', tier: 'good', face: 'think', answer: '고향 바닷물이 이 색이었어요. 그걸 잊기 싫어서요.' },
        { say: '노란 불이 낫지 않아요?', tier: 'meh', face: 'calm', answer: '노란 건 해바라기 같아서요. 후후, 아시잖아요.' },
      ],
    },
    {
      id: 'sickle',
      open: '벽에 걸린 낫이요? 장식이에요. 수확철엔 빌려주기도 하고요.',
      replies: [
        { say: '믿을게요. 장식이죠', tier: 'great', face: 'laugh', answer: '후후, 믿어 주는 손님은 귀해요. 날도 무뎌요, 진짜로.' },
        { say: '한번 빌려 주세요', tier: 'good', face: 'smile', answer: '좋아요. 대신 해바라기 밭엔 쓰지 마세요.' },
        { say: '치우시면 좋겠어요', tier: 'meh', face: 'sorry', answer: '…볼리바스 순경님이랑 같은 말을 하시네요.' },
      ],
    },
    {
      id: 'spring-cleaning',
      open: '봄 대청소 날엔 동네 창고 앞을 돌아요. 다들 버리는 게 많거든요.',
      replies: [
        { say: '저도 같이 돌래요', tier: 'great', remember: 'clean-day', face: 'laugh', answer: ['어머, 수레 하나 더 빌려 둘게요.', '버리는 사람한테는 웃으면서 고맙다고 하는 거예요.'] },
        { say: '주인들이 안 서운해해요?', tier: 'good', face: 'think', answer: '다들 시원해해요. 서운해지면 다시 사 가요. 후후.' },
        { say: '청소는 귀찮아요', tier: 'meh', face: 'calm', answer: '그럼 안 버린 채로 두세요. 언젠가 제가 사 갈게요.' },
      ],
    },
    {
      id: 'janna-forecast',
      open: '잔나 씨 예보에 흐림이 나오면 가게 앞에 등불을 하나 더 걸어요.',
      replies: [
        { say: '흐린 날 같이 기다려요', tier: 'great', remember: 'cloud-wish', face: 'laugh', answer: '후후, 좋아요. 흐림 예보는 저한텐 축제 예고예요.' },
        { say: '예보가 틀리면요?', tier: 'good', face: 'smile', answer: '그럼 다음 날 걸어요. 등불은 기다리는 걸 잘하니까요.' },
        { say: '맑은 날이 좋은데', tier: 'meh', face: 'calm', answer: '어머, 그럼 잔나 씨는 당신 편이네요. 저는 구름 편.' },
      ],
    },
    {
      id: 'rose-gems',
      open: '미스 포츈 씨는 보석을 계산하고, 저는 보석을 모아요. 누가 이길까요?',
      replies: [
        { say: '모으는 쪽이 이기죠', tier: 'great', face: 'laugh', answer: '후후, 응원 고마워요. 계산은 끝나도 수집은 안 끝나요.' },
        { say: '둘 다 웃으면 무서워요', tier: 'good', face: 'smile', answer: '어머, 다들 그래요. 그래서 흥정 땐 손님이 다 피해요.' },
        { say: '보석엔 관심 없어요', tier: 'meh', face: 'calm', answer: '그럼 조개는요? 반짝이는 건 다 친척이에요.' },
      ],
    },
    {
      id: 'back-room-thing',
      when: { ch: 4 },
      open: '뒷방 열쇠 드렸죠. 오늘은 거기서 하나 꺼내 왔어요. 녹슨 종이에요.',
      replies: [
        { say: '고향 보관소 종이에요?', tier: 'great', face: 'think', answer: ['…맞아요. 문 닫을 때 치던 종이요.', '이젠 가게 문 열 때 쳐요. 순서가 바뀌었죠. 후후.'] },
        { say: '한번 쳐 봐도 돼요?', tier: 'good', face: 'laugh', answer: '살살이요. 소리가 안개처럼 오래 남거든요.' },
        { say: '녹슨 건 버리셔야죠', tier: 'meh', face: 'sorry', answer: '…그건 제일 못 하는 일이에요. 아시잖아요.' },
      ],
    },
    {
      id: 'new-notebook',
      when: { love: 'dating' },
      open: '새 공책 말이에요. 첫 장에 뭘 적을까 아직 고민 중이에요.',
      replies: [
        { say: '처음 만난 날부터요', tier: 'great', remember: 'new-notebook', face: 'shy', answer: ['…그날 표정까지 기억해요.', '조금 무서워했죠. 그것도 적을게요. 후후.'] },
        { say: '오늘 이야기부터요', tier: 'good', face: 'smile', answer: '좋아요. 오늘이 첫 장이에요. 날짜는 크게요.' },
        { say: '빈 채로 두면요?', tier: 'meh', face: 'think', answer: '빈 공책은 제가 못 견뎌요. 수집가잖아요.' },
      ],
    },
    {
      id: 'lantern-share',
      when: { love: 'any' },
      open: '{me}, 이 등불, 당신도 들어 봐요. 무겁지 않죠?',
      replies: [
        { say: '생각보다 가볍네요', tier: 'great', face: 'shy', answer: ['예전엔 무거웠어요. 혼자 들 땐.', '…당신 손에 있으니 가벼워졌나 봐요.'] },
        { say: '안에서 소리가 나요', tier: 'good', face: 'laugh', answer: '후후, 단추끼리 부딪는 소리예요. 당신 단추도 있어요.' },
        { say: '돌려 드릴게요', tier: 'meh', face: 'calm', answer: '어머, 벌써요. 다음엔 조금 더 들고 있어요.' },
      ],
    },
  ],
  openers: [
    {
      id: 'op-rain',
      when: { weather: ['rain', 'storm'] },
      open: '{weather}. 좋은 날씨네요. 다들 창고 정리하고 버리는 날이에요.',
      replies: [
        { say: '그걸 쓰레쉬 씨가 받죠?', tier: 'great', face: 'laugh', answer: '후후, 아시네요. 비 그치면 해변도 한 바퀴 돌 거예요.' },
        { say: '우산 하나 주세요', tier: 'good', face: 'smile', answer: '손잡이가 갈고리 모양인 거요? 제일 잘 팔려요.' },
        { say: '비 싫어요', tier: 'meh', face: 'calm', answer: '어머, 그럼 가게 안에 있다 가세요. 여긴 늘 아늑해요.' },
      ],
    },
    {
      id: 'op-snow',
      when: { weather: 'snow' },
      open: '눈이 오면 발자국이 남죠. 누가 어디 갔는지 다 보여요. 후후.',
      replies: [
        { say: '제 발자국도 보셨어요?', tier: 'great', face: 'laugh', answer: '그럼요. 가게 앞에서 두 번 서성이셨죠. 수집했어요.' },
        { say: '눈 오는 날은 조용하네요', tier: 'good', face: 'smile', answer: '그렇죠. 등불 안 속삭임까지 들려요. 농담이에요. 아마.' },
        { say: '추워요', tier: 'meh', face: 'calm', answer: '등불 가까이 오세요. 따뜻하진 않지만 분위기는 있어요.' },
      ],
    },
    {
      id: 'op-night',
      when: { time: 'night' },
      open: '밤이군요. 제 시간이에요. 초록 불빛이 무서우세요?',
      replies: [
        { say: '예뻐요. 반딧불이 같아요', tier: 'great', face: 'shy', answer: '어머. 그런 말은 처음 들어요. 수집 목록 맨 앞에 적을게요.' },
        { say: '조금요. 그래도 왔어요', tier: 'good', face: 'smile', answer: '용기 있는 손님이네요. 안 물어요. 대부분은. 후후.' },
        { say: '그냥 지나가는 길이에요', tier: 'meh', face: 'calm', answer: '그럼 등불 잡고 가세요. 골목이 어두워요.' },
      ],
    },
    {
      id: 'op-sunny',
      when: { weather: 'sunny', time: 'day' },
      open: '아, 햇볕. 오늘은 가게 안쪽에 있을게요. 너무 정직한 빛이에요.',
      replies: [
        { say: '그늘 쪽에서 얘기해요', tier: 'great', face: 'laugh', answer: '배려가 깊으시네요. 후후, 그늘은 제가 제일 잘 알아요.' },
        { say: '햇볕 좀 쬐세요', tier: 'good', face: 'sorry', answer: '…조금만요. 손등만. 그걸로 오늘 몫은 다 했어요.' },
        { say: '날씨 좋은데요', tier: 'meh', face: 'calm', answer: '좋죠. 장사엔 안 좋아요. 다들 밖에 나가거든요.' },
      ],
    },
    {
      id: 'op-festival',
      when: { festival: true },
      open: '축제날엔 다들 지갑이 열려요. 경매도 열고요. 구경 오실래요?',
      replies: [
        { say: '첫 물건이 뭐예요?', tier: 'great', face: 'laugh', answer: '누가 버린 장화 한 짝이요. 사연이 있어요. 기대하세요.' },
        { say: '축제는 즐기셔야죠', tier: 'good', face: 'smile', answer: '즐기고 있어요. 저한텐 경매가 축제거든요. 후후.' },
        { say: '돈이 없어요', tier: 'meh', face: 'calm', answer: '구경은 공짜예요. 나가는 것도요. 농담이에요.' },
      ],
    },
    {
      id: 'op-fish',
      when: { fish: true, time: ['evening', 'night'] },
      open: '{fish} 낚으셨죠? 밤에 잡은 물고기는 제가 비싸게 쳐 드려요.',
      replies: [
        { say: '비늘 하나 드릴게요', tier: 'great', face: 'laugh', answer: '어머, 진열장에 모셔 둘게요. 밤바다 사연이 묻었네요.' },
        { say: '얼마 쳐 주실 건데요?', tier: 'good', face: 'think', answer: '후후, 흥정 시작이네요. 웃으면서 해요, 우리.' },
        { say: '제가 먹을 거예요', tier: 'meh', face: 'calm', answer: '그럼 맛있게 드세요. 뼈는 버리지 마시고요.' },
      ],
    },
    {
      id: 'op-bigfish',
      when: { bigFish: true },
      open: '오늘 엄청난 걸 낚으셨다면서요. 소문이 가게까지 왔어요.',
      replies: [
        { say: '보여 드릴게요. 안 팔아요', tier: 'great', face: 'laugh', answer: '후후, 비매품이군요. 저도 그 마음 알아요. 축하해요.' },
        { say: '파시면 얼마 주실래요?', tier: 'good', face: 'wow', answer: '어머, 그건 감정이 안 돼요. 너무 귀해서요. 처음이에요.' },
        { say: '운이 좋았어요', tier: 'meh', face: 'smile', answer: '운도 사연이에요. 오늘 날짜를 꼭 기억해 두세요.' },
      ],
    },
    {
      id: 'op-gold',
      when: { gold: true },
      open: '금별 작물을 거두셨다고요? 진열장 제일 가운데 자리감이에요.',
      replies: [
        { say: '구경만 시켜 드릴게요', tier: 'great', face: 'laugh', answer: '후후, 그게 제일 감질나요. 흥정은 다음에 해요.' },
        { say: '파는 건 고민해 볼게요', tier: 'good', face: 'smile', answer: '천천히요. 반짝이는 건 오래 고민할수록 값이 올라요.' },
        { say: '그냥 먹을 거예요', tier: 'meh', face: 'sorry', answer: '…어머. 맛있겠네요. 조금 아깝지만요.' },
      ],
    },
    {
      id: 'op-harvest',
      when: { harvest: true },
      open: '밭일 하셨죠? 손에 흙이 묻었어요. 수확한 거 중에 팔 거 있어요?',
      replies: [
        { say: '제일 못생긴 거 드릴게요', tier: 'great', face: 'laugh', answer: '어머, 그게 제일 좋아요. 못생긴 건 사연이 많거든요.' },
        { say: '씨앗 좀 싸게 주세요', tier: 'good', face: 'smile', answer: '제 씨앗이 농협보다 싸요. 비밀로요. 후후.' },
        { say: '해바라기 심었어요', tier: 'meh', face: 'sorry', answer: '…아. 그 밭은 멀리서 응원할게요.' },
      ],
    },
    {
      id: 'op-low',
      when: { mood: 'low' },
      open: '{me}, 오늘 표정이 무겁네요. 무거운 게 있으면 저한테 파세요.',
      replies: [
        { say: '그냥 좀 지쳤어요', tier: 'great', face: 'smile', answer: ['그럼 등불 옆 의자에 앉아요. 단골 자리예요.', '오늘 무게는 제가 대신 모셔 둘게요. 공짜로.'] },
        { say: '팔면 얼마 쳐 주세요?', tier: 'good', face: 'laugh', answer: '후후, 그 농담이 나오면 반은 괜찮은 거예요. 후하게 쳐 드릴게요.' },
        { say: '말하기 싫어요', tier: 'meh', face: 'calm', answer: '그럼 말 안 해도 돼요. 가게 안은 조용하니까 있다 가세요.' },
      ],
    },
    {
      id: 'op-bday',
      when: { bday: true },
      open: '생일 축하해요, {me}. 오늘만은 비매품 하나를 공짜로 드릴게요.',
      replies: [
        { say: '쓰레쉬 씨가 고른 걸로요', tier: 'great', face: 'shy', answer: '…어머. 고르라니요. 그럼 제일 반짝이는 걸로 드릴게요.' },
        { say: '등불 안의 것도요?', tier: 'good', face: 'laugh', answer: '후후, 그건 안 돼요. 생일이어도요. 대신 리본 달아 드릴게요.' },
        { say: '선물은 괜찮아요', tier: 'meh', face: 'smile', answer: '그럼 축하만 드릴게요. 날짜는 단골 명단에 적어 둘게요.' },
      ],
    },
    {
      id: 'op-news-wedding',
      when: { news: 'wedding' },
      open: '마을에 결혼 소식이 있네요. 꽃다발이 잘 팔리겠어요. 후후.',
      replies: [
        { say: '사슬 없는 꽃다발로요', tier: 'great', face: 'laugh', answer: '어머, 제 말버릇을 아시네요. 리본으로 묶어 드려요.' },
        { say: '축하할 일이네요', tier: 'good', face: 'smile', answer: '그렇죠. 결혼식 날 떨어지는 단추도 기념품이 돼요.' },
        { say: '꽃은 금방 시들어요', tier: 'meh', face: 'calm', answer: '그래서 말려 둬요. 시든 꽃도 버리진 않아요.' },
      ],
    },
    {
      id: 'op-news-museum',
      when: { news: 'museum' },
      open: '오늘 마을 소식 보셨어요? 박물관이 또 귀한 걸 가져갔대요. 아쉬워라.',
      replies: [
        { say: '쓰레쉬 씨 가게가 더 낫죠', tier: 'great', face: 'laugh', answer: '후후, 그렇죠. 박물관은 사연을 안 들어 줘요. 전 들어 줘요.' },
        { say: '박물관도 좋던데요', tier: 'good', face: 'smile', answer: '좋죠. 언젠가 제 가게 물건도 거기 갈지 몰라요. 안 팔겠지만.' },
        { say: '관심 없어요', tier: 'meh', face: 'calm', answer: '그럼 진열장 구경이나 하세요. 그게 더 재밌어요.' },
      ],
    },
    {
      id: 'op-frieren',
      when: { bond: 'frieren' },
      open: '{other} 씨 만나셨죠? 그분도 옛 물건을 모아요. 우리 맞수예요.',
      replies: [
        { say: '누가 더 많이 모았어요?', tier: 'great', face: 'laugh', answer: '양은 그분이요. 천 년 모았으니까. 사연은 제가 더 많아요.' },
        { say: '같이 모으면 되잖아요', tier: 'good', face: 'think', answer: '어머, 그건 생각 못 했네요. 근데 고르는 눈이 달라서요.' },
        { say: '빵 얘기만 하던데요', tier: 'meh', face: 'smile', answer: '후후, 그분 수집은 이상한 레시피예요. 저도 하나 샀어요.' },
      ],
    },
    {
      id: 'op-volibas',
      when: { bond: 'volibas' },
      open: '{other} 순경님이 오늘도 제 등불을 수상하게 보셨죠?',
      replies: [
        { say: '반은 맞는 추리 같던데요', tier: 'great', face: 'laugh', answer: '후후, 정확해요. 나머지 반은 그냥 등불이에요.' },
        { say: '걱정하시는 거예요', tier: 'good', face: 'smile', answer: '알아요. 그래서 밤마다 가게 앞은 늘 안전해요. 덕분이죠.' },
        { say: '저도 좀 수상해요', tier: 'meh', face: 'sorry', answer: '어머, 당신까지. 그럼 등불 구경 공짜로 시켜 드릴게요.' },
      ],
    },
    {
      id: 'op-captain',
      when: { bond: 'captain' },
      open: '{other} 선장님 만나셨어요? 어젯밤 주점에서 제 수집품 자랑을 들어 줬어요.',
      replies: [
        { say: '선장님은 다 재밌어하죠', tier: 'great', face: 'laugh', answer: '그렇죠. 장화 한 짝 얘기에도 웃어 줘요. 귀한 청중이에요.' },
        { say: '무슨 자랑을 했어요?', tier: 'good', face: 'smile', answer: '병뚜껑 마흔 개요. 사연까지 하면 밤을 새요. 후후.' },
        { say: '술 얘기만 하던데요', tier: 'meh', face: 'calm', answer: '어머, 그분다워요. 외상 장부도 제가 수집하고 싶네요.' },
      ],
    },
    {
      id: 'op-rose',
      when: { bond: 'rose' },
      open: '{other} 씨 만나셨죠? 어제 보석 흥정을 밤새 했어요. 둘 다 웃으면서요.',
      replies: [
        { say: '누가 이겼어요?', tier: 'great', face: 'laugh', answer: '비겼어요. 늘 그래요. 그래서 재밌어요. 후후.' },
        { say: '무섭게 웃으셨겠네요', tier: 'good', face: 'smile', answer: '어머, 들켰네요. 서로 웃는 얼굴이 제일 무서운 사이예요.' },
        { say: '돈 얘긴 피곤해요', tier: 'meh', face: 'calm', answer: '그분이랑 저한텐 그게 수다예요. 이상하죠.' },
      ],
    },
    {
      id: 'op-makima',
      when: { bond: 'makima' },
      open: '{other} 씨 만나셨어요? 다음 경매에서 같은 걸 노리고 있어요.',
      replies: [
        { say: '쓰레쉬 씨가 이기세요', tier: 'great', face: 'laugh', answer: '후후, 응원이 생기니 값을 한 번 더 부를 용기가 나네요.' },
        { say: '뭘 노리는데요?', tier: 'good', face: 'think', answer: '오래된 회중시계요. 바늘이 거꾸로 돈대요. 탐나죠.' },
        { say: '양보하시면 어때요?', tier: 'meh', face: 'calm', answer: '어머, 수집가한테 양보는 어려운 단어예요. 노력은 할게요.' },
      ],
    },
    {
      id: 'op-shinichi',
      when: { bond: 'shinichi' },
      open: '{other} 탐정님이 또 제 장부를 들여다보고 갔어요. 수상한 건 없는데.',
      replies: [
        { say: '정말 없어요?', tier: 'great', face: 'laugh', answer: '후후, 없어요. 사연이 많을 뿐이에요. 탐정님도 결국 웃었어요.' },
        { say: '장부 정리 잘하시잖아요', tier: 'good', face: 'smile', answer: '그렇죠. 열두 권째예요. 탐정님은 세 권째에서 지쳤어요.' },
        { say: '숨기는 게 있죠?', tier: 'meh', face: 'think', answer: '어머, 다들 저를 그렇게 봐요. 셋째 칸 말고는 없어요.' },
      ],
    },
    {
      id: 'op-cloudy',
      when: { weather: 'cloudy' },
      open: '{weather}. 이런 날을 기다렸어요. 등불이 제일 예쁘게 보이는 날이에요.',
      replies: [
        { say: '그래서 기분이 좋아 보여요', tier: 'great', face: 'laugh', answer: '후후, 들켰네요. 오늘은 덤도 후하게 얹어 드릴게요.' },
        { say: '등불 하나 사 갈까요?', tier: 'good', face: 'smile', answer: '파는 등불은 저쪽이에요. 제 건 빼고요.' },
        { say: '좀 우중충한데요', tier: 'meh', face: 'calm', answer: '어머, 그게 매력이에요. 은접시 같은 하늘이잖아요.' },
      ],
    },
    {
      id: 'op-storm-night',
      when: { weather: 'storm', time: ['evening', 'night'] },
      open: ['밖에 폭풍이에요. 가게에 잠깐 피해 가세요.', '내일 아침 해변엔 뭐가 밀려올지 벌써 설레요.'],
      replies: [
        { say: '내일 새벽에 같이 가요', tier: 'great', face: 'laugh', answer: '어머, 좋아요. 갈고리 두 개, 수레 하나. 준비해 둘게요.' },
        { say: '등불이 안 꺼지네요', tier: 'good', face: 'smile', answer: '이 등불은 바람을 안 타요. 이유는 비밀이에요. 후후.' },
        { say: '천둥이 무서워요', tier: 'meh', face: 'calm', answer: '가게 안쪽에 앉아요. 병들이 떠는 소리만 들릴 거예요.' },
      ],
    },
    {
      id: 'op-dawn',
      when: { time: 'dawn' },
      open: '새벽 해변 한 바퀴 돌고 왔어요. 주머니가 묵직하죠? 보실래요?',
      replies: [
        { say: '뭘 주우셨는지 궁금해요', tier: 'great', face: 'laugh', answer: ['후후, 병뚜껑 셋, 단추 하나, 편지 한 장.', '편지는 안 읽었어요. 주인 찾아 줄 거예요.'] },
        { say: '일찍 일어나셨네요', tier: 'good', face: 'smile', answer: '아니요, 아직 안 잤어요. 밤이 덜 끝나서요.' },
        { say: '졸려서 못 보겠어요', tier: 'meh', face: 'calm', answer: '그럼 자고 오세요. 주운 건 안 도망가요.' },
      ],
    },
    {
      id: 'op-evening',
      when: { time: 'evening' },
      open: '해가 지네요. 등불 심지를 다듬는 시간이에요. 같이 보실래요?',
      replies: [
        { say: '불 켜는 거 보고 싶어요', tier: 'great', face: 'shy', answer: '…구경꾼이 있으니 손이 떨리네요. 후후, 자, 켜졌어요.' },
        { say: '저녁 장사는 잘돼요?', tier: 'good', face: 'smile', answer: '지금부터예요. 낮 손님보다 밤 손님이 사연이 많아요.' },
        { say: '저녁 먹으러 가야 해요', tier: 'meh', face: 'calm', answer: '그럼 다녀오세요. 등불은 그때도 켜져 있을 거예요.' },
      ],
    },
    {
      id: 'op-spring',
      when: { season: 'spring' },
      open: '{season}. 대청소 계절이에요. 동네 창고 문이 다 열려요.',
      replies: [
        { say: '좋은 거 나오면 알려 주세요', tier: 'great', face: 'laugh', answer: '후후, 단골 우선이에요. 첫 수레는 당신 몫으로 볼게요.' },
        { say: '씨앗도 파시죠?', tier: 'good', face: 'smile', answer: '팔죠. 나세라 씨 몰래요. 농담이에요. 반은.' },
        { say: '봄꽃이 예쁘네요', tier: 'meh', face: 'calm', answer: '예쁘죠. 금방 지는 게 아쉬워서 전 말려 둬요.' },
      ],
    },
    {
      id: 'op-summer-night',
      when: { season: 'summer', time: 'night' },
      open: '여름밤이에요. 반딧불이가 제 등불을 친구인 줄 알고 따라와요.',
      replies: [
        { say: '등불이 인기 많네요', tier: 'great', face: 'laugh', answer: '후후, 낮엔 아무도 안 오는데 밤엔 인기쟁이예요.' },
        { say: '잡아 가실 거예요?', tier: 'good', face: 'think', answer: '아니요. 보는 게 수집이에요. 병에 넣으면 빛이 시들어요.' },
        { say: '벌레는 싫어요', tier: 'meh', face: 'sorry', answer: '어머, 그럼 등불을 조금 낮출게요. 미안해요.' },
      ],
    },
    {
      id: 'op-autumn',
      when: { season: 'autumn' },
      open: '가을엔 다들 옛 물건을 꺼내요. 사연 붙은 물건이 제일 많이 들어와요.',
      replies: [
        { say: '제일 좋은 사연은요?', tier: 'great', face: 'think', answer: ['어제 들어온 낡은 장갑이요.', '첫 겨울을 같이 난 장갑이래요. 비매품 칸으로 갔어요.'] },
        { say: '가을 경매도 있죠?', tier: 'good', face: 'laugh', answer: '그럼요. 다들 욕심이 생기는 계절이라 제일 뜨거워요.' },
        { say: '낙엽만 많던데요', tier: 'meh', face: 'calm', answer: '낙엽도 모아요. 책갈피로 쓰면 값이 붙어요. 후후.' },
      ],
    },
    {
      id: 'op-winter',
      when: { season: 'winter' },
      open: '겨울이에요. 밤이 길어져서 등불 켜 두는 시간이 늘었어요. 행복해요.',
      replies: [
        { say: '저도 겨울밤이 좋아요', tier: 'great', face: 'laugh', answer: '어머, 그럼 오늘 밤 목록 정리 같이 해요. 차는 제가 내요.' },
        { say: '난로는 안 켜요?', tier: 'good', face: 'smile', answer: '켜요. 근데 등불이 더 좋아요. 분위기 값이죠.' },
        { say: '추워서 싫어요', tier: 'meh', face: 'calm', answer: '그럼 주점 벽난로 자리 양보해 드릴게요. 한 번만요.' },
      ],
    },
    {
      id: 'op-night-fish',
      when: { fish: ['eel', 'moonhairtail'] },
      open: '어머, {fish}. 밤바다 눈빛을 가진 녀석이네요. 잠깐 보여 주세요.',
      replies: [
        { say: '보여 드릴게요. 오래요', tier: 'great', face: 'wow', answer: ['…아름다워요. 수집 목록 맨 앞 장에 적을게요.', '물고기 대신 오늘 날짜를 모셔 둘게요.'] },
        { say: '파시면 얼마예요?', tier: 'good', face: 'laugh', answer: '후후, 흥정 시작이네요. 오늘은 제가 지는 쪽으로 할게요.' },
        { say: '그냥 구워 먹을래요', tier: 'meh', face: 'sorry', answer: '…어머. 맛있겠네요. 뼈는 꼭 저한테 주세요.' },
      ],
    },
    {
      id: 'op-high',
      when: { mood: 'high' },
      open: '{me}, 오늘 얼굴이 반짝여요. 좋은 일 있었죠? 그 사연, 사고 싶네요.',
      replies: [
        { say: '공짜로 들려 드릴게요', tier: 'great', face: 'laugh', answer: '어머, 공짜라니. 그럼 제일 좋은 의자에 앉아서 들을게요.' },
        { say: '비싸게 팔 거예요', tier: 'good', face: 'smile', answer: '후후, 좋아요. 반짝이는 사연은 값을 쳐 드려야죠.' },
        { say: '그냥 기분이 좋아요', tier: 'meh', face: 'calm', answer: '이유 없는 좋은 날도 있죠. 그것도 적어 둘게요.' },
      ],
    },
    {
      id: 'op-news-birthday',
      when: { news: 'birthday' },
      open: '오늘 마을에 생일인 분이 있대요. 리본 묶은 상자가 잘 나가는 날이에요.',
      replies: [
        { say: '사슬 말고 리본이죠?', tier: 'great', face: 'laugh', answer: '후후, 아시네요. 생일엔 사슬을 다 풀어 둬요.' },
        { say: '선물 고르는 거 도와줘요', tier: 'good', face: 'smile', answer: '좋아요. 반짝이는 것, 사연 있는 것, 둘 중 고르세요.' },
        { say: '저랑은 상관없어요', tier: 'meh', face: 'calm', answer: '그래도 축하는 공짜예요. 한마디 해 주고 가세요.' },
      ],
    },
    {
      id: 'op-news-legend',
      when: { news: 'legend' },
      open: '전설의 물고기가 낚였다는 소식 들었어요. 값을 매길 수가 없어요.',
      replies: [
        { say: '그래도 매겨 보세요', tier: 'great', face: 'think', answer: ['음… 마을 하나요? 아니, 그것도 모자라요.', '후후, 처음으로 감정을 포기해요.'] },
        { say: '구경 가실 거예요?', tier: 'good', face: 'laugh', answer: '벌써 다녀왔어요. 비늘 하나 떨어졌나 봤는데 없더라고요.' },
        { say: '물고기는 물고기죠', tier: 'meh', face: 'calm', answer: '어머, 수집가 앞에서 그런 말을. 오늘만 봐 드릴게요.' },
      ],
    },
    {
      id: 'op-news-record',
      when: { news: 'record' },
      open: '마을 기록이 또 바뀌었대요. 기록 장부 정리하는 게 제 낙인데.',
      replies: [
        { say: '기록 장부도 있어요?', tier: 'great', face: 'laugh', answer: '그럼요. 열세 권째로 갈 뻔했어요. 누가 세웠는지도 적었죠.' },
        { say: '다음엔 제가 세울게요', tier: 'good', face: 'smile', answer: '후후, 그럼 장부 한 장 비워 둘게요. 기다릴게요.' },
        { say: '기록엔 관심 없어요', tier: 'meh', face: 'calm', answer: '그래도 당신 이름은 언젠가 적힐 거예요. 제가 적거든요.' },
      ],
    },
    {
      id: 'op-friend-wedding',
      when: { friendNews: 'wedding' },
      open: '당신 친구가 결혼한다면서요. 축하 선물로 뭘 들고 가실 거예요?',
      replies: [
        { say: '사연 있는 걸로요', tier: 'great', face: 'laugh', answer: '후후, 그럼 오래된 은숟가락 어때요. 백 년 동안 축하받은 거예요.' },
        { say: '꽃다발이요', tier: 'good', face: 'smile', answer: '좋아요. 리본으로 묶어 드릴게요. 사슬은 빼고요.' },
        { say: '아직 못 정했어요', tier: 'meh', face: 'think', answer: '천천히요. 진열장은 늘 열려 있어요.' },
      ],
    },
    {
      id: 'op-voyage',
      when: { recent: 'voyage' },
      open: '먼바다 다녀오셨죠? 바다 밑에 주인 잃은 물건이 잔뜩이라던데요.',
      replies: [
        { say: '하나 건져 왔어요', tier: 'great', face: 'wow', answer: ['어머, 정말요? 보여 주세요.', '…바닷물에 오래 잠긴 냄새. 이건 비싸요.'] },
        { say: '파도가 무서웠어요', tier: 'good', face: 'smile', answer: '무사히 돌아왔으니 그 무서움도 사연이에요.' },
        { say: '물고기만 봤어요', tier: 'meh', face: 'calm', answer: '아쉽네요. 다음엔 갈고리 하나 빌려 드릴게요.' },
      ],
    },
    {
      id: 'op-casino-win',
      when: { recent: 'casinoWin' },
      open: '카지노에서 땄다는 소문 들었어요. 주머니가 무거우면 제가 덜어 드려요.',
      replies: [
        { say: '좋은 거 추천해 주세요', tier: 'great', face: 'laugh', answer: '후후, 기다렸어요. 오늘은 셋째 칸 바로 옆 칸만 보여 줄게요.' },
        { say: '저금할 거예요', tier: 'good', face: 'smile', answer: '현명하네요. 그럼 축하 사연만 받을게요.' },
        { say: '운이었어요', tier: 'meh', face: 'calm', answer: '운도 사연이죠. 오늘 날짜를 적어 둘게요.' },
      ],
    },
    {
      id: 'op-casino-lose',
      when: { recent: 'casinoLose' },
      open: '카지노 다녀오셨군요. 표정이 가볍지 않네요. 주머니는 가볍고.',
      replies: [
        { say: '위로해 주세요', tier: 'great', face: 'smile', answer: ['그럼 등불 옆 의자에 앉아요.', '잃은 건 돈이지 사연은 남았잖아요. 후후.'] },
        { say: '다음엔 딸 거예요', tier: 'good', face: 'laugh', answer: '그 마음, 경매장에서 자주 봐요. 조심하세요.' },
        { say: '말하기 싫어요', tier: 'meh', face: 'calm', answer: '알았어요. 조용히 차나 한 잔 드릴게요.' },
      ],
    },
    {
      id: 'op-museum',
      when: { recent: 'museum' },
      open: '박물관에 기증하셨다면서요. 저한테 팔지 않고요. 후후, 서운해요.',
      replies: [
        { say: '다음엔 여기 올게요', tier: 'great', face: 'laugh', answer: '약속이에요. 단골 명단에 별표 쳐 둘게요.' },
        { say: '모두 보라고 줬어요', tier: 'good', face: 'smile', answer: '…그것도 좋은 수집이에요. 마을 전체가 모아 두는 거니까.' },
        { say: '박물관이 더 좋아요', tier: 'meh', face: 'sorry', answer: '어머, 솔직하시네요. 진열장이 조금 울었어요.' },
      ],
    },
    {
      id: 'op-with-gwen',
      when: { with: 'gwen' },
      open: ['{other} 씨랑 같이 있었어요. 가위를 꼭 쥐고 계시네요.', '안개 조금 걷어 둘게요. 후후, 겁주려던 건 아니에요.'],
      replies: [
        { say: '두 분 친해지면 좋겠어요', tier: 'great', face: 'think', answer: '저도요. 리본 하나 들고 미용실에 가 볼까 해요.' },
        { say: '그웬 씨 긴장했네요', tier: 'good', face: 'sorry', answer: '…제 웃음 때문이겠죠. 연습을 더 할게요.' },
        { say: '안개 좀 치우세요', tier: 'meh', face: 'calm', answer: '어머, 당신까지. 알았어요. 오늘은 반만 깔게요.' },
      ],
    },
    {
      id: 'op-with-captain',
      when: { with: 'captain' },
      open: '{other} 선장님이랑 있었어요. 오늘 밤 주점 자랑 순서를 정하는 중이에요.',
      replies: [
        { say: '쓰레쉬 씨가 먼저 하세요', tier: 'great', face: 'laugh', answer: '후후, 그럼 병뚜껑 이야기부터요. 선장님은 또 웃겠죠.' },
        { say: '저도 들으러 갈래요', tier: 'good', face: 'smile', answer: '좋아요. 벽난로 옆자리 하나 비워 둘게요.' },
        { say: '술은 적당히요', tier: 'meh', face: 'calm', answer: '선장님한테 하세요. 저는 차만 마셔요.' },
      ],
    },
    {
      id: 'op-with-frieren',
      when: { with: 'frieren' },
      open: '{other} 씨랑 마도서 한 권을 두고 고민 중이에요. 둘 다 갖고 싶어서요.',
      replies: [
        { say: '번갈아 빌려 보세요', tier: 'great', face: 'think', answer: ['어머, 그런 방법이. 수집가는 잘 안 떠올리는 답이에요.', '그분은 천천히 읽으니까, 순서는 제가 나중으로.'] },
        { say: '흥정으로 정하세요', tier: 'good', face: 'laugh', answer: '해 봤는데 그분이 빵을 내밀었어요. 이상한 빵이요.' },
        { say: '그냥 양보하세요', tier: 'meh', face: 'sorry', answer: '…수집가한테 제일 어려운 말을 하시네요.' },
      ],
    },
    {
      id: 'op-with-volibas',
      when: { with: 'volibas' },
      open: '{other} 순경님이 또 가게 앞을 지키고 계세요. 오늘도 수상한가 봐요.',
      replies: [
        { say: '순경님 덕에 안전하죠', tier: 'great', face: 'laugh', answer: '후후, 맞아요. 밤마다 공짜 경비예요. 고마워요, 진심으로.' },
        { say: '진짜 수상한 거 없죠?', tier: 'good', face: 'smile', answer: '없어요. 셋째 칸 말고는요. 거긴 그냥 비밀이에요.' },
        { say: '저도 같이 감시할래요', tier: 'meh', face: 'sorry', answer: '어머, 감시받는 쪽이 늘었네요. 차라도 드릴게요.' },
      ],
    },
    {
      id: 'op-nasera',
      when: { bond: 'nasera' },
      open: '{other} 씨 만나셨죠? 또 제 씨앗 값 얘기를 하던가요?',
      replies: [
        { say: '네, 아주 열심히요', tier: 'great', face: 'laugh', answer: '후후, 그분 장부는 저를 위해 한 장이 따로 있대요. 영광이에요.' },
        { say: '인사만 했어요', tier: 'good', face: 'smile', answer: '다행이네요. 그분 인사엔 늘 숫자가 섞여 있거든요.' },
        { say: '값을 맞추세요', tier: 'meh', face: 'calm', answer: '그럼 싸울 거리가 없어지잖아요. 그건 서운해요.' },
      ],
    },
    {
      id: 'op-ornn',
      when: { bond: 'ornn' },
      open: '{other} 씨 대장간 다녀오셨죠? 제 얘기 하면서 모루를 두드렸죠?',
      replies: [
        { say: '쾅 소리가 났어요', tier: 'great', face: 'laugh', answer: '후후, 그게 그분 인사예요. 거절도 칭찬도 다 쾅이에요.' },
        { say: '광석 값 물어볼게요', tier: 'good', face: 'think', answer: '부탁해요. 저 대신 묻는 손님한텐 조금 깎아 주실지도.' },
        { say: '무서운 분이던데요', tier: 'meh', face: 'smile', answer: '말수만 적어요. 사슬 고리는 제일 잘 만들어 주세요.' },
      ],
    },
    {
      id: 'op-sulk',
      when: { sulk: true },
      open: '{other} 씨랑 조금 서먹하다면서요. 소문은 제 가게가 제일 빨라요.',
      replies: [
        { say: '어떻게 풀면 좋을까요', tier: 'great', face: 'think', answer: ['작은 선물이요. 사연 하나 붙여서요.', '말보다 물건이 먼저 문을 열 때가 있어요.'] },
        { say: '내일이면 괜찮아요', tier: 'good', face: 'smile', answer: '그렇죠. 서먹한 것도 오래 안 둬요. 그건 안 모아요.' },
        { say: '모른 척해 주세요', tier: 'meh', face: 'calm', answer: '알았어요. 수집 목록에도 안 적을게요. 이번만.' },
      ],
    },
    {
      id: 'op-festival-night',
      when: { festival: true, time: ['evening', 'night'] },
      open: '축제 밤이에요. 떨어진 물건 주우러 광장 한 바퀴 돌 건데, 같이 가요?',
      replies: [
        { say: '주인도 같이 찾아 줘요', tier: 'great', face: 'laugh', answer: '후후, 그럼요. 주인 있는 건 분실물 선반으로 가요.' },
        { say: '등불은 제가 들게요', tier: 'good', face: 'shy', answer: '어머, 또요? 이러다 등불이 당신을 더 좋아하겠어요.' },
        { say: '축제나 즐길래요', tier: 'meh', face: 'calm', answer: '그것도 좋아요. 뭐 떨어뜨리면 저한테 있어요.' },
      ],
    },
  ],
  callbacks: [
    {
      id: 'cb-regular',
      when: { mem: 'regular' },
      use: 'regular',
      open: '단골 명단에 당신 이름, 요즘 줄이 제일 길어요. 사연 칸이요.',
      replies: [
        { say: '사연이 그렇게 많아요?', tier: 'great', face: 'laugh', answer: '그럼요. 오늘 온 것도 한 줄이에요. 후후, 지금 적어요.' },
        { say: '뭐라고 적었어요?', tier: 'good', face: 'shy', answer: '…비밀이에요. 웃는 얼굴이 좋다는 정도만요.' },
      ],
    },
    {
      id: 'cb-keep-all',
      when: { mem: 'keep-all' },
      use: 'keep-all',
      open: '물건 못 버린다고 하셨죠? 집 정리할 때 부르세요. 버리지 말고 저한테요.',
      replies: [
        { say: '같이 정리해 주세요', tier: 'great', face: 'laugh', answer: '어머, 기꺼이요. 하나도 안 버리는 정리법을 알려 드릴게요.' },
        { say: '다 팔라는 거죠?', tier: 'good', face: 'smile', answer: '후후, 반은요. 나머지 반은 당신이 간직해요.' },
      ],
    },
    {
      id: 'cb-lantern',
      when: { mem: 'lantern-peek' },
      use: 'lantern-peek',
      open: '등불 안이 궁금하다고 하셨죠. 오늘은 기분이 좋아서 살짝 보여 드릴게요.',
      replies: [
        { say: '와, 단추가 반짝여요', tier: 'great', face: 'shy', answer: ['어머, 그거 처음 파신 단추예요.', '…버릴 리가요. 제일 앞자리예요.'] },
        { say: '생각보다 평범하네요', tier: 'good', face: 'laugh', answer: '후후, 그렇죠. 무서운 건 다 소문이에요.' },
      ],
    },
    {
      id: 'cb-beach',
      when: { mem: 'beach-comb' },
      use: 'beach-comb',
      open: '밤 해변 같이 가자고 하셨죠. 어젯밤 혼자 돌다가 당신 몫도 주웠어요.',
      replies: [
        { say: '제 몫이 뭔데요?', tier: 'great', face: 'smile', answer: '파란 유리 조각이요. 등불에 비추면 바다색이 나요. 드릴게요.' },
        { say: '다음엔 꼭 같이 가요', tier: 'good', face: 'laugh', answer: '약속이에요. 갈고리 하나 더 챙겨 둘게요.' },
      ],
    },
    {
      id: 'cb-mist',
      when: { mem: 'mist-home' },
      use: 'mist-home',
      open: '그림자 군도 얘기, 기억하세요? 어젯밤 안개가 꼭 고향 같았어요.',
      replies: [
        { say: '그리웠어요?', tier: 'great', face: 'think', answer: '…조금요. 근데 이젠 이 마을 안개가 더 좋아요. 이유는 알죠?' },
        { say: '등불 들고 산책했어요?', tier: 'good', face: 'smile', answer: '그럼요. 안개 낀 밤 산책이 제 낙이에요. 후후.' },
      ],
    },
    {
      id: 'cb-haggle',
      when: { mem: 'haggle' },
      use: 'haggle',
      open: '웃으면서 깎겠다고 하셨죠. 오늘 연습해 볼래요? 이 유리병으로.',
      replies: [
        { say: '반값이면 살게요. 후후', tier: 'great', face: 'laugh', answer: '어머, 제 웃음까지 따라 하다니. 졌어요. 반값이에요.' },
        { say: '조금만 깎아 주세요', tier: 'good', face: 'smile', answer: '조금만이라니 착하시네요. 덤으로 코르크 마개 드릴게요.' },
      ],
    },
    {
      id: 'cb-taste',
      when: { mem: '@taste', noMem: 'taste-heard' },
      open: '{me}, 좋아하는 게 {taste}라면서요. 수집 목록에 적어 뒀어요. 따로요.',
      replies: [
        { say: '따로 적는 칸이 있어요?', tier: 'great', remember: 'taste-heard', face: 'shy', answer: '…생겼어요. 요즘. 당신 칸이요. 후후.' },
        { say: '들어오면 연락 주세요', tier: 'good', remember: 'taste-heard', face: 'laugh', answer: '그럼요. 단골 우선이에요. 값은 흥정이고요.' },
        { say: '그걸 왜 적어요?', tier: 'meh', remember: 'taste-heard', face: 'calm', answer: '수집가는 다 적어요. 버릇이에요.' },
      ],
    },
    {
      id: 'cb-outing',
      when: { mem: '@outing', noMem: 'outing-talk' },
      open: '같이 걸었던 날 기억나요? 당신 발자국, 모아 두고 싶었어요.',
      replies: [
        { say: '또 같이 걸어요', tier: 'great', remember: 'outing-talk', face: 'shy', answer: '…어머. 그럼 이번엔 밤에요. 등불은 제가 들게요.' },
        { say: '발자국은 못 모아요', tier: 'good', remember: 'outing-talk', face: 'laugh', answer: '알아요. 그래서 기억에 모셔 뒀어요. 후후.' },
        { say: '그날 좀 피곤했어요', tier: 'meh', remember: 'outing-talk', face: 'sorry', answer: '어머, 다음엔 천천히 걸을게요. 그늘로만요.' },
      ],
    },
    {
      id: 'cb-bday',
      when: { mem: '@bday-soon', noMem: 'bday-heard' },
      open: '{me}, 곧 생일이죠? 단골 명단에 적혀 있어요. 선물은 비매품으로요.',
      replies: [
        { say: '쓰레쉬 씨가 고른 거면 좋아요', tier: 'great', remember: 'bday-heard', face: 'shy', answer: '…그럼 오래 고를게요. 진열장 전부 다시 볼 거예요.' },
        { say: '사슬은 빼 주세요', tier: 'good', remember: 'bday-heard', face: 'laugh', answer: '후후, 알았어요. 리본으로 묶어 드릴게요.' },
        { say: '안 챙겨도 돼요', tier: 'meh', remember: 'bday-heard', face: 'calm', answer: '이미 적어 버렸어요. 수집가는 못 지워요.' },
      ],
    },
    {
      id: 'cb-archive',
      when: { mem: 'archive-keeper' },
      use: 'archive-keeper',
      open: ['보관소 문지기 얘기, 기억하세요?', '어젯밤 그 열쇠 하나로 우리 가게 창고를 열어 봤어요. 안 맞더라고요.'],
      replies: [
        { say: '그래도 버리진 않죠?', tier: 'great', face: 'laugh', answer: '후후, 당연하죠. 안 맞는 열쇠도 맞는 문을 기다려요.' },
        { say: '고향 생각 나셨어요?', tier: 'good', face: 'think', answer: '…조금요. 근데 이젠 이 가게 문이 더 익숙해요.' },
      ],
    },
    {
      id: 'cb-lost-found',
      when: { mem: 'lost-found' },
      use: 'lost-found',
      open: '분실물 선반 같이 지키자고 하셨죠. 오늘 장갑 한 짝이 주인을 찾았어요.',
      replies: [
        { say: '누구 거였어요?', tier: 'great', face: 'laugh', answer: ['볼리바스 순경님이요. 순찰하다 떨어뜨렸대요.', '수상한 가게가 찾아 줬다고 머쓱해하셨어요. 후후.'] },
        { say: '잘됐네요', tier: 'good', face: 'smile', answer: '그렇죠. 돌려줄 때가 모을 때만큼 좋아요. 요즘 알았어요.' },
      ],
    },
    {
      id: 'cb-smile',
      when: { mem: 'real-smile' },
      use: 'real-smile',
      open: '안 웃을 때가 더 좋다고 하셨죠. 그 말 때문에 거울 앞에서 헷갈려요.',
      replies: [
        { say: '지금 그 얼굴이요', tier: 'great', face: 'shy', answer: '…이거요? 그냥 곤란한 얼굴인데요. 어머.' },
        { say: '둘 다 좋아요', tier: 'good', face: 'laugh', answer: '후후, 장사꾼한텐 제일 좋은 대답이네요.' },
      ],
    },
    {
      id: 'cb-fog',
      when: { mem: 'fog-walk' },
      use: 'fog-walk',
      open: '어젯밤 안개가 짙었죠. 혹시 길 잃으셨으면 등불 잡으라고 했는데.',
      replies: [
        { say: '등불 보고 찾아왔어요', tier: 'great', face: 'shy', answer: '…정말요? 그럼 등불이 제 일을 했네요. 후후, 뿌듯해요.' },
        { say: '집에 일찍 들어갔어요', tier: 'good', face: 'smile', answer: '잘했어요. 그래도 등불은 밤새 켜 뒀어요. 습관이에요.' },
      ],
    },
    {
      id: 'cb-jar',
      when: { mem: 'jar-label' },
      use: 'jar-label',
      open: '비 냄새 담긴 병, 기억나죠? 그 병 사겠다는 손님이 왔어요.',
      replies: [
        { say: '팔았어요?', tier: 'great', face: 'laugh', answer: '아니요. 이름 지은 분 허락이 필요하다고 했어요. 후후.' },
        { say: '좋은 값 받으세요', tier: 'good', face: 'smile', answer: '그럼 당신 몫도 떼 둘게요. 이름값이에요.' },
      ],
    },
    {
      id: 'cb-winter',
      when: { mem: 'winter-love', season: 'winter' },
      use: 'winter-love',
      open: '긴 겨울밤 좋다고 하셨죠. 드디어 왔어요. 목록 정리하러 오세요.',
      replies: [
        { say: '차는 제가 들고 갈게요', tier: 'great', face: 'laugh', answer: '어머, 그럼 등불 하나 더 켤게요. 오늘 밤은 길어요.' },
        { say: '목록이 몇 권인데요?', tier: 'good', face: 'think', answer: '열두 권이요. 겨울이면 다 넘길 수 있어요. 둘이면요.' },
      ],
    },
    {
      id: 'cb-night-fish',
      when: { mem: 'night-fish' },
      use: 'night-fish',
      open: '밤 물고기 가져오기로 하셨죠. 기다리느라 등불 심지가 짧아졌어요.',
      replies: [
        { say: '오늘 밤 꼭 낚을게요', tier: 'great', face: 'laugh', answer: '후후, 그럼 등불 빌려 드릴게요. 물고기는 초록빛을 좋아해요.' },
        { say: '아직 못 잡았어요', tier: 'good', face: 'smile', answer: '천천히요. 밤바다는 서두르는 사람한텐 안 줘요.' },
      ],
    },
    {
      id: 'cb-fossil',
      when: { mem: 'fossil-talk' },
      use: 'fossil-talk',
      open: '화석 이야기 기억하세요? 고사리 화석 하나가 들어왔어요. 보세요.',
      replies: [
        { say: '시간이 잠들어 있네요', tier: 'great', face: 'wow', answer: '어머, 그 말 좋아요. 이름표에 그렇게 쓸게요.' },
        { say: '광산에서 나왔대요?', tier: 'good', face: 'smile', answer: '네. 광산 깊은 곳이요. 어두운 데서 기다린 거죠.' },
      ],
    },
    {
      id: 'cb-collection',
      when: { mem: 'my-collection' },
      use: 'my-collection',
      open: '당신도 모으는 게 있다고 했죠. 이제 알려 줄 때 됐잖아요. 후후.',
      replies: [
        { say: '쓰레쉬 씨 웃음이요', tier: 'great', face: 'shy', answer: '…어머. 반칙이에요. 그건 비매품인데 벌써 가져갔네요.' },
        { say: '예쁜 조약돌이요', tier: 'good', face: 'laugh', answer: '좋아요. 흔한 돌 말고 예쁜 돌. 그 차이 아는 분이네요.' },
        { say: '비밀이에요', tier: 'meh', face: 'calm', answer: '어머, 수집가답네요. 기다릴게요.' },
      ],
    },
    {
      id: 'cb-ghost',
      when: { mem: 'ghost-story', time: 'night' },
      use: 'ghost-story',
      open: '주점 이야기 마저 들려 드릴까요? 밤이니까 딱이에요.',
      replies: [
        { say: '들려주세요. 끝까지요', tier: 'great', face: 'laugh', answer: ['안개 속 장화 한 짝이 다른 한 짝을 찾는 이야기예요.', '결국 제 가게에서 만나요. 끝. 따뜻하죠?'] },
        { say: '무섭지 않은 거로요', tier: 'good', face: 'smile', answer: '그럼 단추가 집에 돌아가는 이야기로요. 짧아요.' },
      ],
    },
    {
      id: 'cb-gwen',
      when: { mem: 'gwen-truce' },
      use: 'gwen-truce',
      open: '리본 선물하라고 하셨죠. 그웬 씨한테 줬더니 가위를 내려놨어요.',
      replies: [
        { say: '화해했네요!', tier: 'great', face: 'laugh', answer: ['반쯤요. 안개는 여전히 싫대요.', '그래도 제 머리 다듬어 준다고 했어요. 후후.'] },
        { say: '리본은 마음에 들었대요?', tier: 'good', face: 'smile', answer: '바느질 솜씨를 칭찬해 줬어요. 제가 만든 건 아닌데.' },
      ],
    },
    {
      id: 'cb-green',
      when: { mem: 'green-light', time: ['evening', 'night'] },
      use: 'green-light',
      open: '초록 불빛 예쁘다고 하셨죠. 오늘은 당신 쪽으로 조금 더 비출게요.',
      replies: [
        { say: '고향 바다 색이죠', tier: 'great', face: 'shy', answer: '…기억하셨네요. 그 바다보다 지금이 더 따뜻해요.' },
        { say: '눈부셔요', tier: 'good', face: 'laugh', answer: '어머, 제가 눈부신 걸 만들다니. 해바라기 될 뻔했네요.' },
      ],
    },
    {
      id: 'cb-clean',
      when: { mem: 'clean-day', season: 'spring' },
      use: 'clean-day',
      open: '대청소 날이에요. 같이 돌기로 했죠? 수레 두 대 빌려 놨어요.',
      replies: [
        { say: '고맙다고 웃으면서요', tier: 'great', face: 'laugh', answer: '후후, 잘 배웠네요. 오늘 수레 반은 당신 몫이에요.' },
        { say: '제 창고부터 털까요?', tier: 'good', face: 'wow', answer: '어머, 정말요? 버리는 거 말고 파는 거로 할게요.' },
      ],
    },
    {
      id: 'cb-cloud',
      when: { mem: 'cloud-wish', weather: 'cloudy' },
      use: 'cloud-wish',
      open: '{weather}. 같이 기다리던 흐린 날이에요. 등불 하나 더 걸었어요.',
      replies: [
        { say: '등불 구경하러 왔어요', tier: 'great', face: 'laugh', answer: '후후, 제일 좋은 자리 비워 뒀어요. 앉아요.' },
        { say: '잔나 씨 예보 맞았네요', tier: 'good', face: 'smile', answer: '이번엔요. 다음에도 맞으면 등불 하나 선물할래요.' },
      ],
    },
    {
      id: 'cb-firefly',
      when: { mem: 'firefly-woods', season: 'summer' },
      use: 'firefly-woods',
      open: '여름이에요. 숲에서 반딧불이 같이 본 밤, 또 올 때가 됐어요.',
      replies: [
        { say: '오늘 밤 숲에서 봐요', tier: 'great', face: 'shy', answer: '…좋아요. 등불은 낮춰 둘게요. 반딧불이가 주인공이니까.' },
        { say: '모기약 챙길게요', tier: 'good', face: 'laugh', answer: '후후, 기억하셨네요. 저도 쑥 향 챙길게요.' },
      ],
    },
    {
      id: 'cb-shell',
      when: { mem: 'shell-gift' },
      use: 'shell-gift',
      open: '그때 주신 조개요. 아직 등불 제일 앞자리에 있어요. 매일 닦아요.',
      replies: [
        { say: '매일요?', tier: 'great', face: 'shy', answer: '…네. 손님 물건은 가끔 닦는데, 그건 매일이에요.' },
        { say: '하나 더 주울게요', tier: 'good', face: 'laugh', answer: '후후, 그럼 짝이 생기겠네요. 조개도 혼자는 외로워요.' },
      ],
    },
    {
      id: 'cb-night-owl',
      when: { mem: 'night-owl', noMem: 'night-heard', time: 'night' },
      open: '밤이 좋다고 했던 거 기억해요. 오늘 밤도 같은 편이죠?',
      replies: [
        { say: '그럼요. 밤의 단골이에요', tier: 'great', remember: 'night-heard', face: 'laugh', answer: '후후, 명단에 별 하나 더 그릴게요. 밤의 단골 칸에.' },
        { say: '오늘은 좀 졸려요', tier: 'good', remember: 'night-heard', face: 'smile', answer: '그럼 등불 옆에서 조금 쉬다 가요. 깨워 드릴게요.' },
        { say: '요즘은 낮이 좋아요', tier: 'meh', remember: 'night-heard', face: 'sorry', answer: '어머, 변심이네요. 그래도 목록에서 안 지울게요.' },
      ],
    },
    {
      id: 'cb-date',
      when: { mem: '@date', noMem: 'date-heard' },
      open: '당신 방에서 보낸 밤 말이에요. 그 방 컵 하나가 아직 눈에 밟혀요.',
      replies: [
        { say: '그 컵 드릴게요', tier: 'great', remember: 'date-heard', face: 'shy', answer: '…어머. 그 컵은 안 팔고, 안 쓰고, 그냥 볼게요.' },
        { say: '컵 말고 저는요?', tier: 'good', remember: 'date-heard', face: 'laugh', answer: '후후, 당신은 수집 목록 맨 앞 장이에요. 이미요.' },
        { say: '그냥 평범한 컵이에요', tier: 'meh', remember: 'date-heard', face: 'calm', answer: '평범한 것도 그 방에 있으면 달라요. 수집가 눈엔요.' },
      ],
    },
  ],
  chapters: [
    {
      title: '열두 권째 수집 목록',
      hint: '한 번 이야기를 나누면 쓰레쉬가 수집 목록을 펼쳐요.',
      need: { days: 1 },
      scene: [
        '시장 거리 잡화점. 문에 걸린 사슬이 짤랑, 하고 손님을 알린다.',
        '쓰레쉬가 등불 옆에서 두꺼운 공책을 펼친다. 표지에 열둘이라 적혀 있다.',
        '"어서 오세요. 처음 뵙는 손님은 여기 적어 두는 게 버릇이에요."',
        '선반마다 단추, 병뚜껑, 장화 한 짝, 이름표 붙은 유리병이 빼곡하다.',
        '"다 손님들이 팔고 간 거예요. 하나도 안 버렸어요. 못 버려요."',
        '"이름, 오신 시간, 그리고 웃는 얼굴. 물건처럼요. 후후."',
        '그가 펜을 멈추고 당신을 빤히 본다. 초록 불빛이 눈에 비친다.',
        '"아, 겁먹지 마세요. 그냥 목록이에요. 안 물어요. 대부분은."',
        '"고향에선 문을 지키는 일을 했어요. 들어온 건 다 지켰죠."',
        '"그 버릇이 아직 남았나 봐요. 손님도 한번 오면 단골 칸으로 가요."',
      ],
      replies: [
        { say: '예쁘게 적어 주세요', tier: 'great', face: 'laugh', answer: ['어머, 그런 주문은 처음이에요.', '제일 고운 글씨로 쓸게요. 첫 장 맨 위에요.'] },
        { say: '뭘 그렇게 적어요?', tier: 'good', face: 'smile', answer: '사연이요. 사람도 물건도 사연이 값이거든요.' },
        { say: '대부분은이라뇨…', tier: 'meh', face: 'calm', answer: '후후, 농담이에요. 이 가게에선 등불만 무는 척해요.' },
      ],
    },
    {
      title: '반딧불이 등불',
      hint: '밤 아홉 시부터 새벽 두 시 사이에 숲에 가 보세요. 쓰레쉬가 등불을 들고 있대요.',
      need: { days: 3, points: 20, visit: { area: 'woods', from: 21, to: 2 } },
      scene: [
        '깊은 밤의 숲. 나무 사이로 초록 불빛 하나가 흔들린다.',
        '"어머, 정말 오셨네요. 이 시간 숲은 제 단골 자리예요."',
        '쓰레쉬가 등불을 낮추자 주위로 반딧불이가 하나둘 모여든다.',
        '"제 등불이랑 색이 비슷해서 친구인 줄 아나 봐요. 후후."',
        '"잡진 않아요. 보는 게 수집이에요. 이건 병에 못 담거든요."',
        '그가 사슬 끝 고리를 나뭇가지에 걸고 등불을 매단다.',
        '"고향 섬엔 이런 빛이 없었어요. 안개 속 초록빛은 이것 하나였죠."',
        '"길 잃은 사람이 보이면 등불을 내밀었어요. 잡으면 데려왔고요."',
        '"지금도 그래요. 안개 낀 밤 골목에서 몇 분은 이걸 잡았어요."',
        '반딧불이 하나가 당신 어깨에 앉는다. 쓰레쉬가 숨을 죽인다.',
        '"…움직이지 마세요. 지금 이 장면, 목록에 적는 중이에요."',
      ],
      replies: [
        { say: '저도 이 밤을 모셔 둘게요', tier: 'great', remember: 'firefly-woods', face: 'shy', answer: ['…어머. 제 말버릇을 그렇게 쓰다니.', '반칙이에요. 좋네요.'] },
        { say: '숲이 생각보다 따뜻해요', tier: 'good', remember: 'firefly-woods', face: 'smile', answer: '그렇죠. 밤은 무섭지 않아요. 조용할 뿐이에요.' },
        { say: '모기가 많아요', tier: 'meh', remember: 'firefly-woods', face: 'laugh', answer: '후후, 그건 수집 안 해요. 다음엔 쑥 향 챙겨 드릴게요.' },
      ],
    },
    {
      title: '파도가 놓고 간 것',
      hint: '쓰레쉬가 밤 해변 이야기를 했어요. 바닷조개 하나를 가지고 찾아가 보세요.',
      need: { days: 6, points: 40, bring: { item: 'shell', take: true } },
      scene: [
        '바닷조개를 내밀자 쓰레쉬가 손님 대하는 웃음을 잠깐 잊는다.',
        '"…파신다고요? 아니면, 주시는 거예요?"',
        '그가 조개를 등불에 비춘다. 안쪽이 초록빛으로 일렁인다.',
        '"고향 섬 바닷가엔 조개가 없었어요. 안개만 밀려왔죠."',
        '"매일 밤 해변에 나가서 뭐라도 밀려오길 기다렸어요. 아무것도 안 왔죠."',
        '"그래서 이 마을 해변이 좋아요. 파도가 뭘 자꾸 놓고 가거든요."',
        '그가 장부를 펼쳤다가, 매입 칸에 펜을 대고 한참 머뭇거린다.',
        '"이건 장부에 매입이라고 안 적을게요."',
        '새 쪽 맨 위에 그가 또박또박 쓴다. 선물.',
        '"선물 칸은 처음 만들어요. 열두 권 동안 한 번도 없었어요."',
        '"…어머, 손이 떨리네요. 장사꾼이 이러면 안 되는데. 후후."',
      ],
      replies: [
        { say: '선물이에요. 값은 없어요', tier: 'great', remember: 'shell-gift', face: 'shy', answer: ['…값이 없는 물건은 처음이에요.', '등불 제일 앞자리에 모셔 둘게요.'] },
        { say: '흥정은 다음에 해요', tier: 'good', remember: 'shell-gift', face: 'laugh', answer: '후후, 좋아요. 그때 웃으면서 해요. 오늘은 그냥 받을게요.' },
        { say: '해변에 많던데요', tier: 'meh', remember: 'shell-gift', face: 'calm', answer: '많아도 당신이 주운 건 이거 하나예요. 그게 다르죠.' },
      ],
    },
    {
      title: '밤의 단골',
      hint: '쓰레쉬가 밤이 좋은지 낮이 좋은지 물어볼 때, 밤이 좋다고 답해 보세요.',
      need: { days: 9, points: 60, mem: 'night-owl' },
      scene: [
        '문 닫을 시간. 쓰레쉬가 가게 불을 끄고 등불 하나만 남긴다.',
        '"밤이 좋다고 하셨죠. 그래서 문 닫은 뒤에 불렀어요."',
        '"이 시간엔 장사용 웃음을 안 지어도 돼요. 편하네요."',
        '그가 사슬 꾸러미를 풀어 탁자에 내려놓는다. 열쇠 소리가 난다.',
        '"이 녹슨 열쇠들은 고향 보관소 거예요. 안개가 덮친 날 다들 떠났죠."',
        '"저만 남아서 문을 지켰어요. 지킬 사람도 없는데, 오래요."',
        '"그러다 배 한 척이 지나갔어요. 등불을 들고 그냥 탔죠."',
        '그가 맨 끝의 새 열쇠 하나를 떼어 낸다. 아직 반짝인다.',
        '"이건 뒷방 열쇠예요. 버리지 못한 것들이 다 거기 있어요."',
        '"아는 사람은 저 말고 당신이 처음이에요."',
        '"들어가라고 드리는 건 아니에요. 그냥, 하나쯤 나눠 갖고 싶어서요."',
      ],
      replies: [
        { say: '밤마다 놀러 와도 돼요?', tier: 'great', face: 'laugh', answer: ['어머, 물어볼 필요도 없어요.', '등불은 늘 켜 둘게요. 문은 안 잠가요. 당신한텐요.'] },
        { say: '오래 혼자였겠어요', tier: 'good', face: 'think', answer: '…그랬죠. 그래서 이 가게가 이렇게 시끄러운가 봐요. 후후.' },
        { say: '졸려요', tier: 'meh', face: 'smile', answer: '후후, 밤의 단골도 잠은 자야죠. 다음엔 낮잠 자고 와요.' },
      ],
    },
    {
      title: '사슬 없는 꽃다발',
      hint: '쓰레쉬와 아주 가까워지면 그가 웃는 얼굴 뒤를 보여 줘요. 꽃다발 이야기도요.',
      need: { days: 13, points: 96 },
      scene: [
        '흐린 오후. 가게 안엔 손님이 없고, 등불만 낮게 타고 있다.',
        '쓰레쉬가 늘 짓던 웃음을 지으려다, 그만둔다.',
        '"…이상해요. 당신 앞에선 장사용 얼굴이 안 돼요."',
        '"전 갖고 싶은 건 다 등불 안에 모셔 뒀어요. 그게 제 방식이었죠."',
        '"단추도, 조개도, 사연도요. 놓치기 싫은 건 다 그렇게 했어요."',
        '그가 사슬을 손에 감았다가, 천천히 풀어 선반에 걸어 둔다.',
        '"근데 당신은 가두고 싶지가 않아요. 옆에 있었으면 해요."',
        '"제 발로 가게 문을 열고 들어오는 게 좋아요. 매일 새로."',
        '그가 진열장의 꽃다발 하나를 본다. 사슬 없이 리본만 묶인 것.',
        '"그웬 씨가 묶어 준 리본이에요. 화해 선물로 받았죠. 후후."',
        '"그런 꽃다발을 누가 주면… 등불에 안 넣을 첫 번째가 될 거예요."',
      ],
      replies: [
        { say: '그 첫 번째, 제가 할게요', tier: 'great', face: 'shy', answer: ['…어머. 후후, 아니, 웃음이 안 나와요.', '기다릴게요. 등불 말고 꽃병을 닦아 둘게요.'] },
        { say: '지금 그 얼굴이 좋아요', tier: 'good', face: 'shy', answer: '…곤란하네요. 이 얼굴은 비매품이에요. 당신만 봐요.' },
        { say: '꽃은 시들잖아요', tier: 'meh', face: 'calm', answer: '그렇죠. 그래도 그 꽃이면 시든 것까지 아낄 거예요.' },
      ],
    },
    {
      title: '팔 수 없는 것',
      hint: '쓰레쉬와 연인이 되면 마지막 이야기가 열려요.',
      need: { days: 16, love: 'dating' },
      scene: [
        '안개 낀 밤. 쓰레쉬가 열두 권째 수집 목록을 덮고, 새 공책을 꺼낸다.',
        '"평생 모으기만 했어요. 사고, 팔고, 모셔 두고."',
        '"문을 지키던 시절부터 그랬죠. 들어온 건 하나도 안 내보냈어요."',
        '"근데 당신은 값을 매길 수가 없어요. 팔 수도, 모을 수도 없어요."',
        '그가 등불 뚜껑을 열고, 맨 앞자리의 조개를 꺼내 탁자에 놓는다.',
        '"이건 이제 등불 밖에 둘게요. 당신이 매일 볼 수 있게요."',
        '"그래서 목록 대신 이 공책에 적으려고요. 우리 둘 이야기."',
        '새 공책 첫 장엔 아직 아무것도 없다. 날짜 한 줄만 적혀 있다.',
        '그가 등불을 끄고, 빈손을 내민다. 사슬도 갈고리도 없다.',
        '어둠 속에서도 그의 웃음이 보인다. 장사용이 아닌 쪽이다.',
        '"언젠가 반지 하나만은… 수집이 아니라 약속으로 받고 싶어요."',
        '"그날이 오면 그 반지는 등불에 안 넣어요. 제 손에 낄 거예요."',
      ],
      replies: [
        { say: '그 약속, 꼭 할게요', tier: 'great', face: 'shy', answer: ['…후후. 처음으로 흥정 없이 받아요.', '평생 안 버릴게요. 아니, 평생 옆에 둘게요.'] },
        { say: '등불은 왜 껐어요?', tier: 'good', face: 'smile', answer: '오늘은 당신이 더 밝아서요. 큰일이죠. 저 밝은 거 싫어하는데.' },
        { say: '천천히 써요, 우리', tier: 'meh', face: 'smile', answer: '좋아요. 밤은 기니까요. 천천히, 한 장씩.' },
      ],
    },
  ],
  after: [
    '오늘 사연은 잘 받았어요. 등불 안에 모셔 둘게요.',
    '또 오셨네요. 구경은 공짜예요. 나가는 것도요. 후후.',
    '할 얘긴 다 했잖아요. 진열장이나 보고 가세요.',
    '밤에 다시 오세요. 그땐 등불이 더 예뻐요.',
    '단골 명단에 오늘 방문 한 줄 더 적었어요. 후후.',
    '어머, 아직 계셨네요. 사슬 소리 때문에 못 가셨어요? 열쇠예요.',
    '분실물 선반에 당신 그림자가 남은 것 같아요. 농담이에요.',
    '오늘 몫 수다는 끝났어요. 내일 사연은 내일 값으로 쳐 드릴게요.',
    '골목이 어두우면 등불 잡으세요. 가게 앞까지 모셔 올게요.',
  ],
};
